### ISSUE TITLE
Cros is blocked

### ISSUE THREAD

**Issue by inovout** [chromelyapps/Chromely#100]
Calling external AJAX requests,responseText is empty
Version::Chromely.CefGlue.Winapi 4.0.70

Program.cs
-----------------------------
                var startUrl = "local://app/chromely.html";
                 .......
ajaxDemo.html
-----------------------------------------
  function ajaxRun1() {

            $('#ajaxResult1 tbody').html('');
            var http = new XMLHttpRequest();
            //var url = "http://chromely.com/democontroller/movies";
            var url = "http://localhost:10002/Product/6";
            http.open("GET", url, true);
            ......

       ---

**Comment by mattkol** [comment]
You are likely missing a vital configuration.


In Program.cs, register custom schemes:
````csharp
var config = ChromelyConfiguration()
              .Create()
              ....
             .UseDefaultHttpSchemeHandler("http", "localhost")
              .....
````

Or

````csharp
var config = ChromelyConfiguration()
              .Create()
              ....
             .RegisterSchemeHandler("http", "localhost", new CustomHttpSchemeHandlerFactory())
              .....
````

In Controller:

````csharp
public class DemoController : ChromelyController
{
  public DemoController()
  {
    RegisterGetRequest(/Product/6", GetMovies);
    RegisterPostRequest("/Product/6", SaveMovies);
  }
}

````

For more info, please check [wiki](https://github.com/chromelyapps/Chromely/wiki/Restful-Resources).

**Comment by mattkol** [comment]
![image](https://user-images.githubusercontent.com/18384207/58632122-5eeaad00-82aa-11e9-9f6a-e3ad4729240a.png)

**Comment by inovout** [comment]
localhost:10002 is MVC Site
I I want Ajax requests to be sent directly to "Localhost: 10002" site, not ChromelyController.
like Chromely.CefGlue.WinApi v68

**Comment by inovout** [comment]
Chromely.CefGlue.WinApi v4.0.70 not support
but http post request is ok.
http get request is fail.
in fiddler,http get response header not "Access-Control-Origin".
but in FireFox or Chrome browser is ok.
<img width="177" alt="POST" src="https://user-images.githubusercontent.com/2756745/58677255-d6453d00-838d-11e9-89ed-70d3adc74fbb.PNG">
<img width="198" alt="GET" src="https://user-images.githubusercontent.com/2756745/58677261-de04e180-838d-11e9-99a3-56c60cd295e7.PNG">

**Comment by inovout** [comment]
before send http get request,v4.0.70 not send http options request.
but v68 send http options request.

**Comment by mattkol** [comment]
> localhost:10002 is MVC Site
> I I want Ajax requests to be sent directly to "Localhost: 10002" site, not ChromelyController.
> like Chromely.CefGlue.WinApi v68

To do that, you will register it as an external url:

````
  window.RegisterUrlScheme(new UrlScheme("http://localhost:10002/Product/6", true));
````

Please see Wiki - https://github.com/chromelyapps/Chromely/wiki/External-Url-Registration#external-url-scheme and the demos.

**Comment by mattkol** [comment]
The external url registration is likely going to work well with a web page launch. Since you are likely doing a restful request and want data back, I will still suggest you use the Controller.

So from Chromely send a request to the Controller. From Chromely Controller send a request to the localhost. Then return the data from the localhost to the Controller and then back to the UI.

**Comment by inovout** [comment]
after add "  window.RegisterUrlScheme(new UrlScheme("http://localhost:10002/Product/6", true));" ,ajax can read respose body.But,i can't regiester all url.

so...
after add "config..RegisterExternalUrlScheme("http","localhost"),chromely open new ie window.
",

**Comment by mattkol** [comment]
> after add " window.RegisterUrlScheme(new UrlScheme("http://localhost:10002/Product/6", true));" ,ajax can read respose body.But,i can't regiester all url.
> 
> so...
> after add "config..RegisterExternalUrlScheme("http","localhost"),chromely open new ie window.
> ",

Yes, I just realized that after making the comment. That was why I made the newer comment - https://github.com/chromelyapps/Chromely/issues/100#issuecomment-497633097

**Comment by inovout** [comment]
Can you fix?

external url may use regular expression.like “Trusted sites” in ie.

**Comment by mattkol** [comment]
I will consider that a feature and not a "fix". This is something we may have to consider if needed by most developers.

However if you still want to do it, you can configure the necessary handlers to do that. Please check [Configuration wiki page](https://github.com/chromelyapps/Chromely/wiki/Configuration) especially [Handlers](https://github.com/chromelyapps/Chromely/wiki/Configuration#how-to-add-custom-handlers) and [External Url Registration page](https://github.com/chromelyapps/Chromely/wiki/External-Url-Registration).

Are you still trying to solve the original problem? How does external url helps? Right now external url registration will launch a new browser, That is the current design.

Have you considered the previous comment?
What I was suggesting is to use the Controller like:
````csharp
public class DemoController : ChromelyController
{
  public DemoController()
  {
    RegisterGetRequest(/Product", GetProducts);
  }

   private ChromelyResponse GetProducts(ChromelyRequest request)
   {
        var responseTask = client.GetAsync("http://localhost:10002/Product/6");  
        responseTask.Wait();  

        return new ChromelyResponse(request.Id)
        {
            Data = responseTask.Result
        };
    }
}

````
