### ISSUE TITLE
How to Chromely.Cefglue handling filebrowser poput?

### ISSUE THREAD

**Issue by radiaku** [chromelyapps/Chromely#101]
Hey is there any example for handing file browser? in cefsharp there is [OnfileDialog](http://cefsharp.github.io/api/71.0.0/html/M_CefSharp_IDialogHandler_OnFileDialog.htm) and using [tempdialoghandler](https://github.com/cefsharp/CefSharp/blob/master/CefSharp.Example/Handlers/TempFileDialogHandler.cs)

Is there any same ways to use simple handling like that in Chromely.Cefglue?

Thanks.

**Comment by mattkol** [comment]
@radiaku No example, but yes, you can do it.

Create a custom handler:
````csharp
    using Xilium.CefGlue;
    public class CustomCefDialogHandler : CefDialogHandler
    {
    }
````

Register the handler:
````csharp
ChromelyConfiguration config = ChromelyConfiguration
                              .Create()
                              .....
.RegisterCustomHandler(CefHandlerKey.DialogHandler, typeof(CustomCefDialogHandler))
                              ....
````

Please see more info on [Configuration page](https://github.com/chromelyapps/Chromely/wiki/Configuration#how-to-add-custom-handlers) and [Demo Page](https://github.com/chromelyapps/demo-projects/tree/master/regular-chromely/Chromely.CefGlue.Winapi.Demo#with-custom-handlers).

**Comment by radiaku** [comment]
Ok, thank you. I found it.. :)
