### ISSUE TITLE
NullReferenceException thrown when closing CefGlue.WinApi window.

### ISSUE THREAD

**Issue by Soarc** [chromelyapps/Chromely#102]
When closing CefGlue winapi window with "X" button, unhanded null reference exception has been thrown. See screenshot for more details.

![image](https://user-images.githubusercontent.com/3385495/59551071-15c27a80-8f85-11e9-8441-65146a2ce732.png)

Update: I'm using latest code from master branch.

One more Update: this issue only visible, when all exceptions handling is enabled in visual studio.
![image](https://user-images.githubusercontent.com/3385495/59551597-20810d80-8f8d-11e9-93e7-80b313274103.png)

**Comment by mattkol** [comment]
@Soarc cannot seem to be able to reproduce this.
Please can you if there is a specific steps to reproduce this?
Thanks.

**Comment by Soarc** [comment]
I used example project and latest source from master. Also I manually copied CEF libraries into project's output folder.

**Comment by FrankPfattheicher** [comment]
@Soarc 
This is due to an "already disposed" in Xilium.CefGlue.CefBrowser :-/

Due we don't want to change Xilium sources i added a additional check in
CefGlueBrowser.Dispose() so the CefBrowser will not be used if already disposed.

commit ec355ba738a8c14ee84ba25fef5779d223fb2802

**Comment by mattkol** [comment]
@FrankPfattheicher thanks for looking into this.
Please you help with same for CefSharp Winapi?

**Comment by FrankPfattheicher** [comment]
@mattkol as far as i tested this issue was in CefGlue.Winapi only.

**Comment by mattkol** [comment]
@FrankPfattheicher makes sense.
Thank you.
