### ISSUE TITLE
No Plans to support MacOS?

### ISSUE THREAD

**Issue by fendou** [chromelyapps/Chromely#105]
No Plans to support MacOS?

**Comment by mattkol** [comment]
@fendou MacOS support is work-in-progress.

Please read recent comments:
https://github.com/chromelyapps/Chromely/issues/66#issuecomment-500652662
https://github.com/chromelyapps/Chromely/issues/66#issuecomment-500814818

**Comment by mattkol** [comment]
@fendou  please see - https://github.com/chromelyapps/Chromely/issues/135
