### ISSUE TITLE
PR - External Request Scheme Handler  Addition To Scheme Registration

### ISSUE THREAD

**Issue by mattkol** [chromelyapps/Chromely#108]
@Soarc just getting to testing and adding this to the configuration. I see that this is only done for CefGlue. I assume it will just be a simple replication for CefSharp. Or did you notice anything that may not work for CefSharp?

Thanks.

_Originally posted by @mattkol in https://github.com/chromelyapps/Chromely/pull/88#issuecomment-508931347_

**Comment by Soarc** [comment]
In theory it should be same. But i'm not sure - for example [here ](https://github.com/chromelyapps/Chromely/blob/d01bb156da1d9996a308a539a62c457fb89b9944/src/Chromely.CefSharp.Winapi/Browser/Handlers/CefSharpResourceSchemeHandler.cs#L115) returns stream, which should eliminate some of CefGlue's implementation complexity, but on other hand I can't see the headers placing part. 

I can investigate this later and add implementation for CefSharp as well, if it is necessary.

**Comment by mattkol** [comment]
@Soarc that is ok. I will do it. I am just wondering if there is anything I should be aware of.
Thanks.
