### ISSUE TITLE
ChromelyResponse.Status is ignored

### ISSUE THREAD

**Issue by Rodriguevb** [chromelyapps/Chromely#110]
I would like to return a code http 404 with `ChromelyResponse`. But it is ignored and replaced by a 200 code.

jquery:
```
$.ajax({
	url: myLocalUrlToCsharp,
	type: 'POST',
	dataType: "json",
	accepts: "application/json; charset=utf-8",
	data: JSON.stringify(data),
	complete: function (output) {

		// output is always:
		// {
		//	readyState: 4,
		//	responseText: "{\"Data\":\"No Data\"}",
		//	responseJSON : {"Data":"No Data"},
		//	status: 200,
		//	statusText: "Ok"
		//}
	}
});
```

C#
```
private static ChromelyResponse Connect(ChromelyRequest request)
{
	return new ChromelyResponse(request.Id)
	{
		Status = 404,
		StatusText = "Not Found",
		Data = "No Data"
	}
}
```

Can anyone explain my mistake? Thanks

**Comment by mattkol** [comment]
The status is set based on the success (or failure) of a [request processing](https://github.com/chromelyapps/Chromely/blob/5e4e3313e8906d6e046a5b503aafda201109186e/src/Chromely.CefSharp.Winapi/Browser/Handlers/CefSharpHttpSchemeHandler.cs#L65). It was not designed to be part of response data itself. If you want a status as part of the "content" then it will be part of the data, using the "Data" property. 

````csharp
private static ChromelyResponse Connect(ChromelyRequest request)
{
       var content = new SomeClass() {
	       Status = 404,
		StatusText = "Not Found",
		Data = "No Data"
       }
	return new ChromelyResponse(request.Id)
	{
		Data = content
	}
}
````

The alternative is to create a custom HTTP Scheme handler to override default behavior. Please see..[Register New Scheme](https://github.com/chromelyapps/Chromely/wiki/Restful-Resources)
