### ISSUE TITLE
How to start my application using debug mode

### ISSUE THREAD

**Issue by TheForgetTime** [chromelyapps/Chromely#111]
How do I need to configure environment variables to start my program in debug mode?

**Comment by mattkol** [comment]
@TheForgetTime Chromely does not require any special setup for debugging. You debug like any console application.

**Comment by TheForgetTime** [comment]
When I launch my project without using run or debug when I don't publish the project, it outputs something like #10

**Comment by mattkol** [comment]
Ok..I understand the issue now. Current. CEF versions are multi-process and for .net core this does not work in debug mode. It needs publishing as described in the link you sent.

Alternatively you can try the newer approach using subprocess. The demo is here..https://github.com/chromelyapps/demo-projects/tree/master/regular-chromely/CefGlueSubprocess .

This not formally released/nuget published yet, but release candidate.

With the subprocess you do not need to publish .net core first before debugging. Wiki -https://github.com/chromelyapps/Chromely/wiki/Sub-Process

**Comment by TheForgetTime** [comment]
Sorry. I can't find the name 'Subprocess' namespace in the 4.0.70 version of the nuget package.

**Comment by TheForgetTime** [comment]
Update the package on nuget.org, please.

**Comment by mattkol** [comment]
Please read my comment. It is not formally released yet. Updating nuget is part of the release process. We still have a few loose end to tie before we make a release.

Getting the latest will help too.

**Comment by TheForgetTime** [comment]
Sorry, I think my eyes may have a problem.
