### ISSUE TITLE
use gtk on  window 

### ISSUE THREAD

**Issue by TheForgetTime** [chromelyapps/Chromely#112]
When using dotnet core on windows and specifying to use the GTK platform, "Unable to load DLL 'libgtk-win32-2.0-0.dll'" is displayed.

**Comment by TheForgetTime** [comment]
https://github.com/gtksharp/gtksharp

Is it possible to use this as a gtk backend, which provides GTK3 support for the dotnet core on the window, although it is a bit cumbersome to configure.

**Comment by mattkol** [comment]
@TheForgetTime please see gtk win32 setup page - https://github.com/chromelyapps/Chromely/wiki/Getting-Started-CefGlue-Gtk-(Win)

Please note that only win32 is supported.
Thanks.

**Comment by mattkol** [comment]
Please note that this is an old wiki page and CEF binaries are no longer required to be manually downloaded.

**Comment by TheForgetTime** [comment]
Thank you for your answer.
Are you considering providing GTK3 for win64 support for this library?
The above library provides support for GTK3 for win64, and no other packages are required other than GTK3 installed in MYSYS2.

**Comment by mattkol** [comment]
There is no plan for new GTK win work.
