### ISSUE TITLE
Disable resize Chromely window

### ISSUE THREAD

**Issue by smilovich** [chromelyapps/Chromely#114]
I'm using CefGlue on windows. And would like to create non-resizable application.
How can I disable resize of Chromely window?

**Comment by mattkol** [comment]
@smilovich non-resizable feature is not implemented yet, but a feature we should have.

If you want to get your hand dirty, a quick work around it is to send or post message after window creation or set appropriate style during window creation.

I planned doing some work over the weekend, if you would like to wait, I can add the feature.

Thanks.

**Comment by mattkol** [comment]
@smilovich  nuget uploaded - please see details https://github.com/chromelyapps/Chromely/wiki/Window-Flags-and-Custom-Window-Creation-Styles

NoResize is what you need. But NoResize will only disable Max button. To remove both Min and Max boxes you can use NoMinMaxBoxes. If these flags do not do it, you can use custom styles.

Thanks.

**Comment by mattkol** [comment]
@smilovich  demo projects also have the latest - https://github.com/chromelyapps/demo-projects/tree/master/regular-chromely
