### ISSUE TITLE
Relative File path not loaded corrctly

### ISSUE THREAD

**Issue by shengzhizhou** [chromelyapps/Chromely#115]
When I copy paste the demo code, the path to certain file is not from current directory but from Debug directory,
like when I simply run the  following code, the chromely icon never loaded.
```
var config = ChromelyConfiguration
                                 .Create()
                                 .WithHostMode(WindowState.Normal)
                                 .WithHostTitle("DBMProject")
                                 .WithHostIconFile(Path.GetFullPath("chromely.ico"))
                                 ......
```
And when I debug it, it shows the absolute path is from Debug/app directory which is not shown up in file explorer. It should from the main directory which contains program.cs. How can I fix it? Thx for answering!

**Comment by mattkol** [comment]
@shengzhizhou I am not too clear on what you are trying to do.
But what you described is correct. When you are debugging the current directly is the bin/debug folder or wherever you tell the  executable file to be located.

For chromely.ico it is set to be "Copied Always" so it is in the same directly as the executable. No full path needed. If you are using a different icon located somewhere else, you can use the fullpath like "C:\chromely.ico".

To get a complete full path relative to the executable I will suggest:

``````csharp
    var appDirectory = AppDomain.CurrentDomain.BaseDirectory;
    var fullPath = Path.Combine(appDirectory, "chromely.ico");
````
The file chromely.ico must be in same folder as the executable.
