### ISSUE TITLE
subprocess on linux，white screen

### ISSUE THREAD

**Issue by TheForgetTime** [chromelyapps/Chromely#116]
Help me check my code please. White screen when I use subprocess on linux with dotnet core 3.0 preview 7

https://github.com/TheForgetTime/ChromeCefGlueVueDemo.git

**Comment by mattkol** [comment]
@TheForgetTime only thing I see missing is the runtime identifier - https://github.com/chromelyapps/Chromely/blob/4b7ee17afa8842ffca148f40a351c5fd55f52cb0/src/Tests/Chromely.CefGlue.Integration.TestApp/Chromely.CefGlue.Integration.TestApp.csproj#L6

You need to publish to linux-x64

1 | dotnet publish -r linux-x64 -c Release /p:PublishSingleFile=true /p:PublishTrimmed=true
-- | --

From:
https://www.talkingdotnet.com/create-trimmed-self-contained-executable-in-net-core-3-0/

Also I have not tried running .NET Core 3 on Linux yet, so I will be of little help. May be @FrankPfattheicher has. 

Please keep us posted on the progress made.

Thanks.

**Comment by TheForgetTime** [comment]
The program generated by using dotnet publish -r linux-x64 -c Release /p:PublishSingleFile=true /p:PublishTrimmed=true seems to change the running directory

Not sure if the CEF binary package due to this change can only be downloaded and cannot be decompressed

Is it possible to set the two variables `locales-dir-path` and `resources-dir-path` as configurable items?

$ ./PayDemo           
2019-08-08 20:50:23.400 [INFO] Running Linux chromium 70.0.3538.102
[0808/205023.542415:WARNING:resource_bundle.cc(358)] locale_file_path.empty() for locale 
[0808/205023.542514:ERROR:main_delegate.cc(707)] Could not load locale pak for en-US
[0808/205023.542554:ERROR:main_delegate.cc(714)] Could not load cef.pak
[0808/205023.542568:ERROR:main_delegate.cc(731)] Could not load cef_100_percent.pak
[0808/205023.542577:ERROR:main_delegate.cc(740)] Could not load cef_200_percent.pak
[0808/205023.542593:ERROR:main_delegate.cc(750)] Could not load cef_extensions.pak
On CefGlue child process launch arguments:
/var/tmp/.net/PayDemo/c40oxqjq.ohr/PayDemo.Subprocess --type=zygote --no-sandbox=1 --locales-dir-path=`/var/tmp/.net/PayDemo/c40oxqjq.ohr/locales` --log-file=logs/chromely.cef_new.log --log-severity=info --resources-dir-path=`/var/tmp/.net/PayDemo/c40oxqjq.ohr` --lang=en-US --host-process-id=4184 --cefgluepexitsub=1 --custom-scheme=local --custom-cmdline-args=disable-extensions|1|T;disable-gpu|1|T;disable-gpu-compositing|1|T;disable-smooth-scrolling|1|T;no-sandbox|1|T;no-zygote|1|T;disable-gpu|1|T;disable-gpu-compositing|1|T;disable-smooth-scrolling|1|T;no-sandbox|1|T;default-encoding|utf-8|T;|allow-file-access-from-files|F;|allow-universal-access-from-files|F;|disable-web-security|F;|ignore-certificate-errors|F --default-encoding=utf-8 --allow-file-access-from-files --allow-universal-access-from-files --disable-web-security --ignore-certificate-errors
LaunchProcess: failed to execvp:
/var/tmp/.net/PayDemo/c40oxqjq.ohr/PayDemo.Subprocess
[0808/205023.575823:ERROR:content_client.cc(276)] No data resource available for id 20417
[1]    4184 segmentation fault (core dumped)  ./PayDemo

\# auser @ auser-pc in ~/RiderProjects/PayDemo/PayDemo/bin/Release/netcoreapp3.0/linux-x64/publish on git:master x [20:50:24] C:139
$ export LD_LIBRARY_PATH=/home/auser/RiderProjects/PayDemo/PayDemo/bin/Release/netcoreapp3.0/linux-x64/publish

**Comment by mattkol** [comment]
@TheForgetTime 

You are getting close!

Looks like you have the cef binaries already downloaded. But if not ensure it is done - https://github.com/chromelyapps/Chromely/wiki/CefGlue-Application-Layout

The first thing I will check is to make sure the app runs without subprocess.
Then ensure that the subprocess executable is in the same folder as the app executable, that way they share same resource files.

On resource files:
Please ensure that the resource files are downloaded and in the right location.
You can override the "locale" folder location by using custom settings or command line arguments:

Custom setting:
https://github.com/chromelyapps/Chromely/wiki/Configuration#how-to-add-custom-settings
https://github.com/chromelyapps/Chromely/blob/master/src/Chromely.Core/Helpers/CefSettingKeys.cs

Command line arguments:
https://github.com/chromelyapps/Chromely/wiki/Configuration#how-to-add-additional-cef3-command-line-arguments

Also this is the old wiki for Linux - with .NET Core 3 - not sure if it is still relevant:
https://github.com/chromelyapps/Chromely/wiki/Getting-Started-CefGlue-Gtk-(Linux)
