### ISSUE TITLE
Execute c# from javascript.

### ISSUE THREAD

**Issue by KogerCoder** [chromelyapps/Chromely#117]
I am writing crossplatform wrapper on browser. Now i working with Chromely.CefGlue, please can you help me find a way to call c# method from javascript and return result synchromously. My js2csharp bridge works with Task and Promise based on callbacks, but now i searching for some way to get result from c# synchronously.
Something like:
`
  var value = Native.Call();
`

And another issue i found - CefGlueBrowser.CefBrowser.GetMainFrame().V8Context always throw native exception (something about null ptr*). So i use CefGlueBrowser.CefBrowser.GetMainFrame().ExecuteJavascript (which not return result, but it's not problem for my wrapper).

**Comment by KogerCoder** [comment]
In chromely demo i've tried to send sync XMLHttpRequest to chromely controller, but it freeze browser and not return result.

**Comment by mattkol** [comment]
@KogerCoder 


None of Chromely IPC processes support synchronous processing by design. Chromely is based on CefSharp and CefGlue and exposes what they provide. With the multiprocess feature of CEF I do not even think it is advisable to have sync processes. Reason you see the app freezing.

Chromely does not support direct access to V8. For JavaScript execution please see -
https://github.com/chromelyapps/Chromely/wiki/JavaScript-Execution

Also the demos pretty much shows what basic processes Chromely supports.

Thanks.

**Comment by KogerCoder** [comment]
I think i found solution for my problem. In 'Chromely.CefGlue.Gtk.Win.Demo' project i tried again to XMLHttpRequest synchronous request to my controller and it works. Now i can call c# method from js and get value without result without callbacks. 

Reason to use sync js2csharp is to left to make it easy to call native methods in my cross-platform wrapper (just receive value, without Promise). Some browser controls (like android WebView, which was integrated first with my wrapper) allow to make fast js2csharp calls which return value directly. Sometimes it's really usefull and faster than callbacks. But of course in most cases it's better for UX to make async calls (with callbacks).

The last time I tried this method, it caused a browser freeze. This bug, as I understand it, arose due to an error in the routing of the controller.

Controller source:
`
    [ControllerProperty(Name = "TestSyncCallsController", Route = "test_sync_calls")]
    public class TestSyncCallsController:ChromelyController
    {
        public TestSyncCallsController()
        {
            RegisterGetRequest("/test_sync_calls/test1", Test1);
        }

        public ChromelyResponse Test1(ChromelyRequest req)
        {
            ChromelyDialogs.MessageBox("Stop browser while not click 'ok'.");
            return new ChromelyResponse()
            {
                Status = 200,
                Data="Result text"
            };
        }
    }
`

Js sync call source:
`
var http = new XMLHttpRequest();
var url = 'http://chromely.com/test_sync_calls/test1';
http.open("GET", url, false);
http.send();
console.log(http.responseText);
`

Thanks for help.

**Comment by mattkol** [comment]
@KogerCoder that is interesting. 
Does it matter how long it takes? Will this work for a long running process?

**Comment by KogerCoder** [comment]
@mattkol In my example it freeze javascript execution until i click 'ok', so i think it will work for long running process too. It can be usefull when you must freeze browser ui thread while your task running, like it works in other ui frameworks (great example - this native message box).

**Comment by mattkol** [comment]
@KogerCoder got it!
Thanks.
