### ISSUE TITLE
Error: CEF runtime already initialized. at Xilium.CefGlue.CefRuntime.Initialize

### ISSUE THREAD

**Issue by KogerCoder** [chromelyapps/Chromely#119]
Hi again. My previous probem fixed, js2csharp works fine.
Now, can you help me with this:
`
2019-08-19 00:42:51.309 [INFO] Running Windows chromium 70.0.3538.102
2019-08-19 00:42:51.355 [ERROR] Oops! Something went wrong.     CEF runtime already initialized.           at Xilium.CefGlue.CefRuntime.Initialize(CefMainArgs args, CefSettings settings, CefApp application, IntPtr windowsSandboxInfo)
   at Chromely.CefGlue.BrowserWindow.HostBase.RunInternal(String[] args)
   at Chromely.CefGlue.BrowserWindow.HostBase.Run(String[] args)
`

I got this when try to open second window by Run method (in another thread). Exception from here https://github.com/chromelyapps/Chromely/blob/master/src/Chromely.CefGlue/BrowserWindow/HostBase.cs , line 449 , method `CefRuntime.Initialize(mainArgs, settings, app, IntPtr.Zero);
` . Is it bug or am i starting a new window incorrectly?

**Comment by KogerCoder** [comment]
I think better to add warning message in log when CefRuntime initialized before instead to 'killing' Run method.

**Comment by KogerCoder** [comment]
I've forked your project and rerwited method RunInternal. Add check if CefRuntime is initialized. But now there new error in Chromely.CefGlue.Winapi.BrowserWindow.NativeWindow.cs .
![1](https://user-images.githubusercontent.com/26091621/63231288-28c22700-c222-11e9-9d73-6766759d2920.JPG)

So what can i do now? It's really important for my project to run multiple windows.

**Comment by mattkol** [comment]
@KogerCoder 

I will suggest you make them 2 distinct processes and run each separately.
 
Combining them will be a lot of work. This will require you creating 2 controls - like static controls and making them parent of the browser. Doable but will require extra work.

Then add the static controls to the window.

There might be other options but this is the only one I have tried.

**Comment by KogerCoder** [comment]
Doesn't sound very good. If i will start new browser instances in another process - i think it will be hard to make fast interaction between js and c#. 
It seems easier to use CefSharp and Wpf and forget about linux support.

**Comment by mattkol** [comment]
Yes. CefSharp/CefGlue + WPF will do it. Chromely is designed for single process, single browser.
