### ISSUE TITLE
Uncaught ReferenceError: boundControllerAsync is not defined

### ISSUE THREAD

**Issue by ScottKane** [chromelyapps/Chromely#121]
I have just recreated the react sample to use CefGlue in .Net Core 2.2, I'm getting an exception after clicking "Run" on the landing page when the app starts up. Not really sure how the controller binding is being handled as the wiki mentions that registering a handler is only for CefSharp.

    2019-09-05 15:16:53.478 [INFO] Running Windows chromium 70.0.3538.102
    [0905/151655.371:INFO:CONSOLE(38)] "Uncaught ReferenceError: boundControllerAsync is not defined", source: webpack:///./src/services/registered-js-object.service.js? (38)
    [0905/151655.373:INFO:CONSOLE(9626)] "The above error occurred in the <Demo> component:
        in Demo (created by Route)
        in Route (created by App)
        in Switch (created by App)
        in Router (created by BrowserRouter)
        in BrowserRouter (created by App)
        in App

    Consider adding an error boundary to your tree to customize error handling behavior.
    Visit https://fb.me/react-error-boundaries to learn more about error boundaries.", source: webpack:///./node_modules/react-dom/cjs/react-dom.development.js? (9626)
    [0905/151655.374:INFO:CONSOLE(12408)] "Uncaught ReferenceError: boundControllerAsync is not defined", source: webpack:///./node_modules/react-dom/cjs/react-dom.development.js? (12408)

Duplicate of: https://github.com/chromelyapps/demo-projects/issues/4 (feel free to delete one)

**Comment by mattkol** [comment]
@ScottKane you  are not suppose to get any error related to boundControllerAsync for CefGlue. Something wrong with the setup.. sorry no demo for CefGlueReact .. yet

I will suggest you look at how things are done in [CefGlueAngular](https://github.com/chromelyapps/demo-projects/tree/master/angular-react-vue/ChromelyAngularCefGlue).

The equivalent in angular - [This is the equivalent for CefGlue](https://github.com/chromelyapps/demo-projects/blob/master/angular-react-vue/ChromelyAngularCefGlue/angularapp/src/app/demo/messagerouter.service.ts). 

Trying out all the normal CefGlue demos too will help.

**Comment by ScottKane** [comment]
@mattkol I used have modified the registered-js-object.service.js with the following:

    module.exports = {
        boundObjectInfoTemp: function() {
            console.log('External - info');
            return { objective: 'External - Chromely Main Objectives', platform: 'External - Platforms', version: 'External - Version' }
        },

        messageRouterResult: function (response, callback) {
            var jsonData = JSON.parse(response);
            if (jsonData.ReadyState == 4 && jsonData.Status == 200) {
            callback(jsonData.Data);
            }
        },

        messageRouterGet: function (url, parameters) {
            var request = {
                "method": "GET",
                "url": url,
                "parameters": parameters,
                "postData": null
            };
            window.cefQuery({
                request: JSON.stringify(request),
                onSuccess: function (response) {
                    messageRouterResult(response);
                }, onFailure: function (err, msg) {
                    console.log(err, msg);
                }
            });
        },

        messageRouterPost: function (url, parameters, postData) {
            var request = {
                "method": "POST",
                "url": url,
                "parameters": parameters,
                "postData": postData
            };
            window.cefQuery({
                request: JSON.stringify(request),
                onSuccess: function (response) {
                    messageRouterResult(response);
                }, onFailure: function (err, msg) {
                    console.log(err, msg);
                }
            });
        }
    }

I have replaced existing boundObjectGet() with messageRouterGet();

I'm no longer getting errors but the function doesn't return any data, worth noting I'm not a frontend dev and haven't touched much js in a long time. Can you see any reason I'm unable to get the controller response data?

Example of call from Demo.js:

    boundObjectGet1Click(event) {
        event.preventDefault()

        messageRouterGet('/democontroller/movies', null);
        //boundObjectGet('/democontroller/movies', null, response => {
        //  var jsonData = JSON.parse(response.ResponseText);
        //  if (jsonData.ReadyState == 4 && jsonData.Status == 200) {
        //    this.boundObjectGet1Callback(jsonData.Data)
        //  } else {
        //    console.log("An error occurs during message routing. With ur:" + url + ". Response received:" + response);
        //  }
        //});
    }

Once I have it working I can create a PR to save you having to recreate the demo in CefGlue and React.

Thanks in advance

**Comment by mattkol** [comment]
@ScottKane  looks like you are missing out the "callback".

Should be something like the folllowing:
Consider that this is as pseudo code - I did not test it.
Also some of this frameworks may require, you register the window methods/objects - cefQuery ..
If this is the case, please check online for how it is done for React

**** __Also I will delete everything related to boundObjectGet. That is for CefSharp.. I still see stuff from that.__

The controller client service:
````
    module.exports = {

        messageRouterGet: function (url, parameters, callback) {
            var request = {
                "method": "GET",
                "url": url,
                "parameters": parameters,
                "postData": null
            };
            window.cefQuery({
                request: JSON.stringify(request),
                onSuccess: function (response) {
                    callback(response);
                }, onFailure: function (err, msg) {
                    console.log(err, msg);
                }
            });
        },

        messageRouterPost: function (url, parameters, postData, callback) {
            var request = {
                "method": "POST",
                "url": url,
                "parameters": parameters,
                "postData": postData
            };
            window.cefQuery({
                request: JSON.stringify(request),
                onSuccess: function (response) {
                   callback(response);
                }, onFailure: function (err, msg) {
                    console.log(err, msg);
                }
            });
        }
    }
````

To make a request:

Options 1:
````
 getMoviesClick(event) {
        event.preventDefault()

        messageRouterGet('/democontroller/movies', null, response => {
			var jsonData = JSON.parse(response);
			console.log(jsonData);

        });
    }
````

Options 2:
```
 onCallback(data) {
		var jsonData = JSON.parse(response);
		console.log(jsonData);
    }
	`
 getMoviesClick(event) {
        event.preventDefault()
        messageRouterGet('/democontroller/movies', null, onCallback);
    }
````

**Comment by ScottKane** [comment]
Sorry I didn't have access to my PC for the past week, I have tried the following:

Demo.js:

    onCallbackGet1(data) {
        var jsonData = JSON.parse(data);
        console.log(jsonData);
        this.setState({
            get1Result: dataArray
        });
    }

    onCallbackGet2(data) {
        var jsonData = JSON.parse(data);
        console.log(jsonData);
        this.setState({
            get2Result: dataArray
        });
    }

    get1Click(event) {
        event.preventDefault()
        messageRouterGet('/democontroller/movies', null, this.onCallbackGet1);
    }

    get2Click(event) {
        event.preventDefault()
        messageRouterGet('/externalcontroller/movies', null, this.onCallbackGet2);
    }

Message Router:


    module.exports = {
        messageRouterGet: (url, parameters) => {
            var request = {
                "method": "GET",
                "url": url,
                "parameters": parameters,
                "postData": null
            };
            window.cefQuery({
                request: JSON.stringify(request),
                onSuccess: (callback) => {
                    response => {
                        var jsonData = JSON.parse(response);
                        if (jsonData.ReadyState == 4 && jsonData.Status == 200) {
                            callback(jsonData.Data);
                        } else {
                            console.log("An error occurs during message routing. With ur:" + url + ". Response received:" + response);
                        }
                    }
                },
                onFailure: (err, msg) => {
                    console.log(err, msg);
                }
            });
        },

        messageRouterPost: (url, parameters, postData) => {
            var request = {
                "method": "POST",
                "url": url,
                "parameters": parameters,
                "postData": JSON.stringify(postData)
            };
            window.cefQuery({
                request: JSON.stringify(request),
                onSuccess: (callback) => {
                    response => {
                        var jsonData = JSON.parse(response);
                        if (jsonData.ReadyState == 4 && jsonData.Status == 200) {
                            callback(jsonData.Data);
                        } else {
                            console.log("An error occurs during message routing. With ur:" + url + ". Response received:" + response);
                        }
                    }
                },
                onFailure: (err, msg) => {
                    console.log(err, msg);
                }
            });
        }
    }

I'm getting the following errors in the logs:

    2019-09-16 11:09:54.461 [INFO] Running Windows chromium 70.0.3538.102
    [0916/110956.402:INFO:CONSOLE(11493)] "Warning: componentWillMount has been renamed, and is not recommended for use. See https://fb.me/react-async-component-lifecycle-hooks for details.

    * Move code with side effects to componentDidMount, and set initial state in the constructor.
    * Rename componentWillMount to UNSAFE_componentWillMount to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

    Please update the following components: BrowserRouter, Route, Router, Switch", source: webpack:///./node_modules/react-dom/cjs/react-dom.development.js? (11493)
    [0916/110956.404:INFO:CONSOLE(11493)] "Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-async-component-lifecycle-hooks for details.

    * Move data fetching code or side effects to componentDidUpdate.
    * If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state
    * Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

    Please update the following components: Route, Router, Switch", source: webpack:///./node_modules/react-dom/cjs/react-dom.development.js? (11493)
    [0916/110956.669:WARNING:angle_platform_impl.cc(59)] compileToBinary(235): 
    C:\fakepath(73,10-42): warning X3571: pow(f, e) will not work for negative f, use abs(f) or conditionally handle negative values if you expect them
    C:\fakepath(95,10-42): warning X3571: pow(f, e) will not work for negative f, use abs(f) or conditionally handle negative values if you expect them

    [0916/111000.524:INFO:CONSOLE(11493)] "Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-async-component-lifecycle-hooks for details.

    * Move data fetching code or side effects to componentDidUpdate.
    * If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state
    * Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

    Please update the following components: Modal", source: webpack:///./node_modules/react-dom/cjs/react-dom.development.js? (11493)
    [0916/111000.525:INFO:CONSOLE(11493)] "Warning: componentWillUpdate has been renamed, and is not recommended for use. See https://fb.me/react-async-component-lifecycle-hooks for details.

    * Move data fetching code or side effects to componentDidUpdate.
    * Rename componentWillUpdate to UNSAFE_componentWillUpdate to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

    Please update the following components: Modal", source: webpack:///./node_modules/react-dom/cjs/react-dom.development.js? (11493)
    [0916/111001.720:INFO:CONSOLE(11493)] "Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-async-component-lifecycle-hooks for details.

    * Move data fetching code or side effects to componentDidUpdate.
    * If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state
    * Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

    Please update the following components: TabContent, Transition", source: webpack:///./node_modules/react-dom/cjs/react-dom.development.js? (11493)


None of the requests are actually returning data so I'm not convinced the controller is actually being hit.
