### ISSUE TITLE
Window move event not accessible

### ISSUE THREAD

**Issue by Dmihawk** [chromelyapps/Chromely#124]
Our current issue:
1. Open a standard HTML dropdown select control
2. Move the window to a new location

The dropdown options of the select stay in the same place on screen and don't follow the parent window. As an additional follow-on effect, if we move the window to a new location without clicking on any elements and then open the select dropdown, the options appear to be anchored the previous location (before the window was moved). Closing and re-opening the options seems to resolve the location issue

On first click:
![image](https://user-images.githubusercontent.com/11254329/64929321-051deb00-d879-11e9-8f6f-e9a14d9b92c9.png)

After moving the window down a few pixels:
![image](https://user-images.githubusercontent.com/11254329/64929351-5d54ed00-d879-11e9-82e8-f90af8044bb6.png)

A well-timed call to CefBrowserHost.NotifyMoveOrResizeStarted() appears to meet our needs, however we have been having issues hooking into an appropriate event for when the window is moved or resized in order to call the method at the right time (otherwise it will prematurely close the dropdown)

**Comment by mattkol** [comment]
@Dmihawk good you brought that up. First time I am looking closely into this.
Related to - https://magpcss.org/ceforum/viewtopic.php?f=17&t=13879 I think.

Should be something that we can do without much changes. Will look at how that fits in in the evening.

Thanks.

**Comment by mattkol** [comment]
@Dmihawk I put in an implementation - [code change](https://github.com/chromelyapps/Chromely/commit/e93c564c2fcba30049ef795831747f702dc984b0).

This is based on CEF CefClient implementation. Just smoke screen tested at the moment. Your feedbacks will determine what happens next.

Thanks.

**Comment by Dmihawk** [comment]
@mattkol thanks for that - the changes certainly look in line with what we need. We appreciate the prompt response time too!

Will the NuGet package be updated with the fix?

**Comment by mattkol** [comment]
@Dmihawk eventually it will be in Nuget for next release. 

We kindda do releases for major features or CEF/Chromium updates, Issue https://github.com/chromelyapps/Chromely/issues/96 seems like a candidate for that, So most likely when that is completed or when we have bandwidth for a CEF/Chromium updates.

Unfortunately, no fixed timeline for Nuget updates/releases.
