### ISSUE TITLE
React CefGlue

### ISSUE THREAD

**Issue by ScottKane** [chromelyapps/Chromely#125]
Sorry I was off the past week so didn't have time to try your suggestions for CefGlue with React.

I currently have the following:

Demo.js:

    onCallbackGet1(data) {
        var jsonData = JSON.parse(data);
        console.log(jsonData);
        this.setState({
            get1Result: dataArray
        });
    }

    onCallbackGet2(data) {
        var jsonData = JSON.parse(data);
        console.log(jsonData);
        this.setState({
            get2Result: dataArray
        });
    }

    get1Click(event) {
        event.preventDefault()
        messageRouterGet('/democontroller/movies', null, this.onCallbackGet1);
    }

    get2Click(event) {
        event.preventDefault()
        messageRouterGet('/externalcontroller/movies', null, this.onCallbackGet2);
    }

Message Router:

    module.exports = {
        messageRouterGet: (url, parameters) => {
            var request = {
                "method": "GET",
                "url": url,
                "parameters": parameters,
                "postData": null
            };
            window.cefQuery({
                request: JSON.stringify(request),
                onSuccess: (callback) => {
                    response => {
                        var jsonData = JSON.parse(response);
                        if (jsonData.ReadyState == 4 && jsonData.Status == 200) {
                            callback(jsonData.Data);
                        } else {
                            console.log("An error occurs during message routing. With ur:" + url + ". Response received:" + response);
                        }
                    }
                },
                onFailure: (err, msg) => {
                    console.log(err, msg);
                }
            });
        },

        messageRouterPost: (url, parameters, postData) => {
            var request = {
                "method": "POST",
                "url": url,
                "parameters": parameters,
                "postData": JSON.stringify(postData)
            };
            window.cefQuery({
                request: JSON.stringify(request),
                onSuccess: (callback) => {
                    response => {
                        var jsonData = JSON.parse(response);
                        if (jsonData.ReadyState == 4 && jsonData.Status == 200) {
                            callback(jsonData.Data);
                        } else {
                            console.log("An error occurs during message routing. With ur:" + url + ". Response received:" + response);
                        }
                    }
                },
                onFailure: (err, msg) => {
                    console.log(err, msg);
                }
            });
        }
    }

The following log is produced when I run the app, I'm not getting any errors related to the request code but no response is returned, so I'm not convinced the controller is even being hit.

    2019-09-16 11:09:54.461 [INFO] Running Windows chromium 70.0.3538.102
    [0916/110956.402:INFO:CONSOLE(11493)] "Warning: componentWillMount has been renamed, and is not recommended for use. See https://fb.me/react-async-component-lifecycle-hooks for details.

    * Move code with side effects to componentDidMount, and set initial state in the constructor.
    * Rename componentWillMount to UNSAFE_componentWillMount to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

    Please update the following components: BrowserRouter, Route, Router, Switch", source: webpack:///./node_modules/react-dom/cjs/react-dom.development.js? (11493)
    [0916/110956.404:INFO:CONSOLE(11493)] "Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-async-component-lifecycle-hooks for details.

    * Move data fetching code or side effects to componentDidUpdate.
    * If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state
    * Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

    Please update the following components: Route, Router, Switch", source: webpack:///./node_modules/react-dom/cjs/react-dom.development.js? (11493)
    [0916/110956.669:WARNING:angle_platform_impl.cc(59)] compileToBinary(235): 
    C:\fakepath(73,10-42): warning X3571: pow(f, e) will not work for negative f, use abs(f) or conditionally handle negative values if you expect them
    C:\fakepath(95,10-42): warning X3571: pow(f, e) will not work for negative f, use abs(f) or conditionally handle negative values if you expect them

    [0916/111000.524:INFO:CONSOLE(11493)] "Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-async-component-lifecycle-hooks for details.

    * Move data fetching code or side effects to componentDidUpdate.
    * If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state
    * Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

    Please update the following components: Modal", source: webpack:///./node_modules/react-dom/cjs/react-dom.development.js? (11493)
    [0916/111000.525:INFO:CONSOLE(11493)] "Warning: componentWillUpdate has been renamed, and is not recommended for use. See https://fb.me/react-async-component-lifecycle-hooks for details.

    * Move data fetching code or side effects to componentDidUpdate.
    * Rename componentWillUpdate to UNSAFE_componentWillUpdate to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

    Please update the following components: Modal", source: webpack:///./node_modules/react-dom/cjs/react-dom.development.js? (11493)
    [0916/111001.720:INFO:CONSOLE(11493)] "Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-async-component-lifecycle-hooks for details.

    * Move data fetching code or side effects to componentDidUpdate.
    * If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state
    * Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

    Please update the following components: TabContent, Transition", source: webpack:///./node_modules/react-dom/cjs/react-dom.development.js? (11493)

**Comment by mattkol** [comment]
@ScottKane 

These are all React JS warning/errors ...

The only one from Chromely is below and usual/normal:

````
[0916/110956.669:WARNING:angle_platform_impl.cc(59)] compileToBinary(235): 
C:\fakepath(73,10-42): warning X3571: pow(f, e) will not work for negative f, use abs(f) or conditionally handle negative values if you expect them
C:\fakepath(95,10-42): warning X3571: pow(f, e) will not work for negative f, use abs(f) or conditionally handle negative values if you expect them
````

React JS may be dragging the response down, but I doubt it. They seem to be warning due to mismatch of dependencies versions. You can clean that up, just to be sure.

I will also debug Chromely. You can put a break point in the Controller actions and also use DevTool to debug the JavaScipt UI.

[DevTool wiki](https://github.com/chromelyapps/Chromely/wiki/DevTool) See if there are some messages in the Console.

**Comment by ScottKane** [comment]
I have enabled UseDefaultSubprocess() and WithDebuggingMode(true). I am able to see the controller being hit and return a response but there is nothing from js side. As far as I can tell the callback isn't being hit.

**Comment by mattkol** [comment]
That is all you need in my opinion. If Chromely receives a request, it MUST send a response. Next is to figure out what is being received. May be bad data. Or wrong parsing.

Put console.log in js to see the raw response.

**Comment by mattkol** [comment]
Also looking at your code again, you are missing out the callback parameters.
Please see my previous response in the first issue.

I think you are close.

**Comment by ScottKane** [comment]
Demo.js:
    
    parseArrayResult(data) {
        var dataArray = [];

        for (var i = 0; i < data.length; i++) {
            var tempItem = {
                Id: data[i].Id,
                Title: data[i].Title,
                Votes: data[i].Votes,
                Year: data[i].Year,
                Rating: data[i].Rating,
                Date: data[i].Date,
                RestfulAssembly: data[i].RestfulAssembly
            };
            dataArray.push(tempItem);
        }
        return dataArray;
    }

    onCallbackGet1(data) {
        console.log(data);
        var dataArray = this.parseArrayResult(data);
        this.setState({
            get1Result: dataArray
        });
    }

    get1Click(event) {
        event.preventDefault()
        messageRouterGet('/democontroller/movies', null, this.onCallbackGet1);
    }

Message Router:

    messageRouterGet: (url, parameters, callback) => {
        var request = {
            "method": "GET",
            "url": url,
            "parameters": parameters,
            "postData": null
        };
        window.cefQuery({
            request: JSON.stringify(request),
            onSuccess: (response) => {
                var jsonData = JSON.parse(response);
                if (jsonData.ReadyState == 4 && jsonData.Status == 200) {
                    if(callback) callback(jsonData.Data);
                } else {
                    console.log("An error occurs during message routing. With ur:" + url + ". Response received:" + response);
                }
            },
            onFailure: (err, msg) => {
                console.log(err, msg);
            }
        });
    },

    messageRouterPost: (url, parameters, postData) => {
        var request = {
            "method": "POST",
            "url": url,
            "parameters": parameters,
            "postData": JSON.stringify(postData)
        };
        window.cefQuery({
            request: JSON.stringify(request),
            onSuccess: (response) => {
                var jsonData = JSON.parse(response);
                if (jsonData.ReadyState == 4 && jsonData.Status == 200) {
                    if(callback) callback(jsonData.Data);
                } else {
                    console.log("An error occurs during message routing. With ur:" + url + ". Response received:" + response);
                }
            },
            onFailure: (err, msg) => {
                console.log(err, msg);
            }
        });
    }

console.log() in callback is printing the response object, but in the console I am getting:

    Uncaught ReferenceError: parseArrayResult is not defined
        at onCallbackGet1 (Demo.js:177)
        at onSuccess (registered-js-object.service.js:20)

**Comment by mattkol** [comment]
That is all you need. You are receiving something back. As long as in Controller action the right data is being sent back, what is left is to successfully parse the data.

I will first ensure the data is correct. Use all related js methods - parseJson, JsonStringify etc. Or if you are using typescript..use the functions too. Anything to help you see the response in json format in the console.

From my end there is really nothing more that I can do to help.

**Comment by ScottKane** [comment]
Ok thanks for all your advice, it's almost working now so I'm sure I will get it fixed

**Comment by mattkol** [comment]
@ScottKane  I think so too. Usually what happens is some of these frameworks send data in their pipelines differently. Just needs parsing the data as expected by the framework.

So we are still on course on you sharing the final CefGlue React with the project?
