### ISSUE TITLE
loading html from dll

### ISSUE THREAD

**Issue by Naicos** [chromelyapps/Chromely#126]
We're trying to use chromely as UI for an Installer. 
For this task we need to load the html file from a dll as embedded recource.
Till now we did not got this working.
Is there already a way to get this to work?

**Comment by mattkol** [comment]
@Naicos interesting ...
No not specifically, but I think it can be done.

You can see how CefGlue subprocess executable is embedded.

- Embedding:
https://github.com/chromelyapps/Chromely/blob/e93c564c2fcba30049ef795831747f702dc984b0/src/Chromely.CefGlue/Chromely.CefGlue.csproj#L63

Watch carefully the embedding path.
Example:
If the project file is in PROJ and namespace is PROJ, the resource must be as below:
Assume embedding dll name is EMBED.DLL
"C:\PROJ\EMBEDFOLDER\EMBED.DLL"

EMBEDFOLDER\ EMBED.DLL

Namespace may be an impact too.

- Extraction:
[DefaultSubprocessExe](https://github.com/chromelyapps/Chromely/blob/master/src/Chromely.CefGlue/Subprocess/DefaultSubprocessExe.cs)

string resourcePath = "EMBED.DLL.launch.html";
Namespace may be an impact too.

https://github.com/chromelyapps/Chromely/blob/e93c564c2fcba30049ef795831747f702dc984b0/src/Chromely.CefGlue/Subprocess/DefaultSubprocessExe.cs#L116

------
Only need to make sure that the extraction is done before launching Chromely.

**Comment by Fiahblade** [comment]
This is actually very interesting, what if Chromely could natively package the HTML files for you?
