### ISSUE TITLE
Embedding browser in my window

### ISSUE THREAD

**Issue by mrazman9** [chromelyapps/Chromely#127]
Hi, 
All your examples show how to run chromely by creating a ChromelyWindow. But I need to embed chromium into my own window. Is it possible to get instance of a browser as a WPF ContentControl  and embed it into a custom WPF window without need to create the ChromelyWindow instance?

**Comment by mattkol** [comment]
@mrazman9  yes, it is possible. However, it is not an objective of this project and not supported.

Please see summary:

_Chromely is a .NET/.NET Core HTML5 Chromium desktop framework. It is focused on building apps based on Xilium.CefGlue, CefSharp implementations of embedded Chromium (CEF) without WinForms or WPF. Chromely uses Windows and Linux native GUI API as "thin" chromium hosts. It can be extended to use WinForms or WPF._

So to make it work, will require some work from your end. 

Thanks.
