### ISSUE TITLE
Not showing in Windows task bar

### ISSUE THREAD

**Issue by campaignium** [chromelyapps/Chromely#129]
Cool stuff. Just started playing around with this. Is there a setting/argument for CEF i'm missing to make the window show in Windows task bar? Is this a bug?

**Comment by mattkol** [comment]
No, you do not have to do anything.

If you are running any of the [demos](https://github.com/chromelyapps/demo-projects/tree/master/regular-chromely) - you should see something like this on the Task Manager and Task Bar.

![image](https://user-images.githubusercontent.com/18384207/67057636-f5fbb880-f116-11e9-8271-fda22657588d.png)

**Comment by campaignium** [comment]
It shows under 'Background processes' for me in Task Manager and does not show in the Task Bar. I'm running the Vue demo by the way

![image](https://user-images.githubusercontent.com/3458664/67325148-4d64a480-f4da-11e9-9c55-42743a58c2c1.png)
