### ISSUE TITLE
cefglue_gtk_linux_demo.deps.json has already been found but with a different file extension

### ISSUE THREAD

**Issue by rhombask** [chromelyapps/Chromely#132]
Hi, all
I am new to Chromely.
I was trying to run the demo of "Chromely.CefGlue.Gtk.Linux.Demo" project as below.
$dotnet cefglue_gtk_linux_demo.exe
in my Ubuntu 18.04 machine.
And I am getting this error.

Error:
  An assembly specified in the application dependencies manifest (cefglue_gtk_linux_demo.deps.json) has already been found but with a different file extension:
    package: 'cefglue_gtk_linux_demo', version: '1.0.0'
    path: 'cefglue_gtk_linux_demo.dll'
    previously found assembly: '/home/user/Downloads/netcoreapp3.0/cefglue_gtk_linux_demo.exe'

Do you have any idea how to fix this?

**Comment by mattkol** [comment]
@rhombask seems like a conflict in builds. Do you have more than one builds? I will clean up and rebuild again. Deleting all files in bin.

Also if you already publish the exe you do not need to use dotnet to run:
$dotnet cefglue_gtk_linux_demo.exe

What you need to do is:
$./cefglue_gtk_linux_demo.exe

Check this page for how to [publish](https://blogs.msdn.microsoft.com/luisdem/2017/03/19/net-core-1-1-how-to-publish-a-self-contained-application/) for more info.

Thanks.

**Comment by rhombask** [comment]
I have Visual Studio 2017 and 2019 in my PC.
Did you mean this might cause problems?

**Comment by mattkol** [comment]
It can be anything.
I assume then that you are publishing on a Windows PC and running on Linux. Right?
If that is the case, I do not see how that can be an issue as long as you are copying all your published files from the same folder to Linux.

**Comment by rhombask** [comment]
Nop, I have 2 computers.

**1st One**
Windows 10
Visual Studio 2019(I uninstalled every other verions)
Build "Chromely.CefGlue.Gtk.Linux.Demo" project and copy the whole "Chromely.CefGlue.Gtk.Linux.Demo\bin\x64\Debug\netcoreapp3.0" folder to USB flash disk

**2nd One**
Ubuntu 18.04
mono installed
.NET Core SDK 3.0 installed via https://dotnet.microsoft.com/download/linux-package-manager/ubuntu16-04/sdk-current
Run the command below
(I did not publish as a self-contained application)
$ dotnet cefglue_gtk_linux_demo.exe

And I get this error below:
Error:
 An assembly specified in the application dependencies manifest (cefglue_gtk_linux_demo.deps.json) has already been found but with a different file extension:
   package: 'cefglue_gtk_linux_demo', version: '1.0.0'
   path: 'cefglue_gtk_linux_demo.dll'
   previously found assembly: '/home/jmson/Downloads/netcoreapp3.0/cefglue_gtk_linux_demo.exe'

**Comment by mattkol** [comment]
Ok.

you can do the following:

- Publish the exe - at least you will know you are not missing any relevant files. You can use Windows but the best result is to publish on Linux. You can use Visual Studio Code for that.
- Rename the executable file in your project file - 
https://github.com/chromelyapps/demo-projects/blob/4d244c427a843bafe0cb6dead1b900be36c2b694/regular-chromely/Chromely.CefGlue.Gtk.Linux.Demo/Chromely.CefGlue.Gtk.Linux.Demo.csproj#L11
