### ISSUE TITLE
Add support for loading pages from raw HTML strings

### ISSUE THREAD

**Issue by LazDisco** [chromelyapps/Chromely#133]
Hello. I was looking around for something like this project, and it seems pretty good and does everything I want and more, except for the raw html parsing. The main reason I'm after this, is that I want to use it some projects that would require the HTML files to be embedded in DLLs, along with other content.

The issue here lies in that we can't just extract the content to the disk, and thus we cannot use it as it currently stands. For all I know, this could be possible, and I just didn't find out how during my research on this. If that's the case, I'd appreciate a nudge in the right direction, thanks.

**Comment by mattkol** [comment]
@LazDisco it really does not matter how your HTML and content files are packaged. What is important is to extract them to appropriate files before the Window is created.

Please see similar issue:
https://github.com/chromelyapps/Chromely/issues/126

You can also do a search on how to do that..
Some examples:
https://www.c-sharpcorner.com/uploadfile/40e97e/saving-an-embedded-file-in-C-Sharp/
http://www.vcskicks.com/embedded-resource.php

**Comment by FrankPfattheicher** [comment]
@LazDisco maybe you want to have a look at my stonehenge3 project also.
It uses all html files as embedded ressources.
There is a sample in combination with chromely: https://github.com/FrankPfattheicher/stonehenge.Chromely
There is a presentation also describing the ideas...

**Comment by LazDisco** [comment]
Very cool stuff, clearly I didn't research enough! I'll give those links a read and close the issue for now, I'll reopen if I have additional questions. Thanks for the hasty response.
