### ISSUE TITLE
DefaultResourceSchemeHandler: Empty files are stuck "Pending"

### ISSUE THREAD

**Issue by WolfspiritM** [chromelyapps/Chromely#134]
Hi,

Thanks for this awesome library!

I faced a very strange problem where an angular prod build caused the whole page to not display anything at all but the javascript code did run. I then noticed that the prod build for angular creates a style.css which was empty in my case.

Checking the devtools shows that file as "Pending..." which never finished loading.

I'm using CefGlue with UseDefaultResourceSchemeHandler("local", string.Empty).

I've also tested this with a test.js file that is empty and devtools shows that as "Pending..." all the time aswell.

**Comment by mattkol** [comment]
@WolfspiritM interesting ...
We should look at ignoring empty files to see if that will help.
I will take a look and see by weekend,
Thanks.

**Comment by mattkol** [comment]
@WolfspiritM a fix is in - https://github.com/chromelyapps/Chromely/commit/eae5586e4af5391e16a311da4b2f683b19580c11

Keep us posted.
