### ISSUE TITLE
.NET Core 3.0 and MacOS Support

### ISSUE THREAD

**Issue by mattkol** [chromelyapps/Chromely#135]
Chromely is adding:
- .NET Core 3 Support
- MacOS Support

For more info please see [Migration to .NET Core 3 and MacOS Support](https://github.com/chromelyapps/Chromely/wiki/Migration-to-.NET-Core-3-and-MacOS-Support).

Comments, issues and feedbacks will be tracked here.

**Comment by fendou** [comment]
Thanks!

**Comment by Fiahblade** [comment]
Was added in Chromely v5.
