### ISSUE TITLE
How to listen for a C# event in a JS file?

### ISSUE THREAD

**Issue by stevendevit** [chromelyapps/Chromely#138]
I can request data to a REST Controller but what if I want to listen for a event called from the C# Application? How I would do that?

**Comment by mattkol** [comment]
@stevendevit so like you have an event in the Browser (C# code) that will trigger an action in Renderer (JS code?

If that is the case I will suggest you implement a JavaScript Executor controller like in the Demos - [ExecuteJavaScriptDemoController]( https://github.com/chromelyapps/demo-projects/blob/master/regular-chromely/CrossPlatDemo/Controllers/ExecuteJavaScriptDemoController.cs) 

In JavaScript:

````javascript
function methodAction() {
}
````

In C#:

````csharp
private void onEventTrigger()
{
------
scriptExecutor.ExecuteScript("methodAction()");
}
````
Alternatively you can run polling/timer in JS that will continuously check what is happening in the C# code.
