### ISSUE TITLE
Reload Page  / Window

### ISSUE THREAD

**Issue by stevendevit** [chromelyapps/Chromely#140]
How to reload the page / window via C# code?

**Comment by mattkol** [comment]
@stevendevit sorry for the late response.

You can do it in many ways. You need the "Browser" object to that.

You can use the implementation of [IChromelyWindow](https://github.com/chromelyapps/Chromely/blob/master/src/Chromely.Core/Host/IChromelyWindow.cs) or [IChromelyJavaScriptExecutor](https://github.com/chromelyapps/Chromely/blob/master/src/Chromely.Core/IChromelyJavaScriptExecutor.cs).

Sample using Command route:

````chsarp
        [Command(Route = "/controllersample/reload")]
        public void Reload(IDictionary<string, string> queryParameters)
        {
            var scriptExecutor = _config?.JavaScriptExecutor;
            if (scriptExecutor != null)
            {
                Xilium.CefGlue.CefBrowser browser = scriptExecutor.GetBrowser() as Xilium.CefGlue.CefBrowser;
                if (browser != null)
                {
                    browser.Reload();
                }
            }
        }
````

Please check [ExecuteJavaScriptDemoController](https://github.com/chromelyapps/demo-projects/blob/master/regular-chromely/CrossPlatDemo/Controllers/ExecuteJavaScriptDemoController.cs) to see how IChromelyJavaScriptExecutor is implemented.

Thanks.
