### ISSUE TITLE
Add Stylesheets / Scripts

### ISSUE THREAD

**Issue by aheadit** [chromelyapps/Chromely#141]
Does anyone know how to add custom stylesheets or scripts. I tried to add stylesheets as .css file and javascript as .js but the html page is not able to import it. The only time it works on the html page is when i include the contents of the css or js file inside the script tags or style tags of the page. is there a special way to add stylesheet (except link rel href?) i tried with different locations and nothing seemed to work. thanks in advance

**Comment by mattkol** [comment]
@aheadit please make sure the files are set to "Copy Always" or "Copy If Newer" to output. And also ensure that the relative path is correct.

Please see how it is done in the demos.

https://github.com/chromelyapps/demo-projects/blob/e00ba1939c8c67788f968c3b844625117df4481c/regular-chromely/CrossPlatDemo/CrossPlatDemo.csproj#L31

https://github.com/chromelyapps/demo-projects/blob/e00ba1939c8c67788f968c3b844625117df4481c/regular-chromely/CrossPlatDemo/CrossPlatDemo.csproj#L52

In the bin folder, the .css files and .js files must exist there.

If you are using Angular, React or Vue or other similar Frontend framework, you have to check to see how the packing is done for that framework.
