### ISSUE TITLE
Wiki: Create new project references wrong nuget

### ISSUE THREAD

**Issue by 8** [chromelyapps/Chromely#142]
Hi,

I've just completed:
https://github.com/chromelyapps/Chromely/wiki/create-new-project-from-scratch

and couldn't build the application, because of a small error in the wiki,
the package that should be referenced needs to be `Chromely` instead of `Chromely.Core` as `Chromely.Core` does not contain `BasicChromelyApp`.

I am not aware of any way to create pull requests for Wikis on github, if you can point me towards such a resource, I can create a pull request for that.

Take care,
Martin

**Comment by Fiahblade** [comment]
Yes you are correct, typo on my end. Has been fixed, thanks!

**Comment by 8** [comment]
Thnx!
