### ISSUE TITLE
Configuration Can't be changed

### ISSUE THREAD

**Issue by asmodat** [chromelyapps/Chromely#145]
I am using `dotnet add package Chromely --version 5.0.77-pre01` and trying to programmatically change the configuration of the default window without success.

Here is one of my attempts:

```
  IChromelyConfiguration uiConfig= null;

            if (RuntimeEx.IsWindows())
                uiConfig = DefaultConfiguration.CreateOSDefault(ChromelyPlatform.Windows);
            else if (RuntimeEx.IsLinux())
                uiConfig = DefaultConfiguration.CreateOSDefault(ChromelyPlatform.Linux);
            else if (RuntimeEx.IsOSX())
                uiConfig = DefaultConfiguration.CreateOSDefault(ChromelyPlatform.MacOSX);
            else
                uiConfig = DefaultConfiguration.CreateOSDefault(ChromelyPlatform.NotSupported);
            uiConfig.WindowTitle = "Test App";
            uiConfig.AppName = "Test App";
            uiConfig.StartUrl = "https://google.com";

       AppBuilder
                .Create()
                .UseConfiguration<IChromelyConfiguration>(uiConfig)
                .UseApp<TestApp>()
                .Build()
                .Run(args));
```

Furthermore its not extremely clear how to interact with the webpage, capture events and trigger them, e.g. clipboard access, page navigation and so on

**Comment by mattkol** [comment]
@asmodat I just tried the same config and it works on Windows 10. The only thing I changed is .Run(args)); to .Run(args);

![image](https://user-images.githubusercontent.com/18384207/71318435-955e6400-2456-11ea-9efe-ea10acc1c669.png)

We are still working on the final wiki, but if you play with the [demos](https://github.com/chromelyapps/demo-projects) I believe there is enough info to get you started. There is also some documentation [here](https://github.com/chromelyapps/Chromely/tree/master/Documents). Also the [old wiki](https://github.com/chromelyapps/Chromely.Legacy/wiki) is still valid for basic processes.

**Comment by mattkol** [comment]
@asmodat Chromely does not handle page navigation. You can use JavaScript/jQuery to do that. If you use Angular/React/Vue .. you can see samples in the demos how those framework deal with routing.

**Comment by IlyaSemenov** [comment]
@asmodat I think instead of triple switch/case you can use `ChromelyRuntime.Platform` (at least it's what Chromely does itself):

```cs
            var config = DefaultConfiguration.CreateOSDefault(ChromelyRuntime.Platform);
            config.StartUrl = "https://google.com/";

            AppBuilder
                .Create()
                .UseConfiguration<IChromelyConfiguration>(config)
                .UseApp<DemoChromelyApp>()
                .Build()
                .Run(args);
```

**Comment by 8** [comment]
Hi,
I think most of the configuration works - e.g. adding UrlSchemes, WindowWidth, WindowHeight, StartUrl, DebuggingMode and UrlSchemes.

What is not working is the WindowTitle AFAIK - I guess you expect the title of the window to change from "Chromely" to "Test App". I've looked at the code, but IChromelyConfiguration has been refactored since the release of the nuget.

So I guess your config is working except for the window title.

Take care,
Martin

**Comment by 8** [comment]
Found it, it is already fixed in https://github.com/chromelyapps/Chromely/commit/ed9968ce2ad6a27ce97222cf70e7b6571d98604c

**Comment by mattkol** [comment]
@asmodat good catch! We are getting there.
Thanks.

**Comment by Fiahblade** [comment]
**For future reference**

`DefaultConfiguration.CreateOSDefault` has been renamed to `DefaultConfiguration.CreateConfigurationForPlatform` But looking at it now, that's a horrible name. 

`DefaultConfiguration.CreateForPlatform` seems better and perhaps even a separate method (with no parameters) to create a config for the current OS.
`DefaultConfiguration.CreateForCurrentPlatform()`

**Comment by mattkol** [comment]
@Fiahblade great!
Do you also think we should move the file to Defaults folder - https://github.com/chromelyapps/Chromely/tree/master/src/Chromely.Core/Defaults
I am fine with it either way.

Thanks.

**Comment by Fiahblade** [comment]
@mattkol I moved it out of there because at the time I felt that it fitted more under the Configuration namespace (and that everything under Default could fit somewhere else) but now I don't know any more.

**Comment by mattkol** [comment]
@Fiahblade lol! I thought I did.
Lets leave it then.

**Comment by Fiahblade** [comment]
Wiki has been updated. Thanks for everyone's feedback!
[https://github.com/chromelyapps/Chromely/wiki/configuration](https://github.com/chromelyapps/Chromely/wiki/configuration)
