### ISSUE TITLE
Allow to use Embedded Resource in Chromely

### ISSUE THREAD

**Issue by daricvn** [chromelyapps/Chromely#147]
Currently I'm trying to develop a new application on .net core.
I wish to create a local application without exposing the UI html at all. Usually I will hide them by adding the resources as the embedded resources. 
However, latest Chromely does not allow me to do that anymore.
I tried to do that via Controller, but Chromely encoded it anyway.
If you could implement an Assembly type in UrlScheme or give the ChromelyResponse an option not to encode the response body it would be nice, please.

Thank you.

**Comment by mattkol** [comment]
@daricvn not quite sure, I understand what exactly you are trying to do. If it is related to https://github.com/chromelyapps/Chromely/issues/126 then you can do the resource extraction here:

https://github.com/chromelyapps/demo-projects/blob/1cc118d55dafeb1762976dd65c0f6a2f0345a321/regular-chromely/CrossPlatDemo/Program.cs#L27

If this is not it, you can share snippet of what you used to do.

Thanks.

**Comment by daricvn** [comment]
Hello @mattkol ,

What I understand from your answer in the #126 is "Extract it before the Chromely start up". Please correct me if I'm wrong.
Actually the point I want to say here is let chromely read from the assembly instead of extract the file from the dll.
I've taken a look at the source code and found that Chromely only support reading resource files from local only via File.ReadAllText. The thing I mentioned is Assembly.GetManifestResourceStream. 

Regards.

**Comment by mattkol** [comment]
@daricvn  yes, that is what I mean. Extract before Chromely starts.

I kind of understand what you meant. I am trying though to see if what you described will be a general use case or just what a custom resource handler needs to do.

If you think it is a going to be widely used, it is something we can incorporate. Otherwise I will suggest a custom resource handler. I am curious so won't mind to be of help.

Thanks.

**Comment by daricvn** [comment]
@mattkol 
I think it would be great if Chromely have a Custom Resource Handler, I think I can customize many thing there while people could do that in the legacy one.
Regarding to the Assembly support I suggested, I think it may be widely used in future. Personally, I always want my app become more secure, I believe there're many developers want to hide their HTML in their app too (ex: Discord).

Thanks & regards.

**Comment by mattkol** [comment]
@daricvn yes, you can register a custom resource handling. The wiki is gradually being updated - we are not there yet, but legacy wiki is still relevant,

I just updated the documents to include resource handling registration - https://github.com/chromelyapps/Chromely/blob/master/Documents/registering_resource_handlers.md

Please let me know if this is helpful.

If you create a custom handler to do what you suggest, we can incorporate into Chromely.

Thanks.

**Comment by daricvn** [comment]
@mattkol 
Oh my god, this is exactly what I need, it's super helpful!
Thank you very much 👍

**Comment by daricvn** [comment]
@mattkol 
If you don't mind and want to include that feature in Chromely code, you can use my code as below, just update it:
UrlScheme.cs:
```csharp
        /// <summary>
        /// Option setting for Assembly type
        /// </summary>
        public AssemblyOptions AssemblyOptions { get; set; }
 ```

AssemblyOptions.cs
```csharp
    public class AssemblyOptions
    {
        public Assembly TargetAssembly { get; set; }
        public string Prefix { get; set; }
        public AssemblyOptions(Assembly target, string prefix = null)
        {
            if (prefix == null)
                prefix = target.GetName().Name;
            TargetAssembly = target;
            Prefix = prefix;
        }
    }
```

UrlSchemeCollectionExtension.cs
```csharp
        public static List<UrlScheme> GetSchemeList(this List<UrlScheme> urlSchemes, string url, UrlSchemeType type)
        {
            if (urlSchemes == null ||
                 urlSchemes.Count==0 ||
                 string.IsNullOrWhiteSpace(url))
                return null;

            return urlSchemes.Where((x => x.IsUrlOfSameScheme(url) && (x.UrlSchemeType == type))).ToList();
        }
```

CefGlueAssemblySchemeHandler.cs (new, copied from CefGlueResourceSchemeHandler
```csharp

        private Regex _regex = new Regex("[/]");

        public CefGlueAssemblySchemeHandler(IChromelyConfiguration config)
        {
            _config = config;
        }

        [Obsolete]
        protected override bool ProcessRequest(CefRequest request, CefCallback callback)
        {
            var u = new Uri(request.Url);
            var assembly = _config?.UrlSchemes?.GetSchemeList(request.Url, UrlSchemeType.Assembly);
            var file = u.Authority + u.AbsolutePath;
            if (string.IsNullOrEmpty(Path.GetFileName(file)))
                file = Path.Combine(file, "index.html");

            _totalBytesRead = 0;
            _fileBytes = null;
            _completed = false;

            // Check the configured url scheme
            if (assembly != null && assembly.Count > 0)
            {
                var option = assembly.FirstOrDefault()?.AssemblyOptions;
                if (option != null && option.TargetAssembly != null) {
                    var manifestName = string.Join(".", option.Prefix, _regex.Replace(file, ".")).Replace("..", ".");
                    var stream = option.TargetAssembly.GetManifestResourceStream(manifestName);
                    if (stream !=null && stream.Length>0)
                    {
                        Task.Run(() =>
                        {
                            using (callback)
                            {
                                try
                                {
                                    _fileBytes = new byte[stream.Length];
                                    stream.Read(_fileBytes, 0, (int)stream.Length);
                                    stream.Flush();
                                    stream.Dispose();
                                    string extension = Path.GetExtension(file);
                                    _mime = MimeMapper.GetMimeType(extension);
                                }
                                catch (Exception exception)
                                {
                                    Logger.Instance.Log.Error(exception);
                                }
                                finally
                                {
                                    callback.Continue();
                                }
                            }
                        });

                        return true;
                    }
                    else
                    {
                        if (stream!=null)
                            stream.Dispose();
                    }
                }
            }
            callback.Dispose();
            return false;
        }
```

Usage: Place the resource in the project, and set its build action to Embedded Resource
Example: I placed the index.html in app/ folder, set it build action to Embedded Resource.
```csharp
              UrlSchemes= new List<UrlScheme>()
              {
                  new UrlScheme("assembly","local","app","", UrlSchemeType.Assembly, false,
                    assemblyOptions: new AssemblyOptions(Assembly.GetExecutingAssembly()))
              }
```
Then just register the related Factory in the same place where ResourceHandler take place.

**Comment by mattkol** [comment]
@daricvn this is great! I see the point, will surely help with security. 

For this to work for a general adoption, all resources must be embedded, right? Or just a portion can be? Meaning would we need to allow multiple resource schemes? 

I am on vacation, so not really tried anything out yet. I should play with this by next  weekend.

Thanks.

**Comment by daricvn** [comment]
@mattkol 
I'm happy to hear that from you.

Yes by using this approach we can add many UrlSchemes to handle both embedded and local resource. A project/file folder can contains both embedded and local resource. However, one specific file can only have one specific build action.

My test project contains both Assembly and Local Resource to switch between Debug and Release mode for easier development progress when working with Vue or Angular.

Have a wonderful vacation.

**Comment by mattkol** [comment]
@daricvn this is now implemented - https://github.com/chromelyapps/Chromely/commit/a5fcb9059073c90548f16eabe622e3c12b306d85

Usage
````csharp
     var config = DefaultConfiguration.CreateForRuntimePlatform();
      config.StartUrl = "assembly://app/chromely.html";
````

[Demo](https://github.com/chromelyapps/demo-projects/tree/master/regular-chromely/CrossPlatDemo).

Note that the embedding is done in the project: [Chromely.External.Controllers](https://github.com/chromelyapps/demo-projects/blob/258a06d37112c04cb72cb2299141cbfa37cea057/regular-chromely/Chromely.External.Controllers/Chromely.External.Controllers.csproj#L17). 

I did not test the mix yet, but looks like we should be fine.

Please let me know if I miss anything.

Definitely a cool useful feature 👍.

Thanks.

**Comment by mattkol** [comment]
@daricvn I am just thinking about the mix, just joggling in my mind how best it could be be achieved without the developer creating 2 handlers.

What about we bring the default resource handler logic into the assembly resource handler

More like:

````chsarp
  protected override bool ProcessRequest(CefRequest request, CefCallback callback)
  {
       check if exists in assembly
	     - process for assembly
       else 
             - use default handler logic
  }
````
Your thoughts?

I just need more time to prove these scenarios, but let me know what you have tried at your end.

**Comment by daricvn** [comment]
Hi @mattkol 
It's great to see you again and very excite to see new implement for Chromely. 

Regarding the mix option. In my opinion,I think it's great to have that feature, it gives developers a much easier way to debug their code. 
FYI, for more convenient, you can also guide them to assemble their resources easily by doing this in their .csproj file:

> <EmbeddedResource Include="..\Project\*.*" />
It works for .Net framework so I guess it works on .Net core too.
Just hit build and let the compiler do the work. Especially for Vue/Angular/React developer.

**Comment by mattkol** [comment]
@daricvn  I did not quite get the embedding in .csproj file.

```xml 
<EmbeddedResource Include="..\Project\*.*" />
```

You mean:

What we have should be:

```xml 
<EmbeddedResource Include="app\*.*" />
```

Just wondering if "Project" itself is a keyword or a folder in your local directory.

Thanks.

**Comment by daricvn** [comment]
@mattkol Sorry for the late reply, just return from the vacation.
Yes it's. What i want to point out is you can include embedded resource by using wildcard, I think that would be helpful if you want to use Vue/Angular/React to build the app's interface.

**Comment by mattkol** [comment]
@daricvn nice one -  welcome back!
I thought so too - wildcard .. just thought I should clarify and not assume.
Thanks for getting back on this.
