### ISSUE TITLE
WindowKioskMode Cause Application to Crash

### ISSUE THREAD

**Issue by Ayajatra** [chromelyapps/Chromely#149]
Hi, I was trying to use Kiosk Mode with this code:
```csharp
var configuration = DefaultConfiguration.CreateOSDefault(ChromelyPlatform.Windows);
configuration.WindowKioskMode = true;

AppBuilder
    .Create()
    .UseApp<MyChromelyApp>()
    .UseConfiguration<IChromelyConfiguration>(configuration)
    .Build()
    .Run(args);
```
But when I start the application, this error show up:
```
2020-01-06 23:37:30.191 [ERROR] Assembly file: Chromely.External.Controllers.dll does not exist.`
2020-01-06 23:37:30.433 [INFO] Running Windows chromium 77.0.3865.120
[0106/233730.512:FATAL:tsf_text_store.cc(32)] Failed to initialize CategoryMgr.
```

The Chromely window did not show up, only the console show up.

I'm using Windows 10 64 bit

**Comment by mattkol** [comment]
@Ayajatra the configuration works for me.
Does the normal, non-kiosk mode work?

**Comment by Ayajatra** [comment]
@mattkol The normal configuration (non-kiosk mode) work, the error only occur when kiosk-mode is enabled.

**Comment by mattkol** [comment]
@Ayajatra works for me, with released versions and latest source code.

My colleague @Fiahblade  has also made some nice recent changes/cleanups, and using the latest source code it works well. @Fiahblade may also help us here (if he has some bandwidth), to eliminate environment issue.

Please can you use the recent nuget (pre03) dlls or source code directly. Lets see what we could be missing. Please use:

````csharp
    class Program
    {
        [STAThread]
        static void Main(string[] args)
        {
            var uiConfig = DefaultConfiguration.CreateForPlatform(ChromelyPlatform.Windows);
            uiConfig.WindowOptions.KioskMode = true;

            AppBuilder
                     .Create()
                      .UseApp<MyChromelyApp>()
                     .UseConfiguration<IChromelyConfiguration>(uiConfig)
                     .Build()
                     .Run(args);
        }
    }

    public class MyChromelyApp: BasicChromelyApp
    {
    }
````
- Please note the change in setting the Kiosk option.

**Comment by Ayajatra** [comment]
Thanks, it's working without problem now. Using the pre03 fixed the problem.

**Comment by mattkol** [comment]
@Ayajatra interesting!
So likely recent changes fixed that.
Thanks for helping with that.

**Comment by simonbuehler** [comment]
hi,

tried the same with pre03 and it also crashes for me, how can i debug this?

**Comment by mattkol** [comment]
@Ayajatra it will be difficult at these stage to debug pre03, as pre03 code has been modified a lot. Can you please try the source code.

I also just tried it too ..
[KioskModeDemo.zip](https://github.com/chromelyapps/Chromely/files/4159629/KioskModeDemo.zip)

![image](https://user-images.githubusercontent.com/18384207/73844958-3aef4c00-47e7-11ea-9a9a-5258b35b3f46.png)

**Comment by SirePi** [comment]
Sorry to reopen the issue, but I'm having the issue with v.5.0.77.1
```csharp
static void Main(string[] args)
{
	var config = DefaultConfiguration.CreateForRuntimePlatform();
	config.WindowOptions.KioskMode = true;

	AppBuilder
		.Create()
		.UseConfiguration<IChromelyConfiguration>(config)
		.UseApp<ChromelyApp>()
		.Build()
		.Run(args);
}
```

and I end up with
```
2020-03-05 20:07:16.567 [INFO] Running Windows chromium 77.0.3865.120
[0305/200716.934:FATAL:tsf_text_store.cc(32)] Failed to initialize CategoryMgr.
```

**Comment by mattkol** [comment]
Cannot reproduce.
