### ISSUE TITLE
Chromely window handle is always zero on Windows

### ISSUE THREAD

**Issue by donotcodeit** [chromelyapps/Chromely#152]
On my current project I need to control window minimize/maximize functions from the web application. I am trying to migrate the code from this example:
https://github.com/chromelyapps/Chromely.Legacy/tree/master/Demos/regular-chromely/frameless_draggable_command/Chromely.CefGlue.Winapi.Demo

`IChromelyWindow` is well injected by a container, but its `Handle` has always `IntPtr.Zero` value.

During the investigation, I've found this line of code, and it seems incomplete:
https://github.com/chromelyapps/Chromely/blob/9e7b079053279df51487a5940a6c8db054574cd3/src/Chromely/Windows/NativeWindow.cs#L22

Sadly, I don't have a time to make a pull request, but I can suggest a solution, or idea at least.

`IChromelyNativeHost` can expose a window handle as a property, and `Chromely.Native.WinAPIHost` can pass this field as a value:
https://github.com/chromelyapps/Chromely/blob/9e7b079053279df51487a5940a6c8db054574cd3/src/Chromely/Native/WinAPI/WinAPIHost.cs#L23

Then `Chromely.Windows.NativeWindow` can initialize its `Handle` value directly from the `IChromelyNativeHost`.

Currently I use this workaround to get the window handle:
```c#
private static IntPtr GetWindowHandle(IChromelyWindow window)
{
    var mainWindowField = window.GetType()
        .GetField("_mainWindow", BindingFlags.NonPublic | BindingFlags.Instance);
    if (mainWindowField.GetValue(window) is Chromely.Windows.Window mainWindow)
    {
        var nativeHostField = mainWindow.GetType().BaseType
            .GetField("_nativeHost", BindingFlags.NonPublic | BindingFlags.Static | BindingFlags.Instance);
        if (nativeHostField.GetValue(mainWindow) is Chromely.Native.WinAPIHost winApiHost)
        {
            var handleField = winApiHost.GetType()
                .GetField("_handle", BindingFlags.NonPublic | BindingFlags.Instance);
            if (handleField.GetValue(winApiHost) is IntPtr handle)
            {
                return handle;
            }
        }
    }

    return IntPtr.Zero;
}
```
It is hacky, but I don't see any other way to get the handle now.
Can you guys suggest anything?

**Comment by mattkol** [comment]
@donotcodeit good catch! 
This was to be set in OnCreated event. Was just missed.
Fix: https://github.com/chromelyapps/Chromely/commit/6a0463a3f17eb28577aa917d636b5dced15d109b

**Comment by donotcodeit** [comment]
Thank you for the fix!
By the way, how soon it can come to `NuGet`?

**Comment by mattkol** [comment]
@donotcodeit final v5 nuget will be ready very soon. 
Days or worse a week.
