### ISSUE TITLE
Frameless window still have a caption

### ISSUE THREAD

**Issue by donotcodeit** [chromelyapps/Chromely#153]
Can you guys add `styles &= ~WindowStyles.WS_SYSMENU;` to this block?
https://github.com/chromelyapps/Chromely/blob/1a358986894377da8cffe87e00ce0d5893db690b/src/Chromely/Native/WinAPI/WinAPIHost.cs#L224-L228

I'm not really sure, but it may be a way to get rid of the menu line, that is still present for no reason.

![image](https://user-images.githubusercontent.com/30778436/73243541-687e3900-41da-11ea-9973-257cb9299388.png)

Also if we set `windowFrameless` option to `true`, then window cannot be resized, what is unexpeted too.

**Comment by donotcodeit** [comment]
I can confirm that
`WindowStyles.WS_POPUPWINDOW | WindowStyles.WS_CLIPCHILDREN | WindowStyles.WS_CLIPSIBLINGS`
styles will achieve borderless window without the frame and the menu bar at the top.

Currently `WS_SIZEBOX` adding the menu line somehow. But there still will be no possibility of resize the window.

**Comment by mattkol** [comment]
@donotcodeit you can create a parallel NativeWindow host for the frameless work you are doing, and Chromely will still work flawlessly. This way you can reuse code and add your customizations.

   ````csharp

    public class DemoChromelyApp : BasicChromelyApp
    {
        public override void Configure(IChromelyContainer container)
        {
            base.Configure(container);
            container.RegisterSingleton(typeof(IChromelyNativeHost), Guid.NewGuid().ToString(), typeof(CustomWinAPIHost));
        }
    }
  
````

Please see attached for an example. Same can be done for Windows, Linux and MacOS.

At the moment we want to keep the main repo as simple and lean as possible and do not intend to support frameless window at the moment. May be in the future when we are done with the v5 release. Also discussed here - https://github.com/chromelyapps/Chromely/issues/150

We also plan to have a Chromely.Extra repo, that will allow us and other developers to contribute extra features like this. We can start with your work if you want.

Thanks.
[CustomNativeWindow.zip](https://github.com/chromelyapps/Chromely/files/4122527/CustomNativeWindow.zip)

**Comment by donotcodeit** [comment]
Than you for the example. So basically it is copy of the internal implementation, that can bu used to change some details. I can suggest to just make some methods of the `Chromely.Native.WinAPIHost` to be `protected virtual`. Especially `GetWindowStyles` and `WndProc`, also some utility methods like `GetWindowBounds` to be protected, because it is helpful. Also it requires make `Chromely.Native.WinNativeMethods` public.

This will make enough of extensibility for the host class, will not require to copy a much code from that example, and also will not lose further framework updates.

I've already tried to make those changes, and only this that will be left to write, to make this case work, it's this small snippet. By the way, I was inspired by the your code from the `Chromely.Legacy`, to handle the resizing, and to remove caption from a top of the window.

```c#
public class CustomWinApiHost : Chromely.Native.WinAPIHost
{
    protected override Tuple<WindowStyles, WindowExStyles, ShowWindowCommand> GetWindowStyles(WindowState state)
    {
        var baseStyles = base.GetWindowStyles(state);
        var styles = WindowStyles.WS_POPUPWINDOW | WindowStyles.WS_CLIPCHILDREN | WindowStyles.WS_CLIPSIBLINGS
            | WindowStyles.WS_SIZEBOX;

        return new Tuple<WindowStyles, WindowExStyles, ShowWindowCommand>(
            styles, baseStyles.Item2, baseStyles.Item3);
    }

    protected override IntPtr WndProc(IntPtr hWnd, uint message, IntPtr wParam, IntPtr lParam)
    {
        const int WhiteStripeHeight = 7;

        WM msg = (WM)message;
        switch (msg)
        {
            case WM.ERASEBKGND:
                return new IntPtr(1);
            case WM.NCPAINT:
                return IntPtr.Zero;
            case WM.NCACTIVATE:
                return User32Methods.DefWindowProc(hWnd, message, wParam, new IntPtr(-1));
            case WM.NCCALCSIZE:
            {
                var result = User32Methods.DefWindowProc(hWnd, message, wParam, lParam);
                var csp = (NcCalcSizeParams)Marshal.PtrToStructure(lParam, typeof(NcCalcSizeParams));
                csp.Region.Input.TargetWindowRect.Top -= WhiteStripeHeight;
                Marshal.StructureToPtr(csp, lParam, false);
                return result;
            }
        }

        return base.WndProc(hWnd, message, wParam, lParam);
    }
}
```

**Comment by mattkol** [comment]
@donotcodeit 

> So basically it is copy of the internal implementation

No you do not have to make a copy of all files, I did that for convenience since I am not too sure what you will change. You can re-use files.

But you make a good point some of those methods should be made protected or public. The more you look.. the less you see .. I will make that change.

> I've already tried to make those changes, and only remaining code, to make this case work, it's this small snippet

I am not quite sure I understand. Do you want some input from us here?

**Comment by donotcodeit** [comment]
> I am not quite sure I understand. Do you want some input from us here?
No, it is just a working example of how the code may be easily extended with those changes.

Thanks for the another changeset. I've reviewed and commented out some changes. Can you take a look at the comment, please?

**Comment by mattkol** [comment]
@donotcodeit looks cool to me. Even easier to extend now.
I tested it too.

![image](https://user-images.githubusercontent.com/18384207/73453565-e9037d80-4331-11ea-8184-79dd6e1fc3a8.png)

**Comment by donotcodeit** [comment]
Thank you for changes.

There is my working example of frameless window with drag ability. It is for Windows. Tested only on Windows 10 yet. It is not final, and has several unresolved TODOs. But it may give you idea on how to include frameless feature to the Chromely.

[Chromely.BorderlessDemo.zip](https://github.com/chromelyapps/Chromely/files/4137558/Chromely.BorderlessDemo.zip)

**Comment by mattkol** [comment]
@donotcodeit ok, nice work.

Is it possible you highlight the differences between what was done in Chromely.Legacy and what is done now.

Also is it possible you help highlight what are the TODO tasks, this way we know where to pick it up and if other developers are interested too they know where to focus.

Thanks.

**Comment by Fiahblade** [comment]
@mattkol This should also be included in the v5 release right?

**Comment by mattkol** [comment]
@Fiahblade I was thinking Chromely.Extra repo for now. It does not seem completed yet. I personally have not had time to test how it runs. But if you have and comfortable with it, I will say why not.

**Comment by Fiahblade** [comment]
@mattkol Alright I was just asking because this seemed like core functionality to me.

**Comment by mattkol** [comment]
@donotcodeit @Fiahblade I think we got it right this time - I was able to test extensible. I have added the adaptation to  the repo.

I also figured out how -webkit-app-region works - https://github.com/chromelyapps/Chromely/blob/373d8aa377f520bc3d3c042f6c1efe7526a23496/src/Chromely.CefGlue/Browser/Handlers/CefGlueDragHandler.cs#L83
[BorderlessWindow.zip](https://github.com/chromelyapps/Chromely/files/4143405/BorderlessWindow.zip)

@donotcodeit  I did not really change much - just moving code around. See attached for final demo.

![image](https://user-images.githubusercontent.com/18384207/73601175-2cbcd980-4522-11ea-9f8d-b6a34353c392.png)

**Comment by donotcodeit** [comment]
Sorry, I wasn't able to take a look on weekends.

> Is it possible you highlight the differences between what was done in Chromely.Legacy and what is done now.

I didn't make any changes in Chromely, others than you did in dde85d11f5422bc94e002eea72308af7c3b3ba26 and cfe10f45c88ac436e6d8d09936ce04fe685c81ac. Only in the client code. But, as I can see, you already found it.

> I also figured out how -webkit-app-region works

Interesting. I thought that there can be some functional like that. Ideally, we can try to make available all the window related functional (e.g. close/maximize/minimize) available by utilizing `-webkit-app-region` CSS properties. I will try to implement something, if I will have some free time after work.

Thank you for the changes. I'm looking forward to have them on NuGet.

**Comment by donotcodeit** [comment]
Just to be noted, there are some non-crucial issues, which wasn't reflected in TODOs:

- Window must have "overlapped" properties. I.e. maximize to workspace, instead of full screen.
- Doubleclick on draggable space must maximize/restore window - Windows related base functional.
- When begin to drag window, that was previously inactive, it moves slightly while mouse is not yet moved.
- Ideally, border must not be drawn at all.

I didn't figure out how to make it yet.

**Comment by mattkol** [comment]
@donotcodeit cool!
Thanks for making the list. We will figure them out over time.
I think we had huge success this time.
Well done! 👍

**Comment by donotcodeit** [comment]
I found a way to resolve the `// TODO: Find out how to calculate the caption size.`
Here is a code snipped that working as expected:

```C#
case WM.NCCALCSIZE:
{
    var captionHeight = WinApi.User32.User32Methods.GetSystemMetrics(SystemMetrics.SM_CYCAPTION);
    var menuHeight = WinApi.User32.User32Methods.GetSystemMetrics(SystemMetrics.SM_CYMENU);
    var padderBorder = WinApi.User32.User32Methods.GetSystemMetrics(SystemMetrics.SM_CXPADDEDBORDER);
    var topFrameHeight = captionHeight - menuHeight + padderBorder;

    var result = WinNativeMethods.DefWindowProc(hWnd, message, wParam, lParam);
    var csp = (NcCalcSizeParams)Marshal.PtrToStructure(lParam, typeof(NcCalcSizeParams));
    csp.Region.Input.TargetWindowRect.Top -= _maximized == WindowState.Maximized ? 0 : topFrameHeight;
    Marshal.StructureToPtr(csp, lParam, false);
    return result;
}
```

**Comment by donotcodeit** [comment]
Additionally there is more correct way to get `_maximized` value:

```c#
case WM.SIZE:
{
    _maximized = wParam == (IntPtr)WindowSizeFlag.SIZE_MAXIMIZED
        || wParam ==(IntPtr)WindowSizeFlag.SIZE_MAXSHOW;
    ForceRedraw(hWnd);
    break;
}
```

**Comment by donotcodeit** [comment]
Here is my work with full support of `-webkit-app-region`, which contains changes directly for Chromely. It's a patch because I don't have rights to create PR. Also it fixes rare interceptors initialization issue (comments inside).

[drag-related-updates.zip](https://github.com/chromelyapps/Chromely/files/4152845/drag-related-updates.zip)

**Comment by mattkol** [comment]
@donotcodeit I do not understand why you cannot create a PR. We have developers creating PRs since the project started - https://github.com/chromelyapps/Chromely/pulls?q=is%3Apr+is%3Aclosed.

Was something changed by us somewhere? New github policies?

**Comment by mattkol** [comment]
@donotcodeit there may be an error with the patches.

````
error: patch failed: src/Chromely/Native/WinAPI/WindowMessageInterceptor.cs:116
error: src/Chromely/Native/WinAPI/WindowMessageInterceptor.cs: patch does not apply
````

I think we should look at the PR issue. If this is from our side, we should fix that. Alternatively you could attach all the files that are changed and I will figure things out.

What errors do you get when when you are creating a PR?

**Comment by donotcodeit** [comment]
> Was something changed by us somewhere? New github policies?

Nope, it was just my lack of open source experience. I didn't realized that I can create fork to make a pull request. It's done now and also includes abovementioned fixes. Please take a look.

**Comment by mattkol** [comment]
@donotcodeit all merged. I just did a smoke test. But all looks great.
[BorderlessWindow.zip](https://github.com/chromelyapps/Chromely/files/4157412/BorderlessWindow.zip)
Thanks.

**Comment by donotcodeit** [comment]
Thank you. I think this issue can be closed now.

**Comment by mattkol** [comment]
@donotcodeit sure we should close, soon.
I have two things to point out though.

````
        public int DraggableHeight { get; set; }
        public int NonDraggableRightOffsetWidth { get; set; }
````
Any reason why we are not making these 2 configurable? There are likely some developers that may want to change this and not bother with -webkit-app-region functionality. Besides, we are still making  -webkit-app-region functionality optional anyway - UseWebkitAppRegions. 

````
        public bool IsDraggable { get; set; }
````

The original intention of IsDraggable property may be misunderstand here. IsDraggable (also used in Chromely.Legacy) was an optional parameter that says - "make me frameless but not draggable". Yeap, there are use cases like that (was brought up a while a go).

Thanks.

**Comment by donotcodeit** [comment]
> Any reason why we are not making these 2 configurable?

They will not work correctly on non-standard DPI. Developers can use them for sure, but their application will not work as expected on e.g. 4K monitors or some notebooks. Content will be rescaled, so those sizes needed to be recalculated. That is why CSS appearance better for this case - rescaled content will also rescale draggable area.

> Besides, we are still making -webkit-app-region functionality optional anyway - UseWebkitAppRegions

Yes, because some apps, which not use frameless, do not need this at all, right?

> The original intention of IsDraggable property may be misunderstand here. ... "make me frameless but not draggable"

I see. This is possible now, right? We can change default for the method to return always false.

By the way, I think that name is not well suitable for the method. Should we change it?

**Comment by mattkol** [comment]
> Developers can use them for sure ..

From experience on this project, most developers who would use frameless, are power developers/users and will likely get their hands dirty anyways. A few will just want to make minimal changes. So I think it is just easier for us maintainers to leave that as options - less issues to respond to.

> Yes, because some apps, which not use frameless, do not need this at all, right?

No, only used for draggable .. (hence frameless) - used here -https://github.com/chromelyapps/Chromely/blob/29db62c06dc4802768fe56809b6bb560a5339a90/src/Chromely.CefGlue/Browser/Handlers/CefGlueDragHandler.cs#L70

>By the way, I think that name, IsDraggable, is not well suitable for the method. Should we change it?

Of course, we can. Nothing here is written in stone. Anything to make the project better is welcomed.

Thanks.

**Comment by donotcodeit** [comment]
I've added pull request with important fixes: https://github.com/chromelyapps/Chromely/pull/160
Please, review it @mattkol.
