### ISSUE TITLE
Is it possible to have a menu in the window

### ISSUE THREAD

**Issue by MaximeTasset** [chromelyapps/Chromely#155]
I'm looking for a solution lighter than Electron.net for an desktop web application and Chromely seems to be a good choice. But I would like to have a menu and possibly shortcuts. Is it possible?

**Comment by mattkol** [comment]
@MaximeTasset you mean actual native window/gui menu?

If yes, Chromely does not support or provide that. We  provide a blank chromium slate/canvas and developers can design their menus/controls however they want using html/js/css and/or SPA frameworks like Angular/React/Vue.

**Comment by MaximeTasset** [comment]
Yes, it was what I meant, but I'm fine with your answer.
If it was possible, that would have been great, but, it was not mandatory.

**Comment by fendou** [comment]
chromely + NanUI, https://github.com/NetDimension/NanUI/

**Comment by MaximeTasset** [comment]
> chromely + NanUI, https://github.com/NetDimension/NanUI/

Can you explain your answer? Please.

**Comment by fendou** [comment]
> > chromely + NanUI, https://github.com/NetDimension/NanUI/
> 
> Can you explain your answer? Please.

You combine these two once very perfect.

**Comment by MaximeTasset** [comment]
> You combine these two once very perfect.

Ok, but can you give me an example?

**Comment by fendou** [comment]
> > You combine these two once very perfect.
> 
> Ok, but can you give me an example?

Not. My ability is limited!!! If you want a beautiful UI with NanUI.
Want to use cross-platform and easy-to-use API in Chromely. 
https://img2018.cnblogs.com/blog/352785/202002/352785-20200210174401652-795650108.jpg

**Comment by fendou** [comment]
If you can combination chromely and NanUI is the best.
