### ISSUE TITLE
How to debug React+Redux App in Chromely ?

### ISSUE THREAD

**Issue by anton-martynyuk** [chromelyapps/Chromely#158]
I've wriiten a React+Redux web app and I am using NPM to run this app.
I've entered localhost:ip as start page for Chromely App to load my web app.
The web app works fine. I can debug in Chromely using devtools but it's the builded index.js which is not friendly for a developer.

In Google Chrome I have "React Developer Tools" and "Redux DevTools" extensions to debug my app in a friendly way. I can debug all React components and Redux state.

Is there an ability to debug my react+redux app in Chromely using these or similar extensions?

**Comment by mattkol** [comment]
@anton-martynyuk no extension or separate devtool for Chromely. Chromely relies on Chrome DevTools. 

Thanks.

**Comment by anton-martynyuk** [comment]
> @anton-martynyuk no extension or separate devtool for Chromely. Chromely relies on Chrome DevTools.
> 
> Thanks.

So it not possible to use "React DevTools Extension" when debugging inside Chromely App, right?
I can't use extensions added to Google Chrome, right?

When I open my app in Google Chrome as "localhost:ip" and open it's DevTools I have a seperate tab for "React devtools extension" and "Redux devtools extension"

**Comment by mattkol** [comment]
@anton-martynyuk I won't say not possible. I am saying we did not create or look into an extension as far as I know. If it is done in actual Chrome itself, then of course it is possible, but not something I have personally explored.

**Comment by anton-martynyuk** [comment]
@mattkol do you know how to make Chromely App use any of Google Chrome extensions?

**Comment by anton-martynyuk** [comment]
@mattkol thanks a lot
