### ISSUE TITLE
publish / build release binary app

### ISSUE THREAD

**Issue by lastlink** [chromelyapps/Chromely#159]
What are the steps to build the app to run w/out dotnet installed?

Normally you'd run:
`dotnet publish -c Release -r win-x64 --self-contained`
then click and run `bin\Release\netcoreapp3.1\win-x64\crossplatdemo.exe`

Running:
`dotnet run` in the crossplatdemo after doing a `dotnet restore` does work fine

**Comment by lastlink** [comment]
ok it did finally startup, but closing and reopening still takes a few minutes. is there no way to make it start running faster?

**Comment by mattkol** [comment]
Unless it is downloading CEF binaries, I do not see why it will take minutes to restart. Not my experience. I just timed a restart now - about 35 secs.

You can check to see your VS or VSC settings to see whether you are set to rebuild every time.
