### ISSUE TITLE
Chromely Crashes when using select/dropdown on MacOS (not tested on others)

### ISSUE THREAD

**Issue by tylerhartwig** [chromelyapps/Chromely#162]
Steps to reproduce:

Create a cross platform Chromely application (v5+)

Create a select list in the HTML 
```
<select>
	<option value="red">Red</option>
	<option value="blue">Blue</option>
</select>
```

Click on dropdown in rendered HTML

The follow error is produced `crossplatdemo[16426:425841] -[NSApplication isHandlingSendEvent]: unrecognized selector sent to instance 0x7f915273a260`

Tested on Chromely 5.0.77 on MacOS 10.15.2, Chromium version 77.0.3865.120

**Comment by mattkol** [comment]
@tylerhartwig yes, select/dropdown was not specifically tested on all platforms. 
We will look into that.
Will keep you posted.
Thanks.

**Comment by tylerhartwig** [comment]
From what I understand, this is/was a CEF bug, but I am not able to investigate further as to what versions it might have affected, and if it was ever fixed or not.

**Comment by mattkol** [comment]
@tylerhartwig I doubt this is ever fixed for CEF. 

There seems to be some work around for off-screen rendering -
https://magpcss.org/ceforum/viewtopic.php?f=6&t=10343

Chromely does not do off-screen rendering.

The way around it that I see is to use alternatives. The attached has 2 alternatives - using jQuery and Twitter Bootstrap. There are other options out there.

[CrossPlatDemo.zip](https://github.com/chromelyapps/Chromely/files/4271386/CrossPlatDemo.zip)

![image](https://user-images.githubusercontent.com/18384207/75620146-942e6f00-5b4a-11ea-9ead-58f5f89a27a9.png)

![image](https://user-images.githubusercontent.com/18384207/75620156-b0321080-5b4a-11ea-8f4f-d0a7a0be6165.png)

**Comment by mattkol** [comment]
@tylerhartwig this is also being asked in CEF forum to see if something somewhere is missed.
https://magpcss.org/ceforum/viewtopic.php?f=6&t=17419

**Comment by mattkol** [comment]
@tylerhartwig this is now fixed. 

Thanks to @magreenblatt @Czarek on the CEF Forum for their help. Thanks to you too for pointing it out. It is likely going to impact more controls if this core functionality is not gotten right.

You can get latest to use it in v79 or use the new dylib file in your v77 - unzip libchromely.zip and replace libchromely.dylib in your bin folder.

[libchromely.zip](https://github.com/chromelyapps/Chromely/files/4275584/libchromely.zip)

![issue162a](https://user-images.githubusercontent.com/18384207/75680068-5c145280-5c56-11ea-85fb-b761424c469a.png)

**Comment by tylerhartwig** [comment]
@mattkol Awesome thank you so much for this, will be testing Chromely out further today now. Will v79 be published to nuget soon?

**Comment by mattkol** [comment]
@tylerhartwig we have not decided on v79 timeline yet.
I plan to do a minor release - Chromely - 5.0.77.1 that will include the fix.
Will do it evening today my time - US Central.
I will keep you posted.

**Comment by mattkol** [comment]
@tylerhartwig Chromely - 5.0.77.1 published.

**Comment by tylerhartwig** [comment]
@mattkol thank you so much for all this, I got our demo of Chromely working yesterday and the nuget update will make it all the better.
