### ISSUE TITLE
CrossPlatDemo fails to run on Linux 16.04

### ISSUE THREAD

**Issue by snairza** [chromelyapps/Chromely#163]
Hi, I am getting the error:
[0228/140624.133170:ERROR:sandbox_linux.cc(369)] InitializeSandbox() called with multiple threads in process gpu-process.
Any advice on how to get rid ot it? (Ubuntu 16.04)

**Comment by mattkol** [comment]
@snairza this is a general chromium issue -
https://github.com/ungoogled-software/ungoogled-chromium-portablelinux/issues/2
You can do a google on that too.

There should be another issue why you cannot run.
Please ensure you have .NET Core 3 runtime installed. Most relevant errors will show when you run "dotnet restore" or "dotnet build".

Also please read Readme at - https://github.com/chromelyapps/demo-projects

Personally I have tested on Linux - Lint Mint Xfce (Ubuntu 18.04.3 LTS), Linux Mint 19.3 Tricia, Ubuntu 19.10 (x64). But we support from Ubuntu 16.04 and newer. Please let us know if this is a genuine issue for Ubuntu 16.04.

Thanks.

**Comment by FrankPfattheicher** [comment]
@snairza setting up Ubuntu 16.04 ...

**Comment by snairza** [comment]
I need to write a crossplat app that needs to run on 16.04. I am also getting the same issue on 18.04.
I have also simply cloned the demo-project and ran on 18.04 with the same result. I have tried the recommended environment setting MESA_GLSL_CACHE_DISABLE=true but the issue is still there. Very frustrating. Electron.net is looking attractive right now!

**Comment by mattkol** [comment]
@snairza it will be nice if you can copy the entire output you are getting into a text file and attach, we may be able to help better.

Also note that the demo-project is for Windows by default. As stated in [readme](https://github.com/chromelyapps/demo-projects/blob/master/README.md) you need to make at least 2 changes:
1. Set the runtime -    
````
<RuntimeIdentifier>linux-x64</RuntimeIdentifier>
````
2. Use the appropriate chromelyconfig file or delete it to use default one set in the code.

**Comment by snairza** [comment]
[chromely_output.txt](https://github.com/chromelyapps/Chromely/files/4275323/chromely_output.txt)

**Comment by mattkol** [comment]
Thanks for sharing that.
Looks like you are using **5.0.77-pre01**

````
"/home/siva/.nuget/packages/chromely/5.0.77-pre01/build/chromely_win_cef_downloader.exe" download v77 --c
````

Please can you try most recent [nuget version 5.0.77.0](https://www.nuget.org/packages/Chromely) or use the most recent repo code.

Thanks.

**Comment by snairza** [comment]
Now we are getting somewhere! After getting latest (5.0.77) success of CrossPlatdemo on 18.04. 
Will try on 16.04 next

**Comment by snairza** [comment]
CrossPlatDemo does not run as expected on 16.04. The browser window starts and displays a white screen but no content is rendered. Has anyone had better luck?

**Comment by snairza** [comment]
On Ubuntu 16.04 CrossplatDemo does not run as expected. Application runs browser, but only a white screen is displayed without rendering any content.

**Comment by snairza** [comment]
It does not run successfully on 16.04

**Comment by mattkol** [comment]
Usually when you see a white/blank screen it is one of these two things:

- Likely the app did not load the local resource files properly - ensure that startup url is correct and the start file exist. To be pretty sure you can use a simple  index.html file with an "Hello World" test. 

- A blank screen can be due to missing resource files.
Please see the CEF binary files layout for Linux - https://github.com/chromelyapps/Chromely/blob/master/Documents/cef_binaries_download.md. Linux distros are setup differently and can impact how CEF files are treated. In some cases to get things to work on some distros, I copy the entire content of the locale files into the exe folder.

**Comment by FrankPfattheicher** [comment]
@snairza after installing libx11-dev now it runs on Ubuntu 16.04 on my VirtualBox VM

**Comment by snairza** [comment]
Confirmed it now works after cloning again! Thanks all.

**Comment by snairza** [comment]
After cloning again - demo now works on 16.04

**Comment by snairza** [comment]
Thanks for the help guys!
