### ISSUE TITLE
Add an Avalonia implementation

### ISSUE THREAD

**Issue by jingyiliu** [chromelyapps/Chromely#164]
Hi, there. Is is possible for you guys to add an Avalonia implementation to this project? Because we are developing an desktop app, we still needs to interact with the local system. 

For example, say we want to allow the user to download a file, so we need a "Save File" dialog to allow the user to decide where to store the file.

I found a CefGlue.Core project which wrapper the CefGlue in Avalonia, but i am too new to this project to come up with my own implementation. Can i get some help here?

**Comment by mattkol** [comment]
@jingyiliu Avalonia or any other UI framework is out of scope for Chromely. Chromely uses native window hosts and expect developers to use html/jQuery/Angular etc for their controls.

However, if you only need it for Windows, you can use [.NET Framework demo](https://github.com/chromelyapps/demo-projects/tree/master/regular-chromely/NetFrameworkDemo) which will allow you use WinForms/WPF controls. 

Please see the attached demo for how to do that.

````javascript

	<script>
       function showDevTools() {
           var url = "http://command.com/saveasfilecontroller/save";
            var link = document.createElement('a');
            link.href = url;
            document.body.appendChild(link);
            link.click(); 
       }
	</script>
	
    <button class="btn btn-primary" role="button" onclick="showDevTools()" style='margin: 5px;'>SaveAsFile</button>
	
````

````csharp
[Command(Route = "/saveasfilecontroller/save")]
public void SaveAsFile(IDictionary<string, string> queryParameters)
{
	SaveFileDialog saveFileDialog = new SaveFileDialog();
	saveFileDialog.ShowDialog();
}
````

![issue_164](https://user-images.githubusercontent.com/18384207/75609786-05c9d700-5ad1-11ea-9748-732b37f29260.png)

[NetFrameworkDemo.zip](https://github.com/chromelyapps/Chromely/files/4270443/NetFrameworkDemo.zip)


For other platforms (Linux, MacOS), you can see if with WinForms and WPF migration to .NET Core 3 you can use some of the functionalities in Chromely. But note that they are not supported.

**Comment by jingyiliu** [comment]
@mattkol Thanks for the help. I'll give it a try later.
