### ISSUE TITLE
Question over running Chromely as a browser without the backend

### ISSUE THREAD

**Issue by grbd** [chromelyapps/Chromely#165]
Hi,
what I'm trying to setup is a project that can be run in one of two ways

  * Can be viewed / run as a .net core website viewable via the inbuilt Kestrel / Chrome Browser
  * Can be viewed / run via Chromely where Chromely is just acting as a browser to the running Kestrel instance, which is listening on a port such as http://localhost:1111/

I realise this isn't the way Chromely was designed to be used, but it does allow for debugging of javascript / typescript (break points etc) via the Chrome browser at design time and means the project can be used ether as a website or standalone application at release time.

Edit
I managed to get it partially working this way by copying over by wwwdist directory to the build dir
```
    <ItemGroup>
        <None Include="wwwroot\**" CopyToOutputDirectory="PreserveNewest" />
    </ItemGroup>
```

Although it looks as if the browser window pulls an empty page before kestrel has time to serve it out. So I end up having to run location.reload() from the devtools console window to get it to pick it up

```cs
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.SpaServices.Webpack;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using System;
using Chromely;
using Chromely.Core;
using Chromely.Core.Configuration;

namespace AspNetCore.Vue.Vuetify2.Chromely {

    /// <summary> WebHost Startup Class. </summary>
    public class Startup {

        /// <summary> Constructor. </summary>
        /// <param name="configuration"> The configuration. </param>
        public Startup(IConfiguration configuration) {
            Configuration = configuration;
        }

        /// <summary> App Configuration. </summary>
        /// <value> App Configuration. </value>
        public IConfiguration Configuration { get; }

        /// <summary> Called by the runtime. Add services to the container. </summary>
        /// <param name="services"> The services. </param>
        public void ConfigureServices(IServiceCollection services) {
            // Add framework services.
            services.AddMvc(option => option.EnableEndpointRouting = false)
                .SetCompatibilityVersion(CompatibilityVersion.Latest);

            // Simple example with dependency injection for a data provider.
            services.AddSingleton<Providers.IWeatherProvider, Providers.WeatherProviderFake>();
        }

        /// <summary> Called by the runtime. Configure the HTTP request pipeline. </summary>
        /// <param name="app"> The application. </param>
        /// <param name="env"> The environment. </param>
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env) {
            if (env.IsDevelopment()) {
                app.UseDeveloperExceptionPage();

                // TODO run only if ASPNETCORE_CHROMELY is false
                // setup custom config class

                // Webpack initialization with hot-reload.
                //app.UseWebpackDevMiddleware(new WebpackDevMiddlewareOptions {
                //    HotModuleReplacement = true,
                //});
            }
            else {
                app.UseExceptionHandler("/Home/Error");
            }

            app.UseStaticFiles();
            app.UseMvc(routes => {
                routes.MapRoute(
                    name: "default",
                    template: "{controller=Home}/{action=Index}/{id?}");

                routes.MapSpaFallbackRoute(
                    name: "spa-fallback",
                    defaults: new { controller = "Home", action = "Index" });
            });

            if (Environment.GetEnvironmentVariable("ASPNETCORE_CHROMELY") != "false")
                ChromelyBootstrap(null);
        }

        /// <summary> Bootstrap the Chromely browser. </summary>
        public void ChromelyBootstrap(string[] args) {
            //var appUrls = Configuration["app:urls"].Split(";");

            // TODO reload via dev tools required using location.reload()

            var config = DefaultConfiguration.CreateForRuntimePlatform();
            config.WindowOptions.Title = "test title";
            config.StartUrl = "http://localhost:1111";

            AppBuilder
                .Create()
                .UseConfiguration<DefaultConfiguration>(config)
                .UseApp<ChromelyBasicApp>()
                .Build()
                .Run(args);
        }
    }
}
```

**Comment by mattkol** [comment]
@grbd not quite sure there is a question. More like you are sharing a use case, right?

**Comment by grbd** [comment]
Sorry for not being very clear, the question I've got is how do I stop Chromely from using / setting up it's own webserver on http://localhost:1111
and instead just get it to browse to one I've already setup on that address.

From what I can gather at the moment both the kestrel instance I've setup via CreateWebHostBuilder (the normal Kestrel way of setting up a website) and Chromely are competing to allocate port 1111 on localhost at the same time.

**Comment by grbd** [comment]
Okay so I think I've just figured something out I think the Chromely project is running itself as a child process with different arguments which is why I'm getting multiple attempts at trying to allocate port 1111

**Comment by mattkol** [comment]
Ok. So, so far nothing we need to look into yet, right?

**Comment by grbd** [comment]
Hi,
I've got one last question
In order to check if the exe is being launched as a child process and not the initial parent process I'm just checking for a random argument passed to the child process by Chromely "--no-sandbox"
The question is, is there a argument or environmental variable that will always be set by Chromely when it's launching it's child process's?
and if not is there a way of inserting such an argument? such as "--chromelychildproc" Just to make the whole thing tidy / easy to check for?

I've put a full working example here:
I'll probably put a pull request in once I've added another example that uses webpack / allows debugging of typescript if that's okay

  * https://github.com/Hecatron-Forks/chromely-demo-projects/tree/master/web-chromely

I tried adding in a argument that's passed to the AppBuilder just to see if it would make it through to the child process but it didn't seem to.
```cs
var tmplist = args.ToList();
tmplist.Append("--chromelychildprocess");
args = tmplist.ToArray();
```

**Comment by mattkol** [comment]
I am assuming that these are the child processes launched by Chromely?

If that is the case you can do that here:

https://github.com/chromelyapps/Chromely/blob/1a358986894377da8cffe87e00ce0d5893db690b/src/Chromely.CefGlue/Browser/Handlers/CefGlueBrowserProcessHandler.cs#L37

https://github.com/chromelyapps/Chromely.Legacy/blob/75496b75bf572376b9306e346bb557115cfae124/src/Chromely.CefGlue/Browser/Handlers/CefGlueBrowserProcessHandler.cs#L34

**Comment by grbd** [comment]
Yep it's the options to the child process I'm trying to modify
I've had a look through the source and I can manually add in something like
```
browser_cmd.AppendSwitch("chromely-child-process");
```
into the function you've pointed to (CefGlueBrowserProcessHandler / OnBeforeChildProcessLaunch)

But I was wondering is there supposed to be a way to add in options without modifying the source? (unless I should put this through as a minor pull request / modification)
overriding CefGlueApp and CefGlueBrowserProcessHandler might be one way
but that's used by HostBase / RunInternal() which is inherited by ChromelyWindow, so I can't see an easy way to do it
I did notice there's an option for CommandLineArgs / CommandLineOptions within DefaultConfiguration, but I don't think this is used (unless it's used for something else or not implemented yet)

**Comment by mattkol** [comment]
This is central to how CEF is launched, yes they are being used.

https://github.com/chromelyapps/Chromely/blob/f147ba0f7a3a9b18dbc8d6de1598eee1b0644d0b/src/Chromely.CefGlue/Browser/CefGlueApp.cs#L81

One way around this is to add a new property for child process command line args or expand current to support both parent and child.

Needs a closer look.

**Comment by mattkol** [comment]
@grbd please see what I am using to detect main/subprocess .. 
https://github.com/chromelyapps/demo-projects/blob/master/blazor/ServerAppDemo/ServerAppUtil.cs#L32

I think that should be enough. A similar logic is here - https://github.com/chromelyapps/Chromely/blob/master/src/Chromely.CefGlue/Browser/ClientAppUtils.cs

**Comment by grbd** [comment]
Yep that's spot on, thanks for your help with this.
I've just updated the examples on the pull request I submitted to use ClientAppUtils.GetProcessType(args) if your interested.

**Comment by mattkol** [comment]
@grbd actually I am interested in the PR. I want to see how Chromely plays well with ASP.NET MVC Controllers and how your approach defers from https://github.com/chromelyapps/Chromely/issues/166#issuecomment-596055309, [ServerAppDemo](https://github.com/chromelyapps/demo-projects/tree/master/blazor/ServerAppDemo) to see what new thing to learn.

Both cool approaches, I think.

But I am not able to run either of the demos. 
- web-chromely-mvc - everytime i get https error - even though I am launching with http://localhost:5000

- web-chromely-vuetify2 - seems to be an npm build errors.

Both errors I can look into, but I did not have that much time over the weekend.  Project 2 uses Vuetify ...We try to stay as simple as possible with the demos (less to deal with), and since we are already using Twitter Bootstrap for all demos, I think it is better to stay consistent. If the project showcases a scenario we do not have yet, we can replace Vuetify with Bootstrap.

I may not be able to zoom in until weekend. Also if there are specific instructions that I am missing please let me know.

Thanks.

**Comment by grbd** [comment]
For both demo's I'm using Visual Studio 2019 Community edition.
For the browser selected in Visual Studio I'm using Chrome (since it has debugging capabilities that link with Visual Studio, but this is only useful for the second example)

Looking at the first one **web.chromely.mvc**, this should be the most basic one.
It's basically the template created within Visual Studio 2019 when you select a new .Net Core web application and select the MVC Profile.
The only difference is chromely is added on.

  * it looks like some of the javascript was missing due to .gitignore so I've added that back in
  * I've modified the **Properties/launchSettings.json** file to make things simpler, it should now always use http://localhost:1111 for everything

There should be just 2 launch profiles now

  * web.chromely.mvc - launches as a website / chrome
  * Chromely - launches via chromely window.

The way kestrel normally works is that it defaults to urls of
http://localhost:5000, https://localhost:5001
for websites

However for chromely the intention is to run as a stand-alone application and we might be running multiple apps at the same time, so I put some logic in when running as chromely to instead pick a free port that was available and force the use of that.
This is what happens in the Program.cs GetAppUrl() function and is set via UseUrls()

This can be overridden via the ASPNETCORE_URLS environmental variable which is what is set when you add in a setting of something like
```
"applicationUrl": "http://localhost:1111/",
```
to launchSettings.json
to make things simpler I've just set everything to http://localhost:1111

let me know if you have any problems with the above
I'll have a look at the 2nd one next

**Comment by grbd** [comment]
For the second example - **web-chromely-bootstrap4**, I've switched it across to Bootstrap instead of vuetify (I already had one setup) although I think the sidemenu isn't perfect at smaller window sizes
It's a home grown one originally based on a .net vue template

I plan on releasing a bunch of similar ones for bootstrap / vuetify / foundation on one of my git repos at some later stage.
It might be too complex for the Chromely examples, but it highlights the typescript debugging / single stepping part which is what I was interested in.


## Prebuild steps

First I tend to use nodejs / npm installed via https://chocolatey.org/ since it's more recent than the one included with VStudio
```
choco install nodejs
```

Next before launching visual studio at a Development command prompt let's install the npm packages
(I tend to use pnpm instead usually as it saves on disk space, but npm will work just as fine)
```
cd web-chromely-vuetify2\ClientApp
npm install
```

It's possible to force a rebuild of the javascript, to check for any problems building with webpack using
```
# inside the web-chromely-vuetify2\ClientApp directory
npm run build:dev
```
Although visual studio should do this on the first run

## Overview

This is a much more complicated example, but has some interesting useful features.

  * Uses webpack to build the javascript into two bundles - vendor (stuff that's not likley to change very often) and user (stuff local to the site)
  * Supports Hotreloading when running as a website - this means as you edit / save the javascript / client side code the page should auto refresh on the go while running in VStudio
  * Supports debugging / breakpoints within javascript / typescript, this only works with chrome but means you can add breakpoints or single step through the typescript code / hover over variables etc inside the VStudio IDE
  * The webpack files are split up to make them easier to read instead of the usual example of one big huge lump.
  * adding / remvoving packages is fairly easy via package.json / npm install

**Comment by mattkol** [comment]
@grbd thanks for adding more info.
I should look closely by the weekend.
Thanks.

**Comment by mattkol** [comment]
@grbd I am able to run web.chromely.mvc. I can see clearly now ...
Okay this is cool... but they seem to be independent of each other. Is that the intention? 

![image](https://user-images.githubusercontent.com/18384207/76375919-fb031380-6314-11ea-9bd9-25771f8c2360.png)

![image](https://user-images.githubusercontent.com/18384207/76376010-39003780-6315-11ea-8ef7-090cc7c61901.png)

**Comment by grbd** [comment]
being independent of one another makes sense in that Chromely is just acting as a web browser looking at http://localhost:1111/ which is being served from kestrel as a website.
So they'll have independent states, like two different web browsers browsing the same website

The launch profile web.chromely.mvc should run kestrel, then open a web browser window
and the launch profile Chromely should run kestrel, then open a chromely window

although there's nothing stopping someone from pointing a browser at http://localhost:1111/ and seeing the the same page that the Chromely window can see. (unless you added in some kind of authentication / authorisation to stop it from being viewed that way)

The main reason I wanted to switch between the two personally was to allow for debugging of client side code in the Visual Studio ide (which I tried but didn't seem to work via the chromely window)

**Comment by mattkol** [comment]
@grbd  I am able to debug code in typescript. I am sure javascript will be fine too.

If you have sometime to provide a short readme that will be great, otherwise I can make some summary from the info you have provided.

Thanks.

**Comment by grbd** [comment]
There should be a readme here
https://github.com/chromelyapps/demo-projects/blob/master/web-chromely/README.md
but I'm not sure I've included all the bits mentioned above

**Comment by mattkol** [comment]
Sorry, lazy me! Of course, that should be enough.
Thanks!

**Comment by mattkol** [comment]
There is still more work to be done, but not changing the basics of what you have done. Just something I have wanted to do for a while - how ASP.NET MVC Controllers fits with Chromely. I am not able to get to that today, but may be overtime. 

I am thinking:
- Use your approach of typescript codebehind and replicate [vueapp](https://github.com/chromelyapps/demo-projects/tree/master/angular-react-vue/ChromelyVue/vueapp) in the bootstrap4 project.
-  Controllers in web-chromely-mvc

-- while keeping core basics of what you have done.

We can close the issue anytime, and these changes are just enhancements, and I am not sure when I will get to them.

**Comment by grbd** [comment]
No problem that looks fine to me
I'm using the setup to write a couple of desktop type apps which should in theory be cross platform now thanks to this and should probably even run on the rpi
thanks for you help

**Comment by grbd** [comment]
Note for pushing communication from the server to the client it should be possible to do this with signalr
https://docs.microsoft.com/en-us/aspnet/core/tutorials/signalr?view=aspnetcore-3.1&tabs=visual-studio

I didn't include that in any of the web demo's but it shouldn't be any different than the above link
