### ISSUE TITLE
Running Blazor Server App

### ISSUE THREAD

**Issue by mikart143** [chromelyapps/Chromely#166]
I saw in sample repository that all the examples are blazor webassembly.
I want to run Blazor Server App because of that I can access system informations.
I am planning to build rich GUI application that uses some system informations.

**Comment by mattkol** [comment]
@mikart143 Chromely is a desktop framework and fits well with blazor webassembly and will be **for now** what we will use in the demos (still work in progress .. but the heavy lifting part is done already so developers can still use as-is).

To use blazor server I am guessing (not tried yet) should be easy by making some changes.

The key I think is how you copy the dist files from server to client if you are not hosting the urls in Chromely -

https://github.com/chromelyapps/demo-projects/blob/c28414f9ca65da476e23113a5661857376060431/blazor/BlazorComponents/BlazorComponents.csproj#L16

**Comment by mikart143** [comment]
Okay, but how about BlazorControllersDemo. It looks like it is going to server data from BlazorControllersDemo for BlazorControllers. Is it ready ? In this way I can get my information in console project and then send to blazor webassembly

**Comment by mattkol** [comment]
I do not understand your question about readiness. This is work in progress, and will be updated as it progresses.

> ..  fits well with blazor webassembly and will be for now what we will use in the demos (still work in progress .. but the heavy lifting part is done already so developers can still use as-is).

The "Controller" here is referring to Chromely controller.

To illustrate, I just updated the demo..

Using Component:
https://github.com/chromelyapps/demo-projects/blob/c9041d8ccc876122624bc2d424eec92e6ab42c4f/blazor/BlazorComponents/Pages/TmdbMovies.razor#L79

Using Controller:
https://github.com/chromelyapps/demo-projects/blob/master/blazor/BlazorControllersDemo/Controllers/TmdbMoviesController.cs

But of course you can also send it to a blazor server controller .. you just have to make the request and external request.

**Comment by mikart143** [comment]
When I saw Controllers I understood that you are going to access those controllers from Blazor webassembly. Like not usual API but rather like GRPC. Now I understand what is this all about.  It will be nice to see Blazor Server App in the future. It is going to be easier to make some specific apps

**Comment by mikart143** [comment]
I wonder if using  SignalR with Chromely could be the best solution

**Comment by mattkol** [comment]
There are lot of possibilities with Chromely like any other framework. We have limited bandwidth with our time on the project and we cannot provide demos for every scenario.

Usually developers try different approaches and sometimes they run into roadblocks .. sometime we can help, sometime we walk thru things together.

With bandwidth and if it is a common request, we will surely consider Blazor Server Apps in the future.

Thank you.

**Comment by roceh** [comment]
I've put a sample that works here: https://github.com/roceh/BlazorChromelyTest

It mostly just works, you can debug blazor pages using visual studio. The only thing I had to do extra was put some checks to determine whether the exe was being run up as a child process or not  and only start the localhost web server up if its the first process. It would be nice if chromely would allow custom args to be passed to child processes when it spins them up.

Also the console window annoyingly always shows in visual studio when the project SDK is "Microsoft.NET.Sdk.Web", it doesn't if you just run the exe - so its not a major problem.

**Comment by mattkol** [comment]
@roceh thanks for the sample. I will see about adopting it into a publishable demo.

**Comment by mattkol** [comment]
@roceh @mikart143  I added [ServerApp Demo](https://github.com/chromelyapps/demo-projects/tree/master/blazor/ServerAppDemo) based on @roceh sample.

@roceh please see the logic I am using to detect main/subprocess - https://github.com/chromelyapps/demo-projects/blob/master/blazor/ServerAppDemo/ServerAppUtil.cs#L32

Please let me know if I get the flow right.

Thanks.

**Comment by roceh** [comment]
Seems to work great! 

I don't know if you want to change the app type to winexe to remove the console. It is useful during debug though... perhaps you could make the release build winexe. You could modify the csproj

```
  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <ApplicationIcon />
    <OutputType>WinExe</OutputType>
    <StartupObject />
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <OutputType>Exe</OutputType>
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>
```

**Comment by mattkol** [comment]
@roceh I cannot get the console to disappear, I really must be doing something wrong. 
If you can send a sample project file, I can see what I may be missing.
Not that important though, but a nice-to-have.

**Comment by mikart143** [comment]
Do you plan to add child window support ?
I Invoke this script to open child window:
```
await JSRuntime.InvokeAsync<object>("open","/Statistics","_blank");
```
and this is log:
```
-------------------------OPEN-------------------------
On CefGlue child process launch arguments:
"D:\Projects\legendarycockpit\src\ChromelyDesktopInterface\bin\Release\netcoreapp3.1\ChromelyDesktopInterface.exe" --type=gpu-process --field-trial-handle=2940,10277487760772091127,12027158553528862649,131072 --disable-features=OutOfBlinkCors --disable-gpu-sandbox --use-gl=disabled --no-sandbox --locales-dir-path="D:\Projects\legendarycockpit\src\ChromelyDesktopInterface\bin\Release\netcoreapp3.1\locales" --log-file="logs\chromely.cef_20200311.log" --log-severity=info --resources-dir-path="D:\Projects\legendarycockpit\src\ChromelyDesktopInterface\bin\Release\netcoreapp3.1\\" --lang=en-US --default-encoding=utf-8 --allow-file-access-from-files --allow-universal-access-from-files --disable-web-security --ignore-certificate-errors /prefetch:2
2020-03-11 22:51:36.725 [INFO] Running Windows chromium 77.0.3865.120
2020-03-11 22:51:38.162 [INFO] Sub process executes successfully with code: 0
```

I know that there was an issue, but maybe sth changed

**Comment by roceh** [comment]
@mattkol does setting the output type to Windows Application not stop it appearing?

**Comment by mattkol** [comment]
@roceh no, it does not.

**Comment by roceh** [comment]
For me it does not show when the exe is run outside visual studio (when output type is set to windows application). One way I can seem to get it not to show within visual studio is to enable "Automatically close the console when debugging stops" in tools options. But that is a user option and not ideal.

The other better way is to change the Debug info to **Executable** instead of **Project** in the project properties. I suspect when visual studio sees the project SDK as Microsoft.NET.Sdk.Web it is automatically opening a console window. 

You then have to put $(TargetDir)\$(TargetName).exe as the executable.

![image](https://user-images.githubusercontent.com/15068726/76680182-7b0fce80-65de-11ea-9c7a-88b7a5ce59b9.png)

**Comment by mattkol** [comment]
> For me it does not show when the exe is run outside visual studio

Ok, I may have missed this part. Yes it works when ran outside Visual Studio. Thanks.

But I just noticed something interesting though. Running exe on its own does not seem to work as expected. Seems like Chromely ran before the server is launched. But running from VS is fine.

![image](https://user-images.githubusercontent.com/18384207/76684595-29b21000-65db-11ea-9a48-940d395b99c5.png)

Please if you have sometime (anytime), please can you help run the demo as-is to eliminate environment issues.

Thanks.

**Comment by roceh** [comment]
That looks like a missing wwwroot folder in the debug folder, on my test project i was copying it into the folder with a msbuild post build action. 

```
  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="xcopy &quot;$(ProjectDir)wwwroot&quot; &quot;$(TargetDir)\wwwroot&quot;   /i /s /r /y /c&#xD;&#xA;" />
  </Target>
```

I think i copied that from your other examples.

I think when in visual studio it sets the working directory to the project folder so it picks up the wwwroot directly. There might be some advantage to doing it like that, its certainly how a normal blazor project works.

Perhaps only do the wwwroot copy for release build.

**Comment by mattkol** [comment]
@mikart143 

> Do you plan to add child window support ?
> I Invoke this script to open child window:
> 
> ```
> await JSRuntime.InvokeAsync<object>("open","/Statistics","_blank");

Sorry for the late response. This is likely due to a bug. 

This method below should return false if not handled:
https://github.com/chromelyapps/Chromely/blob/eb59c52593864b4b02bcebf6f73e709b50b3ca2d/src/Chromely.CefGlue/Browser/Handlers/CefGlueLifeSpanHandler.cs#L73

You can get latest to fix that. But if you need to use the nuget version you can create a [custom handler](https://github.com/chromelyapps/Chromely/blob/master/Documents/registering_custom_handlers.md). 

I plan to have an updated nuget between now and the weekend.

Thanks.
