### ISSUE TITLE
storage persistence

### ISSUE THREAD

**Issue by alextroto** [chromelyapps/Chromely#168]
Hi,
I would like to keep local application storage, right now it seems it's cleared when I close the window.
Is it possible?
Thank you,
Alex

**Comment by mattkol** [comment]
@alextroto yes.

This needs setting cachepath:

````
  var config = DefaultConfiguration.CreateForRuntimePlatform();
  config.CustomSettings["cachePath"] = "path to cache folder",
````

Please see how to here: https://github.com/chromelyapps/Chromely/blob/master/Documents/configuration.md
https://github.com/chromelyapps/Chromely/blob/f147ba0f7a3a9b18dbc8d6de1598eee1b0644d0b/src/Chromely.Core/Helpers/ConfigKeys.cs#L58

You can read more about other related properties here:
CachePath 
PersistUserPreferences 
PersistSessionCookies

https://github.com/chromelyapps/Chromely/blob/b657d24505590a1c8bffab98c124aa335b4e675f/src/Chromely.CefGlue/CefGlue/Structs/CefRequestContextSettings.cs#L15

This CefSharp Stackoverflow issue may be helpful too:
https://stackoverflow.com/questions/30867798/winforms-cefsharp-browser-localstorage-not-working

**Comment by alextroto** [comment]
@mattkol I've set up the cachePath param, but it seems local storage is still cleared after I'm closing the app.

In CefRequestContextSettings.cs is written: "HTML5 databases such as localStorage will only persist across sessions if a cache path is specified". I don't quite understand, is it mean local storage will always be cleared, even cachePath is not null ?

**Comment by mattkol** [comment]
@alextroto this is not something I have personally looked at.  I can take a closer look.

Please can you share what your configuration looks like.

**Comment by alextroto** [comment]
Config it's simple:

var config = DefaultConfiguration.CreateForRuntimePlatform();
            config.StartUrl = "local://wwwroot/index.html";
            config.CustomSettings["CachePath"] = "cache";
            config.CustomSettings["PersistSessionCookies"] = "cache";
            config.CustomSettings["PersistUserPreferences"] = "cache";
            config.CefDownloadOptions = new CefDownloadOptions { AutoDownloadWhenMissing = true, DownloadSilently = false };
            config.DebuggingMode = false;
            config.WindowOptions.WindowState = Chromely.Core.Host.WindowState.Maximize;
            AppBuilder
            .Create()
            .UseApp<ChromelyBasicApp>()
            .UseConfiguration<IChromelyConfiguration>(config)
            .Build()
            .Run(args);

cache subfolder is created, but nothing is saved.
Maybe it's related to this? https://github.com/cncjs/cncjs/issues/41

**Comment by mattkol** [comment]
>Maybe it's related to this? cncjs/cncjs#41

May be.

Please try  change the "cache" to:
````
var appDirectory = AppDomain.CurrentDomain.BaseDirectory;
var cachePath = Path.Combine(appDirectory , "cache");
config.CustomSettings["CachePath"] = cachePath;
````
Please see how some of the folders are set here - https://github.com/chromelyapps/Chromely/blob/f147ba0f7a3a9b18dbc8d6de1598eee1b0644d0b/src/Chromely.CefGlue/BrowserWindow/HostBase.cs#L199

**Comment by alextroto** [comment]
@mattkol Working like a charm!
Thank you!
