### ISSUE TITLE
Headless usage?

### ISSUE THREAD

**Issue by Ziriax** [chromelyapps/Chromely#169]
Hello,

First of all congrats with this great project!

I was wondering, can Chromely also be used for headless console apps? E.g. starting the Chromium browser, rendering to a HTML canvas, saving the result, and exiting, all in a .NET Core console app?

Or would it be better to use [Puppeteer](https://github.com/kblok/puppeteer-sharp) for this?

Thanks!
Peter

**Comment by mattkol** [comment]
@Ziriax 

>First of all congrats with this great project! 

Thank you.

No, out of the box, Chromely is not designed for headless. Yes Puppeteer and similar projects will be appropriate.

Thanks.
