### ISSUE TITLE
Sending file data using ChromelyRequest

### ISSUE THREAD

**Issue by zztessema** [chromelyapps/Chromely#170]
I am creating Chromely project that has a file input element. I am attempting to figure out how to send the file input data to the server using the ChromelyRequest object. Using axios, I send the file data (as a javascrpt File object) to the server. On the server side, the ChromelyRequest never seems to contain the byte data of the file object. How should I be parsing file input data in order to be able to access the file data on the server side using the ChromelyRequest object.

`var postData = new FormData();`
`postData.append('LicenseFile', this.LicenseFile);`
`axios.post('http://chromely.com/admincontroller/getlicenses',` `JSON.stringify(Object.fromEntries(postData)), { headers: { 'Content-Type': 'multipart/form-data' } })`
`        .then(response => {`
`          console.log(response.data)`
`        })`
`        .catch(error => {`
`          console.log(error)`
`        })`

**Comment by mattkol** [comment]
@zztessema I think you should just pass the postdata as-is without stringify. If you need to use stringify then extract the info you need from the File object. I just tried it (see attached) and I can see data in request Data property.

Ways to get info from file object:
https://javascript.info/file

[AxiosDemo.zip](https://github.com/chromelyapps/Chromely/files/4362485/AxiosDemo.zip)
