### ISSUE TITLE
[HELP/INFO NEEDED] How to --disable-web-security? OR how to access iFrame URL?

### ISSUE THREAD

**Issue by bunakbg** [chromelyapps/Chromely#171]
I need to do some cross-origin stuff (no hacking - I promisse, I own the domain!) and I can't detect the URL of the iframe within chromely app. The only thing i've found is to disable web security with --disable-web-security - how to start all chromely processes with that argument?
OR
I am making a program which is mix between my domain and localapp - I am not allowing browsing to any other site (whitelist check onBeforeBrowse etc). I need to know where the user is browsing within an iFrame on the domain.
I only want to save the URL so that when the user wants to return to the domain iframe to navigate to the last visited URL. That is all.

Additional info: using blazor, I have 3 nav-tabs - 1 is my domain in iframe, the other 2 are utilities. when the user navigates something on the iframe on the domain - everything works OK, but when he navigates to one of the utilities nav-tabs, when returning to the domain nav-tab he is not on the last visited url on the iframe. I want save the last visited url in a var and consequently to open it in the iframe.

Any suggestions?

**Comment by mattkol** [comment]
Web security is disabled by default:

https://github.com/chromelyapps/Chromely/blob/76a730bf2c5dd233d620f7893319205daf8e8458/src/Chromely.CefGlue/Browser/CefGlueBrowser.cs#L182
https://github.com/chromelyapps/Chromely/blob/eb59c52593864b4b02bcebf6f73e709b50b3ca2d/src/Chromely.CefGlue/Browser/Handlers/CefGlueBrowserProcessHandler.cs#L40

-- to ensure it is done or to add  other argument options you can use - 
[CommandLineArgs or CommandLineOptions](https://github.com/chromelyapps/Chromely/blob/master/Documents/configuration.md)

You can see how iframe url are changed in the demos - may be helpful:
https://github.com/chromelyapps/demo-projects/blob/a844ab6dfc2ca581f22c4dd709a132daca6a930e/regular-chromely/CrossPlatDemo/app/chromely.html#L35

**Comment by bunakbg** [comment]
Hello mattkol,
thanks for the reply, I've checked that all child processes do spawn with --disable-web-security args and yet I still get
`Uncaught DOMException: Blocked a frame with origin "https://127.0.0.1:10111" from accessing a cross-origin frame.`
Additional info:
I am using your blazor example. I've made some modifications on it - removed all or most of your code and inserted mine. I've added additional asp.net MVC project that emulates my domain (faster debugging). Blazor works on https://127.0.0.1:10111 - spawns OK, mvc works on http://127.0.01:5000 and shows inside the iFrame. The interesting part is that they are now both on same-origin - 127.0.0.1 and I still get that error. I've added 
`config.CommandLineOptions = new List<string>();`
`config.CommandLineOptions.Add("disable-web-security");`
inside `Program.cs` to be sure that the first process spawns with disabled security and yet I still have that error when trying to access the iFrame document location href.
The js I'm injecting is
`document.getElementById("theIframe').contentWindow.location.href;`
This is not directly related the your project itself and I feel dumb for asking you for this information, but I've stubmled upon this when I was using CefSharp (but CefSharp ain't cross-platfrom and your project is - thanks for that!) I disabled web-security with arguments and it was working.
Can you tell me (if you can) what am I doing wrong?
Thanks for your time!
