### ISSUE TITLE
Name of the application on OSX is incorrect

### ISSUE THREAD

**Issue by jchomarat** [chromelyapps/Chromely#172]
Hello,

When I launch the crossplatdemo on osx (10.15.3), on the menu bar, I do not see the name of the app, but "Chromium Embedded Framework" instead.
Before launching it, I've copied config/chromelyconfig_mac.json content to root folder

<img width="923" alt="chromely" src="https://user-images.githubusercontent.com/6317287/77825067-3ec48e00-7107-11ea-8fdd-93eed8daf0d2.png">

Thanks
Julien

**Comment by mattkol** [comment]
@jchomarat AppName was not set for MacOS. We will look into it.
Thanks for pointing it out.

**Comment by jchomarat** [comment]
If it can help: when you launch an app on OSX, if it has to download CEF, then the name in the menu bar is ok (appname from config file). If you close it, and reopen it (so no need to d/l CEF anymore), then the name is incorrect

**Comment by mattkol** [comment]
Yes, that info is helpful.

I think you should be able to change it in the file: ../Info.plist (should be in the executable folder).
````
<plist version="1.0">
<dict>
	<key>CFBundleExecutable</key>
	<string>Chromium Embedded Framework</string>
</dict>
</plist>

````
Please let me know if that works. We could make the change in the code or guide developers on that.

Thanks.

**Comment by jchomarat** [comment]
I confirm it works! Thanks.
I think though that it should be handled in the code... but there is a workaround so that's cool.

Cheers

**Comment by mattkol** [comment]
Thanks for helping with the confirmation.

Yes, I agree. Best to handle in code. Less issues to deal with in the future. 
But that is for developers who use the automatic CEF binaries download. 
For those who will do manual downloads, we need to put in some documentation.
