### ISSUE TITLE
Question over api for maximise / minimise / close under frameless

### ISSUE THREAD

**Issue by grbd** [chromelyapps/Chromely#173]
Hi,
This is just a quick question
Is there an API to trigger a maximise / minimise / close from within code while the configuration is set to frameless?

The reason I ask is that I was thinking of using something like this

  * https://quasar.dev/vue-components/bar#Styling

**Comment by mattkol** [comment]
Yes.

[Html](https://github.com/chromelyapps/demo-projects/blob/4972e12513112877275a8476a6acb3643a970abe/regular-chromely/FramelessDemo/app/index.html#L68)
[Controller](https://github.com/chromelyapps/demo-projects/blob/master/regular-chromely/FramelessDemo/Controllers/WindowController.cs)

**Comment by grbd** [comment]
ah thanks very much
