### ISSUE TITLE
frameless mode styling

### ISSUE THREAD

**Issue by grbd** [chromelyapps/Chromely#174]
Hi,
I've recently been experimenting with the frameless setup
and creating my own buttons for restore / minimise / maximise / close etc
One of the things I've discovered is that sometimes the buttons require a double click to trigger
I think this is a result of the draggable bar implemented by libcef while in frameless mode

It might be related to this

  * https://github.com/chromelyapps/Chromely/issues/93

from what I can figure

  * First of all this only happens in frameless mode
  * It doesn't happen when the window is maximised (I'm guessing because the drag bar is not present)
  * It only effects buttons in the zone of the draggable area

I've put together a demo to show this off

  * https://github.com/Hecatron/Hecatron.Scraps/tree/master/Chromely.Examples/Chromely.Quasar1

For the demo it should just be a case of running "npm install" in the ClientApp Directory before trying to run it under visual studio
There should be 2 lanuch profiles, one for a website the other for chromely
There's also some settings under appsettings.Development.json for turning frameless on and off

I'm guessing it might be related to WindowMessageInterceptor which I noticed was used within
Chromely/src/Chromely/Windows/Window.cs 

I realise getting frameless to work right might be difficult with the mouse clicks
so I'll probably be sticking to framed for now, but I thought it'd be best to mention it

**Comment by grbd** [comment]
I just tried this out with the master version instead of the latest nuget release but appears to be the same

**Comment by piloitte** [comment]
@grbd thanks for letting us know. 

It is something I have observed too. 

I think I have tried these 2 options:
[Option 1](https://github.com/chromelyapps/demo-projects/blob/4972e12513112877275a8476a6acb3643a970abe/regular-chromely/FramelessDemo/app/index.html#L57)      [Option 2](https://github.com/chromelyapps/Chromely.Legacy/blob/8e71bc91e9aa689a00ac0ca004e6ff73e49a6437/Demos/regular-chromely/frameless_draggable_command/Chromely.CefGlue.Winapi.Demo/app/chromely_frameless.html#L53)

I really cannot remember if there is a difference, because at the time my focus was not on how the command works but frameless itself.

**Or maybe we need to register the click events.**

Frameless window has been a major challenge for the project, and although we have had some progess on it, these unknowns will creep up.

Hopefully we find sometime in the future to take a stab at it again.

Thanks.

**Comment by grbd** [comment]
I suspect what's happening is that the drag bar is intercepting the clicks for the drag area
So the first click is intercepted by the drag area, the second click for some reason then gets passed through.

I think I'll try using the FramelessOption / IsDraggableCallback since it looks like it's setable via the WindowOptions.
The idea being to set the drag region so that it doesn't overlap the close / max / min buttons.

Another thing would be to add in a double click listener to WindowMessageInterceptor.cs
to toggle between maximise / restore.
So I might have a look at that as well, or see if its possible to pass the click events through and handle the double click on the web control.

**Comment by grbd** [comment]
I've been looking into customising the size of the drag box at the top
One thing I've discovered is that the scale setting for the desktop has an impact on the result of
GetWindowClientSize (WinAPIHost.cs) / GetClientSize / GetClientRect (WinNativeMethods.cs)
https://social.msdn.microsoft.com/Forums/en-US/948ec624-a506-45f7-a347-3c166ba34cea/getwindowrect-on-windows-10?forum=vcgeneral

So within FramelessOptions for example
when you click at the far right of the window and it checks to see if your'e in the drag box

If the desktop scale is set to 100%
(under right click on desktop -> display settings -> Display -> Scale and Layout)
Then everything works as it should
point.X and size.Width will be very close to the same value (such as 1200 wide, point.x 1198)

However if the desktop scale is set to 125% (as it is for my desktop, as it's recomended for 1920x1080)
Then the numbers will end up being much more different of something like
1200 wide, point.x being 958 which is much more different

This is because 1200 is now at 125%
so if we know the scale actual_width = (1200 / 125) * 100 = 960
which seems to tally up

so the next thing I need to look at is what API to use to get the display scale for the screen
I'm not sure if anything else important is dependent on GetWindowClientSize but it may also affect that as well

**Comment by grbd** [comment]
This looks like the answer
``` csharp
                // Returns a rectangle in pixels
                GetClientRect(_handle, out var rectangle);

                // The returned value is the dpi, dividing by 96f results in the scale
                var windowscale = GetDpiForWindow(_handle) / 96f;

                size.Width = (int) (rectangle.Width / windowscale);
                size.Height = (int) (rectangle.Height / windowscale);
```

**Comment by grbd** [comment]
I've renamed this issue to track changes to the frameless mode
Things work better now than they did, but I suspect some of the styling under windows could be tweaked to be better

Currently Maximise under frameless results in a full screen with no start menu visible as one example. I suspect this is due to the use of WS_POPUPWINDOW although I'm not sure of the correct combination of stylings to get around that.

I did come across this which might be useful

  * https://github.com/rossy/borderless-window

Also this for a frameless GTK Window (although it lacks drag)

  * https://gist.github.com/jeandudey/02dc5146864cd0abc30f

**Comment by donotcodeit** [comment]
@grbd Isn't `FramelessOption.UseWebkitAppRegions = true` suits your needs? It allows you to define draggable area with CSS. `-webkit-app-region: drag;` - causes all element to be draggable area. `-webkit-app-region: no-drag;` - if placed over draggable area will disable drag ability, for e.g. placing minimize/close button over it.

**Comment by grbd** [comment]
not really no, because this is dragging the entire window around the desktop, not dragging within the brwoser
