### ISSUE TITLE
Access to nativeHost from ChromelyApp

### ISSUE THREAD

**Issue by grbd** [chromelyapps/Chromely#181]
Hi,
I've been attempting to access the nativeHost instance
this is to call the new methods I've setup to maximise / minimise / restore the window etc
I think this is supposed to be already accessible as it's part of the interface IChromelyWindow
it's also one of the parameters I added into the doubleclick handler for the drag region

If the pull request goes through then in theory I should be able to do something like this
(this is assuming app = the chromelyapp)
```csharp
app.Window.NativeHost.SetWindowState(WindowState.Minimize);
```

## NativeHost Access

However it looks like NativeHost property is always null
After a bit of digging into the code I think I found the problem
it's just a question of the best way to fix it from a design point of view

1. The **Chromely.Windows.ChromelyWindow** constructor is called
The nativeHost parameter is null
this calls the base class constructor of **Chromely.CefGlue.BrowserWindow.HostBase**

2. The **HostBase** constructor is called
At this point the **nativeHost** property of **HostBase** is null and remains null

3. The **ChromelyWindow.CreateMainView** function is called
This creates a new instance of the **Chromely.Windows.Window** Class

4. The **Window** Class picks up on the fact the nativehost parameter is null
so creates a new one via **NativeHostFactory.GetNativeHost**
(this is done inside of Window's base class NativeWindow)

So we do have a Nativehost floating about used in memory, but it's not reachable via the ChromelyWindow
since it's setup later on before ChromelyWindow can get a hold of it
It's only reachable via the Window instance which isn't reachable I think because it might be platform specific

## Fixes

There are different ways to fix this
I think the simplest would be to create / setup nativeHost inside of ChromelyWindow if it's not already been passed in

1. so first change the _nativeHost property inside HostBase so that it's not readonly
2. Next change the following

From 
```csharp
    public ChromelyWindow(IChromelyNativeHost nativeHost, IChromelyContainer container, IChromelyConfiguration config, IChromelyRequestTaskRunner requestTaskRunner, IChromelyCommandTaskRunner commandTaskRunner)
        : base(nativeHost, container, config, requestTaskRunner, commandTaskRunner)
    {
    }
```

To
```csharp
        public ChromelyWindow(IChromelyNativeHost nativeHost, IChromelyContainer container, IChromelyConfiguration config, IChromelyRequestTaskRunner requestTaskRunner, IChromelyCommandTaskRunner commandTaskRunner)
            : base(nativeHost, container, config, requestTaskRunner, commandTaskRunner)
        {
            if (nativeHost == null) {
                _nativeHost = NativeHostFactory.GetNativeHost(_config);
            }
        }
```

It might also be possible to set it up inside the SimpleContainer before SimpleContainer.ActivateInstance is called I'm not sure

**Comment by mattkol** [comment]
Nice catch!
