### ISSUE TITLE
Searching for libX11.so / libX11.so.6

### ISSUE THREAD

**Issue by grbd** [chromelyapps/Chromely#182]
Hi,
This is just another minor thing I've spotted testing under Linux
I've been testing linux support recently using Kubuntu

Under Chromely\Native\LinuxGtk3\Library.cs
The name of libX11 is specified as **libX11.so**

Typically on a standard kubuntu install there's a **libX11.so.6** file
but no symlink from **libX11.so** to **libX11.so.6**

## Fix 1

One way to fix this is to use **libX11.so.6** instead of **libX11.so** inside Library.cs
This is what Avalonia seems to be doing - https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.X11/XLib.cs

## Fix 2

Another way around this is to install libx11-dev for the symlink to be created
Then add a note to the docs to make sure people are aware 
```
apt-get install -y libx11-dev
```

According to these links this isn't classed as a bug for some reason, so perhaps Fix 1 would be better
If using libX11.so is somehow development and libX11.so.6 is considered release

  * https://bugs.launchpad.net/ubuntu/+source/libx11/+bug/13362
  * https://bugzilla.redhat.com/show_bug.cgi?id=118007

**Comment by mattkol** [comment]
Nice! Been looking for a clear explanation of what the differences are. 
Thanks for fishing this out!
