### ISSUE TITLE
DefaultRequestTaskRunner does not handle `IsAsync` routes

### ISSUE THREAD

**Issue by jel-massih** [chromelyapps/Chromely#183]
It appears that the IsAsync flag is not used, so async ActionRoutes which only have ActionAsync set,  have Action try to be called (which is null).

```
        public SampleController()
        {
            RegisterGetRequestAsync("/data", GetData);
        }

        public async Task<ChromelyResponse> GetData(ChromelyRequest request)
        {
              return new ChromelyResponse() { RequestId = request.Id, Data = "Hello"}; ;
        }
```

Might make sense to remove the async methods if the intention is to no longer support Async methods. 

Got it working for project im working on in this cl, but definately super janky.
https://github.com/jel-massih/Chromely/commit/692598665209fa87f0fd2196a09f944bb65d71ff

**Comment by mattkol** [comment]
I cannot remember if this was missed at the time or intentional. But we should add it. I will look into adopting what you have done.

Also I noticed a bug on that.. you should be able to replace that with a custom implementation, but we are not replacing single instances with older registered.

This should be allowed:

````
    public class DemoChromelyApp : ChromelyBasicApp
    {
        public override void Configure(IChromelyContainer container)
        {
            base.Configure(container);
            --------
            container.RegisterSingleton(typeof(IChromelyRequestTaskRunner), typeof(IChromelyRequestTaskRunner).Name, typeof(CustomRequestTaskRunner));
        }
    }
````

I will look into that too.

Thanks for pointing it out.

**Comment by mattkol** [comment]
@jel-massih  please let me know if you find anything with fix. 
Planning a nuget update based on - https://github.com/chromelyapps/Chromely/pull/180, but hoping to include this too.

Between now and tomorrow is fine. 
No hurry.

Thanks.

**Comment by jel-massih** [comment]
Hey! That CL looks good to me, and Aync routes are working for me with the changes. Thanks!
