### ISSUE TITLE
Communication protocol between angular app and dotnet

### ISSUE THREAD

**Issue by anaselhajjaji** [chromelyapps/Chromely#184]
Hello,

In the sample ChromelyAngular, I saw that there is some JSON serialization and the use of the ChromelyController. I understood the the communication protocol is a REST API. Is that correct ?

Is there any other protocol that we can use between Angular and dotnet, like websocket, signalr, grpc, any inproc com possibility ?

Thank you

**Comment by mattkol** [comment]
@anaselhajjaji communication protocol is not really REST API. 

Chromely uses Restful like approach to achieve what CEF allows.

From Marshall A. Greenblatt:

_The recommended method for browser/renderer communication is either XMLHttpRequest which uses the network stack and can be intercepted or something like the [generic message router](https://bitbucket.org/chromiumembedded/cef/wiki/GeneralUsage.md#markdown-header-generic-message-router) which uses IPC._

Reference -https://magpcss.org/ceforum/viewtopic.php?f=10&t=13562

This is referenced in readme:

Options of communicating (IPC) with rendering process are via:

- Generic Message Routing - more info @ [Generic Message Routing](https://github.com/chromelyapps/Chromely/blob/master/Documents/generic_message_routing.md).
- Ajax HTTP/XHR -  more info @ [Custom Scheme Handling](https://github.com/chromelyapps/Chromely/blob/master/Documents/ajax_xhr_request_handling.md).

Yes, you can use other protocols, but I am not sure all are supported by CEF out-of-the-box. WebSocket is supported with [Http/WebSockets server](https://bitbucket.org/chromiumembedded/cef/issues/2278/expose-internal-http-websockets-server). Chromely has an implementation of that in [Legacy Chromely](https://github.com/chromelyapps/Chromely.Legacy/wiki/Real-time-with-Websocket) but not supported anymore.

**Comment by anaselhajjaji** [comment]
Ok thank you.
