### ISSUE TITLE
Multi window support?

### ISSUE THREAD

**Issue by ywxt** [chromelyapps/Chromely#185]
Hi,
Do I have a way to create multiple windows at this time?
And can I change some properties such as a window's title, icon or size after it created?
Thanks.

**Comment by mattkol** [comment]
@ywxt 

> Do I have a way to create multiple windows at this time?

No, not without some work. Primarily Chromely is one-window framework. There were developers that have tried using multiple window by sharing same CEF binaries. 

>And can I change some properties such as a window's title, icon or size after it created?

Not provided out of the box. You need to do some work around that. With Windows I know you can SendMessage/PostMessage to the window using the handle. For Linux/MacOS there should be something similar.

You can have access to the winodw handle/native window - [Handle](https://github.com/chromelyapps/Chromely/blob/1589d83206f05e2ede4e5b9f173a5e4d6d5f8cc8/src/Chromely.Core/Host/IChromelyWindow.cs#L8) [NativeWindow](https://github.com/chromelyapps/Chromely/blob/1589d83206f05e2ede4e5b9f173a5e4d6d5f8cc8/src/Chromely.Core/Host/IChromelyWindow.cs#L9).

**Comment by ywxt** [comment]
> @ywxt
> 
> > Do I have a way to create multiple windows at this time?
> 
> No, not without some work. Primarily Chromely is one-window framework. There were developers that have tried using multiple window by sharing same CEF binaries.
> 
> > And can I change some properties such as a window's title, icon or size after it created?
> 
> Not provided out of the box. You need to do some work around that. With Windows I know you can SendMessage/PostMessage to the window using the handle. For Linux/MacOS there should be something similar.
> 
> You can have access to the winodw handle/native window - [Handle](https://github.com/chromelyapps/Chromely/blob/1589d83206f05e2ede4e5b9f173a5e4d6d5f8cc8/src/Chromely.Core/Host/IChromelyWindow.cs#L8) [NativeWindow](https://github.com/chromelyapps/Chromely/blob/1589d83206f05e2ede4e5b9f173a5e4d6d5f8cc8/src/Chromely.Core/Host/IChromelyWindow.cs#L9).

Thanks for your rely. I will try it.
