### ISSUE TITLE
Why do Blazor Demo run start so slowly

### ISSUE THREAD

**Issue by jzlhll** [chromelyapps/Chromely#186]
When run WebAssemblyChromelyControllersDemo, for the blazor project.
Please do not say that cef is not down...It's already downloaded, And still always blank about >30s and then shows the "loading..", and show the real html.
What that?

**Comment by mattkol** [comment]
@jzlhll the demos are provided as-is to help and guide.
If you see something we can help improve on, please let us know.

**Comment by jzlhll** [comment]
> @jzlhll the demos are provided as-is to help and guide.
> If you see something we can help improve on, please let us know.
Thanks.
Both window10 and OSX10.14.6,  when run WebAssemblyChromelyControllersDemo, a white view shows for about 20-30 seconds. After that the index.html "Loading..." appears quickly , and then, the real home.razor shows. 

So, what is the white views doing? I will try more and get more infos.

**Comment by mattkol** [comment]
@jzlhll you do have a genuine concern for sure. We all do if that is common for everyone.

But the way to look at it is this - if basic Chromely -  [CrossPlatDemo](https://github.com/chromelyapps/demo-projects/tree/master/regular-chromely/CrossPlatDemo) shows that behavior, then we should look deeper at Chromely, CefGlue, CEF to see what is happening.

Demos with a framework that is not "really" part of Chromely, should be considered as-is. We have limited bandwidth to investigate everything that is not really related to Chromely. So if you debug it and you think you find a reason why that is happening, then we can look at it together and improve on it for you and everyone.

WebAssembly is well-documented to be slow and still in preview. Is that the reason for what you see, I do not know. 

Thanks.

**Comment by jzlhll** [comment]
> @jzlhll you do have a genuine concern for sure. We all do if that is common for everyone.
> 
> But the way to look at it is this - if basic Chromely - [CrossPlatDemo](https://github.com/chromelyapps/demo-projects/tree/master/regular-chromely/CrossPlatDemo) shows that behavior, then we should look deeper at Chromely, CefGlue, CEF to see what is happening.
> 
> Demos with a framework that is not "really" part of Chromely, should be considered as-is. We have limited bandwidth to investigate everything that is not really related to Chromely. So if you debug it and you think you find a reason why that is happening, then we can look at it together and improve on it for you and everyone.
> 
> WebAssembly is well-documented to be slow and still in preview. Is that the reason for what you see, I do not know.
> 
> Thanks.

Thanks, since I'm a winform/android developer , not quitly familiar with web Technology.As you said, maybe It's webassembly loading too slow. The CrossPlatDemo is faster.

While, please modify the chromelyconfig_mac.json in CrossPlatDemo, 
logs\\chromely.cef.log  to logs/chromely.cef.log
