### ISSUE TITLE
Chromely Crossplatform Demo crashes on Fedora 31 Linux

### ISSUE THREAD

**Issue by ameliadiedrich** [chromelyapps/Chromely#187]
When trying to run the Chromely crossplatform example on Fedora Linux using dotnet run, it crashes and displays the following error message:

[0423/123654.046190:ERROR:sandbox_linux.cc(369)] InitializeSandbox() called with multiple threads in process gpu-process.

It would be nice if someone could help me with this issue.
Thanks!

**Comment by ameliadiedrich** [comment]
I am aware of issue #163 , however, even after I set the runtimeidentifier and changed the config file, it didn't run.

**Comment by mattkol** [comment]
The error you see is common and does not stop the app from running.

- Please follow the readme for guide - https://github.com/chromelyapps/demo-projects/edit/master/README.md

I will suggest you delete the config file, when this was done it was for ubuntu - may have an impact. Also please try using Visual Studio Code to debug, this way it will tell you if you are missing some packages.

Also you can upgrade nugets. There have been a few changes since we published the demos. I will find time over the weekend to upgrade the demos.

I personally have not tested on Fedora Linux. If all this does not help you can attach logs here and we can take it from there.

Thanks.

**Comment by ameliadiedrich** [comment]
@mattkol Thanks for your answer!

I know took a look at the guide again and after seeing now issues with the code, I tried debugging the application using VSCode like you suggested.

Weirdly, the Debug Console only returned 

[INFO] Running Linux chromium 77.0.3865.120

The program '[5955] crossplatform.dll' has exited with code 0 (0x0).

Are there other logs I could provide you with, to help solving this issue ?

**Comment by mattkol** [comment]
Seems weird. 

You have:
````
    <!-- <RuntimeIdentifier>win-x64</RuntimeIdentifier>-->
    <RuntimeIdentifier>linux-x64</RuntimeIdentifier>
    <!-- <RuntimeIdentifier>osx-x64</RuntimeIdentifier>-->
    <Platforms>x64</Platforms>
````

and the following:

- Download and install .NET Core 3 Runtime binaries. You will need .NET Core 3 runtime installed. You can install directly if you know what is required. Or you start with building and running and see what is missing.

dotnet restore
dotnet build
dotnet run

Also check to see that Microsoft supports the Linux distro you are using. Seems to me that Fedora will be part of it.

Please look for the files in the folder Logs in the app directory.

If you did all that, and still there is a problem then we may have to look at Fedora closely.

**Comment by mattkol** [comment]
May be this will help.
https://docs.microsoft.com/en-us/dotnet/core/install/linux-package-manager-fedora31

**Comment by ameliadiedrich** [comment]
@mattkol alright, after making sure that I have the .NET Core runtimes installed, I took a look at the log file and discovered an output stating that Chromely is unable to load the libcef library or one of its dependencies, any suggestions ?

**Comment by mattkol** [comment]
That is good then. 

Unless you remove the option, CEF binaries should start downloading after that. There should be a window browser message message saying download as started. Of course you need internet for that.

If you do not see that, then something else is still wrong, and you may have to do that manually - https://github.com/chromelyapps/Chromely/blob/master/Documents/cef_binaries_download.md

**Comment by ameliadiedrich** [comment]
@mattkol okay, so the download finished successfully, but there is still no window opening even if I debug using vs code or use dotnet run, I'm starting to think that might be a Fedora specific issue

**Comment by ameliadiedrich** [comment]
@mattkol alright, what in the world, I now found out that it is an issue with GNOME, as soon as I tried to run the application using XFCE and Gnome Classic it worked perfectly. What a strange behaviour....

**Comment by mattkol** [comment]
Nice!

Good its working. But that is something we need to study closely so we can advise other developers in future. Maybe some dependencies missing.

Will keep that in mind.
Thanks.
