### ISSUE TITLE
File Download in a Chromely App

### ISSUE THREAD

**Issue by zztessema** [chromelyapps/Chromely#189]
I am building a chromely app and I would like to allow the user to downlaod a file that is generated by the application. When i use the link tag to prompt the download nothing happens. 
For example, adding 
`<a id="dlLink" href="data:text/plain;charset=utf-8,This%20is%20the%20content%20of%20my%20file" download="test.txt">link</a>`
does not seem to bring up the "Save As..." dialog window when clicking the link. 

Is file download not possible in a Chromely App, or is there a different way to do this?

**Comment by mattkol** [comment]
There is no default download handler configured. You need to implement one -
https://github.com/chromelyapps/Chromely/blob/master/Documents/registering_custom_handlers.md

I just added one to the repo- https://github.com/chromelyapps/Chromely/commit/8983c31b4b488d2542f2530214360f3f4f727b63

Or you can register a custom one if you want to use nugets:

````csharp
 public class CustomDownloadHandler : CefDownloadHandler
    {
        protected override void OnBeforeDownload(CefBrowser browser, CefDownloadItem downloadItem, string suggestedName, CefBeforeDownloadCallback callback)
        {
            if (callback != null)
            {
                using (callback)
                {
                    callback.Continue(downloadItem.SuggestedFileName, showDialog: true);
                }
            }
        }
    }



    public class DemoChromelyApp : ChromelyBasicApp
    {
        public override void Configure(IChromelyContainer container)
        {
            base.Configure(container);
            -----

            container.RegisterSingleton(typeof(IChromelyCustomHandler), Guid.NewGuid().ToString(), typeof(CustomDownloadHandler));
        }
    }
````

**Comment by zztessema** [comment]
This solves my issue. Thanks!
