### ISSUE TITLE
Is there a clean way to prevent Chromely from killing the program process when the Chromely window is closed?

### ISSUE THREAD

**Issue by elgonzo** [chromelyapps/Chromely#191]
How can i prevent Chromely from killing the main program's process?
Basically, i want to keep my program running after the user closes the Chromely window, with `AppBuilder.Run` simply returning instead of killing the main program's process. Kinda like:

```
private void OpenWebForm()
{
    ... do all the necessary preparations/configuration ...

    AppBuilder
        .Create()
        .UseConfiguration<DefaultConfiguration>(config)
        .UseApp<ChromelyBasicApp>()
        .Build()
        .Run(args);

   ... DO MORE STUFF HERE ...        <<<-----------------------------------------------
}
```

I am in the midst of developing a console application, that under certain circumstances relies on a web-based login form to obtain an access token for other services handled by my console application.

Since i want to keep my console app x-platfom, yet need to rely on web-based login forms, i found Chromely a good match (due to its x-platform support, unlike the original CefGlue which i first favored). 

However, there is a problem i can't solve. My program needs to continue execution after the Chromely window has been closed (obviously, since it needs to do something with the obtained access tokens).

Now, i don't know yet how my code would interface with Chromely in a way that would allow it to obtain those access tokens, and i expected this to be the most difficult thing to figure out.

Unfortunately, i hit a roadblock much, much earlier: I can't figure out how to prevent Chromely from killing the main program's process in a clean way without hacking around in the Chromely codebase (which i do not really have any meaningful understanding of, either), and i would also like to avoid having to spawn a child process just for using Chromely for a web login form.

**Comment by mattkol** [comment]
Without getting your hand dirty with changes in [Native Window](https://github.com/chromelyapps/Chromely/tree/master/src/Chromely/Native) I will suggest creating a separate process for Chromely and pass parameters to the separate process either via command line or some confg file.

There was a developer a while ago who embedded Chromely in Excel using VBA doing something similar. But I cannot remember the conclusive approach details.

**Comment by mattkol** [comment]
Then, of course there is the cross-platform hurdle that the VBA approach did not have.

**Comment by elgonzo** [comment]
Yeah, i was afraid that spawning a child process for Chromely is how to do it. It's not what i preferred, but it is a workable approach.

Anyways, a big Thank You! for your quick response!
