### ISSUE TITLE
Automatically sync HTML title with window title

### ISSUE THREAD

**Issue by johannesegger** [chromelyapps/Chromely#193]
I use Chromely as container for my own webpage (basically as a replacement for Electron).
The webpage has an HTML title attribute that sometimes changes.
I expected Chromely's window title to mirror the title attribute of the HTML webpage and found it very irritating that it doesn't behave like that.
I worked around that using the `TitleChanged` event (thank god you implemented that). Still I had to use the native method to update the window title because [`IChromelyNativeHost`](https://github.com/chromelyapps/Chromely/blob/master/src/Chromely.Core/Host/IChromelyNativeHost.cs) as well as [`WinAPIHost`](https://github.com/chromelyapps/Chromely/blob/master/src/Chromely/Native/WinAPI/WinAPIHost.cs) don't support that (warning: F# code ahead).

```fsharp
open Chromely
open Chromely.CefGlue.Browser.EventParams
open Chromely.Core
open Chromely.Core.Helpers
open System

module Win32 =
    open System.Runtime.InteropServices

    [<DllImport("user32.dll", SetLastError = true, CharSet = CharSet.Auto)>]
    extern bool SetWindowText(IntPtr hWnd, string lpString)

type ChromelyApp() =
    inherit ChromelyBasicApp()
    override x.RegisterEvents(container: IChromelyContainer) =
        let eventHandler =
            ChromelyEventHandler<TitleChangedEventArgs>(
                CefEventKey.TitleChanged,
                fun sender e -> Win32.SetWindowText(x.Window.Handle, e.Title) |> ignore
            )
        container.RegisterInstance(typeof<CefEventHandlerTypes.ITitleChangedHandler>, eventHandler.Key, eventHandler)
```

Shouldn't it be the default behavior or at least some config switch to enable automatic update of the window title whenever the webpage title changes?

**Comment by mattkol** [comment]
@johannesegger 
> Shouldn't it be the default behavior or at least some config switch to enable automatic update of the window title whenever the webpage title changes?

So you will think.... if it was thought of at the time.

The project has evolved over time by developers like you suggesting features or contributing PRs. I hope this is one of those situations - a feature request. Sure that we can do in next iteration, I just do not understand the use of the word **"irritating"** here. People have put a lot of efforts to get to where we are.

Thanks.

**Comment by johannesegger** [comment]
Hm you're right, I didn't mean to say "irritating", I meant "confusing" or "unexpected". It was a wrong translation from the german word "irritierend", sorry.

Yes this might then be a feature request or at least a workaround for someone else wanting the same.

**Comment by mattkol** [comment]
Thanks for the clarification. Appreciated.

Sure a nice basic feature to have, it was just missed.
This will be added.

Thanks.

**Comment by johannesegger** [comment]
Woah, that was fast. Thanks 👍
What do you think about the automatic synchronization of the window title? Should the library user implement it herself using `ITitleChangedHandler` or do you think it makes sense to provide a switch or something like that in the configuration object?

**Comment by mattkol** [comment]
I think it is advisable to use ITitleChangedHandler as you a need a trigger to do the change. Putting a switch in configuration is fine, but configuration is not designed for event handling.

Also note that when we decided on the current Chromely we want it to be as lean as possible while making it extensible and flexible for developers:
> The plan here is to make Chromely leaner and fully cross-platform

[Migration to .NET Core 3](https://github.com/chromelyapps/Chromely/wiki/Migration-to-.NET-Core-3-and-MacOS-Support)

Of course in consequent releases  we will add more functionalities, but still keeping it simple and lean. A synchronized title change seems commonly needed and  simple and will be considered as a feature.
