### ISSUE TITLE
how do i change the version of Cefsharp ? i need to enable flash 

### ISSUE THREAD

**Issue by wilari932** [chromelyapps/Chromely#194]
I downloaded the binaries and loaded as the documentation but it dos not work ? 
in order to enable flash i need to change this value 
profile.default_content_setting_values.plugins =  1 ;
but on older version of Cef i did need to enble this in order to make flash work? 
do you know how to fix this to get flash working ?

**Comment by mattkol** [comment]
@wilari932 this is a CefGlue project, CefSharp support was discontinued ... but may be related to this - https://github.com/cefsharp/CefSharp/issues/3048

See [List - CommandLineOptions](https://github.com/chromelyapps/Chromely/blob/master/Documents/configuration.md) to see flags.

**Comment by wilari932** [comment]
Im sorry i think i mean Cef frammework  
in Cef frammework you have this flag profile.default_content_setting_values.plugins = 1 ;
but in your wrapper i canot find a way to set tit or to change the binaries to an older version of cef 
https://www.magpcss.org/ceforum/viewtopic.php?f=7&t=17068&start=10

**Comment by mattkol** [comment]
CefGlue does not allow you to change binaries at will. Every release branch has it it's own version specified - see the [current here](https://github.com/chromelyapps/Chromely/blob/8983c31b4b488d2542f2530214360f3f4f727b63/src/Chromely.CefGlue/CefGlue/Interop/version.g.cs#L12).

What you are trying to do can be a lot of work, depending on what version you want. Below are the versions we have supported so far. 

64.0.3282.119/3.3282.1741.gcd94615
65.0.3325.181/3.3325.1751.ge5b78a5
66.0.3359.117/3.3359.1772.gd1df190
68.0.3440.84/3.3440.1805.gbe070f9
77.0.3865.120/77.1.14%2Bg4fb61d2%2Bchromium-77.0.3865.120
79.0.3945.130/79.1.36+g90301bd+chromium-79.0.3945.130

If the version you want is not in the list, you need to do the following:

- identify the version you want
- Go to the CefGlue [released branches](https://gitlab.com/xiliumhq/chromiumembedded/cefglue/-/branches) to see if CefGlue has that released.
- You need to extract that and replace in the folder - [here](https://github.com/chromelyapps/Chromely/tree/master/src/Chromely.CefGlue/CefGlue)


Sorry we do not have bandwidth to support all versions, but let me know if I can help with more guides.

Thanks.
