### ISSUE TITLE
how to execute JS function

### ISSUE THREAD

**Issue by Neilfy** [chromelyapps/Chromely#195]
I want to execute js function in VUE, how should I do? Thanks!

**Comment by mattkol** [comment]
These links may help.

[Guide](https://github.com/chromelyapps/Chromely/blob/master/Documents/javascript_execution.md)

[Demo](https://github.com/chromelyapps/demo-projects/tree/master/angular-react-vue/ChromelyVue)
[Controller class](https://github.com/chromelyapps/demo-projects/blob/master/angular-react-vue/ChromelyVue/Controllers/ExecuteJavaScriptDemoController.cs)
[Html/Javascript](https://github.com/chromelyapps/demo-projects/blob/866b2738bd443cedb95ff300eb50ba9eae754da5/angular-react-vue/ChromelyVue/vueapp/src/components/JavasSriptDemo.vue#L51)
