### ISSUE TITLE
publish/release displays white screen

### ISSUE THREAD

**Issue by mwa-corey** [chromelyapps/Chromely#196]
installed package Chromely 5.0.77.3
building on Win10 Version 10.0.17134.1006

Attempting to release build or publish the ChromelyReact demo project results in the application opening to a white screen. The dev tools show no html, and no errors on console. There are no log files in the directory. I also attempted publishing the ChromelyAngular, has the same result.

Running the app in debug appears to work fine.

**Comment by mattkol** [comment]
@mwa-corey 

Please [readme](https://github.com/chromelyapps/demo-projects/edit/master/README.md).

> For Angular/React/Vue using start url - local://dist/index.html it uses xcopy (on Windows to copy the dist folder to bin/exe folder) since it may be different for other platforms, you may have to copy the dist folder manually or replace xcopy functionality.

The xcopy is missing for Release, you can replicate what was done in debug for simple releases, but not advisable for production installers.

Thanks.

**Comment by mwa-corey** [comment]
@mattkol thanks. i actually stumbled across the copying of the dist (prior to readme) and have been using that. just wants sure if that was the preferred method or a hack.

thanks for the prompt reply and clarification.
