### ISSUE TITLE
Failed AJAX requests returning status code 200 OK

### ISSUE THREAD

**Issue by donotcodeit** [chromelyapps/Chromely#199]
I have another problem with AJAX requests. Since we enabled it in PR https://github.com/chromelyapps/Chromely/pull/157 it was all good. But today I was needed to handle errors on API requests, and found that all failed requests will have status code 200 with no content. Because of this I am not able to know in JS code is request was failed (no connection, non-OK API response) or it is just a normal response.

It can be reproduced with sending any request on non-exist API e.g.:
`https://non-exist-api.com/get`

URL scheme should be registered as AJAX:
`new UrlScheme("default-api", string.Empty, string.Empty, "non-exist-api.com", UrlSchemeType.Ajax, false)`

**Comment by mattkol** [comment]
@donotcodeit 
I think that the setting [here](https://github.com/chromelyapps/Chromely/blob/8684d310c1dc6cff48c37cb2e471900b08e062b8/src/Chromely.CefGlue/Browser/Handlers/ExternalRequestSchemeHandler.cs#L122) ...is being blocked by the callback in [External Http Handler](https://github.com/chromelyapps/Chromely/blob/8684d310c1dc6cff48c37cb2e471900b08e062b8/src/Chromely.CefGlue/Browser/Handlers/CefGlueAsyncHandlerBase.cs#L160)

Compare with what is done for for 
[Local Http Handler](https://github.com/chromelyapps/Chromely/blob/8684d310c1dc6cff48c37cb2e471900b08e062b8/src/Chromely.CefGlue/Browser/Handlers/CefGlueHttpSchemeHandler.cs#L191)


If this is something you want to look into, I will suggest that the callback [continue, cancel] be removed. 

Additoanlly this should be done [here](https://github.com/chromelyapps/Chromely/blob/8684d310c1dc6cff48c37cb2e471900b08e062b8/src/Chromely.CefGlue/Browser/Handlers/ExternalRequestSchemeHandler.cs#L114)

````csharp

if (_httpResponseMessage == null)
{
   response.Status = something with error (NOT OK);
   response.StatusText = some reason;
   return;
}
````
*** Note: **I did not prove that to be correct yet, just comparing the two approaches.**

Thanks.

**Comment by donotcodeit** [comment]
I can confirm that removing these lines: https://github.com/chromelyapps/Chromely/blob/8684d310c1dc6cff48c37cb2e471900b08e062b8/src/Chromely.CefGlue/Browser/Handlers/ExternalRequestSchemeHandler.cs#L114-L115 fixing unexpected behavior.

@mattkol can you include this to the next build? I will fix it locally for now.

**Comment by mattkol** [comment]
@donotcodeit makes sense. 
Thanks.

**Comment by donotcodeit** [comment]
@mattkol sorry I was wrong. Those lines should be replaced with:
```c#
if (_httpResponseMessage == null)
{
    response.Error = CefErrorCode.Failed;
    return;
}
```

Or we'll just get null ref exception.
