### ISSUE TITLE
Blazor server app (Certificate error)

### ISSUE THREAD

**Issue by CSondergaard** [chromelyapps/Chromely#201]
I created a blazor server application and set it up with chromely, in fine on my own computer for debug, and the build version also runs without any problems. 

However if i try to run the program on a none development machine, i get certificate error when loading the program.

![image](https://user-images.githubusercontent.com/21744985/81813320-9b4d0280-9527-11ea-86dc-b12f6f41117d.png)

This is the error i see in the console when trying to open the program.

Is there anyway to have certificate with the app, or is there a way to not use https endpoints, since the the https is basicly on on the pc it shouldnt matter?

I also tried to build the demo server app, and i receive the same error when using that application.

**Comment by mattkol** [comment]
I think https has been disabled for the demos. If that does not work (I think you say it does), then see more on howto here.
https://stackoverflow.com/questions/50935730/asp-net-core-2-1-kestrel-how-to-disable-https

I am not too sure Microsoft allows you to disable HTTPS for production. I think it is a requirement. May be possible to disable. This may help -
https://docs.microsoft.com/en-us/aspnet/core/security/enforcing-ssl?view=aspnetcore-3.1&tabs=visual-studio

No, we do not intend to add a certificate, these are just demos and development/debug builds are enough.

Thanks.
