### ISSUE TITLE
Way to feed  c# captured video / images into canvas ?

### ISSUE THREAD

**Issue by simonbuehler** [chromelyapps/Chromely#205]
hi,

is there a way to push images or video captured with opencvsharp and processed in c# to the ui? Maybe filling  a canvas or using a video element ? 

Any hint would be great!

**Comment by Donaut** [comment]
You can write a SetTimeout in Javascript and call the C# script periodically.  But that would be slow another thing is that you can use https://github.com/lolp1/Overlay.NET or any similar library and draw to the window itself.

**Comment by Mercurial** [comment]
if you are using blazor try this https://github.com/Mercurial/BlazorMedia
