### ISSUE TITLE
Allow to change request type and response type to plain-text, json or binary

### ISSUE THREAD

**Issue by Jluil** [chromelyapps/Chromely#211]
Currently the post request type is always treated as json and the return type is also always treated as json. Standard request/response can also be plain-text and binary, where binary is very commonly used with file/large data transfers. Probably some attributes/properties should be added to routes to support this behavior.

**Comment by mattkol** [comment]
@Jluil the use of json in default implementations is based on popularity. You can return anything you want. 

Chromely is extensible, so you just need to provide your handler.
````
 public class DemoChromelyApp : ChromelyBasicApp
    {
        public override void Configure(IChromelyContainer container)
        {
            base.Configure(container);
            container.RegisterSingleton(typeof(IChromelySchemeHandlerFactory), "custom-01", typeof(CustomHttpSchemeHandlerFactory));
        }
    }
````
The main change will be primarily here - https://github.com/chromelyapps/Chromely/blob/4a1319f5bac4628400d94fb088d615bbb34c7926/src/Chromely.CefGlue/Browser/Handlers/CefGlueHttpSchemeHandler.cs#L85

Please see [Wiki](https://github.com/chromelyapps/Chromely/wiki) and [documentations](https://github.com/chromelyapps/Chromely/tree/master/Documents) for more on how to use and extend Chromely.

This https://github.com/chromelyapps/Chromely/issues/170 describes how to send files.

**Comment by Jluil** [comment]
ok this makes sense althought the default handler could easily be more flexible

**Comment by mattkol** [comment]
@Jluil that is true. Remember it is a framework and you have to keep to some well understood and well used standards. Plain text and binaries are pretty standard, and sure can be looked at. But what percentage of developers will be served by this? Not sure. But sure something to think about.

Noted. Thanks.

**Comment by Jluil** [comment]
so I'm looking into the custom handler and there is this special treatment of default scheme handler factory where it gets different parameters compared to a custom scheme factory which is not very nice:

https://github.com/chromelyapps/Chromely/blob/4a1319f5bac4628400d94fb088d615bbb34c7926/src/Chromely.CefGlue/BrowserWindow/HostServicesBase.cs#L182

https://github.com/chromelyapps/Chromely/blob/4a1319f5bac4628400d94fb088d615bbb34c7926/src/Chromely.CefGlue/Browser/Handlers/CefGlueHttpSchemeHandlerFactory.cs#L35

How would you suggest to proceed here?

**Comment by mattkol** [comment]
@Jluil I do not understand what makes it "not very nice".

One registers the factory handler, the other creates the handler. They are 2 different things.  Please look closely.

Another clarifications: Yes it is a custom handler. But everything we provide out of the box is default for the developers.  So the links you sent are all referring to default registration and implementation.

This custom implementation is registered here:
https://github.com/chromelyapps/Chromely/blob/4a1319f5bac4628400d94fb088d615bbb34c7926/src/Chromely.CefGlue/BrowserWindow/HostServicesBase.cs#L176

You cannot separate factory/handler creation - see samples here:
https://stackoverflow.com/questions/35965912/cefsharp-custom-schemehandler
https://github.com/cefsharp/CefSharp/issues/769

Personally I welcome improvement on what we have done so far. Developers have contributed well to the project, you can see it all over. I am not clearly seeing the objective here. Last time you said you will provide suggestions, now we are going into "not very nice" territory. Please try understand what we have done very well and see what other CEF related projects have done (to see how CEF works), this way I think you can help to contribute positively. Looking at snippets of code is not enough.

Thanks.

**Comment by Jluil** [comment]
As I said I like the project, I'm here to help not to make you feel bad, please don't take it personally.. I think the project has great potential.
I will try to reformulate my question:
DefaultSchemeHandler/Factory uses parameters IChromelyContainer container, IChromelyConfiguration config, IChromelyRequestTaskRunner requestTaskRunner.
CefSchemeHandlerFactory::Create has CefBrowser browser, CefFrame frame, string schemeName, CefRequest request.
Is it possible to inject IChromelyContainer, IChromelyConfiguration, IChromelyRequestTaskRunner to custom scheme handler/factory, because these parameters are manually passed to DefaultSchemeHandlerFactory only.

**Comment by mattkol** [comment]
@Jluil there is nothing personal about my question. 

So think about this. It takes somewhat of 5min to an hour to respond to a question. Yes, I may understand the project more than anyone else, but I still have to look around and see how best to respond, you can see @FrankPfattheicher coming to help too. So we want the project to keep its simplicity, leanness while being agile. As you can see there have been many positive inputs.

If you spend time to understand the project, you can help to minimize the time we spend to respond to your requests. And I also think it will help you to contribute positively.

> Is it possible to inject IChromelyContainer, IChromelyConfiguration, IChromelyRequestTaskRunner to custom scheme handler/factory, because these parameters are manually passed to DefaultSchemeHandlerFactory only.

**You want to create a custom handler - I showed you how to do it and the documentation explaining that. All that is ignored.**

I sent you how the registration is done in above comment:
````
public class DemoChromelyApp : ChromelyBasicApp
    {
        public override void Configure(IChromelyContainer container)
        {
            base.Configure(container);
             ----
            container.RegisterSingleton(typeof(IChromelySchemeHandlerFactory), "custom-01", typeof(CustomHttpSchemeHandlerFactory));
        }
    }
````

So where are those manually passed in the registration of the factory handler? The question still shows you are not taking time to understand the project. You are looking too deep into code snippet still. 

If you are using any of Chromely primary objects, it will be injected for you:
See - https://github.com/chromelyapps/Chromely/blob/fdf33e529d2f9b1a8006d73c91c40fe6b660c9db/src/Chromely.Core/ChromelyApp.cs#L107

Documentation
[Getting Started](https://github.com/chromelyapps/Chromely/blob/master/Documents/getting_started.md)
[Registering Custom Scheme Handlers](https://github.com/chromelyapps/Chromely/blob/master/Documents/registering_scheme_handlers.md)

My advise is - leave the source code the way it is. Play with the [demos](https://github.com/chromelyapps/demo-projects), read some documentations or wiki pages. Then you can see what the source code does. 

I am sure you are serious about contributing positively and I believe you will but let us do this process a lot smarter.

Thanks.
