### ISSUE TITLE
Single instance error, JetBrains Rider

### ISSUE THREAD

**Issue by nurbat** [chromelyapps/Chromely#213]
![изображение](https://user-images.githubusercontent.com/5789051/85067494-105bc980-b1b1-11ea-868b-5717488f0d4f.png)

public static void Main(string[] args)
        {
            var applicationName = Assembly.GetEntryAssembly()?.GetName().Name;
            var Mutex = new Mutex(true, applicationName, out isInitilized);

// var config = DefaultConfiguration.CreateForRuntimePlatform();
            // config.StartUrl = "http://google.com";
            if (isInitilized) AppBuilder.Create()
                // .UseConfiguration<DefaultConfiguration>(config)
                .UseApp<DemoChromelyApp>()
                .Build()
                .Run(args);
        }
class DemoChromelyApp : ChromelyBasicApp
        {

        }

**Comment by mattkol** [comment]
@nurbat I am able to reproduce.
Interesting - we need to look closely to see what is going on.
Thanks.

**Comment by mattkol** [comment]
The issue is that the mutex is being checked for every process. CEF has the browser process (main) and render processes (child processes) and others like gpu processes ...

The mutex should only be checked for in the main process.

We have used similar approach:

https://github.com/chromelyapps/demo-projects/bob/a844ab6dfc2ca581f22c4dd709a132daca6a930e/web-chromely/web-chromely-mvc/Program.cs#L30

https://github.com/chromelyapps/demo-projects/blob/a844ab6dfc2ca581f22c4dd709a132daca6a930e/web-chromely/web-chromely-bootstrap4/Program.cs#L36

````csharp
    class Program
    {
        static Mutex mutex = new Mutex(true, "{8F6F0AC4-B9A1-45fd-A8CF-72F04E6BDE8F}");

        [STAThread]
        static void Main(string[] args)
        {
            // We only want to check if it is the browser process
            var proctype = ClientAppUtils.GetProcessType(args);
            if (proctype == ProcessType.Browser)
            {
                if (mutex.WaitOne(TimeSpan.Zero, true))
                {
                    RunApp(args);
                    mutex.ReleaseMutex();
                }
                else
                {
                    Environment.Exit(0);
                }
            }

            // Child processes will run here
            RunApp(args);
        }

        static void RunApp(string[] args)
        {
            var config = DefaultConfiguration.CreateForRuntimePlatform();
            config.StartUrl = "local://app/chromely.html";

            AppBuilder
            .Create()
            .UseConfiguration<DefaultConfiguration>(config)
            .UseApp<DemoChromelyApp>()
            .Build()
            .Run(args);
        }
    }
````

**Comment by nurbat** [comment]
The problem repeats, the app's white screen and spam in the console.
[Example.zip](https://github.com/chromelyapps/Chromely/files/4807685/Example.zip)

**Comment by mattkol** [comment]
Seems fine and works for me.

- The white screen happens because there is no valid start url.
- The "spam" is just usual CEF logged messages. Ignore it. You can turn it off by changing project Output type to "Windows Application" or turn CEF log off (not advisable). If you read the logs it just says when each process happens - warnings and errors etc. Some errors are just related to features that you do not have plug-ins for - they are not showstoppers.

[Example.zip](https://github.com/chromelyapps/Chromely/files/4807741/Example.zip)

````csharp
    public class Program
    {
        static Mutex mutex = new Mutex(true, "{8F6F0AC4-B9A1-45fd-A8CF-72F04E6BDE8F}");
        
        [STAThread]
        static void Main(string[] args)
        {
            // We only want to check if it is the browser process
            var proctype = ClientAppUtils.GetProcessType(args);
            if (proctype == ProcessType.Browser)
            {
                if (mutex.WaitOne(TimeSpan.Zero, true))
                {
                    Initilize(args);
                    mutex.ReleaseMutex();
                }
                else
                    Environment.Exit(0);
            }
            else
            {
                // Child processes will run here
                Initilize(args);
            }
        }

        private static void Initilize(string[] args)
        {
            var config = DefaultConfiguration.CreateForRuntimePlatform();
            config.StartUrl = "http://google.com";
            config.WindowOptions.Title = "Vodji Chat";
            AppBuilder.Create()
                .UseConfiguration<DefaultConfiguration>(config)
                .UseApp<DemoChromelyApp>()
                .Build()
                .Run(args);
        }
        
       
        class DemoChromelyApp : ChromelyBasicApp
        {

        }
    }
````
![image](https://user-images.githubusercontent.com/18384207/85199902-ad555a00-b2b8-11ea-85f5-a541ec33366e.png)

![image](https://user-images.githubusercontent.com/18384207/85199834-11c3e980-b2b8-11ea-9316-492648732088.png)

![image](https://user-images.githubusercontent.com/18384207/85199816-01137380-b2b8-11ea-9fb2-8d8584cc8f12.png)

**Comment by mattkol** [comment]
@nurbat if you do no mind, please can you rename the issue "Single instance error" or something similar. Easier to refer to it later.

This is important that we get to the bottom of this if still not working for you.

Thanks.

**Comment by nurbat** [comment]
![изображение](https://user-images.githubusercontent.com/5789051/85200680-cd593d80-b2f9-11ea-907a-11178c94c398.png)
![изображение](https://user-images.githubusercontent.com/5789051/85200690-e661ee80-b2f9-11ea-8add-c918075cff3b.png)

**Comment by mattkol** [comment]
So let us separate the issues:
- White screen
- Single instance error (does the mutex work?)
- Spam

Which one of this still showing up?

**Comment by mattkol** [comment]
The white screen may be due to the google url - http/hpps.

I added 2 other options. By try them in turn.
````csharp
            config.StartUrl = "http://google.com";
            config.StartUrl = "https://google.com";
            config.StartUrl = "local://app/index.html";
````
[Example.zip](https://github.com/chromelyapps/Chromely/files/4807810/Example.zip)

**Comment by nurbat** [comment]
1. If you run from the bin folder.
1.1. The Mutex works.
1.2. Spam in console is not present.
1.3. All 3 options work.

2. If you run from the IDE
2.1. Spam in the console there
2.2. White screen
2.3. None of the options works.

**Comment by mattkol** [comment]
Can you try changing to debug mode for IDE. Delete bin/obj folders and retry.
Seems strange.

**Comment by nurbat** [comment]
Ide call app
On CefGlue child process launch arguments:
"C:\Program Files\dotnet\dotnet.exe"

Bin Call app 
On CefGlue child process launch arguments:
"{APP_DIR}\Vodji.Chat.exe"

**Comment by nurbat** [comment]
![изображение](https://user-images.githubusercontent.com/5789051/85201784-55434580-b302-11ea-8e64-01442c90c26e.png)
as I understand it, the application in the bin folder runs under the process, calling itself. what creates new instances in the task Manager.

But the ide apparently runs the application from under the dotnet command, and when it tries to create a subprocess, it refers to the dotnet process and not to the program instance itself.

**Comment by nurbat** [comment]
is there a way to run a sub-process in a thread from the app itself without external calls?

**Comment by mattkol** [comment]
> But the ide apparently runs the application from under the dotnet command, and when it tries to create a subprocess, it refers to the dotnet process and not to the program instance itself.

Not really...

I just ran from IDE and you can see that I am  running from Vodji.Client.exe

![image](https://user-images.githubusercontent.com/18384207/85201910-899a1000-b2c8-11ea-8bd8-df29d3e81385.png)

This seems like an environment issue. From .net core 3.0 it should run from app.exe not dotnet.exe. Looks like on your machine it is falling back to pre 3.0 way.

**It is one of the main reasons we moved to .NET Core 3**

May be this will help:
````
 <PropertyGroup>
  ...
    <PublishSingleFile>true</PublishSingleFile>
...
  </PropertyGroup>
````

If you try the demos, can you run from IDE?

**Comment by nurbat** [comment]
<PublishSingleFile>true</PublishSingleFile>
all project in erros

![изображение](https://user-images.githubusercontent.com/5789051/85202179-ddc2e580-b304-11ea-913a-a9746a0dd700.png)


![изображение](https://user-images.githubusercontent.com/5789051/85202143-9b010d80-b304-11ea-928e-38bf909d6b75.png)

**Comment by mattkol** [comment]
What is the IDE? I am using Visual Studio 2019.

**Comment by nurbat** [comment]
![изображение](https://user-images.githubusercontent.com/5789051/85202301-b7ea1080-b305-11ea-99b0-1866f459c2c1.png)

**Comment by mattkol** [comment]
Not familiar with it.

I just tried on Visual Studio Code and it works.
I still think it is an environment issue. You may have to look at the settings. I cannot remember if I did anything special for my setup.

I am sure there will be some documentation out there that will help.
Thanks.

![image](https://user-images.githubusercontent.com/18384207/85202340-6329a400-b2cb-11ea-8c18-2253977c0416.png)

**Comment by nurbat** [comment]
![изображение](https://user-images.githubusercontent.com/5789051/85202392-668e5100-b306-11ea-8670-7e2566468990.png)

**Comment by nurbat** [comment]
![изображение](https://user-images.githubusercontent.com/5789051/85202575-9b4ed800-b307-11ea-97d2-9af7041c1f80.png)

For those who use Rider
1. Create an Executive profile
2. In the profile to specify the. EXE assembled
3. in the profile, specify that you need to build the project before launching.

**Comment by mattkol** [comment]
@nurbat cool! That is it we are goodie goodie now?

**Comment by nurbat** [comment]
Yes, now everything works well and I will add the word rider to the title so that we can then find how to solve the problem.

**Comment by mattkol** [comment]
Cool! Thanks for bringing this up. I have always had single instance in my mind, just never get to looking into it.
