### ISSUE TITLE
Fill out the documentation

### ISSUE THREAD

**Issue by nurbat** [chromelyapps/Chromely#215]
1. How do I open a new link in an existing window? C#
2. How to execute C# code in JS
3. How to execute JS in C code#
4. how can I move the created window and change its settings ?

**Comment by mattkol** [comment]
1. You mean, like a popup window. Html popup should just work, with JavaScript - window.open(). A child Chromely window is not supported.
2. The [wiki](https://github.com/chromelyapps/Chromely/wiki) has all the documentation  - You cannot directly execute csharp code in JS - you have to do it via the controller classes - see sample usage - [Controller classes](https://github.com/chromelyapps/demo-projects/tree/master/regular-chromely/CrossPlatDemo/Controllers)
3. In [wiki](https://github.com/chromelyapps/Chromely/wiki)- but specifically -  [JavaScript Execution](https://github.com/chromelyapps/Chromely/blob/master/Documents/javascript_execution.md) - see sample usages in all the demos - 

     - Html/JavaScript - https://github.com/chromelyapps/demo-projects/blob/cbb0eb2e930285d28813bbb3e60cc110de68ea0a/regular-chromely/CrossPlatDemo/app/pages/javascriptdemo.html#L72

    -  Code   https://github.com/chromelyapps/demo-projects/blob/cbb0eb2e930285d28813bbb3e60cc110de68ea0a/regular-chromely/CrossPlatDemo/Controllers/ExecuteJavaScriptDemoController.cs#L64

4. Not quite sure I understand.

**Comment by nurbat** [comment]
4. Example:
`var window = Window.Create("Copy Window #2", "http://google.com");
window.Move(x, y);
window.SetStyle(....);
window.SetTitle("new Name Title");
`

**Comment by mattkol** [comment]
- SetTitle  - there is SetWindowTitle - https://github.com/chromelyapps/Chromely/blob/fbd02e3f63322dd63c5afa9a267825013c7ef7ae/src/Chromely.Core/Host/IChromelyNativeHost.cs#L23
- For Move - for now you can implement that in native window. But seems like a functionality we should add.
- SetStyle - that should be done via html/css. 

To implement the [native window](https://github.com/chromelyapps/Chromely/blob/master/src/Chromely.Core/Host/IChromelyNativeHost.cs) -
Assume on Windows, you will inherit  [WinAPIHost](https://github.com/chromelyapps/Chromely/blob/master/src/Chromely/Native/WinAPI/WinAPIHost.cs) and that will give you access to the Handler - https://github.com/chromelyapps/Chromely/blob/fbd02e3f63322dd63c5afa9a267825013c7ef7ae/src/Chromely.Core/Host/IChromelyNativeHost.cs#L14 and other methods you can override.

```csharp
    public class DemoChromelyApp : ChromelyBasicApp
    {
        public override void Configure(IChromelyContainer container)
        {
            base.Configure(container);
			----

            container.RegisterSingleton(typeof(IChromelyNativeHost ), Guid.NewGuid().ToString(), typeof(CustomNativeWindow));
        }
    }

public class CustomNativeWindow : WinAPIHost
{
}
````
