### ISSUE TITLE
Support for new version .net core

### ISSUE THREAD

**Issue by hejiajun107** [chromelyapps/Chromely#216]
Is There Any Plan To Migrate to the version of .net core 3.1

**Comment by nurbat** [comment]
I use Net Core 5
Everything works fine, I don't see any problems using later versions

**Comment by FrankPfattheicher** [comment]
@hejiajun107 
Chromely is a LIBRARY, it is on netstandard 2.0.
netcore3.1 is a RUNTIME.
Your application can use netcore3.1 with netstandard libraries.
So this is no issue here...
