### ISSUE TITLE
Set Min windows size

### ISSUE THREAD

**Issue by Laetar** [chromelyapps/Chromely#218]
Can i somehow set a minimum window size?

**Comment by mattkol** [comment]
@Laetar not out of the box for now. Likely in next version.
But yes, you can - https://github.com/chromelyapps/Chromely/issues/203

**Comment by nicolasdeory** [comment]
@mattkol that broke some stuff for me when running a frameless window.

When that handler is registered, I'm getting a narrow white drag bar, and the window can't be resized.

**Comment by nicolasdeory** [comment]
It seems the cause isn't the min max section of the code, but just handling the message and registering the singleton.
I'm doing this:
            `container.RegisterSingleton(typeof(IChromelyNativeHost), typeof(IChromelyNativeHost).Name, typeof(CustomNativeWindow));`

**Comment by mattkol** [comment]
There are two native classes for Windows:
[WinAPIHost](https://github.com/chromelyapps/Chromely/blob/master/src/Chromely/Native/WinAPI/WinAPIHost.cs)
[FramelessWinAPIHost](https://github.com/chromelyapps/Chromely/blob/master/src/Chromely/Native/WinAPI/FramelessWinAPIHost.cs)

So you may likely have  a wrong base class.

Also the Min/Max functionality was not tested for frameless, so not sure what edge cases may have been missed.

**Comment by nicolasdeory** [comment]
The base class was the problem. There's still the bug when resizing the window, where the layout only updates after the mouse is released.

**Comment by mattkol** [comment]
Frameless window is not optimal. We have had a lot of progress over time on this, but there are still issues for sure. If it is not one of the issues we are tracking you can log it.

Thanks.
