### ISSUE TITLE
Call C# function without using ajax or xhr.

### ISSUE THREAD

**Issue by redplane** [chromelyapps/Chromely#221]
Hi,

I'm having a problem while calling C# function while using **Chromely**.
I have read [this tutorial](https://github.com/chromelyapps/Chromely/blob/master/Documents/ajax_xhr_request_handling.md) which is about calling C# function in **Chromely**, but the solution requires using **ajax** or **xhr**.

This is what I want to achieve in my application.

**device-service.js**
```

deviceUtil = () => {

	getUserDevice() {
		
		if (window.IsUsingChromely())
			return 'chromely';
			
		if (window.IsRaspBerry()) 
			return 'berry';
			
		return 'web-browser';
	}
}

```

I want to create a class **deviceUtil** for detecting whether user is using **Physical device** or **Web browser**, base on the device user is using, I would do different things on different devices. Such as:

- Calling **http://chromely.com** end point if user is using Physical device
- Calling ""http://my-hosting-on-internet.com** end point if user is using web browser.

This kind of [question on stackoverflow about CefSharp](https://stackoverflow.com/questions/23425059/call-net-from-javascript-in-cefsharp-1-wpf) is similar to what I want to achieve.

Any plans for this support, please ?

**Comment by mattkol** [comment]
@redplane 

> .. about calling C# function in Chromely, but the solution requires using ajax or xhr.

Actually Ajax/Xhr is not the default. It is provided for backward compatibility. The primary form is [CEF Generic Message Routing](https://bitbucket.org/chromiumembedded/cef/wiki/GeneralUsage.md#markdown-header-generic-message-router).

See Readme:
> Options of communicating (IPC) with rendering process are via:
Generic Message Routing - more info @ Generic Message Routing.
Ajax HTTP/XHR - more info @ Custom Scheme Handling.

See - https://github.com/chromelyapps/Chromely/blob/master/Documents/generic_message_routing.md

The approaches are basically the same between what is done here and what you shared. Here the method - **cefQuery** is already registered for you. CefSharp allows you to register a custom method and adds more abstractions.

> Any plans for this support, please ?

No there won't be plans for that approach. Current Chromely is based on ONLY CefGlue. Legacy Chromely has [CefSharp functionalities](https://github.com/chromelyapps/Chromely.Legacy/blob/8e71bc91e9aa689a00ac0ca004e6ff73e49a6437/Demos/regular-chromely/Chromely.CefSharp.Winapi.Demo/app/pages/boundobject.html#L38) if you want to revert to CefSharp, but no longer supported.

[See how this is done html](https://github.com/chromelyapps/demo-projects/blob/cbb0eb2e930285d28813bbb3e60cc110de68ea0a/regular-chromely/CrossPlatDemo/app/pages/messagerouterdemo.html#L45)

[In C# (controller)](https://github.com/chromelyapps/demo-projects/blob/cbb0eb2e930285d28813bbb3e60cc110de68ea0a/regular-chromely/CrossPlatDemo/Controllers/DemoController.cs#L35)

Please spend some time getting familiar with the wiki and demos, most basic things you need are there.
