### ISSUE TITLE
MacOSX fails with icudtl.dat not found in bundle

### ISSUE THREAD

**Issue by captainjono** [chromelyapps/Chromely#222]
First off, really like your work on this fork, its the closest to a working xplatform CEF example i can find right now on .net. Kudos on the downloader, no one explains the necessary directory layouts anywhere for this type of setup so its saved me a few nights banging my head against the wall.

Cloning and running the current repo on macOSx Catalina compiles but fails to launch due to this issue

```
CI-TRACE: Application=Started
CI-TRACE: Chromely.Core=5.0.0.4
CI-TRACE: Platform=MacOSX
CI-TRACE: AppDirectory=../Chromely-master/src/Tests/Chromely.Integration.TestApp/bin/x64/Debug/netcoreapp3.1/
CI-TRACE: Configuration=Created
2020-07-13 16:08:00.958 [INFO] Running MacOSX chromium 79.0.3945.130
[0713/160801.050579:ERROR:icu_util.cc(132)] icudtl.dat not found in bundle
[0713/160801.051177:ERROR:icu_util.cc(177)] Invalid file descriptor to ICU data received.
```
https://bitbucket.org/chromiumembedded/java-cef/issues/109/linux-mac-fix-discovery-of-icudtldat

```
.NET Core SDK (reflecting any global.json):
 Version:   3.1.301
 Commit:    7feb845744

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.15
 OS Platform: Darwin
 RID:         osx.10.15-x64
 Base Path:   /usr/local/share/dotnet/sdk/3.1.301/

Host (useful for support):
  Version: 3.1.5
  Commit:  65cd789777

.NET Core SDKs installed:
  2.0.0 [/usr/local/share/dotnet/sdk]
  3.1.300 [/usr/local/share/dotnet/sdk]
  3.1.301 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.4 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.18 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.19 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.4 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
```

If i find a solution i'll make a PR.

**Comment by mattkol** [comment]
@captainjono 

>First off, really like your work on this fork, its the closest to a working xplatform CEF example i can find right now on .net. Kudos on the downloader, no one explains the necessary directory layouts anywhere for this type of setup so its saved me a few nights banging my head against the wall.

Thank you.

Most samples work well on Windows without some modifications. Please let me see if following helps, then we can see how to guide others for MacOS.. 

For Chromely in MacOS, Linux it is best to start with CrossPlatDemo - https://github.com/chromelyapps/demo-projects/tree/master/regular-chromely/CrossPlatDemo

Also please follow the ReadMe minimal 3 steps - https://github.com/chromelyapps/demo-projects#running-the-demos

If that still does not work please see this chromelyapps/Chromely#214
Attached a flattened demo ChromelyMac79.zip that can help with debugging - https://github.com/chromelyapps/Chromely/issues/214#issuecomment-647009304. With this we can know where the issue is coming from.

Thanks.

_

**Comment by captainjono** [comment]
@mattkol 

Sorry i just realised this was a dupe report - sorry about that!

I was not after a .net core solution originally, rather I was attempting to run Chromely via Xamarin.Mac (modern, latest version of the framework that will turn into .net MUI). I leveraged the Chromely.Integration.Test code and shoehorned it into a Xamarin mac solution and it worked after i applied this patch that i found in another fork -> 

```
        protected override void OnBeforeChildProcessLaunch(CefCommandLine browser_cmd)
        {
            // Disable security features
            browser_cmd.AppendSwitch("default-encoding", "utf-8");
            browser_cmd.AppendSwitch("allow-file-access-from-files");
            browser_cmd.AppendSwitch("allow-universal-access-from-files");
            browser_cmd.AppendSwitch("disable-web-security");
            browser_cmd.AppendSwitch("ignore-certificate-errors");

            if (_config.Platform == ChromelyPlatform.MacOSX || _config.Platform == ChromelyPlatform.Linux)
            {
                if (!browser_cmd.HasSwitch("cefglue"))
                {

                    //var path = new Uri(Assembly.GetEntryAssembly().CodeBase).LocalPath;
                    // ^^ not correct path, points too src/TestApp.macOS/bin/Debug/TestApp.Mac.app/Contents/Monobundle/TestApp.Mac.exe

                    //explicit path to see if it solved issue
                    browser_cmd.SetProgram("src/TestApp.macOS/bin/Debug/TestApp.Mac.app/Contents/MacOS/TestApp.Mac");

                    browser_cmd.AppendSwitch("cefglue", "w");
                }
            }

            if (_config.DebuggingMode)
            {
                Console.WriteLine("On CefGlue child process launch arguments:");
                Console.WriteLine(browser_cmd.ToString());
            }
        }
```

Xam mac uses a different folder structure then .net core and also wraps the mono/code in a Cocoa mac.app so it can be natively executed. 

In this case, the app directory ends up being
``` ..src/TestApp.macOS/bin/Debug/TestApp.Mac.app/Contents/MonoBundle ```

this is where CEF.framework is extracted too automatically by your tooling. The xamarin mac folder allows more probing paths, and ultiamtely doesnt trigger the the issue seen in .net core (mac has MANY probing paths, it really go to extreme lengths searching for your library!) i can optionally put CEF.framework in the folder structure specified by the cefclient.mac documentation (Frameworks/Libaries/Resources folders) and it will work.

So folder structure is 1 element of the failure, the other element is the Helper.app's required for cef mac. The setprogram switch takes care of this for Xam.mac because it bundles mono into an native mac executable (using mkbundle i think) and the cefglue.host implements the CEFclient correctly (great job!! - im going to attempt to port to xamarin.mac using / c#). Im not familiar with .net core native binaries, but this may mean you will need to setprogram to Assembly.ExecutingAssembly().Location and then prepend the "dotnet" runner.

Alot of existing examples of mac code that i came across relied on setting the cefsettings.singleprocessmode = true and i think thats why they worked previously without these extra switches. This option is now deprecated, so you must provide helpers as per the CEFClient docuementation.

Regarding .net core, I found another cefglue fork labeled "avalonia" which also runs on .net core. I had alot of trouble getting off the ground because no on explains to you that you needed to rename CEF.framework as distributed from the main repo, to "libcef". For that branch, I was able to resolve the issue but putting CEF.framework in
``` CefGlue.Avalonia/bin/debug/runtimes/osx/native/{cef.framework} ```
But i also had to label from "Chrominium embedded framework" to  "liblibcef". Notice the "liblib"!

This dir didnt exist in your .net core build but i did play around quickly by adding it to all the locations it had probed before but had no luck, could never find the .dat. Thats when i saw that for JCEF, they ended up symloinking this file to what would be the ```/frameworks/{dotnetcore.framework}/dotnet ``` directory witch indicates to me that you might need to setup that new command-line arg as per the link i provided.

I only got this working late last night. I am still cleaning up my code so i can ensure it will slot into my existing code-base correctly (i am replacing cefsharp). Would u like me to submit a PR and a demo project once i have a working / reliable implementation on Xamarin? I think once .net5 lands, Xamarin and net core will be running on the same underlining platform, but until then, they both run .net standard, but xamarin.mac requires a mac to compile on and compiles to native cocoa apps by default.

Ive got a deadline to meet so i cant help right this moment debugging the net core issue. I will check back in on the other thread and it if no one else is able to help i will give you a hand at resolving this.

**Comment by mattkol** [comment]
@captainjono so if I understand this well, this is about Chromely + Xamarin.Mac.

The main objective of Chromely is to provide a single browser framework using the "thinnest" possible native host. 

>  It is focused on building apps based on Xilium.CefGlue, CefSharp implementations of embedded Chromium (CEF) without WinForms or WPF, but can be extended to use WinForms or WPF. Chromely uses Windows, Linux and MacOS native GUI API as "thin" chromium hosts.

Xamarin is a full-fledged UI framework like WPF/WinForms, and as such will violate that premise. I kindda explained more here - https://github.com/chromelyapps/Chromely/issues/52

If you go through the history of Chromely, it took us a while to add MacOS support-  none of the 3 of us has Mac experience. We had a few volunteers, but no serious dedication. I had to learn Cocoa API/Objective C from scratch. Of course I did consider Avalonia, LibUI, and Xamarin.Mac but all were too heavy for what we needed it for. LibUI came close but I was spending a lot of time deleting what was not needed.

So my point is if there is a fork dedicated to Chromely/Xamarin, I think it will be great, but I do not think it is advisable to pull into main repo. You can see that we put a lot of thought into the leanness and simplicity and actually removed CefSharp support because of that. But I am looking to bring it back as a separate project. Something I have always wanted to do,

**Comment by captainjono** [comment]
@mattkol 

I understand the premise of this project and i appreciate its leanness. I disagree Xamarin.mac is fat!

- Xamarin.Mac allows you write C# _instead_ of Objective-C, against ALL the native mac APIs. 

Thats what Xamarin mac is. In theory, i can write LibChromely.dynlib in Xamarin.mac and interface directly with lib_cef_dll without any objective C code.

To elaborate further
- Xamarin.Mac is NOT _Xamarin.Forms_. They _can_ be used with _eachother_, or _seperately_
- _Avalonia_ is a cross-platform UI framework which is designed to have the same "look and feel" on each OS, as opposed to Xamarin.Forms, which is designed to take on the "native look and feel" for each OS. its a fat framework which supports cross-platform p/invoke and takes a different approach to Xamarin.Forms.

The Avalonia fork i mentioned was implemented in .net core as your integration test isI mentioned it because it had a different directly layout and didnt suffer from .dat issue i am experiencing with yours. I mentioned it purely to help with your debugging of this issue. It suffered from other problems though and didnt launch.

I liteterly copy/pasted the current integration test into a Xam.mac project, compiled and ran it, and it basically worked except for the browser_sub_process issue i mentioned previously.

In terms of what i value in cross-platform code, i value the ability to run the _same code_ on _any platform_ so i can re-use logic and tests and onboard new platforms without fuss. I think restricting yourself to running on .net core only defeats the purpose of .net standard and the work you have done to make this library compliant with it.

My end goal is to run the same SPA/C# backend using CEF on Win/mac/Linux/Andriod/iOS.

**Comment by captainjono** [comment]
@mattkol 

i understand what you are saying now. Point noted on not wanting to show Xamarin.mac as a supported path as it will increase the workload in the project without appropriate resources and dilute the work going into other areas.

From my perspective, i wanted to show the community an option for Xamarin.mac with CEF. I will continue to work on my intergration and if i am successful i will push a branch to help others out.
