### ISSUE TITLE
v5 and custom CefResourceHandler

### ISSUE THREAD

**Issue by viceice** [chromelyapps/Chromely#224]
I'm currently using chromely v4 and want to migrate to v5 but i have some issues.

I'm using a custom `CefResourceHandler` and `CefSchemeHandlerFactory`. On v4 i could use `IChromelyConfiguration.RegisterSchemeHandler` to use it.

I use it to process all requests with a specific path prefix. 
Is there a better way to generically process these requests?
I don't want to add a controller for each url, because there are to many.
On my normal aspnet core project i can simply use a `IApplicationBuilder.Map` to process requests.

I also use my processing runtime from `HttpTaskAsyncHandler` in net45 aspnet framework, so it needs to be generic for all.

**Comment by mattkol** [comment]
@viceice please check the [wiki](https://github.com/chromelyapps/Chromely/wiki) almost everything you need is there.

Specifically - [Scheme Handlers](https://github.com/chromelyapps/Chromely/blob/master/Documents/registering_scheme_handlers.md)
	
````csharp
 public class DemoChromelyApp : ChromelyBasicApp
    {
        public override void Configure(IChromelyContainer container)
        {
            base.Configure(container);
            container.RegisterSingleton(typeof(IChromelySchemeHandlerFactory), "custom-01", 
typeof(CustomHttpSchemeHandlerFactory));
        }
    }
````

You do not have to add controllers for each url ,  you can register the assemblies where they are defined:

````csharp
    var config = new DefaultConfiguration();
    config.ControllerAssemblies = new List<ControllerAssemblyInfo>();
    config.ControllerAssemblies.RegisterServiceAssembly("Chromely.External.Controllers.dll");
````

More assembly registrations [options here](https://github.com/chromelyapps/Chromely/blob/1a358986894377da8cffe87e00ce0d5893db690b/src/Chromely.Core/Network/RegisterServiceAssembliesExtension.cs).

**Comment by viceice** [comment]
Thanks, got it to compile again, but did not have time to fully test 🙃
