### ISSUE TITLE
mac CreateMainView never returns

### ISSUE THREAD

**Issue by captainjono** [chromelyapps/Chromely#226]
Using v5.0.0.4

I am seeing the behavior outlined in the below code when extending chromelywindow. 

In both cases Chromely correctly opens and displays the browser. Is this expected or a bug?

```  
public class TestChromelyWindow : ChromelyWindow
    {

        public TestChromelyWindow(IChromelyNativeHost nativeHost, IChromelyContainer container, IChromelyConfiguration config, IChromelyRequestTaskRunner requestTaskRunner, IChromelyCommandTaskRunner commandTaskRunner) : base(nativeHost, container, config, requestTaskRunner, commandTaskRunner)
        {

        }


        protected override IWindow CreateMainView()
        {
            //called on win and mac

            var result = base.CreateMainView();

            //never returns on mac

            return result;
        }

        protected override void Run()
        {
            //never called on mac
            base.Run();
        }
    }
```

**Comment by mattkol** [comment]
@captainjono 

Yes it is expected - those methods are never call for Mac. This is part of the challenge with having a single code source for cross-platform, the platforms do not play same way.

Those 2 methods are handled in [libchromely.dylib](https://github.com/chromelyapps/Chromely/blob/master/src/mac/chromely_mac.mm) that you are familiar with. If you want to subscribe to some events, I will suggest any of these delegates passed to it - https://github.com/chromelyapps/Chromely/blob/867e69fd32d4efc2395baffd5eeeda7418cdf469/src/Chromely/Native/MacCocoa/MacCocoaHost.cs#L48

**Comment by captainjono** [comment]
Ok great - I just wanted to ensure i wasnt doing anything wrong.

Thanks for tips!
