### ISSUE TITLE
launch crash on osx 10.15.6

### ISSUE THREAD

**Issue by windhuan** [chromelyapps/Chromely#227]
my code 

    class Program
    {
        static void Main(string[] args)
        {
            var config = DefaultConfiguration.CreateForRuntimePlatform();
            config.WindowOptions.Title = "Title Window";
            config.StartUrl = "http://www.baidu.com";

            AppBuilder
       .Create()
          .UseConfiguration<DefaultConfiguration>(config)
       .UseApp<ChromelyBasicApp>()
       .Build()
       .Run(args);
            Console.WriteLine("Hello World!");
        }
    }
launch logs:

[Chromely.log](https://github.com/chromelyapps/Chromely/files/4974967/Chromely.log)

**Comment by mattkol** [comment]
Please see - https://github.com/chromelyapps/Chromely/issues/228

**Comment by windhuan** [comment]
> Please see - #228

use CrossPlatDemo project get the same error

**Comment by mattkol** [comment]
In the previous comment, this is what you are running:
````
wind@WindMacBook ~ % cd /Users/wind/Projects/ChromelyTest/ChromelyTest/bin/Release/netcoreapp3.1
wind@WindMacBook netcoreapp3.1 % dotnet ChromelyTest.dll
````

You need to run the application (exe file) itself - should be crossplatdemo **(not *.dll)**. Please follow the 3 items in the readme. 

If you follow the guide and use Visual Studio Code, it is easier.

dotnet restore
dotnet build
dotnet run

All in the readme.

**Comment by windhuan** [comment]
> In the previous comment, this is what you are running:
> 
> ```
> wind@WindMacBook ~ % cd /Users/wind/Projects/ChromelyTest/ChromelyTest/bin/Release/netcoreapp3.1
> wind@WindMacBook netcoreapp3.1 % dotnet ChromelyTest.dll
> ```
> 
> You need to run the application (exe file) itself - should be crossplatdemo **(not *.dll)**. Please follow the 3 items in the readme.
> 
> If you follow the guide and use Visual Studio Code, it is easier.
> 
> dotnet restore
> dotnet build
> dotnet run
> 
> All in the readme.

Thanks,  i found the issue, it's caused by  CefGlue child process.
