### ISSUE TITLE
ChromelyResponse won't serialize structs correctly

### ISSUE THREAD

**Issue by nicolasdeory** [chromelyapps/Chromely#229]
I made a controller that returns a list of `struct` objects, each `struct` with three `float` values.

When I print the console output in the dev tools or print the JSON representation of the `ChromelyResponse` object, structs are serialized as `{}`.

Do structs have to be wrapped in an object in order to be properly serialized?

**Comment by mattkol** [comment]
@nicolasdeory Chromely uses System.Text.Json, so may you want to look closely into that for struct serialization.

May be related to this: 
https://github.com/dotnet/runtime/issues/29455

Using what was discussed here, may help:
https://stackoverflow.com/questions/59242149/jsonserializer-struct-with-asp-net-core-3-0

````
        [Serializable]
        struct Item
        {
            public float x { get; set; }
            public float y { get; set; }
            public float z { get; set; }
        }
````
````
            var item= new Item();
            item.x = 10.0F;
            item.y = 10.0F;
            item.z = 10.0F;

            return new ChromelyResponse(request.Id)
            {
                Status = 200,
                Data = item
            };

````
````
{
   "RequestId":"",
   "ReadyState":4,
   "Status":200,
   "StatusText":"OK",
   "Data":{
      "x":10,
      "y":10,
      "z":10
   }
}
````

**Comment by nicolasdeory** [comment]
Thanks for the detailed response. Adding public properties and the `Serializable` attribute fixes the issue.
