### ISSUE TITLE
cefQuery return Chromely.Core.Network.ChromelyResponse

### ISSUE THREAD

**Issue by redplane** [chromelyapps/Chromely#231]
Hi,

I'm following [this tutorial](https://github.com/chromelyapps/Chromely/blob/master/Documents/generic_message_routing.md) and [this tutorial](https://github.com/chromelyapps/demo-projects/blob/cbb0eb2e930285d28813bbb3e60cc110de68ea0a/regular-chromely/CrossPlatDemo/app/pages/messagerouterdemo.html#L45) to call a method in controller.

This is my controller code:

```
public class SystemController : ChromelyController
    {
        #region Properties

        private readonly IHttpResponseService _httpResponseService;


        #endregion

        #region Constructor

        public SystemController(IHttpResponseService httpResponseService)
        {
            _httpResponseService = httpResponseService;

            RegisterGetRequest("/system/platform", GetPlatformAsync);
        }

        #endregion

        #region Methods

        /// <summary>
        /// Get platform asynchronously.
        /// </summary>
        /// <returns></returns>
        public virtual ChromelyResponse GetPlatformAsync(ChromelyRequest arg)
        {
            ChromelyResponse httpResponse;
            if (RuntimeInformation.IsOSPlatform(OSPlatform.Windows))
                httpResponse = _httpResponseService.ToValidResponse(Platforms.Windows);
            else if (RuntimeInformation.IsOSPlatform(OSPlatform.Linux))
                httpResponse = _httpResponseService.ToValidResponse(Platforms.Linux);
            else if (RuntimeInformation.IsOSPlatform(OSPlatform.OSX))
                httpResponse = _httpResponseService.ToValidResponse(Platforms.MacOs);
            else
                httpResponse = _httpResponseService.ToValidResponse(Platforms.Unknown);

            return httpResponse;
        }

        #endregion
    }
```

This is the service I'm using to generate response:

```
 public class HttpResponseService : IHttpResponseService
    {
        #region Methods

        public virtual ChromelyResponse ToValidResponse()
        {
            var validHttpResponse = new ValidHttpResponseViewModel<object>((object) null, HttpStatusCode.OK);
            var chromelyResponse = new ChromelyResponse();
            chromelyResponse.Data = JsonConvert.DeserializeObject(JsonConvert.SerializeObject(validHttpResponse,
                new JsonSerializerSettings() { ContractResolver = new CamelCasePropertyNamesContractResolver() }));

            return chromelyResponse;
        }
        #endregion
    }
```

- The function I'm using to call command:

```
const fullUrl = `/system/platform`;

                    const httpRequest = {
                        "method": "GET",
                        "url": fullUrl,
                        "parameters": null,
                        "postData": null
                    };

                    cefQuery({
                        request: JSON.stringify(httpRequest),
                        onSuccess: (httpResponse) => {
                            console.log(httpResponse);
                        },
                        onFailure: (error_code, error_message) => {
                            console.log(error_code);
                            console.log(error_message);
                        }
                    })
```

- Expected:

  - Returned data should be :
```
{
 data: 2,
 status: 200
}
```

- Actual:

  - Returned data is: `Chromely.Core.Network.ChromelyResponse`.

Am I missing anything ?
Thank you,

**Comment by mattkol** [comment]
@redplane there is a bug related to this, but not a fix for what you raised.

What you are doing is double serialization of the property: Data. First you serialize "Data" and the framework serializes the entire ChromelyResponse object. That is why you see the error.
https://github.com/chromelyapps/Chromely/blob/9bf2efb2c25e6a9ea31b6cba8b6f422647d2642c/src/Chromely.CefGlue/Browser/Handlers/CefGlueMessageRouterHandler.cs#L60

The issue of camelCase was raised here - https://github.com/chromelyapps/Chromely/issues/209
Unfortunately, no changes will be made to that for current Chromely. 

This is now implemented in Chromely 5.1
https://github.com/chromelyapps/Chromely/blob/master/src_v5_1/Chromely.Core/IChromelySerializerUtil.cs
https://github.com/chromelyapps/Chromely/blob/master/src_v5_1/Chromely.Core/Defaults/DefaultSerializerUtil.cs
https://github.com/chromelyapps/demo-projects/blob/a7fd0826ea2cfeee68683aacd7e1a60550779771/chromely_v5_1/CrossPlatDemo/Program.cs#L73

My suggestion is you do any of these, if relevant:
- Do not serialize the Data - leave as-is 
- If you have to you can add JsonProperty attributes to ensure camel case, like below - there may be other ways.
   - https://stackoverflow.com/questions/58475629/what-is-the-equivalent-of-newtonsoft-jsons-json-nets-jsonproperty-field-in-s
   - https://stackoverflow.com/questions/56360401/jsonconverter-equivalent-in-using-system-text-json
- The other option is to register custom handlers.
- Or you try version v5.1.
