### ISSUE TITLE
Frameless mode: top ~30px of window: mouse click does not work. mouse click+drag works like there a window title bar there

### ISSUE THREAD

**Issue by GerHobbelt** [chromelyapps/Chromely#232]
While checking out #230, I noted this in the code provided there:

The webpage shown in the frameless window has a couple of buttons at the top, plus an input field.

Clicking on the input field does nothing, whatever I do.

Clicking on the buttons (divs) **only works when you click near their bottom edge**, i.e. about 30-35px from the top of the frameless window.

When click anywhere in the page closer to the top (you see a mouse cursor change when hovering there), you can click+drag to move the Chromely app window itself. Looks to me like a still-present-yet-invisible Windows titlebar is somehow 'overlaid' over the HTML content.

Repo for code to reproduce issue:

https://github.com/GerHobbelt/chromely-issue-230

- build master branch
- run
- click 'START' or 'RESTART' button to having something running
- try clicking the big setInterval or animationFrame button at the very top to change the statistics shown.

(If you want to run with minimal JS code, use commit https://github.com/GerHobbelt/chromely-issue-230/commit/9fd6f13e89dea4e0d9e07ecac36d7f9ecfee967e but the important (top) part of the UI remains the same)

Possibly related to #174 🤔

**Comment by mattkol** [comment]
@GerHobbelt 
Looks like you need to split the drag zones into smaller widths.

https://github.com/chromelyapps/Chromely/blob/9bf2efb2c25e6a9ea31b6cba8b6f422647d2642c/src/Chromely.Core/Configuration/FramelessOption.cs#L33

![image](https://user-images.githubusercontent.com/18384207/89351101-4bda2680-d67f-11ea-8ba4-5081c40ecf6b.png)

**Comment by GerHobbelt** [comment]
Aha!

Thanks! 👍
