### ISSUE TITLE
Cannot access my controller

### ISSUE THREAD

**Issue by Nickman87** [chromelyapps/Chromely#233]
I've been staring and trying stuff for the past hours and cannot find why one of my controllers does not want to be triggered...
Posting this in hope somebody can point me in the right direction.

Controller:
```
using Chromely.Core.Network;
using CTEPDotNetLib.Transactions.Retail;
using NerdPOS.DTOs;
using NerdPOS.Logic.JSON;
using NerdPOS.Peripherals.Terminals.Worldline;
using NerdPOS.Services;
using System.Linq;
using System.Text.Json;

namespace NerdPOS.Controllers
{
    [ControllerProperty(Name = "TerminalController", Route = "terminalcontroller")]
    public class TerminalController : ChromelyController, IYomaniListener
    {
        private readonly ClientEventsService ClientEventsService;

        private Yomani _instance;
        private Yomani YomaniInterface
        {
            get
            {
                if (_instance == null)
                {
                    _instance = new Yomani(this);
                }

                return _instance;
            }
            set
            {
                _instance = value;
            }
        }

        public TerminalController(ClientEventsService clientEventsService)
        {
            ClientEventsService = clientEventsService;

            RegisterGetRequest("/terminal/start", StartTerminal);
            RegisterGetRequest("/terminal/stop", StopTerminal);
        }

        [HttpGet(Route = "/terminal/start")]
        public ChromelyResponse StartTerminal(ChromelyRequest request)
        {
            YomaniInterface.StartService();
            return new ChromelyResponse() { RequestId = request.Id };
        }

        [HttpGet(Route = "/terminal/stop")]
        public ChromelyResponse StopTerminal(ChromelyRequest request)
        {
            YomaniInterface.StopService();
            return new ChromelyResponse() { RequestId = request.Id };
        }

        [HttpPost(Route = "/terminal/payment")]
        public ChromelyResponse CreateOrder(ChromelyRequest request)
        {
            var payment = ((JsonElement)request.PostData).ToObject<Payment>();

            YomaniInterface.ProcessPayment(YomaniInterface.TerminalIdentifiers.First(), payment);

            return new ChromelyResponse()
            {
                RequestId = request.Id
            };
        }

        public void OnPaymentSuccesfull(SaleResult result)
        {
            /*
                authorized amount: 1
	            authorization code: D44812
	            sale system action identifier: 01020300
            */
            ClientEventsService.SendEvent("terminalPaymentSuccess", new
            {
                amount = result.authorizedAmount(),
                authorizationCode = result.authorizationCode(),
                timestamp = result.timeStamp(),
                actionIdentifier = result.saleSystemActionIdentifier() // TODO we might need to pass this in?
            });
        }

        public void OnPaymentFailed(string code, string description)
        {
            ClientEventsService.SendEvent("terminalPaymentFailed", new
            {
                code, description
            });
        }

        public void OnTerminalListUpdated()
        {
            ClientEventsService.SendEvent("terminalListUpdated", YomaniInterface.TerminalIdentifiers);
        }

        public void OnStatusUpdate(string status)
        {
            ClientEventsService.SendEvent("terminalStatusUpdate", status);
        }
    }
}
```

Registration:
```
container.RegisterSingleton(typeof(ChromelyController), Guid.NewGuid().ToString(), typeof(TerminalController));
```

Calling:
```
    messageRouterGet(
      "/terminal/start",
      null,
      () => {
        console.log("terminal start sent");
      },
      (...params) => {
        console.log("terminal sent failed", params);
      }
    );
```

messageRouterGet (little adaptation on the one from the examples):
```
export function messageRouterGet(url, parameters, callback, onError, mocks) {
  var request = {
    method: "GET",
    url: url,
    parameters: parameters,
    postData: null,
  };

  if (!window.cefQuery) {
    if (callback) callback(mocks);
    return;
  }

  window.cefQuery({
    request: JSON.stringify(request),
    onSuccess: (response) => {
      var jsonData = JSON.parse(response);
      if (jsonData.ReadyState == 4 && jsonData.Status == 200) {
        if (callback) callback(jsonData.Data);
      } else {
        console.log(
          "An error occurs during message routing. With ur:" +
            url +
            ". Response received:" +
            response
        );
      }
    },
    onFailure: (err, msg) => {
      console.error(err, msg);
      if (onError) onError(err, msg);
    },
  });
}
```

I've been using this setup for multiple controllers for a while now and everything works fine. But this controller does not want to trigger.
I added the `RegisterGetRequest` calls as a last resort to get them called, but to no avail.
The `messageRouterGet` is being called correctly, but never returns, no success and no error.

If anyone can help me, That would be amazing!

**Comment by mattkol** [comment]
@Nickman87 

Only thing I see is,  you have 5 parameters in messageRouterGet method definition. You are passing 4 parameters.
````
messageRouterGet(url, parameters, callback, onError, mocks) 
````
Also you have:
````
 RegisterGetRequest("/terminal/start", StartTerminal);
````
and
````
[HttpGet(Route = "/terminal/start")]
````

You need to pick one. The system will register the first one it encounters. Consequent ones with same url keys will be ignored.

**Comment by Nickman87** [comment]
@mattkol thanks for the response.
The double route registration was a last resort try. The method is just never triggered.
The missing parameter of the messageRouterGet should not be an issue, as I even call it with just a single parameter in some places and it works perfectly.

Is there a way to debug the actual registered routes in the Chromely framework?

**Comment by mattkol** [comment]
@Nickman87 

Sure you can debug the registered routes - you can see if the route is registered - [Routes](https://github.com/chromelyapps/Chromely/blob/master/src/Chromely.Core/Infrastructure/ServiceRouteProvider.cs) but if you asked me I won't spend that much time there at the initial stage. You said it works for other controllers, right?

I will suggest you do the following first:
- Ensure you are actually calling messageRouterGet method. Put as many console logs as possible and use [DevTools](https://github.com/chromelyapps/Chromely/blob/master/Documents/devtools.md) to see if you are getting the console messages. If you are sure the ceQuery is being triggered and there is no error in devtools (html/js errors),then you can focus on the controller.
Something like: (**not sophisticated, yes, but helps quickly to localize**).
````
export function messageRouterGet(url, parameters, callback, onError, mocks) {
 *****console.log('message 1');

  var request = {
--
  };

  if (!window.cefQuery) {
  }

  *****console.log('message 2');

  window.cefQuery({
    onSuccess: (response) => {
       *****console.log('message 3');
         ---
      }
    },
    onFailure: (err, msg) => {
     *****console.log('message 4');
     --
    },
  });
}
````
- At the controller end - use System.Console.Writeline too .. using breakpoints sometime may not help because of mulithreading.
- If you are now sure it is the controller then you can start with simple skeletal controller that works. You can change the url keys  "/terminal/start" to "/terminal/start001" for instance to  make sure it is not being used somewhere else in your app.
- Also I am guessing this is React App. If it is start with the demo and work backwards.
   - I noticed use of "module.export" and "this" in the demo .. cannot remember the details around that - https://github.com/chromelyapps/demo-projects/blob/4dff87d6fbb5c09ef59ca3ffab901bad167dc24a/angular-react-vue/ChromelyReact/reactapp/src/services/Chromely.Service.js#L2
