### ISSUE TITLE
Chromely Transparent Window

### ISSUE THREAD

**Issue by mattkol** [chromelyapps/Chromely#235]
To create transparent window, please follow the guide here:
https://www.experts-exchange.com/articles/1783/Win32-Semi-Transparent-Window.html

- First you create a custom NativeHost
````csharp
    public class CustomNativeWindow : WinAPIHost
    {
        enum LWA : uint
        {
            COLORKEY = 0x00000001,
            ALPHA = 0x00000002
        }

        [DllImport("user32.dll", ExactSpelling = true, SetLastError = true)]
        static extern bool SetLayeredWindowAttributes(IntPtr hwnd, int crKey, byte bAlpha, LWA dwFlags);

        public override void CreateWindow(IWindowOptions options, bool debugging)
        {
            base.CreateWindow(options, debugging);

            SetLayeredWindowAttributes(Handle, 0, (255 * 70) / 100, LWA.ALPHA);
        }
    }
````

- Set the window styles 
````csharp
            var config = DefaultConfiguration.CreateForRuntimePlatform();
            config.StartUrl = "local://app/chromely.html";

            var styles = WindowStyles.WS_OVERLAPPEDWINDOW | WindowStyles.WS_CLIPCHILDREN | WindowStyles.WS_CLIPSIBLINGS;
            var exStyles = WindowExStyles.WS_EX_LAYERED;
            config.WindowOptions.UseCustomStyle = true;
            config.WindowOptions.CustomStyle = new WindowCustomStyle((int)styles, (int)exStyles);
````

- 

Register the Native window
````csharp
    public class DemoChromelyApp : ChromelyBasicApp
    {
        public override void Configure(IChromelyContainer container)
        {
            base.Configure(container);
            --
            container.RegisterSingleton(typeof(IChromelyNativeHost), typeof(IChromelyNativeHost).Name, typeof(CustomNativeWindow));
        }
    }
````

See attached for source code - [ChromelyTransparentWindow.zip](https://github.com/chromelyapps/Chromely/files/5048452/ChromelyTransparentWindow.zip)

![image](https://user-images.githubusercontent.com/18384207/89742462-2f1b6580-da68-11ea-888c-afac1017537a.png)

**Comment by orrburgel** [comment]
Hey,
Is there a way to make just a single color transparent and not the entire window? similar to what you can see here:
https://ourcodeworld.com/articles/read/315/how-to-create-a-transparent-window-with-electron-framework
![image](https://user-images.githubusercontent.com/41600149/114109515-1a84bb00-98de-11eb-8074-bb1376d3be10.png)
![image](https://user-images.githubusercontent.com/41600149/114109609-43a54b80-98de-11eb-8787-99173776de9d.png)
![image](https://user-images.githubusercontent.com/41600149/114109627-4ef87700-98de-11eb-9097-aad9825ebd72.png)
![image](https://user-images.githubusercontent.com/41600149/114109652-5b7ccf80-98de-11eb-910d-d0ced32917b4.png)
