### ISSUE TITLE
: Gdk-ERROR **: The program 'ceshi' received an X Window System error.

### ISSUE THREAD

**Issue by dreamsfly900** [chromelyapps/Chromely#242]
: Gdk-ERROR **: The program 'ceshi' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadValue (integer parameter out of range for operation)'.
  (Details: serial 210 error_code 2 request_code 12 (core protocol) minor_code 0)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the GDK_SYNCHRONIZE environment
   variable to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
[0825/094900.513878:ERROR:sandbox_linux.cc(374)] InitializeSandbox() called with multiple threads in process gpu-process.
Trace/breakpoint trap(吐核)
[root@localhost winform]# [0825/094915.530340:INFO:child_thread_impl.cc(839)] ChildThreadImpl::EnsureConnected()
[0825/094915.792479:INFO:child_thread_impl.cc(839)] ChildThreadImpl::EnsureConnected()

**Comment by mattkol** [comment]
@dreamsfly900  is this a continuation of https://github.com/chromelyapps/Chromely/issues/240? We can close that if not needed anymore.

This log is intentional to help in debugging. Generally they are not showstoppers. Looks more of a disconnect between CEF and GDK/X Window. Those who are experts in X Window may help guide in what is going on. 

You can also ignore the logs if you like by turning debugging off - https://github.com/chromelyapps/Chromely/blob/5e3b2124bccd5f7343ed2c5f72145724c27295ce/src/Chromely.Core/Configuration/IChromelyConfiguration.cs#L17

**Comment by dreamsfly900** [comment]
config.DebuggingMode = false;

The error was 'BadValue (integer parameter out of range for operation)'.
  (Details: serial 210 error_code 2 request_code 12 (core protocol) minor_code 0)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the GDK_SYNCHRONIZE environment
   variable to change this behavior. You can then get a meaningfu

**Comment by dreamsfly900** [comment]
# hostnamectl
   Static hostname: localhost.localdomain
         Icon name: computer-vm
           Chassis: vm
        Machine ID: a753f8a59ae447959cd59e145c5e8035
           Boot ID: 3e68ea50280a4be499f9fe120f96558a
    Virtualization: vmware
  Operating System: CentOS Linux 7 (Core)
       CPE OS Name: cpe:/o:centos:centos:7
            Kernel: Linux 3.10.0-862.el7.x86_64
      Architecture: x86-64

**Comment by mattkol** [comment]
> config.DebuggingMode = false;
The error was 'BadValue (integer parameter out of range for operation)'.
(Details: serial 210 error_code 2 request_code 12 (core protocol) minor_code 0)
(Note to programmers: normally, X errors are reported asynchronously;
that is, you will receive the error a while after causing it.
To debug your program, run it with the GDK_SYNCHRONIZE environment
variable to change this behavior. You can then get a meaningfu

Definitely not what I am thinking. The is an error then not a warning. Can you please attach the log, it should be under folder Logs in the bin directory.

Thanks,
