### ISSUE TITLE
file:/// type resource path problem

### ISSUE THREAD

**Issue by kefengwei** [chromelyapps/Chromely#244]
It can't correct load the resource when  the path has special character(like `space`  ,`+`  and chinese character) by use   `file:///` type path.
example:
` <img src="file:///d:/projects/hello world/header.jpg">` 
 the image can't correct load.

**Comment by mattkol** [comment]
@kefengwei please note that use of file protocol is discouraged generally.
https://www.magpcss.org/ceforum/viewtopic.php?f=6&t=17015
https://github.com/chromelyapps/Chromely/blob/master/Documents/loading_html.md#file-protocol

But with a custom resource handler - sample shared with you in #246 you may be able to get around it.

I am curious too, so may try it over the weekend.

Thanks.

**Comment by kefengwei** [comment]
@mattkol  Thanks for your response. The `local:://` protocol has the same problem. I will try the new sample.

**Comment by kefengwei** [comment]
@mattkol I try the new sample. it's working when the path used by the `StartUrl`. But It's not working in `file:///` type or `my-schema` type when I run this in blazor server mode.
This is Demo project(These are changes in the `Test.razor` and `Program.cs`):
   

>  [ServerAppDemo.zip](https://github.com/chromelyapps/Chromely/files/5284116/ServerAppDemo.zip)

**Comment by mattkol** [comment]
@kefengwei the custom resource handling process is not meant for file protocol. That was the reason for pointing out that it is "generally discouraged". It is not officially supported either, but I have seen some developers use it successfully.

I have also never used it differently besides the start url. 

This is what I will do:
````
<img src="/d/projects/hello world/header.jpg">
<img src="./d/projects/hello world/header.jpg">
````

Then in the handler map ""/d/projects/hello world/header.jpg" to "/d:/projects/hello world/header.jpg" and read from actual file in the directory - https://github.com/chromelyapps/Chromely/blob/7f8ba7ee7c350825855a5d58f05c347b348123a5/src/Chromely/Browser/Handlers/DefaultResourceSchemeHandler.cs#L33

**Comment by cederron** [comment]
This is such a common requirement for a desktop application... I wonder why there is not already some handler for this situation , or at least provide some code to easily paste, for non cef experts...
Now i'm going to investigate and implement a custom resource scheme handler, sigh

**Comment by simonbuehler** [comment]
@cederron did you succeed with it? i also need the resouces to be editable (filesystem based) and not packed away in dlls.

**Comment by mattkol** [comment]
@simonbuehler attached is a demo of one approach.
I will find time to look at it closely to make it a lot simpler.


[CrossPlatDemo.zip](https://github.com/chromelyapps/Chromely/files/6795391/CrossPlatDemo.zip)

````c#
    public class DemoApp : ChromelyBasicApp
    {
        public override void ConfigureServices(IServiceCollection services)
        {
            base.ConfigureServices(services);

            services.AddSingleton(typeof(IChromelySchemeHandler), typeof(CustomSchemeHandler));

            RegisterControllerAssembly(services, typeof(DemoApp).Assembly);
        }
    }

    public class CustomSchemeHandler : IChromelySchemeHandler
    {
        public CustomSchemeHandler()
        {
            Name = "MyCustomResourceSchemeHamdler";
            // Scheme: htpp
            // Host: img- placeholder for folder name/or network path containing resource files
            Scheme = new UrlScheme("mycustomscheme", "http", "img", string.Empty, UrlSchemeType.Resource, false);
            HandlerFactory = new CustomResourceSchemeHandlerFactory(new DefaultErrorHandler());
            IsCorsEnabled = true;
            IsSecure = false;
        }

        public string Name { get; set; }
        public UrlScheme Scheme { get; set; }
        public object Handler { get; set; }
        public object HandlerFactory { get; set; }
        public bool IsCorsEnabled { get; set; }
        public bool IsSecure { get; set; }
    }

    public class CustomResourceSchemeHandlerFactory : DefaultResourceSchemeHandlerFactory
    {
        public CustomResourceSchemeHandlerFactory(IChromelyErrorHandler chromelyErrorHandler) : base(chromelyErrorHandler)
        {
        }

        protected override CefResourceHandler Create(CefBrowser browser, CefFrame frame, string schemeName, CefRequest request)
        {
            return new CustomResourceSchemeHandler(_chromelyErrorHandler);
        }
    }

    public class CustomResourceSchemeHandler : DefaultResourceSchemeHandler
    {
        private const string FOLDER = @"E:\img";

        public CustomResourceSchemeHandler(IChromelyErrorHandler chromelyErrorHandler) : base(chromelyErrorHandler)
        {
        }

        [Obsolete]
        protected override bool ProcessRequest(CefRequest request, CefCallback callback)
        {
            // http://img/chromely_gray.png
            var u = new Uri(request.Url);
            var file = $"{FOLDER}{u.AbsolutePath}";

            _totalBytesRead = 0;
            _chromelyResource.Content = null;
            _completed = false;

            _fileInfo = new FileInfo(file);
            // Check if file exists 
            if (!_fileInfo.Exists)
            {
                _chromelyResource = _chromelyErrorHandler.HandleError(_fileInfo);
                callback.Continue();
            }
            // Check if file exists but empty
            else if (_fileInfo.Length == 0)
            {
                _chromelyResource = _chromelyErrorHandler.HandleError(_fileInfo);
                callback.Continue();
            }
            else
            {
                Task.Run(() =>
                {
                    using (callback)
                    {
                        try
                        {
                            var fileBytes = File.ReadAllBytes(file);
                            _chromelyResource.Content = new MemoryStream(fileBytes);

                            string extension = Path.GetExtension(file);
                            _chromelyResource.MimeType = MimeMapper.GetMimeType(extension);
                            _chromelyResource.StatusCode = ResourceConstants.StatusOK;
                            _chromelyResource.StatusText = ResourceConstants.StatusOKText;
                        }
                        catch (Exception exception)
                        {
                            _chromelyResource = _chromelyErrorHandler.HandleError(_fileInfo, exception);
                        }
                        finally
                        {
                            callback.Continue();
                        }
                    }
                });

                return true;
            }

            callback.Dispose();
            return false;
        }
    }
````

````javascript
  <img src="http://img/chromely_gray.png" class="img-rounded" alt="Cinque Terre" width="240" height="240">
````

![image](https://user-images.githubusercontent.com/18384207/125165774-74f41880-e166-11eb-9f7c-91e80d71bb74.png)

![image](https://user-images.githubusercontent.com/18384207/125165813-994ff500-e166-11eb-8e54-139939d2cc85.png)

**Comment by cederron** [comment]
> @cederron did you succeed with it? i also need the resouces to be editable (filesystem based) and not packed away in dlls.

Yes, But i ditched scheme handlers and all that stuff.

I assign img src to a controller returning a FileStream result. Works great and much simpler.
(I'm using Chromely + Blazor)

`<img  src="@("/api/download/image?filename=" + item.Thumb)" />`

`[Route("image")]
        public async Task<FileStreamResult> Image(string filename)
        {
            FileStream stream = null;
            stream = System.IO.File.OpenRead(filename);
            FileStreamResult result = File(
            fileStream: stream,
            contentType: new MediaTypeHeaderValue("image/" + Path.GetExtension(filename).Remove(0, 1)).MediaType
             );
            return result;
        }`

**Comment by simonbuehler** [comment]
thanks for the feedback i will check it out!

**Comment by mattkol** [comment]
Please read! - https://github.com/chromelyapps/Chromely/issues/357
