### ISSUE TITLE
Angular Watch

### ISSUE THREAD

**Issue by Eonasdan** [chromelyapps/Chromely#245]
Is it possible to get the page to refresh when using something like angular watch or `ng serve`? I was able to point the start url to the angular server but unfortunately, webpack didn't cause a refresh. I think webpack uses sockets for this.

It's unfortunate that the Controllers aren't parity with web api controllers.  Right now I think I'll create a test webapi project and point the angular fetching bits to that project and just run `npm start` against the angular project. This will let me me more rapidly prototype the over all project. Unfortunately this will require me to duplicate work back to the Chromely controllers.

**Comment by mattkol** [comment]
@Eonasdan 
> Is it possible to get the page to refresh when using something like angular watch or ng serve? 

I do not see why not. If it works in Chrome outside Chromely it should work in Chromely too.

> It's unfortunate that the Controllers aren't parity with web api controllers. 

Chromely is intended to be far lighter than web api. So a much lighter controller pattern.

> Right now I think I'll create a test webapi project and point the angular fetching bits to that project and just run npm start against the angular project. This will let me me more rapidly prototype the over all project. Unfortunately this will require me to duplicate work back to the Chromely controllers.

It depends. An option is to turn the controllers to api controller and use httpclient from Chromely controllers. Others have also used external scheme handlers - [Default handler](https://github.com/chromelyapps/Chromely/blob/master/src/Chromely/Browser/Handlers/DefaultExternalRequestSchemeHandler.cs) - looking through issues may help. The [web-chromely demos](https://github.com/chromelyapps/demo-projects/tree/master/web-chromely) may help too.
