### ISSUE TITLE
Customized browser host issues

### ISSUE THREAD

**Issue by smx-smx** [chromelyapps/Chromely#248]
Hello and thank you for this project

I'm working on creating a customized browser host to provide custom IPC handlers, schema handlers and process handlers

I stumbled about these code-related problems:
- The Window class needs to provide a virtual `CreateBrowser` method so that i can supply my own `CefGlueBrowser`-derived object (currently it happens in the constructor and i can't skip it)
https://github.com/chromelyapps/Chromely/blob/a6881d738b6e43ec22aad83df8d90fae6539dfe8/src_5.0/Chromely/Windows/Window.cs#L34
- While we are at it, the `Window` class name is a bit ambiguos, as it also creates the browser host
- `HostBase` doesn't allow to provide a custom `CefGlueApp`-derived object
https://github.com/chromelyapps/Chromely/blob/a6881d738b6e43ec22aad83df8d90fae6539dfe8/src_5.0/Chromely.CefGlue/BrowserWindow/HostBase.cs#L227
- `HostBase` could provide hooks to opt-out features that aren't required: https://github.com/chromelyapps/Chromely/blob/a6881d738b6e43ec22aad83df8d90fae6539dfe8/src_5.0/Chromely.CefGlue/BrowserWindow/HostBase.cs#L245-L250
- `CefGlueBrowser.Create` needs to be virtual, so i can supply my custom `CefClient`-derived object instead of the default
https://github.com/chromelyapps/Chromely/blob/a6881d738b6e43ec22aad83df8d90fae6539dfe8/src_5.0/Chromely.CefGlue/Browser/CefGlueBrowser.cs#L154

**Comment by mattkol** [comment]
@smx-smx 
> Hello and thank you for this project

Thank you.

What has been done satisfies most commonly used scenarios. Customizations and extension are encouraged via custom handlers, inheritance and other patterns. Sure, nothing here is written in stone, but we need to weigh benefits of changes (pros and cons). 

It should be fine making these changes. I do not see it breaking anything.

I have made some changes based on the [link](https://github.com/uxmal/reko-chromely/tree/native-hosts/src/BrowserHost/ChromelyExtensions) you provided, I am not sure I captured everything. If this is not correct, I will advise you create a PR. If you do for 5.0 I will find time between now and the weekend to apply to 5.1.

Note that 5.0 is not on C#8 (5.1 is) , so there will be issues with https://github.com/uxmal/reko-chromely/blob/34780c3f80d1709c1eda95ae590b16187d0ef068/src/BrowserHost/ChromelyExtensions/ActionTask.cs#L36

> - `HostBase` could provide hooks to opt-out features that aren't required: https://github.com/chromelyapps/Chromely/blob/a6881d738b6e43ec22aad83df8d90fae6539dfe8/src_5.0/Chromely.CefGlue/BrowserWindow/HostBase.cs#L245-L250

If the handlers/features are not registered those method calls should be pass thru, I think.
 
Also note that some of the points you raised may have been addressed in 5.1.

Thanks.

**Comment by smx-smx** [comment]
Thank you for the changes, @mattkol.
To be honest, i didn't know there were 2 different versions of the project (5.0 and 5.1)
I discovered it yesterday, and i'm in the process of migrating the codebase over it

I'll let you know if i find some issue with that

**Comment by mattkol** [comment]
@smx-smx 5.0 will still be valid for a while, so I expect we will still fix bugs for sometime on 5.0. But of course major changes will be on 5.1 going forward. If you have done considerable work on 5.0 that should not be discarded. We can apply the changes to both.

Thanks.
