### ISSUE TITLE
Support for using Razor Class Library in Blazor Appllication 

### ISSUE THREAD

**Issue by techierathore** [chromelyapps/Chromely#251]
Don't know whether this issue should be raised here or in Demo Repo. 

**Current Blazor samples uses the UI and static content from sample project**, whereas when we architect or develop Blazor applications **we mainly keep the UI in a separate Razor Class library project** so that it can be utilized in different project heads (like WASM , PWA )  When I tried to do that in Chromely it was not able to use the static resources like css and js files can you please suggest a solution for this.

You can see the demo implementation here : https://github.com/techierathore/TrBlazorEx

**Comment by mattkol** [comment]
@techierathore 

You need to register the assembly as embedded resource - https://github.com/chromelyapps/Chromely/blob/master/Documents/registering_resource_handlers.md

````c#
var config = DefaultConfiguration.CreateForRuntimePlatform();
var assemblyOptions = new AssemblyOptions("embeddedAssemblyName.dll", null, "app");
config.UrlSchemes.Add(new UrlScheme(DefaultSchemeName.ASSEMBLYRESOURCE, "assembly", "app", string.Empty,   UrlSchemeType.AssemblyResource, false, assemblyOptions));

````
An embeddable sample project - https://github.com/chromelyapps/demo-projects/tree/master/v_5.0/regular-chromely/Chromely.External.Controllers
https://github.com/chromelyapps/demo-projects/blob/53ccbdd22eac818ebf96df594f6fc81369965772/v_5.0/regular-chromely/Chromely.External.Controllers/Chromely.External.Controllers.csproj#L18

See these issues where it was discussed, 
https://github.com/chromelyapps/Chromely/issues/147
https://github.com/chromelyapps/Chromely/issues/207

**Comment by techierathore** [comment]
Thanks @mattkol for quick response, my apologies that I missed it. Is there any way we can have a discussion about Chromely and would love to contribute in a anyway I can. Is there any IM channels for discussion like gitter/discord/slack etc.

**Comment by mattkol** [comment]
@techierathore sure, there is [gitter](https://gitter.im/chromely_/Lobby?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge).

Also I am hoping to expand on some series of Howtos - https://github.com/chromelyapps/Chromely/search?q=Howto&type=issues

If this works for you it will be appreciated if you contribute by creating an issue. It is just going to be simple skeletal way to embed resources. Just highlighting the relevant code and have an attachment. I noticed that this is most helpful in answering developers questions.

Thanks.

**Comment by techierathore** [comment]
Thanks @mattkol , I have joinned the gitter lobby and has asked a few queries related to executing the samples on Mac as I am facing issue in that. Let me know if you want me to create an issue for those. Once my sample application works correectly then I am planning to create video/blog series about using How to build cross platform desktop app with Blazor and Chromely.  

Thanks
