### ISSUE TITLE
RequestAction do not work and RegisterRequest works well

### ISSUE THREAD

**Issue by xjfnet** [chromelyapps/Chromely#252]
chromely.cefsharp.5.1.83-pre02
RequestAction do not work and RegisterRequest works well

**Comment by mattkol** [comment]
@xjfnet I think you need to provide more info.

[CefSharpDemo.zip](https://github.com/chromelyapps/Chromely/files/5432889/CefSharpDemo.zip)

````c#
namespace CefSharpDemo
{
    class Program
    {
        [STAThread]
        static void Main(string[] args)
        {

            AppBuilder
            .Create()
            .UseApp<DemoApp>()
            .Build()
            .Run(args);
        }
    }

    public class DemoApp : ChromelyBasicApp
    {
        public override void ConfigureServices(ServiceCollection services)
        {
            base.ConfigureServices(services);
            RegisterControllerAssembly(services, typeof(DemoApp).Assembly);
        }
    }

    [ControllerProperty(Name = "DemoController")]
    public class DemoController : ChromelyController
    {
        [RequestAction(RouteKey = "/democontroller/hello")]
        public IChromelyResponse Hello(IChromelyRequest request)
        {
            return new ChromelyResponse(request.Id)
            {
                Data = "Hello Chromely"
            };
        }
    }
}
````

![image](https://user-images.githubusercontent.com/18384207/97082127-58fb1780-15d5-11eb-9d6a-5f19b047fd90.png)

**Comment by xjfnet** [comment]
change ChromelyBasicApp to ChromelyFramelessApp and try again!

**Comment by mattkol** [comment]
Changing to ChromelyFramelessApp works.

[CefSharpDemo_with_ChromelyFrameLassApp.zip](https://github.com/chromelyapps/Chromely/files/5432939/CefSharpDemo_with_ChromelyFrameLassApp.zip)

**Comment by xjfnet** [comment]
maybe it's my mistake
it works now, and i don't know what happend
i use JetBrains Rider to build my program, anyway it works
thanks.
