### ISSUE TITLE
defunct child process with ChromelyApp on linux

### ISSUE THREAD

**Issue by jirinalepa** [chromelyapps/Chromely#253]
Can be reproduced on CrossPlatDemo Project.
Started processes ends correctly, until Chromely starts.

Just insert this code to Program.cs before AppBuilder.....Run().

<pre>
var tokenSource = new CancellationTokenSource();
var task = Task.Run(async () =>
{
	var cmd = new string[] { "ls", "-l" };
	while (!tokenSource.Token.IsCancellationRequested)
	{
		try
		{
			cmd.RunShell();
		}
		catch (Exception ex)
		{
			Console.WriteLine(ex);
		}
		await Task.Delay(1000);
	}
});
</pre>
And `RunShell()` is defined as:
<pre>
public static string RunShell(this IEnumerable<string> cmdAndArgs, int timeout = 5000)
{
	var result = string.Empty;
	var cmd = cmdAndArgs.FirstOrDefault();

	if (string.IsNullOrWhiteSpace(cmd))
		return string.Empty;

	using (var process = new Process())
	{
		process.EnableRaisingEvents = true;
		process.StartInfo = new ProcessStartInfo
		{
			FileName = cmd,
			RedirectStandardOutput = true,
			UseShellExecute = false
		};
		foreach (var arg in cmdAndArgs.Skip(1))
			process.StartInfo.ArgumentList.Add(arg);
		process.Start();

		result = process.StandardOutput.ReadToEnd();
		if (timeout > 0)
		{
			if (!process.WaitForExit(timeout))
				Console.WriteLine($"ERR: '{string.Join(' ', cmdAndArgs)}' process doesn't exited.");
			else
				Console.WriteLine($"OKK: '{string.Join(' ', cmdAndArgs)}' exited properly.");
		}
		else
		{
			process.WaitForExit();
		}
		process.Kill(true);
	}

	return result;
}
</pre>

**Comment by mattkol** [comment]
@jirinalepa this is not directly related to Chromely. CEF is a multi-process, so what you are trying to do may be impacted by that. What we have done with mvc and single instance may be helpful:
[web-chromely-mvc](https://github.com/chromelyapps/demo-projects/blob/master/web-chromely/web-chromely-mvc/Program.cs)
[Single Instance](https://github.com/chromelyapps/Chromely/issues/213#issuecomment-646977459)

**Comment by jirinalepa** [comment]
Thanks for the directions. Although it did not completely solve the problem, at least it inspired me to find a workaround.
