### ISSUE TITLE
CEF runtime download fails with a 403

### ISSUE THREAD

**Issue by cheeplusplus** [chromelyapps/Chromely#257]
Looks like #99 has reappeared, I get a 403 when trying to run a published build of my application.

It looks like they moved stuff again, when I go to http://opensource.spotify.com/cefbuilds/index.html it says they're moving to https://cef-builds.spotifycdn.com

**Comment by mattkol** [comment]
@cheeplusplus we should have made that configurable.
You can get latest nuget Chromely v5.8.3.1 or you [download manually](https://github.com/chromelyapps/Chromely/blob/master/Documents/cef_binaries_download.md).
Thanks for pointing that out.

**Comment by amaitland** [comment]
I'd suggest switching to `JSON` and using https://cef-builds.spotifycdn.com/index.json instead of using `Regex` to parse the `html`. You can then simply match the `cef_version` property e.g. `91.1.22+gc67b5dd+chromium-91.0.4472.124`
