### ISSUE TITLE
Do chromely provide any Api to run shell commands?

### ISSUE THREAD

**Issue by hexdump2002** [chromelyapps/Chromely#258]
Hi,

This is key for my project because I'm building a frontend for a shell tool we have. I know in electron there's an API to accomplish this but I haven't seen anything in Chromely. Is it possible?

Cheers!

**Comment by mattkol** [comment]
@hexdump2002 no, there is no formal API for that.
If you intend to run on C# end, I am sure Process class will do

See usages here
https://github.com/chromelyapps/Chromely/blob/6cd69850f7ea5bdfc665f9e6fa78beceb874cc3f/src/Chromely/BrowserLauncher.cs#L27

https://github.com/chromelyapps/Chromely/blob/6cd69850f7ea5bdfc665f9e6fa78beceb874cc3f/src/Chromely/UnixBashCmd.cs#L14

For JavaScript, I am sure there will be many options out there.
