### ISSUE TITLE
ChromelyEventedApp missing in 5.1

### ISSUE THREAD

**Issue by MichelJansson** [chromelyapps/Chromely#259]
First - thanks for this project!

I just updated to 5.1 and it seems to have some breaking changes.
I've used `ChromelyEventedApp` to override some events. This class is now gone, is there any upgrade paths to take?

Did have a look at #225 but could not find anything there. Thanks

**Comment by MichelJansson** [comment]
So I eventually figured out that the events of `ChromelyEventedApp` is now accessible/customizable by creating a custom window class inheriting from `Chromely.Window`, and then regisitering it in the builder with `.UseWindow<MyWindow>()`.

Full code in the demo-projects:
[DemoWindow.cs](https://github.com/chromelyapps/demo-projects/blob/6482de0412/regular-chromely/CrossPlatDemo/DemoWindow.cs)
[Program.cs (.UseWindow)](https://github.com/chromelyapps/demo-projects/blob/6482de041298eb5afbfb521a8198b2c1e3daf8bb/regular-chromely/CrossPlatDemo/Program.cs#L30)

---

Although I now got the event I'm looking for (`BeforeClose`) - what I actually used the event for no longer works here though, namely accessing the CefCookieManager, which now returns null... Ideas?

```c#
private void MyWindow_BeforeClose(object sender, BeforeCloseEventArgs e)
{
    // Flush cache
    // This is needed since there is some delay from when a cookie
    // has been set/deleted before it is actually persisted to disk.
    // This ensures all cookies is written to disk before exit.
    var cookieManager = CefCookieManager.GetGlobal(null);
    cookieManager.FlushStore(null);
}
```

**Comment by mattkol** [comment]
@MichelJansson 

If this was working before, then it must be because it was a hack and was fixed -
https://github.com/chromelyapps/Chromely/commit/fcb6e8eb1670e6788d521ef3bb80dbf4027b1078   

But having said that I think we should be able to do stuff before actually closing/disposing CEF. The events handler need to move to the Window class itself rather than the Browser. Good catch! 👍 

Meanwhile I think you can do this:

````c#
public class DemoWindow : Window
{
        public DemoWindow(IChromelyNativeHost nativeHost,
                      IChromelyConfiguration config,
                      ChromelyHandlersResolver handlersResolver)
            : base(nativeHost, config, handlersResolver)
        {
            nativeHost.HostClose += NativeHost_HostClose;

        }

        private void NativeHost_HostClose(object sender, CloseEventArgs e)
        {
            // Flush cache
            // This is needed since there is some delay from when a cookie
            // has been set/deleted before it is actually persisted to disk.
            // This ensures all cookies is written to disk before exit.
            var cookieManager = CefCookieManager.GetGlobal(null);
            cookieManager.FlushStore(null);
        }
}
````

**Comment by MichelJansson** [comment]
@mattkol, that works!

I agree that it's probably a good idea to allow that. On the other hand, why I require it here is not that I particularly _want to_, more that I just have to, to workaround the issue with cookies not being saved. So if that was handled somewhere else....

But that's for an other day! Closing this now - thanks for your prompt and accurate support!

**Comment by mattkol** [comment]
@MichelJansson definitely, not a showstopper, but  it is still an issue and needs to be fixed.
Easy to forget if closed, reopening.
Thanks.

**Comment by mattkol** [comment]
@MichelJansson after looking at this closely, the code is doing the right thing. CefShutdown actually triggers the BeforeClose event, so the right place to do what you are doing is NativeHost HostClose event. Which is what you have now.
Thanks.
