### ISSUE TITLE
[Chromely.Interop.User32] Keystroke / KeyPress

### ISSUE THREAD

**Issue by nurbat** [chromelyapps/Chromely#260]
привет, я увидел в вашем последнем обновлении что вы используете хук клавиш. Вы можете получать нажатие клавиш любой операционной системы, можно ли получить нажатие клавиш в любой операционной системе без фокуса приложения? Если можно, не могли бы сделать или добавить в wiki инструкцию как можно все это сделать.

hi, I saw in your last update that you use a keyboard hook. You can get keystrokes from any operating system, can I get keystrokes from any operating system without app focus? If possible, could you make or add to the wiki instructions on how to do all this?

[Chromely.Interop.User32] src/Chromely/NativeHosts/WinHost/WinBase/DefaulKeyboadHookHandler.cs 
https://github.com/chromelyapps/Chromely/commit/b383c3f6e165895f8a216e50ba551a6e26c0a65a

__
Очень хочется видеть данную функцию что бы можно было получать нажатие клавиш как в фокусе так и вне фокуса на любой операционной системе.

I really want to see this function so that you can get keystrokes both in focus and out of focus on any operating system.

**Comment by mattkol** [comment]
@nurbat 

> hi, I saw in your last update that you use a keyboard hook. You can get keystrokes from any operating system, can I get keystrokes from any operating system without app focus? If possible, could you make or add to the wiki instructions on how to do all this?

Use of OS keyboard keystrokes is not within scope of this project. The addition of keyboard hooks is for backward compatibility of [Kiosk function contributed earlier](https://github.com/chromelyapps/Chromely/commit/c86ca10511015916958685fafaf254b236a2effb) and allow extensibility.
