### ISSUE TITLE
Migration guide to v5.1

### ISSUE THREAD

**Issue by xplicit** [chromelyapps/Chromely#261]
Trying to update Chromely to the latest version and have found huge amount of breaking changes. Is there a guide how to migrate to the latest version of chromely?

For example not full list of breaking changes:

```
CommandAttritute(Route="") => CommandActionAttribute(RouteKey="")
HttpGetAttribute(Route="") => RequestAttribute(RouteKey="")
plus change params for RequestAction:
ChromelyRequest -> IChromelyRequest
ChromelyResponse -> IChromelyResponse

CefLifespanHandler -> DefaultLifespanHandler

FramelessWinAPIHost -> ChromelyWinFramelessHost. 
Now it Becomes internal and we cannot override WndProc and other methods. 
How to override methods of ChromelyWinFrameless host? 
UPD: Fixed in the latest commits

AppBuilder.UseContainer<> is missing 
(how to get access to container before running app, to add some required sevices?)
UPD: Fixed in the latest commits, new method is AppBuilder.UseServices(ServiceCollection services)

RegisterEventHandler(container, CefEventKey.ConsoleMessage, new ChromelyEventHandler<ConsoleMessageEventArgs>(CefEventKey.ConsoleMessage, OnConsoleMessage));  =>  ????

IChromelySchemeHandlerFactory => ???
IChromelyCustomHandler => ???

ExternalRequestSchemeHandlerFactory => DefaultExternalRequestSchemeHandlerFactory

IChromelyNativeHost.Close -> IChromelyNativeHost.HostClose
```

I am going to update the list during fixing incompatibilities issues...

**Comment by mattkol** [comment]
@xplicit 

> FramelessWinAPIHost -> ChromelyWinFramelessHost. 
Now it Becomes internal and we cannot override WndProc and other methods. 
How to override methods of ChromelyWinFrameless host?

This must have been overlooked it should be public as [ChromelyWinHost](https://github.com/chromelyapps/Chromely/blob/master/src/Chromely/NativeHosts/WinHost/ChromelyWinHost.cs).

**Comment by mattkol** [comment]
> Trying to update Chromely to the latest version and have found huge amount of breaking changes. Is there a guide how to migrate to the latest version of chromely?

No official guide, but there should be enough info:
[Upgrade to v5.1 - Changes to DI, Logger; CefSharp, .NET 5 Support](https://github.com/chromelyapps/Chromely/issues/225)
[Documentation](https://github.com/chromelyapps/Chromely/tree/master/Documents)
[Demos](https://github.com/chromelyapps/demo-projects/tree/master/regular-chromely).

**Comment by xplicit** [comment]
Thanks for making classes public. What about returning back analogue of `AppBuilder.UseContainer<>`? Something like `AppBuilder.UserServices(ServiceColelction services)` So we could use our own services instead on empty service collection which is created at this line

https://github.com/chromelyapps/Chromely/blob/master/src/Chromely.Core/AppBuilder.cs#L96

**Comment by mattkol** [comment]
> What about returning back analogue of AppBuilder.UseContainer<>? Something like AppBuilder.UseServices(ServiceColelction services) So we could use our own services instead on empty service collection which is created at this line

Sure, good idea 👍

**Comment by xplicit** [comment]
Thank you! I was able to migrate to v5.1, solution is compiling now and I was able to see our React application inside of Chromely. Have a some issues with FramelessWindow, I'll look more deeper and post an another issue if it's related to changes in Chromely.
