### ISSUE TITLE
Closing Frameless Window causes crash

### ISSUE THREAD

**Issue by donotcodeit** [chromelyapps/Chromely#265]
There's minimum reproduceable app:
https://github.com/donotcodeit/ChromelyMin51/tree/repro/error-on-close

Steps to reproduce:
* Launch app in Debug mode (e.g. F5 in VS Code)
* Press Close button

Exception is a little transient, probably because it happens inside of `Task.Run`, but I was able to reproduce it every 2 out of 3 times.

I didn't tested it in any mode but Frameless. Exception will be thrown in `NativeHostBase`, so it is probably not related only to Frameless.

**Comment by donotcodeit** [comment]
I also can confirm that process will not be killed when exception happens:
![image](https://user-images.githubusercontent.com/30778436/100701932-3679cc80-33d3-11eb-9cc1-578c63eebb26.png)

**Comment by mattkol** [comment]
@donotcodeit 
Please is this still happening?

**Comment by donotcodeit** [comment]
@mattkol i've just tested it - yes, it is still happening.

**Comment by donotcodeit** [comment]
Exception happening in a `NativeHostBase.cs`. Do we really need to kill UI process after exiting out of message loop?
![image](https://user-images.githubusercontent.com/30778436/101741405-96235680-3afc-11eb-97fa-b01a8ddd5b87.png)

**Comment by mattkol** [comment]
@donotcodeit looks like it was fixing an issue that was reported.
I really do not think it is needed, but not a bad safeguard. I removed from the background thread and also checked to ensure that the process id is valid. I am sure 99.9% of the time that will not be called.

**Comment by donotcodeit** [comment]
@mattkol I've tested - it's OK now. Thanks!
