### ISSUE TITLE
Chromely opens multiple windows of the main processes

### ISSUE THREAD

**Issue by vadd98** [chromelyapps/Chromely#268]
I'm developing a desktop app using WinUI and I'm trying to implement Chromely as a Class Library instead of a Console/Window Application as in the Demos. I can successfully run the Chromely WebView, but as soon as it starts it opens other 4 new windows of the main process that has called Chromely (so 4 windows of my original app) along the one of the Chromely browser (which remains frozen and doesn't load any page). I can't find out why it has such behaviour. 
Any suggestions?

**Comment by mattkol** [comment]
@vadd98 

CEF is multi-process, and you will require sub-processes to fix that. Chromely depends on CefGlue and CefGlue does not implement sub-process, we used to support sub-process but not anymore. 

I will suggest 2 options
- Create a [sub-process](https://github.com/chromelyapps/Chromely.Legacy/tree/master/src/Subprocesses) and assign it.
````
 config.CustomSettings[CefSettingKeys.BROWSERSUBPROCESSPATH] = "path to subprocess";
````

- Use [Chromely CefSharp](https://github.com/chromelyapps/CefSharp) - CefSharp implements subprocess.

**Comment by vadd98** [comment]
Thanks for your answer. I have one question: Chromely CefSharp supports cross-platform development or does it work just for Windows? I was using the CefGlue based version exactly for this reason because I'm developing an app that will run on both Windows and Mac

**Comment by mattkol** [comment]
Chromely CefSharp is only supported on Windows .

**Comment by vadd98** [comment]
So I think I am forced to stay on Ceflgue. May you give me some hint about the subprocess, please?
I don't understand if it is enough to build the subprocess project from the legacy repo you linked (paying attention to the different versions of the chromely.core between my main project and the subprocess one) and put the build in the BROWSERSUBPROCESSPATH or if I have to do something more

**Comment by mattkol** [comment]
On sub-process, I personnaly won't be of much help beyond on Windows. I only tried it once on Windows in the legacy code. Then CEF changed Networking Service processes and that broke. When we moved to v5.0 we decided to go leaner and that was [discontinued](https://github.com/chromelyapps/Chromely/wiki/Migration-to-.NET-Core-3-and-MacOS-Support).

If you are comfortable with development on all platforms, then maybe creating sub-processes will be a way to go - between CefSharp and CEF itself you can get enough info to complete the dev. Developers have tried working around this successfully without sub-processes, though.

Work around without sub-process will be my preferred approach:
- Starting Chromely on its own process within your application as a child process.
- Incorporate it in your project like what was done in https://github.com/chromelyapps/demo-projects/tree/master/web-chromely

If you check closely..    **CreateWebHostBuilder**  is only called when the process is of type Browser.. so **CreateWebHostBuilder** will be equivalent to your main app entry function.

https://github.com/chromelyapps/demo-projects/blob/0ed0bf5a82ec196a9211ccacef85560aecfd11af/web-chromely/web-chromely-mvc/Program.cs#L32
https://github.com/chromelyapps/demo-projects/blob/0ed0bf5a82ec196a9211ccacef85560aecfd11af/web-chromely/web-chromely-bootstrap4/Program.cs#L38
- Adopt the single instance approach - https://github.com/chromelyapps/Chromely/issues/213#issuecomment-646890455
This approach is not that different from #2, it is just easier to comprehend if one is not familiar with ASP.NET CORE.

Related, I can remember are:
https://github.com/chromelyapps/Chromely/issues/213
https://github.com/chromelyapps/Chromely/issues/128
https://github.com/chromelyapps/Chromely/issues/165
https://github.com/chromelyapps/Chromely/issues/166
