### ISSUE TITLE
Feature Request: Provide a way of getting/setting the browser zoom level

### ISSUE THREAD

**Issue by wwarby** [chromelyapps/Chromely#270]
I believe the CEF project exposes APIs to get and set the browser's zoom level and I see a couple of references to zoom levels in the Chromely codebase, but no usable API to set it. It'd be really useful for the project I'm working on to be able call an API to change the zoom level and read the current zoom level.

**Comment by mattkol** [comment]
@wwarby sure that can be done. Holiday season... will see this weekend.

**Comment by wwarby** [comment]
Sweet - no rush obviously 👍

**Comment by mattkol** [comment]
@wwarby you can also actually do this without the fix.

[SetZoomtDemo.zip](https://github.com/chromelyapps/Chromely/files/5762289/SetZoomtDemo.zip)

````c#

    class Program
    {
        [STAThread]
        static void Main(string[] args)
        {
            AppBuilder
            .Create()
            .UseWindow<DemoWindow>()
            .UseApp<DemoApp>()
            .Build()
            .Run(args);
        }
    }

    public class DemoApp : ChromelyBasicApp
    {
    }

    public class DemoWindow : Window
    {
        public DemoWindow(IChromelyNativeHost nativeHost,
                      IChromelyConfiguration config,
                      ChromelyHandlersResolver handlersResolver)
            : base(nativeHost, config, handlersResolver)
        {
            FrameLoadStart += DemoWindow_FrameLoadStart;
        }

        public CefBrowserHost BrowserHost
        {
            get
            {
                return Browser?.GetHost();
            }
        }

        public double GetZoomLevel()
        {
           return BrowserHost == null ? 0 : BrowserHost.GetZoomLevel();
        }

        public void SetZoomLevel(double value)
        {
            BrowserHost?.SetZoomLevel(value);
        }

        private void DemoWindow_FrameLoadStart(object sender, FrameLoadStartEventArgs e)
        {
            SetZoomLevel(26.0);
        }
    }

````

Before zoom:

![image](https://user-images.githubusercontent.com/18384207/103488762-8cc89980-4ddd-11eb-9be4-c24eda2b952c.png)

After zoom:
![image](https://user-images.githubusercontent.com/18384207/103488775-a36ef080-4ddd-11eb-9cc9-688024b2aeca.png)

**Comment by wwarby** [comment]
Thanks so much for this - I can confirm it works like an absolute charm. I have a slider in my app that changes the page zoom level and up until now I'd been using the CSS `zoom` property with a CSS variable, which _kind of_ works but causes all sorts of issues with third party components like the ones from Angular Material. Setting the zoom level at the browser level completely resolves all those issue :)
