### ISSUE TITLE
Source map loading fails in demo apps

### ISSUE THREAD

**Issue by wwarby** [chromelyapps/Chromely#272]
Apologies for raising multiple issues in quick succession. I'm building an Angular app with Chromely and I've noticed that source maps for my TypeScript code are not available in the debugging tools for the apps. When I investigated I found that the same thing occurs in the out-of-the-box demo app:

![image](https://user-images.githubusercontent.com/6769065/103271587-90f65080-49b2-11eb-880a-466b15177736.png)

I tried building a custom scheme handler using the `http` scheme to directly address the `ERR_UNKNOWN_URL_SCHEME` error but it just moves the problem elsewhere (`ERR_NAME_NOT_RESOLVED`):

![image](https://user-images.githubusercontent.com/6769065/103280824-446a3f80-49c9-11eb-894f-6fffe9601435.png)

My hunch is that the reason is the developer tools are making the request for the source map and the developer tools are running in a different process than the Chromely browser instance itself, and only the browser process knows how to resolve the custom request handlers that have been configured. I found a recent forum thread for CEF that seems to be related: https://magpcss.org/ceforum/viewtopic.php?f=6&t=17910

Any idea if this can be worked around? My understanding of the internals of CEF is too limited for me to get much further with this. If source maps can't be made to work it isn't the end of the world, just makes debugging a little more cumbersome that it otherwise might be.

**Comment by mattkol** [comment]
We tried to track it here earlier - https://github.com/chromelyapps/demo-projects/issues/28
But from what I see from https://magpcss.org/ceforum/viewtopic.php?f=6&t=17910, it seems it may be CEF related.

With the custom resource scheme handler you created, do the files get here:
https://github.com/chromelyapps/Chromely/blob/09885aef7d98520be3a466b901331defe3193105/src/Chromely/Browser/Handlers/DefaultResourceSchemeHandler.cs#L42

If the files get there, then we can see if we can control what happens from there, if it does not get there, then we may have to rely on a fix from CEF.

**Comment by wwarby** [comment]
Ah apologies - I did search around but didn't land on the issue you linked above. Yeah, the request doesn't get as far as the line you referenced above, so I think it's probably as you say and issue at the CEF level. I didn't know how the scheme handlers created in Chomely map into CEF itself so wasn't sure if there was a way around it but I guess not. Oh well - thanks anyway. I'll close this ticket as there's nothing much that can be done about it within this project 👍
