### ISSUE TITLE
QN: How to hide console for Blazor Server APP

### ISSUE THREAD

**Issue by VarunSaiTeja** [chromelyapps/Chromely#277]
I downloaded your BlazorServerAppDemo.
When I ran it a console is also opening in the background.
How can I prevent it?
I changed application type to Windows from Console. But it does not work.

**Comment by mattkol** [comment]
@VarunSaiTeja I think you need to verify first what triggers the console - The Web Server App or Chromely desktop app. The way it is done, Chromely is more or less a child process - so I doubt you can solely control that.

If it is what I think it is, you may need to look at how console is suppressed in a normal ASP.NET Core app.

These may also help:
https://github.com/chromelyapps/Chromely.Legacy/wiki/Getting-Started-CefGlue-Winapi-(.NET-Core)#how-to-hide-net-core-console
https://docs.microsoft.com/en-us/cpp/build/reference/editbin-reference?view=msvc-160

**Comment by VarunSaiTeja** [comment]
The normal Web Server app not showing console. When I copied Program.cs and ServerAppUtil.cs from the demo. I am seeing console
