### ISSUE TITLE
Prevent window navigation on mouse4/mouse5 clicks

### ISSUE THREAD

**Issue by nicolasdeory** [chromelyapps/Chromely#278]
I'd like to prevent the window from navigating forward/backwards when the user clicks the mouse4 or mouse5 buttons. Likewise, when debug mode is enabled, I'd like to prevent the context menu from being shown when the user right clicks.

Normally I wouldn't have control over these events since browsers handle those events before they're even passed to the Javascript execution environment, but I was wondering if there was any way to control this behavior in Chromely.

I've tried the following with JQuery, without success:
```javascript
$(document).on('click contextmenu', (e) => {
        e.preventDefault();
        e.stopImmediatePropagation();
    });
```

**Comment by mattkol** [comment]
@nicolasdeory 
>I'd like to prevent the window from navigating forward/backwards when the user clicks the mouse4 or mouse5 buttons. 

You will need to capture the keyboard entry and prevent that. It may be possible in JavaScript .. you can also register a custom keyboard handler.

````c#
  public class CusomChromelyApp : ChromelyBasicApp
    {
          public override void ConfigureServices(IServiceCollection services)
        {
            base.ConfigureServices(services);
            services.AddSingleton<CefKeyboardHandler, CustomKeyboardHandler>();
        }
    }

    public class CustomKeyboardHandler : CefKeyboardHandler
    {
    }
````
[CefSharp Sample](https://github.com/cefsharp/CefSharp/blob/master/CefSharp.WinForms.Example/Handlers/KeyboardHandler.cs)

>Likewise, when debug mode is enabled, I'd like to prevent the context menu from being shown when the user right clicks.

You can disable debugging.

https://github.com/chromelyapps/Chromely/blob/edbf50b307b18ee330ad93fc8fe17c3f9f8e4751/src/Chromely/Browser/Handlers/DefaultContextMenuHandler.cs#L35

````c#
var config = DefaultConfiguration.CreateForRuntimePlatform();
 config.DebuggingMode = false;
````
Or register a custom context menu handler.
````c#
  public class CusomChromelyApp : ChromelyBasicApp
    {
          public override void ConfigureServices(IServiceCollection services)
        {
            base.ConfigureServices(services);
            services.AddSingleton<CefContextMenuHandler, CustomContextMenuHandler>();
        }
    }

    public class CustomContextMenuHandler : CefContextMenuHandler
    {
    }
````
More info - https://github.com/chromelyapps/Chromely/blob/master/Documents/registering_custom_handlers.md

**Comment by nicolasdeory** [comment]
> You will need to capture the keyboard entry and prevent that. It may be possible in JavaScript .. you can also register a custom keyboard handler.

Would the keyboard handler also work for mouse button presses? In Javascript they count as mouse clicks, not keyboard. 
It seems like there isn't a custom handler for mouse 4/5 buttons; neither `CefContextMenuHandler` or `CefKeyboardHandler` seem to handle those.

**Comment by mattkol** [comment]
> Would the keyboard handler also work for mouse button presses? In Javascript they count as mouse clicks, not keyboard.

You are right, I must have mis-read that. The keyboard handler is not for mouse handling.

There is a suggestion here - https://magpcss.org/ceforum/viewtopic.php?f=6&t=16936#p42657

**Comment by nicolasdeory** [comment]
In that case, is there any way to disable navigation history? My use case is a configuration page where the user can configure key/mouse bindings, so it's somewhat annoying that the page will navigate elsewhere whenever they press one of the side mouse buttons.

**Comment by mattkol** [comment]
I doubt that clearing history is supported by CEF yet -	https://magpcss.org/ceforum/viewtopic.php?f=6&t=11003

> My use case is a configuration page where the user can configure key/mouse bindings, so it's somewhat annoying that the page will navigate elsewhere whenever they press one of the side mouse

Is this an event that can be captured and then stop propagation?

I rarely do web development so, I am not familiar with what you are experiencing.

**Comment by nicolasdeory** [comment]
You can capture the event and stop propagation inside the website itself, but browser-level events such as navigation or right click are handled by CEF before they're even passed to javascript. So no, nothing can be done client-side.

A possible solution could be intercepting navigation events in Chromely (although I don't know if that's possible with static resource URLs), and either sending the same page or canceling the event. Somehow detecting that the client has clicked the back button.

**Comment by mattkol** [comment]
> A possible solution could be intercepting navigation events in Chromely (although I don't know if that's possible with static resource URLs), and either sending the same page or canceling the event. Somehow detecting that the client has clicked the back button.

Its is not a lot of code, you can put break points in a few places to see. Especially in the [handlers](https://github.com/chromelyapps/Chromely/tree/master/src/Chromely/Browser/Handlers).

I will start here:
https://github.com/chromelyapps/Chromely/blob/00571d633fe48888b085d98522e9a61eec17b6e3/src/Chromely/Browser/Handlers/DefaultRequestHandler.cs#L68

**Comment by mattkol** [comment]
These may be helpful:

https://magpcss.org/ceforum/viewtopic.php?f=6&t=15172
https://bitbucket.org/chromiumembedded/cef/wiki/JavaScriptIntegration.md#markdown-header-executejavascript

**Comment by nicolasdeory** [comment]
> https://magpcss.org/ceforum/apidocs/projects/(default)/CefRequestHandler.html#OnBeforeBrowse(CefRefPtr%3CCefBrowser%3E,CefRefPtr%3CCefFrame%3E,CefRefPtr%3CCefRequest%3E,NavType,bool)
OnBeforeBrowse
`public virtual bool OnBeforeBrowse( CefRefPtr< CefBrowser > browser, CefRefPtr< CefFrame > frame, CefRefPtr< CefRequest > request, CefRequestHandler::NavType navType, bool isRedirect );`
Called on the UI thread before browser navigation. Return true to cancel the navigation or false to allow the navigation to proceed.

> https://magpcss.org/ceforum/apidocs/projects/(default)/cef_handler_navtype_t.html
Field Summary
--
NAVTYPE_BACKFORWARD
NAVTYPE_FORMRESUBMITTED
NAVTYPE_FORMSUBMITTED
NAVTYPE_LINKCLICKED = 0
NAVTYPE_LINKDROPPED
NAVTYPE_OTHER
NAVTYPE_RELOAD

It seems like this would be perfect for my use case, but the method signature here https://github.com/chromelyapps/Chromely/blob/00571d633fe48888b085d98522e9a61eec17b6e3/src/Chromely/Browser/Handlers/DefaultRequestHandler.cs#L66
seems to be a bool instead of a `CefRequestHandler::NavType` enum. What is `userGesture` in the Chromely request handler?

**Comment by mattkol** [comment]
> What is userGesture in the Chromely request handler?

The method - OnBeforeBrowse - is an override method from CefGlue.

> The |user_gesture| value will be true if the browser
navigated via explicit user gesture (e.g. clicking a link) or false if it
navigated automatically (e.g. via the DomContentLoaded event).

https://github.com/chromelyapps/Chromely/blob/00571d633fe48888b085d98522e9a61eec17b6e3/src/Chromely/CefGlue/Classes.Handlers/CefRequestHandler.cs#L38

**Comment by nicolasdeory** [comment]
https://github.com/chromelyapps/Chromely/blob/00571d633fe48888b085d98522e9a61eec17b6e3/src/Chromely/CefGlue/Classes.Handlers/CefRequestHandler.cs#L15

The userGesture value is exposed as a `bool`, not an `int`. Would there be any way to access this without a custom Chromely build?

**Comment by mattkol** [comment]
I doubt there is a way to access the int value without a custom build.
CefGlue may have done it that way for a reason.

But you can create a new method to access it, should be easy to do, the source code is there. If it works for you we just keep it.

Making change in the file -https://github.com/chromelyapps/Chromely/blob/master/src/Chromely/CefGlue/Classes.Handlers/CefRequestHandler.cs

````c#
        private int on_before_browse(cef_request_handler_t* self, cef_browser_t* browser, cef_frame_t* frame, cef_request_t* request, int user_gesture, int is_redirect)
        {
            CheckSelf(self);

            var m_browser = CefBrowser.FromNative(browser);
            var m_frame = CefFrame.FromNative(frame);
            var m_request = CefRequest.FromNative(request);
           // var m_userGesture = user_gesture != 0;
            var m_isRedirect = is_redirect != 0;

            var result = OnBeforeBrowse(m_browser, m_frame, m_request, user_gesture, m_isRedirect);

            return result ? 1 : 0;
        }

        /// <summary>
        /// Called on the UI thread before browser navigation. Return true to cancel
        /// the navigation or false to allow the navigation to proceed. The |request|
        /// object cannot be modified in this callback.
        /// CefLoadHandler::OnLoadingStateChange will be called twice in all cases.
        /// If the navigation is allowed CefLoadHandler::OnLoadStart and
        /// CefLoadHandler::OnLoadEnd will be called. If the navigation is canceled
        /// CefLoadHandler::OnLoadError will be called with an |errorCode| value of
        /// ERR_ABORTED. The |user_gesture| value will be true if the browser
        /// navigated via explicit user gesture (e.g. clicking a link) or false if it
        /// navigated automatically (e.g. via the DomContentLoaded event).
        /// </summary>
        protected virtual bool OnBeforeBrowse(CefBrowser browser, CefFrame frame, CefRequest request, int userGesture, bool isRedirect)
        {
            return false;
        }

````

**Comment by nicolasdeory** [comment]
I'll give it a try as soon as I can.
