### ISSUE TITLE
About custom handles

### ISSUE THREAD

**Issue by Nuan-Yang** [chromelyapps/Chromely#280]
Hello, Author.
I love using Chromely and In the process of using it, I found some areas that I think can be optimized, and now I will discuss with you.
In Chromely Source, "ChromelyAppBase.cs" ConfigureDefaultHandlers(IServiceCollection services) function, I see a lot of CEF handles registered, I tried to register a custom CEF handle in my code "services.AddSingleton<CefRenderProcessHandler, JsObjectCefRenderProcessHandler>();", I found that I needed to inherit the IDeFaultCustomHandler interface, but IDeFaultCustomHandler (internal interface) I can't  inherit it. so I try rebuild chromely source IDeFaultCustomHandler(public interface), now it's working.
    internal class JsObjectCefRenderProcessHandler : DefaultRenderProcessHandler, IDefaultCustomHandler
    {
        public JsObjectCefRenderProcessHandler(IChromelyConfiguration config)
            : base(config)
        {

        }
        protected override void OnContextCreated(CefBrowser browser, CefFrame frame, CefV8Context context)
        {
            var global = context.GetGlobal();
            var extent = CefV8Value.CreateObject(null);
            global.SetValue("V8", extent, CefV8PropertyAttribute.None);
        }
    }

Can this interface be opened to users to customize the functions they want to achieve?

**Comment by mattkol** [comment]
@Nuan-Yang 
>  I found that I needed to inherit the IDeFaultCustomHandler interface, but IDeFaultCustomHandler (internal interface) I can't inherit it

Those were made internal intentionally.
Please read the wiki about creating custom handlers -
https://github.com/chromelyapps/Chromely/blob/master/Documents/registering_custom_handlers.md

You need something like this:
````c#
public class DemoApp : ChromelyBasicApp
    {
        public override void ConfigureServices(IServiceCollection services)
        {
            base.ConfigureServices(services);
            services.AddSingleton<CefRenderProcessHandler, CustomRenderProcessHandler>();
        }
    }

    public class CustomRenderProcessHandler : DefaultRenderProcessHandler
    {
        public CustomRenderProcessHandler(IChromelyConfiguration config) : base(config)
        {
        }
    }
````

**Comment by Nuan-Yang** [comment]
I've tried this. it doesn't working.
![image](https://user-images.githubusercontent.com/14990488/103968560-088c6280-519f-11eb-93c7-579572899280.png)
DefaultRenderProcessHandler, no inheritance interface above any one so not work

**Comment by Nuan-Yang** [comment]
``` 
   services.AddSingleton<CefRenderProcessHandler, JsObjectCefRenderProcessHandler>();


   internal class JsObjectCefRenderProcessHandler : DefaultRenderProcessHandler, IDefaultCustomHandler
    {
        public JsObjectCefRenderProcessHandler(IChromelyConfiguration config)
            : base(config)
        {

        }

        protected override void OnContextCreated(CefBrowser browser, CefFrame frame, CefV8Context context)
        {
            var global = context.GetGlobal();
            List<Type> types = new List<Type>();
            foreach (var assembly in AppDomain.CurrentDomain.GetAssemblies())
            {
                types.AddRange(assembly
                   .GetTypes()
                   .Where(c => c.CustomAttributes.FirstOrDefault(d => d.AttributeType == typeof(Dotnet2JavaScriptAttribute)) != null)
                   .ToList());

            }
            CefV8PropertyAttribute attributes = CefV8PropertyAttribute.ReadOnly;
            //反射创建对象
            foreach (var item in types)
            {

                var constructor = item.GetConstructors().First(c => c.GetParameters().Length == 0);
                object data = constructor.Invoke(new object[] { });
                var extent = CefV8Value.CreateObject(null);
                foreach (var method in data.GetType().GetMethods())
                {
                    extent.SetValue(method.Name, CefV8Value.CreateFunction(method.Name, new CefFunction(data, method)));
                }
                global.SetValue(item.Name, extent, attributes);
            }
        }
    }

-    internal interface IDefaultCustomHandler
-    {
-    }

+    public interface IDefaultCustomHandler
+   {
+    }
```

I modified the Chromely source code to work properly.

**Comment by Nuan-Yang** [comment]
Sorry, I noticed that the object has been attached to V8 but there is no breakpoint.
