### ISSUE TITLE
Howto: Set the host window hidden at first, then show it at frame load end

### ISSUE THREAD

**Issue by xjfnet** [chromelyapps/Chromely#282]
it need about 4 seconds to show the first page in my program with cef 86.0.21
it mean's that the host window will keep blank for about 4 seconds, then the first page shown.

so i want to hide the host window at startup, then show the host window at first frame load end;
but how to hide the host window at startup?

**Comment by xjfnet** [comment]
i try to use IWindowOptions.CustomStyle and found that
WindowCustomStyle.WindowStyles is int
WindowCustomStyle.WindowExStyles is int
but
Chromely.Interop.User32.WS is uint
Chromely.Interop.User32.WS_EX is uint
and some WS value can't cast to uint because of overflow

**Comment by mattkol** [comment]
@xjfnet 
> so i want to hide the host window at startup, then show the host window at first frame load end;

I will suggest an override of GetWindowStyles
https://github.com/chromelyapps/Chromely/blob/00571d633fe48888b085d98522e9a61eec17b6e3/src_5.0/Chromely/Native/WinAPI/WinAPIHost.cs#L368

https://github.com/chromelyapps/Chromely/blob/00571d633fe48888b085d98522e9a61eec17b6e3/src_5.0/Chromely/Native/WinAPI/WinNativeMethods.cs#L154

.. and in Frameloadend you show the window ..
````c#
   private void DemoWindow_FrameLoadEnd(object sender, FrameLoadEndEventArgs e)
    {
    }
````
https://github.com/chromelyapps/demo-projects/blob/5302b553770098fdc86ed38b53e080016e267602/regular-chromely/CrossPlatDemo/DemoWindow.cs#L52

**Comment by xjfnet** [comment]
it works, thanks!

```cs
public class CustomWinHost : ChromelyWinHost
    {
        public CustomWinHost(IWindowMessageInterceptor messageInterceptor, IKeyboadHookHandler keyboadHandler)
            : base(messageInterceptor, keyboadHandler)
        {
        }

        protected override WindowStylePlacement GetWindowStylePlacement(WindowState state)
        {
            var windowStylePlacement = base.GetWindowStylePlacement(state);
            windowStylePlacement.ShowCommand = Interop.User32.SW.Hide;
            return windowStylePlacement;
        }
    }

public class CustomWindow : Window
    {
        public CustomWindow(IChromelyNativeHost nativeHost, IChromelyConfiguration config, ChromelyHandlersResolver handlersResolver)
            : base(nativeHost, config, handlersResolver)
        {
            this.FrameLoadEnd += OnFrameLoadEnd;
        }

        private void OnFrameLoadEnd(object sender, FrameLoadEndEventArgs e)
        {
            Interop.User32.ShowWindow(this.Handle, Interop.User32.SW.NORMAL);
            this.FrameLoadEnd -= OnFrameLoadEnd;
        }
    }
```
