### ISSUE TITLE
Bring back RegisterDeleteRequestAsync, RegisterPostRequestAsync, ...

### ISSUE THREAD

**Issue by redplane** [chromelyapps/Chromely#284]
Previously with `Chromely` version `5.0.83`
I could use different kinds of `RegisterRequestAsync`, such as:

```
            RegisterGetRequestAsync("/connection/connected", GetIsConnectionConnectedAsync);
            RegisterGetRequestAsync("/connection/settings", GetConnectionSettingsAsync);
            RegisterGetRequestAsync("/connection/available-ports", GetAvailablePortsAsync);
            RegisterPostRequestAsync("/connection/connectivity", EstablishConnectionAsync);

            RegisterPostRequestAsync("/connection/disconnect", DisconnectConnectionAsync);

            RegisterPostRequestAsync("/connection", AddConnectionAsync);
            RegisterGetRequestAsync("/connection", GetConnectionsAsync);
            RegisterPutRequestAsync("/connection", EditConnectionAsync);
            RegisterDeleteRequestAsync("/connection", DeleteSerialPortAsync);

            RegisterPostRequestAsync("/connections/status", GetConnectionsStatusAsync);
```

I don't know why `RegisterGetRequestAsync` or `RegisterPostRequestAsync` are changed to `RegisterRequestAsync`.
From view of web developer, supporting GET/POST/... is very great feature, because there are some standards about HTTP Verb, such as:

- **GET** for items retrieval
- **POST** for item creation
- **PUT** for item modification.

Just like what **ASP.Net Core** is supporting.

I have no idea why `Chromely` is merging every `RegisterXXXRequestAsync` into `RegisterRequestAsync`.
I think it should be supported as previous version. Developer can separate their API End-point concern, both in **Controller** and Front-end services.

**Comment by mattkol** [comment]
@redplane 

> The use of API Restful methods like "Get", "Post" gives an impression that the Chromely Renderer process is an API. Few issues have been raised on this - use of the verbs will be discontinued as it confuses developers - it is not an API, those verbs were there to help re-use url paths. This will not be used anymore - simple, a url path will map to an action resource.

https://github.com/chromelyapps/Chromely/issues/225

I think should be easier to change to:

````c#
RegisterRequestAsync("/connection/connected/get", GetIsConnectionConnectedAsync);
RegisterRequestAsync("/connection/settings/get", GetConnectionSettingsAsync);
RegisterRequestAsync("/connection/available-ports/get", GetAvailablePortsAsync);
RegisterRequestAsync("/connection/connectivity/post", EstablishConnectionAsync);

RegisterRequestAsync("/connection/disconnect/post", DisconnectConnectionAsync);

RegisterRequestAsync("/connection/post", AddConnectionAsync);
RegisterRequestAsync("/connection/get", GetConnectionsAsync);
RegisterRequestAsync("/connection/put", EditConnectionAsync);
RegisterRequestAsync("/connection/delete", DeleteSerialPortAsync);
````

**Comment by redplane** [comment]
@mattkol , actually now I have to do the same thing above as a workaround.

> use of the verbs will be discontinued as it confuses developers

From a view of developer who doing both back-end & front-end.
I don't understand what can confuse developer when we use verb ?
The way we are developing desktop app is similar to what we are doing with a Web app.
Front-end and back-end, HTTP as a communication.
The way we are defining **Controller** is the same as what we do with **ASP.Net**
If we are following API design pattern, **VERB** plays a very important role in deciding the action.

Defining the `end-point` as `/get`, `/post`. It makes me remember about junior in university when they study web development at the first time :|

**Comment by mattkol** [comment]
@redplane 

**This is the exact misunderstanding the new approach is trying to address.**

The pattern adopted here seems Restful but it is not really, it is just a way to map a a path (**key**) to a resource (**value**). Sure, "**Controller**" is borrowed form ASP.NET, but  it does not make it an ASP.NET Core-like application or an API.  The name "**Controller**" could have been called anything.

So you can have **"/38CAADA0-947A-4D7D-B27A-B68E7548FC7D"** or **"/38CAADA0-947A-4D7D-B27A-B68E7548FC7D.com/save"** and they are all valid.

Sample:
````js
    var request = {
            "method": "",
            "url": "/38CAADA0-947A-4D7D-B27A-B68E7548FC7D",
            "parameters": null,
           "postData": null,
    };
````
````c#
    public class DemoController : ChromelyController
    {
        public DemoController()
        {
            RegisterRequest("/38CAADA0-947A-4D7D-B27A-B68E7548FC7D", JustAmethod);
        }

        private IChromelyResponse JustAmethod(IChromelyRequest request)
        {
		   return null
        }
    }
````
The only time a well-formed url is important is if you use XHR request and even at that only the route path is useful for Chromely.

````js
 function ajaxGetRun() {
    var http = new XMLHttpRequest();
    var url = "http://chromely.com/38CAADA0-947A-4D7D-B27A-B68E7548FC7D";
    http.open("GET", url, true);

    http.onreadystatechange = function () {
    }
    http.send();
 }
````

**Again this is not an ASP.NET Core framework, terms are borrowed because developers are familiar with them.**

**Comment by redplane** [comment]
IMO, I think the previous approach is good for developer when he/she starts using `Chromely`.
Most developer use `Hybrid app` are web developer.
And it does not make sense when we use HTTP calls from `Front-end` view but do not follow **API naming convention**
