### ISSUE TITLE
Chromely release to add CEF binaries version

### ISSUE THREAD

**Issue by mattkol** [chromelyapps/Chromely#286]
Chromely release should mention what version of Chromium it uses (providing download link is very good option)

**Comment by nurbat** [comment]
https://github.com/chromelyapps/Chromely/wiki/Custom-CEF-Binaries
Didn't you learn to read the documentation ?

**Comment by RobertBouillon** [comment]
What CEF Binaries do I need to install? I'd prefer for my users not to see the Chromely CEF popup - I'd rather package CEF as part of my installer.

**Comment by mattkol** [comment]
Please see - https://github.com/chromelyapps/Chromely/issues/296#issuecomment-778537766
To suppress the popup during download, you can do a silent one:
````C#
   var config = DefaultConfiguration.CreateForRuntimePlatform();
   config.CefDownloadOptions.DownloadSilently = true;
````
