### ISSUE TITLE
Overriding the default request handler to provide custom error handling

### ISSUE THREAD

**Issue by wwarby** [chromelyapps/Chromely#289]
I've noticed in my app that often times if I set something up incorrectly in my controllers (most often I just name something incorrectly so that the route I've requested doesn't exist), I generally get a 400 Bad request response in my UI, which my app is configured to treat differently from 404 and 500 responses. It also sends no detail about the error to the client, which is logical for default behaviour but in my case I actually want to send detailed error messages to the client so I decided I ought to replace the default scheme handler to gain control of the error handling defined [here](https://github.com/chromelyapps/Chromely/blob/3622bc432a8f48181d78ec7720816a7fe4fd0654/src/Chromely/Browser/Handlers/DefaultRequestSchemeHandler.cs#L153) (as an aside, "occurred" is spelled incorrectly on this line of code).

I'm struggling to figure out the least invasive way of replacing this default request handler from the wiki, partly because I think some of the wiki pages such as [this one](https://github.com/chromelyapps/Chromely/wiki/registering-custom-scheme-handlers) are describing obsolete ways of doing things. I've been going round in circles with this for a couple of hours now - any chance you could give me a quick steer in the right direction?

In terms of project feedback related to this issue, a feature that allowed the user to define some kind of custom global error handler (rather than dropping into the lower level of replacing scheme handlers) would be pretty sweet - just some way of defining a method that takes the exception as it's input and returns an `IChromelyResponse` as it's output. I'd also tentatively suggest that returning 400 Bad request in response to both "file not found" and runtime exception scenarios is probably not the ideal behaviour - it should probably return 404 and 500 responses respectively?

**Comment by mattkol** [comment]
@wwarby 

1. Registering the request scheme handler 
Yes, that wiki page is for v5.0 - that needs to be cleaned up. The most current is found in [Documents](https://github.com/chromelyapps/Chromely/tree/master/Documents) and the page you need is [Registering Custom Scheme Handlers](https://github.com/chromelyapps/Chromely/blob/master/Documents/registering_scheme_handlers.md). **This is a tricky one, note that it is the handler factory that is registered, not the handler**.

2. Global error handler - not a bad idea. Any ideas what you have in mind? 

3. Status codes - at the beginning it was just meant to tell users an error occurs, the specificity of it has never really been discussed until now, sure we should add those codes that are obvious.

**Comment by wwarby** [comment]
Yeah, it did seem kinda tricky, perhaps impossible to do exactly what I'm trying to do, and perhaps undesirable anyway (overriding the default handler that is) especially if it were easier to override some of it's behaviour as discussed. I've read all the relevant wiki articles including the one you linked above - I already have a couple of working custom scheme handlers in my project which I built following that documentation, but overriding the default seems tricky.

With regards to global error handling, I haven't given it a huge amount of thought but here's an opening gambit...

I think you'd only want to deal with scenarios that are unreachable though traditional try/catch logic or that necessitate very repetitive code. In other words don't re-invent C#'s native exception handling capabilities. Therefore I see the scenarios where global error handling are useful as principally (1) controller action execution and (2) routing.

First let's look at controller action execution. I can't remember what Chromely does out-of-the-box if you throw an exception inside a controller action, but whatever it was it didn't meet my needs so I created a bas controller:
```csharp
public abstract class ControllerBase : ChromelyController {
	
	protected IMapper Mapper { get; }

	protected ControllerBase(IMapper mapper) {
		Mapper = mapper;
	}

	protected IChromelyResponse TryExecute(Action<IChromelyRequest> func, IChromelyRequest request) {
		return TryExecute(_ => {
			func(request);
			return true;
		}, request);
	}

	protected IChromelyResponse TryExecute<T>(Func<IChromelyRequest, T> func, IChromelyRequest request) {
		try {
			var result = func(request);
			return new ChromelyResponse(request.Id) {
				Data = result
			};
		} catch (Exception ex) {
			var innerEx = ex.GetInnermostException();
			Debug.WriteLine(innerEx.Message);
			Debug.WriteLine(innerEx.StackTrace);

			return new ChromelyResponse(request.Id) {
				Data = Mapper.Map<ErrorViewModel>(new ExceptionDetails(ex, "Controller Action")),
				Status = (int)HttpStatusCode.InternalServerError,
				StatusText = "Internal Server Error",
				Error = ex.Message
			};
		}
	}

	protected async Task<IChromelyResponse> TryExecuteAsync(Func<IChromelyRequest, Task> func, IChromelyRequest request) {
		return await TryExecuteAsync(async _ => {
			await func(request);
			return true;
		}, request);
	}

	protected async Task<IChromelyResponse> TryExecuteAsync<T>(Func<IChromelyRequest, Task<T>> func, IChromelyRequest request) {
		try {
			var result = await func(request);
			return new ChromelyResponse(request.Id) {
				Data = result
			};
		} catch (Exception ex) {
			var innerEx = ex.GetInnermostException();
			Debug.WriteLine(innerEx.Message);
			Debug.WriteLine(innerEx.StackTrace);

			return new ChromelyResponse(request.Id) {
				Data = Mapper.Map<ErrorViewModel>(new ExceptionDetails(ex, "Controller Action")),
				Status = (int)HttpStatusCode.InternalServerError,
				StatusText = "Internal Server Error",
				Error = ex.Message
			};
		}
	}

}
```
...and then I implement  controller actions like this:
```csharp
public class SomeController : ControllerBase {

	public SomeController(
		IMapper mapper
	 ) : base(mapper) {
		RegisterRequest("/path/method-1", Method1);
		RegisterRequest("/path/method-2", Method2);
		RegisterRequestAsync("/path/method-3", Method3);
	}

	private IChromelyResponse Method1(IChromelyRequest request) =>
		TryExecute(r => {
			/// ... behaviour
		}, request);
	
	private IChromelyResponse Method2(IChromelyRequest request) =>
		TryExecute(r => {
			/// ... behaviour
		}, request);
	
	private IChromelyResponse Delete(IChromelyRequest request) =>
		TryExecuteAsync(async r => {
			/// ... async behaviour
		}, request);

}
```
This is fine, but it does get a little repetitive. A simple change that would make this kind of code easier to handle would be something like this:
```csharp
public abstract class ChromelyController {
    ...
    protected virtual void OnException() {
        // default behaviour
    }
    ...
}
```
Something like the above could provide a neat syntax for capturing errors at the controller or app level (via a shared base class) for anything that goes wrong inside an actual controller action.

Then routing - this is the problem that led me to raise the issue in the first place. If I request the URL `http://chomely.com/wrong-path` from my app, I currently get a 400 Bad Request response, which doesn't help me understand the cause of my error. I can't catch this error at all because the execution scope is outside my own code. For this scenario I think a global error handling interface is needed, something like this:
```csharp
AppBuilder
    .Create()
    .UseConfig<DefaultConfiguration>(config)
    .UseErrorHandler<MyChromelyErrorHandler>()
    .UseApp<MyChromelyApp>()
    .Build()
    .Run(args);
```
where `MyChromelyErrorHandler` implements `IChromelyErrorHandler`:
```csharp
public interface IChromelyErrorHandler {
    IChromelyReponse HandleRouteNotFound(IChromelyRequest request);
}
```
I guess the expectation would then be that if you provide the implementation of that interface then that response is rendered to the client, otherwise a default response is returned with a the most applicable HTTP status code.

You could then extend the above interface with other scenarios that might throw errors the user cannot currently handle. Off the top of my head I guess that might include deserialization of the request, serialization of the response, static resources not found on disk (or access denied) and so on. Something like this:
```csharp
    IChromelyReponse HandleRouteNotFound(IChromelyRequest request);
    IChromelyReponse HandleRequestSerializationException(IChromelyRequest request, Exception ex);
    IChromelyReponse HandleResponseSerializationException(IChromelyRequest request, IChromelyResponse response, Exception ex);
    IChromelyReponse HandleResourceNotFound(IChromelyRequest request);
```
Just a starter for 10... what do you reckon?

**Comment by mattkol** [comment]
The unhandled exceptions are being caught and logged when the actions are executed.
https://github.com/chromelyapps/Chromely/blob/6a7aeef0a8a386d231e10117417c893be757a5bb/src/Chromely/Browser/Handlers/DefaultRequestSchemeHandler.cs#L96

https://github.com/chromelyapps/Chromely/blob/6a7aeef0a8a386d231e10117417c893be757a5bb/src/Chromely/Browser/Handlers/DefaultRequestSchemeHandler.cs#L148

But I see that we are missing that for the Message Router handler, which is likely why you have the issue in the first place.
https://github.com/chromelyapps/Chromely/blob/00571d633fe48888b085d98522e9a61eec17b6e3/src_5.0/Chromely.CefGlue/Browser/Handlers/CefGlueMessageRouterHandler.cs#L72 This needs to be fixed.

The **IChromelyErrorHandler** idea is cool, I think we should do that. But that should be plugged in in the RequestSchemeHandler and MessageRouterHandler when an exception occurs. 

I do better when I do a change like this weekends, so unless you want to play with it before then, I can see about looking into it then.

Thanks.
