### ISSUE TITLE
Incorrect steps in documentation for latest version of package

### ISSUE THREAD

**Issue by rishikeshjadhav** [chromelyapps/Chromely#290]
Doc Link: https://github.com/chromelyapps/Chromely/wiki/create-new-project-from-scratch

The steps mentioned are not working with latest version of package.
The classes are resolved correctly with version 5.0.77 of package.

**Comment by mattkol** [comment]
@rishikeshjadhav 
The doc was written for v5.0 and still valid, but that will be changed to make it obvious.
Thanks for pointing it out.
