### ISSUE TITLE
how to register a messageHandler

### ISSUE THREAD

**Issue by liesauer** [chromelyapps/Chromely#292]
in c#, may be:
```csharp
var browser/scriptCtx.registerMessageHandler("hybrid", myHybirdMessageHandler);

public void myHybirdMessageHandler(scriptCtx, message)
{
    Console.WriteLine(message); // hello
    // here we can receive the message posted by postMessage.
}
```
in js, we can:
```js
window.messageHandlers.hybrid.postMessage("hello");
// or normally in modern hybrid h5 app
window.webkit.messageHandlers.hybrid.postMessage("hello");
```

**Comment by mattkol** [comment]
CEF/CefGlue/Chromely provides a generic [window.cefQuery](https://github.com/chromelyapps/Chromely/blob/master/Documents/generic_message_routing.md).
````js
 // Create and send a new query.
 var request_id = window.cefQuery({
        request: 'my_request',
        persistent: false,
        onSuccess: function(response) {},
        onFailure: function(error_code, error_message) {}
     });
 
// Optionally cancel the query.
window.cefQueryCancel(request_id)
````

Please get familiar with the [demos](https://github.com/chromelyapps/demo-projects) to see how it is used.

What you described is not supported out of the box. To do that you need to create a custom handler -https://bitbucket.org/chromiumembedded/cef/wiki/GeneralUsage.md#markdown-header-generic-message-router
