### ISSUE TITLE
WindowOptions.Title does not support chinese on osx

### ISSUE THREAD

**Issue by liesauer** [chromelyapps/Chromely#295]
```csharp
var config = DefaultConfiguration.CreateForRuntimePlatform();
config.WindowOptions.Title = "测试";
```
on osx
![image](https://user-images.githubusercontent.com/8676741/106708282-8d975a00-662d-11eb-8407-c23d0ab3bd38.png)

on windows, it is fine.
![image](https://user-images.githubusercontent.com/8676741/106708406-c8998d80-662d-11eb-9935-5d0894de13ec.png)

**Comment by mattkol** [comment]
@liesauer 

Will verbatim work?
````c#
var config = DefaultConfiguration.CreateForRuntimePlatform();
config.WindowOptions.Title = @"测试";
````

**Comment by liesauer** [comment]
no

here's my code

```csharp
var config = DefaultConfiguration.CreateForRuntimePlatform();
config.CefDownloadOptions.AutoDownloadWhenMissing = false;
config.WindowOptions.Title = "测试";
config.WindowOptions.RelativePathToIconFile = "favicon.ico";

var appDirectory = AppDomain.CurrentDomain.BaseDirectory;
config.StartUrl = $"file:///{appDirectory}web/index.html";

var appBuilder = AppBuilder
.Create()
.UseConfig<DefaultConfiguration>(config)
.UseApp<HybridApp>()
.Build();

appBuilder.Run(args);
```

**Comment by mattkol** [comment]
Did you try the "@" in front of the title? Try change "测试" to @"测试".

**Comment by liesauer** [comment]
> Did you try the "@" in front of the title? Try change "测试" to @"测试".

doesn't work.

**Comment by mattkol** [comment]
Seems like a disconnect between .NET/C# and Cocoa/Objective-C. It will require looking at how Cocoa/Objective-C handles encoding.

**Comment by mattkol** [comment]
@liesauer 

This is now fixed.

![Fix_issue_295](https://user-images.githubusercontent.com/18384207/112774781-b7a34200-9008-11eb-81c9-95cf0857fb4a.PNG)
![Fix_issue_295_2](https://user-images.githubusercontent.com/18384207/112774784-ba059c00-9008-11eb-80b0-1ba793e33015.PNG)

**Comment by liesauer** [comment]
thanks!
