### ISSUE TITLE
PublishSingleFile not working

### ISSUE THREAD

**Issue by charlie-haley** [chromelyapps/Chromely#296]
I'm looking to condense the number of output files as much as possible, I'm running this command:

`dotnet publish -c Release -p:PublishSingleFile=true -r win-x64` 

It seems to work as I get quite a large exe (75mb), but when I open it I get an error
```
CEF binaries download completed with error.
Error message: The remote server returned an error: (403) Forbidden.
```

Is there a recommend way to compile the app into a single execeutable or as little files as possible?

**Comment by mattkol** [comment]
@charlie-haley 

> Is there a recommend way to compile the app into a single execeutable or as little files as possible?

Installation/packing is not supported, so really no formal recommendation on creating single executable. 

You maybe doing the packing right, but that may be blocking the download process. If the download works without publishing, I will check first what is causing the download error. There should be a "Logs" folder in the bin directory that should have logged the details.

**Comment by charlie-haley** [comment]
> @charlie-haley
> 
> > Is there a recommend way to compile the app into a single execeutable or as little files as possible?
> 
> Installation/packing is not supported, so really no formal recommendation on creating single executable.
> 
> You maybe doing the packing right, but that may be blocking the download process. If the download works without publishing, I will check first what is causing the download error. There should be a "Logs" folder in the bin directory that should have logged the details.

Is it possible to download the cef binaries at build/publish time so I can bundle them and prevent the download even needing to start?

**Comment by mattkol** [comment]
@charlie-haley 
Yes, the guide to download is here - https://github.com/chromelyapps/Chromely/blob/master/Documents/cef_binaries_download.md

If you are doing this on Windows and build using Visual Studio/Visual Studio Code with nuget, it should have downloaded it for you already. You can check the nuget folder ..

![image](https://user-images.githubusercontent.com/18384207/107837475-fa69cd00-6d6e-11eb-8e11-6c486d8b092d.png)

Check the "CEF" folder.

Alternatively (Windows ONLY) - issue #297

**Comment by peerem** [comment]
This is actually not a problem. Simply use "PublishSingleFile" and then copy the "Chromely.dll" into the output folder. Works fine.
