### ISSUE TITLE
Howto enable access to camera and microphone

### ISSUE THREAD

**Issue by peerem** [chromelyapps/Chromely#298]
Hello.

How can we pass "enable-media-stream" to Cef? It is required for the camera and microphone in WebRtc.

**Comment by mattkol** [comment]
Please see how to set [CommandLineOptions](https://github.com/chromelyapps/Chromely/blob/master/Documents/configuration.md).

````c#
 var config = DefaultConfiguration.CreateForRuntimePlatform();
 config.CommandLineOptions.Add("enable-media-stream");
````

**Comment by peerem** [comment]
Works fine, thank you.
