### ISSUE TITLE
Failed to load resource: the server responded with a status of 404 (File not found.)

### ISSUE THREAD

**Issue by redaxol** [chromelyapps/Chromely#300]
I added a file index.js in my file index.html 
<script src="content/index.js"></script>
but after execution i got this error
Failed to load resource: the server responded with a status of 404 (File not found.)                index.js
I have verified that the path of the JS file is correct
is there a solution ?

**Comment by mattkol** [comment]
@redaxol 
> I have verified that the path of the JS file is correct

You mean the file source location is correct? Is it in the destination folder (bin) directory?
If not in bin, then it is likely you are not copying it over.

Please ensure "Copy Always" or "Copy if Newer" is set.
https://github.com/chromelyapps/demo-projects/blob/1cac58ffb95098223e206043ad9748c3f80dcea1/regular-chromely/CrossPlatDemo/CrossPlatDemo.csproj#L58

If this is not the issue, then I will suggest starting with [CrossPlatDemo](https://github.com/chromelyapps/demo-projects/tree/master/regular-chromely/CrossPlatDemo) and make incremental changes.

**Comment by redaxol** [comment]
Works fine, thank you.
