### ISSUE TITLE
Print file directly 

### ISSUE THREAD

**Issue by redaxol** [chromelyapps/Chromely#301]
how to print a pdf file directly to default printer without showing print dialog or option like kiosk

**Comment by mattkol** [comment]
@redaxol 

You can do most custom tasks in the [Controllers](https://github.com/chromelyapps/demo-projects/tree/master/regular-chromely/CrossPlatDemo/Controllers) for C# and for JavaScript in [html or js files](https://github.com/chromelyapps/demo-projects/tree/master/regular-chromely/CrossPlatDemo/app)  but actual pdf printing itself is not supported. You need to look into other projects for that.

**Comment by redaxol** [comment]
Is that there are lightweight alternatives of Chromely in .net that support this feature ?

**Comment by mattkol** [comment]
@redaxol 

> Is that there are lightweight alternatives of Chromely in .net that support this feature ?

My statement was a bit misleading. I just updated that.

This is what I meant:  https://github.com/chromelyapps/Chromely/issues/303. 

So what you intend to do will will be done in this method:

````c#
       class PrintToPdfCallback : CefPdfPrintCallback
        {
            protected override void OnPdfPrintFinished(string path, bool ok)
            {
                if (ok)
                {
                    // Do the printer work here.
                    // Or other tasks.
                }
            }

            public void Dispose()
            {
            }
        }
````

We can look into feature exposing printing to PDF.
