### ISSUE TITLE
RelativePathToIconFile - I don't see a icon

### ISSUE THREAD

**Issue by HenriApperloo** [chromelyapps/Chromely#302]
No Icon left upper...

config.WindowOptions.RelativePathToIconFile = "favicon.ico";

I use nuget package, https://www.nuget.org/packages/Chromely/5.1.86/

**Comment by mattkol** [comment]
@HenriApperloo 

You do have the icon file "favicon.ico", right?
Likely same issue here - https://github.com/chromelyapps/Chromely/issues/300.

https://github.com/chromelyapps/demo-projects/blob/1cac58ffb95098223e206043ad9748c3f80dcea1/regular-chromely/CrossPlatDemo/CrossPlatDemo.csproj#L90
