### ISSUE TITLE
Call c# function in JavaScrpit 

### ISSUE THREAD

**Issue by redaxol** [chromelyapps/Chromely#304]
there is a way to call c# function in JavaScrpit and vice-versa

**Comment by mattkol** [comment]
@redaxol 

To call JavaScript from C#:
https://github.com/chromelyapps/demo-projects/blob/1cac58ffb95098223e206043ad9748c3f80dcea1/regular-chromely/CrossPlatDemo/app/pages/javascriptdemo.html#L71
https://github.com/chromelyapps/Chromely/blob/master/Documents/javascript_execution.md
https://github.com/chromelyapps/demo-projects/blob/0ed0bf5a82ec196a9211ccacef85560aecfd11af/regular-chromely/CrossPlatDemo/Controllers/ExecuteJavaScriptDemoController.cs#L50

To call C# from JavaScript:
Please see the [demos](https://github.com/chromelyapps/demo-projects)  -  https://github.com/chromelyapps/demo-projects/tree/master/regular-chromely/CrossPlatDemo/app
