### ISSUE TITLE
Can chrome run on centos7

### ISSUE THREAD

**Issue by zx1992147** [chromelyapps/Chromely#307]

**Comment by mattkol** [comment]
@zx1992147 


I am not sure if CEF supports [CentOS officially](https://bitbucket.org/chromiumembedded/cef/wiki/BranchesAndBuilding), but it looks like there are [developers using CEF on CentOS](https://www.magpcss.org/ceforum/search.php?keywords=Centos).

So, sure you can try. 

Ensure you have the right CentOS version supported by .NET Core:
https://github.com/dotnet/core/blob/main/release-notes/3.0/3.0-supported-os.md
https://github.com/dotnet/core/blob/main/release-notes/5.0/5.0-supported-os.md

For Chromely you can start with [Readme](https://github.com/chromelyapps/demo-projects/blob/master/README.md) and  [CrossPlatDemo](https://github.com/chromelyapps/demo-projects/tree/master/regular-chromely/CrossPlatDemo).
