### ISSUE TITLE
I am running on CentOS 7, and the following error is prompted. Can you help me to have a look?

### ISSUE THREAD

**Issue by zx1992147** [chromelyapps/Chromely#308]
(dotnet:5884): Gdk-ERROR **: 17:27:59.062: The program 'dotnet' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadValue (integer parameter out of range for operation)'.
  (Details: serial 221 error_code 2 request_code 12 (core protocol) minor_code 0)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the GDK_SYNCHRONIZE environment
   variable to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)

**Comment by mattkol** [comment]
@zx1992147 

Likely same as error in - https://github.com/chromelyapps/Chromely/issues/299

Please see my comments:
https://github.com/chromelyapps/Chromely/issues/299#issuecomment-797494943
https://github.com/chromelyapps/Chromely/issues/299#issuecomment-799233864

**Comment by zx1992147** [comment]
Can I generate Linux programs on windows and run them on CentOS 7？

**Comment by zx1992147** [comment]
Thank you. It's ready to run now. But how do I use it in a production environment
