### ISSUE TITLE
How to Create Setup.exe

### ISSUE THREAD

**Issue by redaxol** [chromelyapps/Chromely#309]
I want to create an executable file of the application in order to install the application on several machines with different operating systems (Windows, linux, Mac)

**Comment by mattkol** [comment]
@redaxol 

The project does not offer/support packaging/installations.
You need to look at projects like Wix, Squirrel or alternatives
https://stackoverflow.com/questions/1544292/what-installation-product-to-use-installshield-wix-wise-advanced-installer
