### ISSUE TITLE
file open dialog changes root folder?

### ISSUE THREAD

**Issue by kroehne** [chromelyapps/Chromely#311]
If within an HTML page a file is selected using an input of type="file", and if the file is located in another directory, then Chromly loses its root directory and cannot navigate afterward (e.g. by link). An illustration in the example attached. How to implement a file open dialog (in the browser)?

Thanks and best regards
kroehne 

[OpenFileJSExample.zip](https://github.com/chromelyapps/Chromely/files/6246210/OpenFileJSExample.zip)

**Comment by mattkol** [comment]
@kroehne 

I cannot reproduce or may be I need more info.


![issue](https://user-images.githubusercontent.com/18384207/113527135-93a4ab00-958a-11eb-98b6-322bbded1644.gif)

**Comment by kroehne** [comment]
Thank you for your feedback and your attempt to reproduce this issue. I suggest closing the issue since I can't reproduce it after re-installing my Visual Studio over the last few days. When I observe the problem again, I'll reopen the issue.
Kind regards.
