### ISSUE TITLE
Question: Is it possible to change to Kiosk mode during runtime?

### ISSUE THREAD

**Issue by kroehne** [chromelyapps/Chromely#313]
Hi,
I find the option ```config.WindowOptions.KioskMode = true;``` quite useful, and it's working as expected if I configure it before calling ```AppBuilder```. I was wondering, if it also possible to switch to Kisok mode during runtime (so only when the user decides to use Kiosk mode) and if so: How? 
Thanks and kind regards.

**Comment by mattkol** [comment]
@kroehne 

Related to https://github.com/chromelyapps/Chromely/issues/185#issuecomment-617815483

You can either access the native host in the Controllers or [Window](https://github.com/chromelyapps/demo-projects/blob/53ccbdd22eac818ebf96df594f6fc81369965772/regular-chromely/CrossPlatDemo/DemoWindow.cs#L15).
