### ISSUE TITLE
Using Chromely On Linux With Visual Studio

### ISSUE THREAD

**Issue by orrburgel** [chromelyapps/Chromely#315]
It looks like Visual Studio is required to use Chromely and it should support Linux but I can't find any version of Visual Studio for linux, it says online there isn't one, so I'm confused how that works, Can I build for Linux from Windows and then just take the executables, since Visual Studio doesn't exist on Linux, If so How do I do that?
Can I also build for Mac from Windows or vice versa?
I think the ultimate question is how do I build for Linux am I missing it in the docs? cause I can't see it there for some reason

**Comment by mattkol** [comment]
@orrburgel 

You can use Visual Studio Code too. But you need to install .NET Core 3 or NET 5 on the distro.

https://docs.microsoft.com/en-us/dotnet/core/install/linux
https://dotnet.microsoft.com/download

Guide:
https://github.com/chromelyapps/demo-projects/blob/master/README.md

**Comment by orrburgel** [comment]
Thanks that helped a lot.
