### ISSUE TITLE
Question: Where can I see a list of configuration options?

### ISSUE THREAD

**Issue by orrburgel** [chromelyapps/Chromely#316]
I saw this issue about the microphone permissions that interested me:
https://github.com/chromelyapps/Chromely/issues/298
and saw the use of **enable-media-stream**
`config.CommandLineOptions.Add("enable-media-stream");`
I wanted to see where I can find more configuration options and learn more about **enable-media-stream** but couldn't find a list with it included, care to link me, please?
I already searched here and every link that comes out of here:
https://github.com/chromelyapps/Chromely/blob/master/Documents/configuration.md
https://github.com/chromelyapps/Chromely/blob/master/Documents/commands.md

**Comment by mattkol** [comment]
@orrburgel 

This may help -https://peter.sh/experiments/chromium-command-line-switches/

**Comment by orrburgel** [comment]
Thanks it helped
