### ISSUE TITLE
Configured CefLogFile path overridden to include date

### ISSUE THREAD

**Issue by MichelJansson** [chromelyapps/Chromely#317]
The `CefLogFile` as configured in "CustomSettings" is overridden to include date, with no way to prevent that behavior.
It makes sense to have the filename be autogenerated for the default name (which it does), but not when explicitly specified.

The below config will actually write to the file `logs\my.cef_20210409.log`. (yyyyMMdd)
```cs
config.CustomSettings = new Dictionary<string, string>()
{
    ["cefLogFile"] = "logs\\my.cef.log",
};
```

### Suggested solution

This should be changed to just take the unchanged value of the setting:
https://github.com/chromelyapps/Chromely/blob/1f95b7d1475cd56bd9a50b1d8df7140e42810e22/src/Chromely/Browser/CefSettingsExtension.cs#L118 

The default name is handled here, and should be unaffected by this change:
https://github.com/chromelyapps/Chromely/blob/1f95b7d1475cd56bd9a50b1d8df7140e42810e22/src/Chromely/WindowController.Run.cs#L68

----

Thank you for your work on this project!

**Comment by mattkol** [comment]
@MichelJansson 

So if I understand the suggestion 

On line:
https://github.com/chromelyapps/Chromely/blob/1f95b7d1475cd56bd9a50b1d8df7140e42810e22/src/Chromely/Browser/CefSettingsExtension.cs#L118

we should have:

````c#
 cefSettings.LogFile = config.CustomSettings["cefLogFile"]; 
````

Right?


> Thank you for your work on this project!

yw

**Comment by MichelJansson** [comment]
@mattkol Thanks for looking into this.

I would say that since this is all within a `foreach`, line 118 would read:
```cefSettings.LogFile = setting.Value``` 
and of course, line 116 and 117 is then not needed.

**Comment by mattkol** [comment]
@MichelJansson thanks for pointing this out, I could not remember why it was done this way in first place.

**Comment by MichelJansson** [comment]
Good stuff @mattkol - Thanks!
