### ISSUE TITLE
I get an exception when running the executable.

### ISSUE THREAD

**Issue by karuzzo** [chromelyapps/Chromely#318]
Stack: .NET 5 + blazor server side
if I run the application from under Visual Studio it runs correctly, but as soon as I try to run the executable file in the release or debug folder, it gives an error.

![изображение_2021-04-25_115327](https://user-images.githubusercontent.com/18124355/115987231-d8859580-a5bc-11eb-8bf6-faa9299976b6.png)

the same error is present in the blazor server side demo app

**Comment by mattkol** [comment]
@karuzzo you are likely missing static files. This project does not support installation and publishing, you can check other resources online to see how to package ( or add static files in Asp.Net Core). This is just a bare bone demo.

**Comment by karuzzo** [comment]
Thank you for such a quick response.
