### ISSUE TITLE
setting width and height programmatically

### ISSUE THREAD

**Issue by haviduck** [chromelyapps/Chromely#319]
Heya, sweet framework. really fast! 
Im trying to avoid using config.json, but cant find any references to setting frame width and height from cs config. any tips?

**Comment by FrankPfattheicher** [comment]
Hi @haviduck ,

see ChromelyConfiguration.WindowOptions.Size

Source sample in Chromely.Integration.TestApp

**Comment by haviduck** [comment]
> Hi @haviduck ,
> 
> see ChromelyConfiguration.WindowOptions.Size
> 
> Source sample in Chromely.Integration.TestApp

thanks a bunch!
