### ISSUE TITLE
Are there any plans to support input method switching? For fcitx, ibus, etc.

### ISSUE THREAD

**Issue by TheForgetTime** [chromelyapps/Chromely#321]

**Comment by mattkol** [comment]
@TheForgetTime 

I see a discussion of that on CEF [hosting site](https://bitbucket.org/chromiumembedded/cef/issues/1813/cef-does-not-work-with-imes-on-linux), but I do not see an implementation of it on CefGlue. So, in essence, no plans  for that .. for now. If CefGlue exposes it, certainly we could revisit this. 

There may also  be other ways to support it using .NET Core. If there is, then of course we should work with the developers on that.

There is also a related issue #294.
