### ISSUE TITLE
Dragging area does not work under Mac

### ISSUE THREAD

**Issue by xplicit** [chromelyapps/Chromely#323]
Looks like [DefaultDragHandler ](https://github.com/chromelyapps/Chromely/blob/master/src/Chromely/Browser/Handlers/DefaultDragHandler.cs) does not work at Mac for frameless window. 

[framelessOption.IsDraggable](https://github.com/chromelyapps/Chromely/blob/master/src/Chromely/Browser/Handlers/DefaultDragHandler.cs#L72) is never called under Mac, while on Windows it works without issues.

**Comment by mattkol** [comment]
@xplicit frameless feature is implemented for Windows only.
