### ISSUE TITLE
How to publish an .net 5.0 application contains "Chromely" correctly?

### ISSUE THREAD

**Issue by LiveOrNot** [chromelyapps/Chromely#324]
I use "dotnet publish -r linux-x64 /p:PublishSingleFile=true" to publish my .net 5.0 application, all cef files are copied to publish path, but when I use "./myApplication" to run my application on Ubuntu 18.04, some errors like 'System.DllNotFoundException' occured. Here is the details.
![image](https://user-images.githubusercontent.com/67695402/119620038-29e0a900-be37-11eb-8f83-31e812648329.png)

thanks, looking forword to your reply!

**Comment by mattkol** [comment]
@LiveOrNot the project does not support publishing or packaging. If this works in  the IDE, it would be advisable to compare what works with what doesn't on the same machine.

From experience if it is unable to load libcef and it is physically there then it likely means some dependencies are missing or you have the wrong file (x86 for x64  or vice versa).

This is an [old wiki page](https://github.com/chromelyapps/Chromely.Legacy/wiki/Getting-Started-CefGlue-Gtk-(Linux)#on-linux-ubuntu-with-published-self-contained-net-core) but some info there may help, especially checking for dependencies.

**Comment by LiveOrNot** [comment]
Thanks, Cross-Platform is really a pit! I hope the coming Maui can give C# programmers a little comfort，hahaha
