### ISSUE TITLE
Does Chromely support Media Source Extensions?

### ISSUE THREAD

**Issue by jim-lin507** [chromelyapps/Chromely#325]
I am using flv.js(https://github.com/bilibili/flv.js) to play video that relies on **Media Source Extensions**, it works fine on Chrome(Version 91) and other browsers.
Please tell me why if you know. Thanks!

**Comment by mattkol** [comment]
@jim-lin507 Chromely is based on CEF/CefGlue, so if it does not work, it may be proprietary issue - https://www.magpcss.org/ceforum/viewtopic.php?f=17&t=18373
