### ISSUE TITLE
DOM Manipulation?

### ISSUE THREAD

**Issue by ameisen** [chromelyapps/Chromely#327]
Hello,

I'm looking to port a BridgeDotNet project to something more suitable for its nature as a desktop application. Presently, the code heavily manipulates the DOM - the entire page is effectively dynamically generated and manipulated.

I'm having trouble, going over the samples, finding anything that functions quite like that. Does Chromely have any in-built APIs to interact with the DOM itself, or would those need to be written from scratch on top of IPC?

**Comment by mattkol** [comment]
@ameisen 

>> Does Chromely have any in-built APIs to interact with the DOM itself, 

No, not out of the box.

>> or would those need to be written from scratch on top of IPC?

Yes, you need to add implementation to visit the DOM (VisitDOM).

These are links that may help:
https://github.com/chromelyapps/Chromely/issues/280
https://www.magpcss.org/ceforum/viewtopic.php?f=6&t=12723
https://www.programmersought.com/article/82555459603/


If you do not need to go that granular, you can look into executing JavaScript functions:
https://github.com/chromelyapps/Chromely/blob/master/Documents/javascript_execution.md
https://github.com/chromelyapps/Chromely/issues/304
