### ISSUE TITLE
How to mount a JS object on a window object via c# code?

### ISSUE THREAD

**Issue by 2505817596** [chromelyapps/Chromely#332]
How to mount a JS object on a window object via c# code?

For example
`//c# eng.Execute("window.name = "test"");`

Expected
`<script>alert(window.myXXXX); //test</script>`

**Comment by mattkol** [comment]
@2505817596 

Related:
https://github.com/chromelyapps/Chromely/issues/304
https://github.com/chromelyapps/Chromely/issues/138
https://github.com/chromelyapps/Chromely/blob/master/Documents/javascript_execution.md
