### ISSUE TITLE
App Icon not showing on Linux

### ISSUE THREAD

**Issue by peerem** [chromelyapps/Chromely#336]
Hello.

The app icon is not showing on Linux. On Windows all works fine. The icon is definitely in the right place.

**Comment by FrankPfattheicher** [comment]
Hi @peerem ,

did you try the Chromely.Integration.TestApp ?

Be sure the icon is added as content (copy always) - not as embedded-resource.

As you can see below - the icon is there.

![Chromely](https://user-images.githubusercontent.com/921532/128184905-9f650ce8-868b-476f-8aec-d2d0c7217824.png)

**Comment by peerem** [comment]
Under Windows all run fine, but under Linux I see only an "X" symbol.

This is the configuration:

`config.WindowOptions.RelativePathToIconFile = "peerem.ico";`

And this the files in the folder:

cef_100_percent.pak
cef_200_percent.pak
cef_extensions.pak
cef.pak
chrome-sandbox
data
devtools_resources.pak
ffmpeg
icudtl.dat
libcef.so
libEGL.so
libe_sqlcipher.so
libGLESv2.so
locales
Logs
**PeerEmDesktop
peerem.ico**
snapshot_blob.bin
swiftshader
v8_context_snapshot.bin
wwwroot

**Comment by FrankPfattheicher** [comment]
Can you please add a screen shot;
And have you tried a PNG icon?
Maybe the file is invalid for Linux.

**Comment by peerem** [comment]
It works with the PNG. I changed my configuration because Windows needs the ICO.

`config.WindowOptions.RelativePathToIconFile = $"peerem.{(RuntimeInformation.IsOSPlatform(OSPlatform.Linux) ? "png" : "ico")}";`

**Comment by FrankPfattheicher** [comment]
Fine - this behaviour should be documented.
