### ISSUE TITLE
Change URL at runtime

### ISSUE THREAD

**Issue by heckradr** [chromelyapps/Chromely#337]
Hello. Is it possible to change the URL at runtime? I saw only the possiblity to provide the start url within the configuration (DefaultConfiguration) but no way to switch programmatically to another URL while the application is running.

**Comment by mattkol** [comment]
@heckradr 
You can try:

Howto: Reload with a Url Change #338

````csharp
  Xilium.CefGlue.CefBrowser browser = scriptExecutor.GetBrowser() as Xilium.CefGlue.CefBrowser;
  if (browser != null)
  {
      browser.GetMainFrame().LoadUrl("https://google.com");
  }
````

**Comment by heckradr** [comment]
@mattkol works perfectly, thank you very much
