### ISSUE TITLE
How to invoke system dialog?

### ISSUE THREAD

**Issue by siquylee** [chromelyapps/Chromely#340]
Could you please show me the sample to display FileOpen/FileSave dialog of native OS?

**Comment by mattkol** [comment]
@siquylee there is an an example on how to do it on Windows - https://github.com/chromelyapps/Chromely/issues/164 (you need to change to FileOpen/FileSave methods).

For Linux and Mac OS, it should be similar. 

There is an example for Linux using gtk on .NET Core - http://docs.go-mono.com/index.aspx?link=T%3AGtk.FileChooserDialog
For MacOS - you may have to write objective-C to do that, but none of these are supported out of the box in Chromely.

Thanks.
