### ISSUE TITLE
Show download progress

### ISSUE THREAD

**Issue by peerem** [chromelyapps/Chromely#342]
How can we implement a download progress? We have installed the NuGet package 5.1.88 and the "ChromlyBasicApp" does not contain an overwritable function called "Configure", as described in the documentation.

**Comment by peerem** [comment]
That works well. Now I just have to find out how I can communicate with blazor.

**Comment by mattkol** [comment]
Ok.

**Comment by peerem** [comment]
The handling between this and Blazor is not so easy. Is there a way to open the system default browser for external links from Blazor? I have read something about "OnBeforeNavigation" in terms of Cefsharp, but no idea how I can use that in Chromely.
