### ISSUE TITLE
Getting the rendered Html source

### ISSUE THREAD

**Issue by kennethlou** [chromelyapps/Chromely#350]
Hi,

I am trying the Chromely cross-platform demo.

Just wondering do you know how to get the HTML source from a button? I was looking for the events triggered but the frames do not seem to have the HTML source. The browser object itself also does not seem to have the HTML.

Regards

**Comment by mattkol** [comment]
@kennethlou this may help - https://github.com/chromelyapps/Chromely/issues/351.

**Comment by kennethlou** [comment]
Hi,

Apart from the user clicking on the menu to create a notepad, is there any method that can be used to store the HTML string into a variable?

Regards,

**Comment by mattkol** [comment]
@kennethlou this may help - https://github.com/chromelyapps/Chromely/issues/352
