### ISSUE TITLE
Upgrade to v5.2 - .NET 6, AspNetCore Owin, MVC-styled controller actions

### ISSUE THREAD

**Issue by mattkol** [chromelyapps/Chromely#355]
Version 5.2 upgrade begins a gradual code base move to .NET 6. 

Source - https://github.com/chromelyapps/Chromely/blob/master/src
Demos - https://github.com/chromelyapps/demo-projects

**Comments are welcome.**

### Planned/implemented
-  Move to .NET 6. 
- AspNetCore Owin support - this implements a new library - [Chromely.Owin](https://github.com/chromelyapps/Chromely/blob/master/src/Chromely.Owin) and is an implementation of @amaitland [Chromium.AspNetCore.Bridge](https://github.com/amaitland/Chromium.AspNetCore.Bridge). It is in essence a migration of [Chromely.AspNetCore.Mvc.Example](https://github.com/amaitland/Chromium.AspNetCore.Bridge/tree/master/Chromely.AspNetCore.Mvc.Example). There is also a similar implementation in [EdgeSharp](https://github.com/webview2/EdgeSharp/tree/main/src/EdgeSharp.Core.Owin).
- MVC-styled controller actions - change to move from using [IChromelyRequest](https://github.com/chromelyapps/Chromely/blob/master/src/Chromely.Core/Network/IChromelyRequest.cs), [IChromelyResponse](https://github.com/chromelyapps/Chromely/blob/master/src/Chromely.Core/Network/IChromelyResponse.cs) as controller action request/response wrappers. Developers can now define their own action arguments and response types. 
Basic types are supported:

	 - Primitive types
	 - List
	 - Dictionary
	 - dynamic/object
	 - Models serializable by [System.Text.Json](https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-how-to?pivots=dotnet-6-0)
  
  This is extensible by implementing and registering a [IChromelyModelBinder](https://github.com/chromelyapps/Chromely/blob/master/src/Chromely.Core/Network/IChromelyModelBinder.cs).
  A similar approach has been previously implemented by @RupertAvery - [Chromely.Mvc](https://github.com/RupertAvery/Chromely.Mvc). 
  This is also implemented in [EdgeSharp](https://github.com/webview2/EdgeSharp.Samples/blob/60a862ae703720b2ccfbe9f877276b2cb75252f4/win-32/EdgeSharp.Shared/ActionControllers/MoviesActionController.cs#L23).
  
- Controller base renaming - to avoid conflict with AspNetCore Owin Mvc controller naming, Chromely base controller will be renamed [ChromelyController](https://github.com/chromelyapps/Chromely/blob/master/src/Chromely.Core/Network/ChromelyController.cs).

- Resource folder url scheme: Currently the UrlSchemeType "Resource" maps to a relative folder in the application folder.    Based on https://github.com/chromelyapps/Chromely/issues/244, UrlSchemeType "Resource" type will be split into:
   - [LocalResource](https://github.com/chromelyapps/Chromely/blob/f8d66b26dcd15d2ab675ec4a6d7353c6b1d64042/src/Chromely.Core/Network/UrlSchemeType.cs#L9): this does what the current "Resource" do, using app relative path.
   - [FolderResource](https://github.com/chromelyapps/Chromely/blob/f8d66b26dcd15d2ab675ec4a6d7353c6b1d64042/src/Chromely.Core/Network/UrlSchemeType.cs#L10): this allows host names to be mapped to actual folder path. 
      e.g., "E:\img" can be mapped to "http://img"
	  
  The only requirement is to register the Url schemes:
  
  ````C#
    UrlSchemes.Add(new UrlScheme(DefaultSchemeName.LOCALRESOURCE, "local", string.Empty, string.Empty, UrlSchemeType.LocalResource));
    UrlSchemes.Add(new UrlScheme(DefaultSchemeName.FOLDERRESOURCE, "http", "img", "E:\img", string.Empty, UrlSchemeType.FolderResource));
  ````

Nice to have:
-  Notification of CEF Binaries download -
https://github.com/chromelyapps/Chromely/issues/347

**Comment by tenove** [comment]
Especially hope to support packaging into exe
