### ISSUE TITLE
Especially hope to support packaging into exe for production  

### ISSUE THREAD

**Issue by tenove** [chromelyapps/Chromely#358]
Especially hope to support packaging into exe for production

**Comment by mattkol** [comment]
@tenove there are no plans to support publishing and packing for the project. 

There are resources out there to help you with it. There is Squirrel or alternatives like WiX, InstallShield, etc. You can also try self-contained with .NET Core or  [Single file deployment and executable](https://docs.microsoft.com/en-us/dotnet/core/deploying/single-file). 

You can pick any of these options, and if you run into issues you can share with us, there are developers out there who have used similar tools that would be able to help.

**Comment by amaitland** [comment]
If you choose to go down the WiX path then https://github.com/oleg-shilo/wixsharp is totally worth checking out.
