### ISSUE TITLE
cef package is too large

### ISSUE THREAD

**Issue by tenove** [chromelyapps/Chromely#359]
The volume of the cef package is too large, which leads to the application, and the overall package volume reaches 400M+. Is there a way to reduce it?

**Comment by mattkol** [comment]
@tenove maybe, it depends.

Unzipped CEF binaries for v96 is about 315 MB.

This is the current layout:
![image](https://user-images.githubusercontent.com/18384207/150517012-ea8ea7e5-8039-4dca-a96b-7a4e3ead829f.png)

So on CEF binaries, you can investigate what files and resources are required for your app and see those you can remove. This wiki should help - https://bitbucket.org/chromiumembedded/cef/wiki/Tutorial.md

For .NET Core/.NET 6 dll files, you can see if you can trim them. There are various options online to do that.

Compression/decompression may be helpful too.

**Comment by amaitland** [comment]
You don't need cef_sandbox.lib (or any of the lib files). I wouldn't exclude/delete anything else.
