### ISSUE TITLE
404 Page in the current Wiki

### ISSUE THREAD

**Issue by burgil** [chromelyapps/Chromely#362]
The following link is erroring out, coming from the main wiki:
[How to use commands](https://github.com/chromelyapps/Chromely/blob/master/Documents/commands.md)

**Comment by burgil** [comment]
found the file:
https://github.com/chromelyapps/Chromely/blob/3cdb28e16182651e7fbec193593c07343e657e85/Documents/commands.md
the following commit removed it:

[Removed temp src_5.2 folder.](https://github.com/chromelyapps/Chromely/commit/9b08a59a0d5271c23f18acc5e01fbb99c775d10d)[](https://github.com/mattkol)

@[mattkol](https://github.com/chromelyapps/Chromely/commits?author=mattkol)
mattkol committed on Jan 29

**Comment by mattkol** [comment]
@burgil the "MVC-styled controller actions" mentioned in https://github.com/chromelyapps/Chromely/issues/355 eliminates use of "Commands". Generally Commands would now be equivalent to Controller actions without return values. 

Something like: 
https://github.com/chromelyapps/demo-projects/blob/6cf6a116ddadb6bda587da39ae25ab850d9a7f80/regular-chromely/Chromely.CrossPlat/ChromelyControllers/MovieController.cs#L26

If you still need to use Commands you need to stay with [5.1](https://github.com/chromelyapps/Chromely/tree/master/src_5.1).

Thanks.
