### ISSUE TITLE
wiki document: missing urls?

### ISSUE THREAD

**Issue by AlphaBs** [chromelyapps/Chromely#363]
https://github.com/chromelyapps/Chromely/wiki/configuration

Where is ConfigurationHandler?

https://github.com/chromelyapps/Chromely/blob/master/src/Chromely.Core/Configuration/ConfigurationHandler.cs
https://github.com/chromelyapps/demo-projects/blob/master/regular-chromely/CrossPlatDemo/chromelyconfig.json

**Comment by mattkol** [comment]
@AlphaBs ConfigurationHandler is no longer supported. It was used in [v5.0](https://github.com/chromelyapps/Chromely/tree/master/src_5.0)
The latest configuration file is here - [Configuration](https://github.com/chromelyapps/Chromely/blob/master/Documents/configuration.md)

**Comment by AlphaBs** [comment]
thank you. As a beginner, It was confused that wiki and /Documents/*.md are different. (maybe wiki is not latest?)

**Comment by mattkol** [comment]
@AlphaBs I will find time to clean that out. Thanks for pointing it out.
