### ISSUE TITLE
The content of Main window is not responsive after custom CefLifeSpanHandler

### ISSUE THREAD

**Issue by hungle9320** [chromelyapps/Chromely#364]
I need to display popup then I have create a custom 
`public class CustomCefLifeSpanHandler : CefLifeSpanHandler
    {
    }`

`services.AddSingleton<CefLifeSpanHandler, CustomCefLifeSpanHandler>();`

After this, the pop up can populate at expected size and responsive but the main window content is now fixed at default 1200x900, It cannot responsive when I resize the browser.
And the popup cannot request to the cef-controller.

Are there any fix for this?

Thanks

**Comment by mattkol** [comment]
@hungle9320 could this be because the popup is shown as a dialog?
It will be difficult to understand without some code. Do you have like a skeletal code to attach?
