### ISSUE TITLE
Include libcef.dll etc. when publishing

### ISSUE THREAD

**Issue by teremy** [chromelyapps/Chromely#380]
Hi. I just downloaded the ChromelySamples and I want to publish the Chromely.CrossPlat-Application. 
In the output directory the libcef.dll etc. file is missing and the application won't start. The application will actually download libcef etc. in the background but I'd like to include it (=have it shipped with) in the application, because the downloading in background is very user unfriendly (for the user the application just looks like it didn't start in a reasonable amount of time) and it's possible that the download won't work. 
The files are included in the build folders but not in the publish folder. 

How can I make this work in an easy and idiomatic way?

**Comment by mattkol** [comment]
@teremy please note that publishing/packing is not supported, please see other issues where this has been discussed to see if you can find some hints:
https://github.com/chromelyapps/Chromely/search?p=2&q=publish&type=issues
https://github.com/chromelyapps/Chromely/search?q=install&type=issues

**Comment by teremy** [comment]
Thanks for your answer. I was already looking at WiX and tested Squirrel before. I just like the single executable option when using the publish feature, because it gives a more clear output instead of a great many files.
