### ISSUE TITLE
FFmpegDemuxer: no supported streams

### ISSUE THREAD

**Issue by jie-zhou-123** [chromelyapps/Chromely#382]
I am playing video file by rx-player and video tag  in CEF but it is not working. But when tried with same version of chrome it's work fine.
![image](https://user-images.githubusercontent.com/83751573/185870190-503682e8-2e07-4f64-bc05-da091773b12a.png)
![image](https://user-images.githubusercontent.com/83751573/185870295-927baf37-032b-467c-ba3c-3ed2f037010b.png)

**Comment by mattkol** [comment]
@jie-zhou-123 this is most likely a proprietary issue. 

These may help to highlight that:
https://www.magpcss.org/ceforum/viewtopic.php?f=17&t=18373
https://groups.google.com/g/cefpython/c/439zOnnHfP4

If you need further clarifications, you may raise an issue on CEF Forum - https://www.magpcss.org/ceforum/

Thanks.

**Comment by jie-zhou-123** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by jie-zhou-123** [comment]
@mattkol Thanks a lot
