### ISSUE TITLE
adding eto.forms library ?

### ISSUE THREAD

**Issue by PrestigeDevop** [chromelyapps/Chromely#385]
Hello , Is it possible to include Eto.forms with chromely.xplat ?
I prefer blazor but also any other project is okay , 
I'm  not sure how to boostrap the app  should I modify appbuilderbase.cs ?
  
https://github.com/picoe/Eto/issues/2296

**Comment by mattkol** [comment]
@PrestigeDevop if you mean Chromely and Eto.Forms as host. Certainly, but won't work out of the box, you may have to do some work. 

Background info - Eto.Forms was strongly considered to be Chromely host. But it was more work trying to peal off what was not needed. The plan as always been to make the hosts as thin as possible. So we had to do most of it from the base. Of course with help from other repos.

**Comment by PrestigeDevop** [comment]
> 

thanks for the replay , yes I meant to use Chromely and Eto forms as host and blazor  as frontend  . after reading [Meet WebWindow, a cross-platform webview library for .NET Core](https://blog.stevensanderson.com/2019/11/18/2019-11-18-webwindow-a-cross-platform-webview-for-dotnet-core/) , if the only concerns is app size I don't mind  it , but it shouldn't have deployment complexity .

**Comment by mattkol** [comment]
> was there any prototype build before ?

Good question. I think there was, I doubt it made it to a stage where I could keep it. So no, nothing kept and I have changed workstations since then.

The only prototype I still have on my machine is for https://github.com/andlabs/libui.
