### ISSUE TITLE
Chromely browser with miltiple tabs on Linux

### ISSUE THREAD

**Issue by christK9999** [chromelyapps/Chromely#386]
I want to implement a browser based on Xilium.CefGlue that works on Windows and on Linux I found a solution with Chromely. I implemented the Browser according to this Chromely [tutorial ](https://github.com/chromelyapps/Chromely/wiki/create-new-project-from-scratch)and it works fine on Windows and on Linux. Now I want to have more than one tabs. It seems to be possible, but chromely have to be extended as mentioned [here.](https://github.com/chromelyapps/Chromely)

I tried to use Avalonia and Chromely, but the are not compatible. I found this [question](https://github.com/chromelyapps/demo-projects/issues/6) talking about a "Chromely.CefGlue.Gtk.Linux.Demo"-Project but no code of that project.

Can someone help me please?

**Comment by mattkol** [comment]
@christK9999 

> Now I want to have more than one tabs. It seems to be possible, but chromely have to be extended

Yes, that is true, Chromely is a one-window framework.

 "Chromely.CefGlue.Gtk.Linux.Demo" is  based on [Chromely.CefGlue.Gtk.Linux](https://github.com/chromelyapps/Chromely.Legacy/tree/master/src/Chromely.CefGlue.Gtk) - old project that is not used anymore. If you want to work on extending [Chromely.CefGlue.Gtk.Linux](https://github.com/chromelyapps/Chromely.Legacy/tree/master/src/Chromely.CefGlue.Gtk), you can see the updated code here - [Chromely/NativeHosts/LinuxHost](https://github.com/chromelyapps/Chromely/tree/master/src/Chromely/NativeHosts/LinuxHost).

You can see related issues here:
https://github.com/chromelyapps/Chromely/issues/139
https://github.com/chromelyapps/Chromely/issues/185

But note that multi-tabs is not supported.

Thanks.

**Comment by christK9999** [comment]
Thanks you for your reply.
I'm trying to solve it using Gtk now

Thanks :)
