### ISSUE TITLE
App does not execute

### ISSUE THREAD

**Issue by Chebona** [chromelyapps/Chromely#389]
Dears,
I've started to write testing app (VS2022 Pro, .NET 6.0) based on Chromely 5.2.101.
All the tests I've made on Windows work normally. However, I cannot execute the app on Ubuntu (tested 18.04LTS and 20.04LTS, in both cases the Ubuntu OS is newly installed). On both versions, I've got the similar errors (see below). 

The runtime identifier is set to linux-x64.

Please, can you help me to resolve this problem? Thank you.

`
 $dotnet ChromelyTest.dll
On CefGlue child process launch arguments:
/proc/self/exe --type=gpu-process --no-sandbox --locales-dir-path=/home/radek/Predator/VSLinuxDbg/ChromelyTest/locales --log-severity=info --resources-dir-path=/home/radek/Predator/VSLinuxDbg/ChromelyTest --lang=en-US --user-data-dir=/home/radek/.config/cef_user_data --default-encoding=utf-8 --allow-file-access-from-files --allow-universal-access-from-files --disable-web-security --ignore-certificate-errors
On CefGlue child process launch arguments:

DevTools listening on ws://127.0.0.1:20480/devtools/browser/3f40e225-4306-42f8-82d1-c6129d3678dc
/proc/self/exe --type=utility --utility-sub-type=network.mojom.NetworkService --lang=en-US --service-sandbox-type=none --no-sandbox --locales-dir-path=/home/radek/Predator/VSLinuxDbg/ChromelyTest/locales --log-severity=info --resources-dir-path=/home/radek/Predator/VSLinuxDbg/ChromelyTest --lang=en-US --user-data-dir=/home/radek/.config/cef_user_data --default-encoding=utf-8 --allow-file-access-from-files --allow-universal-access-from-files --disable-web-security --ignore-certificate-errors
Could not execute because the specified command or file was not found.
Possible reasons for this include:
  * You misspelled a built-in dotnet command.
  * You intended to execute a .NET program, but dotnet---type=utility does not exist.
  * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.Could not execute because the specified command or file was not found.
Possible reasons for this include:
  * You misspelled a built-in dotnet command.
  * You intended to execute a .NET program, but dotnet---type=gpu-process does not exist.
  * You in
tended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.
[1125/113345.880120:ERROR:gpu_process_host.cc(974)] GPU process exited unexpectedly: exit_code=256
[1125/113345.880194:WARNING:gpu_process_host.cc(1279)] The GPU process has crashed 1 time(s)
[1125/113345.880879:ERROR:network_service_instance_impl.cc(978)] Network service crashed, restarting service.
On CefGlue child process launch arguments:
/proc/self/exe --type=utility --utility-sub-type=network.mojom.NetworkService --lang=en-US --service-sandbox-type=none --no-sandbox --locales-dir-path=/home/radek/Predator/VSLinuxDbg/ChromelyTest/locales --log-severity=info --resources-dir-path=/home/radek/Predator/VSLinuxDbg/ChromelyTest --lang=en-US --user-data-dir=/home/radek/.config/cef_user_data --default-encoding=utf-8 --allow-file-access-from-files --allow-universal-access-from-files --disable-web-security --ignore-certificate-errors
On CefGlue child process launch arguments:
/proc/self/exe --type=gpu-process --no-sandbox --locales-dir-path=/home/radek/Predator/VSLinuxDbg/ChromelyTest/locales --log-severity=info --resources-dir-path=/home/radek/Predator/VSLinuxDbg/ChromelyTest --lang=en-US --user-data-dir=/home/radek/.config/cef_user_data --default-encoding=utf-8 --allow-file-access-from-files --allow-universal-access-from-files --disable-web-security --ignore-certificate-errors
On CefGlue child process launch arguments:
/proc/self/exe --type=renderer --locales-dir-path=/home/radek/Predator/VSLinuxDbg/ChromelyTest/locales --log-severity=info --resources-dir-path=/home/radek/Predator/VSLinuxDbg/ChromelyTest --user-data-dir=/home/radek/.config/cef_user_data --default-encoding=utf-8 --allow-file-access-from-files --allow-universal-access-from-files --disable-web-security --ignore-certificate-errors
On CefGlue child process launch arguments:
/proc/self/exe --type=renderer --locales-dir-path=/home/radek/Predator/VSLinuxDbg/ChromelyTest/locales --log-severity=info --resources-dir-path=/home/radek/Predator/VSLinuxDbg/ChromelyTest --user-data-dir=/home/radek/.config/cef_user_data --default-encoding=utf-8 --allow-file-access-from-files --allow-universal-access-from-files --disable-web-security --ignore-certificate-errors
Could not execute because the specified command or file was not found.
Possible reasons for this include:
  * You misspelled a built-in dotnet command.
  * You intended to execute a .NET program, but dotnet---type=utility does not exist.
  * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.
[1125/113346.071511:ERROR:network_service_instance_impl.cc(978)] Network service crashed, restarting service.
On CefGlue child process launch arguments:
/proc/self/exe --type=utility --utility-sub-type=network.mojom.NetworkService --lang=en-US --service-sandbox-type=none --no-sandbox --locales-dir-path=/home/radek/Predator/VSLinuxDbg/ChromelyTest/locales --log-severity=info --resources-dir-path=/home/radek/Predator/VSLinuxDbg/ChromelyTest --lang=en-US --user-data-dir=/home/radek/.config/cef_user_data --default-encoding=utf-8 --allow-file-access-from-files --allow-universal-access-from-files --disable-web-security --ignore-certificate-errors
Could not execute because the specified command or file was not found.
Possible reasons for this include:
  * You misspelled a built-in dotnet command.
  * You intended to execute a .NET program, but dotnet---type=renderer does not exist.
  * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.
Could not execute because the specified command or file was not found.
Possible reasons for this include:
  * You misspelled a built-in dotnet command.
  * You intended to execute a .NET program, but dotnet---type=gpu-process does not exist.
  * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.
[1125/113346.159912:ERROR:gpu_process_host.cc(974)] GPU process exited unexpectedly: exit_code=256
[1125/113346.160025:WARNING:gpu_process_host.cc(1279)] The GPU process has crashed 2 time(s)
On CefGlue child process launch arguments:
/proc/self/exe --type=gpu-process --no-sandbox --locales-dir-path=/home/radek/Predator/VSLinuxDbg/ChromelyTest/locales --log-severity=info --resources-dir-path=/home/radek/Predator/VSLinuxDbg/ChromelyTest --lang=en-US --user-data-dir=/home/radek/.config/cef_user_data --default-encoding=utf-8 --allow-file-access-from-files --allow-universal-access-from-files --disable-web-security --ignore-certificate-errors
Could not execute because the specified command or file was not found.
Possible reasons for this include:
  * You misspelled a built-in dotnet command.
  * You intended to execute a .NET program, but dotnet---type=renderer does not exist.
  * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.
Could not execute because the specified command or file was not found.
Possible reasons for this include:
  * You misspelled a built-in dotnet command.
  * You intended to execute a .NET program, but dotnet---type=utility does not exist.
  * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.
[1125/113346.253177:ERROR:network_service_instance_impl.cc(978)] Network service crashed, restarting service.
On CefGlue child process launch arguments:
/proc/self/exe --type=utility --utility-sub-type=network.mojom.NetworkService --lang=en-US --service-sandbox-type=none --no-sandbox --locales-dir-path=/home/radek/Predator/VSLinuxDbg/ChromelyTest/locales --log-severity=info --resources-dir-path=/home/radek/Predator/VSLinuxDbg/ChromelyTest --lang=en-US --user-data-dir=/home/radek/.config/cef_user_data --default-encoding=utf-8 --allow-file-access-from-files --allow-universal-access-from-files --disable-web-security --ignore-certificate-errors
Could not execute because the specified command or file was not found.
Possible reasons for this include:
  * You misspelled a built-in dotnet command.
  * You intended to execute a .NET program, but dotnet---type=gpu-process does not exist.
  * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.
[1125/113346.315756:ERROR:gpu_process_host.cc(974)] GPU process exited unexpectedly: exit_code=256
[1125/113346.315831:WARNING:gpu_process_host.cc(1279)] The GPU process has crashed 3 time(s)
On CefGlue child process launch arguments:
/proc/self/exe --type=gpu-process --no-sandbox --locales-dir-path=/home/radek/Predator/VSLinuxDbg/ChromelyTest/locales --log-severity=info --resources-dir-path=/home/radek/Predator/VSLinuxDbg/ChromelyTest --lang=en-US --user-data-dir=/home/radek/.config/cef_user_data --default-encoding=utf-8 --allow-file-access-from-files --allow-universal-access-from-files --disable-web-security --ignore-certificate-errors
Could not execute because the specified command or file was not found.
Possible reasons for this include:
  * You misspelled a built-in dotnet command.
  * You intended to execute a .NET program, but dotnet---type=utility does not exist.
  * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.
[1125/113346.383967:ERROR:network_service_instance_impl.cc(978)] Network service crashed, restarting service.
On CefGlue child process launch arguments:
/proc/self/exe --type=utility --utility-sub-type=network.mojom.NetworkService --lang=en-US --service-sandbox-type=none --no-sandbox --locales-dir-path=/home/radek/Predator/VSLinuxDbg/ChromelyTest/locales --log-severity=info --resources-dir-path=/home/radek/Predator/VSLinuxDbg/ChromelyTest --lang=en-US --user-data-dir=/home/radek/.config/cef_user_data --default-encoding=utf-8 --allow-file-access-from-files --allow-universal-access-from-files --disable-web-security --ignore-certificate-errors
Could not execute because the specified command or file was not found.
Possible reasons for this include:
  * You misspelled a built-in dotnet command.
  * You intended to execute a .NET program, but dotnet---type=gpu-process does not exist.
  * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.
On CefGlue child process launch arguments:
/proc/self/exe --type=gpu-process --no-sandbox --locales-dir-path=/home/radek/Predator/VSLinuxDbg/ChromelyTest/locales --log-severity=info --resources-dir-path=/home/radek/Predator/VSLinuxDbg/ChromelyTest --lang=en-US --user-data-dir=/home/radek/.config/cef_user_data --default-encoding=utf-8 --allow-file-access-from-files --allow-universal-access-from-files --disable-web-security --ignore-certificate-errors
Could not execute because the specified command or file was not found.
Possible reasons for this include:
  * You misspelled a built-in dotnet command.
  * You intended to execute a .NET program, but dotnet---type=utility does not exist.
  * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.
[1125/113346.515430:ERROR:network_service_instance_impl.cc(978)] Network service crashed, restarting service.
On CefGlue child process launch arguments:
/proc/self/exe --type=utility --utility-sub-type=network.mojom.NetworkService --lang=en-US --service-sandbox-type=none --no-sandbox --locales-dir-path=/home/radek/Predator/VSLinuxDbg/ChromelyTest/locales --log-severity=info --resources-dir-path=/home/radek/Predator/VSLinuxDbg/ChromelyTest --lang=en-US --user-data-dir=/home/radek/.config/cef_user_data --default-encoding=utf-8 --allow-file-access-from-files --allow-universal-access-from-files --disable-web-security --ignore-certificate-errors
Could not execute because the specified command or file was not found.
Possible reasons for this include:
  * You misspelled a built-in dotnet command.
  * You intended to execute a .NET program, but dotnet---type=gpu-process does not exist.
  * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.
[1125/113346.595831:ERROR:gpu_process_host.cc(974)] GPU process exited unexpectedly: exit_code=256
[1125/113346.595869:WARNING:gpu_process_host.cc(1279)] The GPU process has crashed 4 time(s)
On CefGlue child process launch arguments:
/proc/self/exe --type=gpu-process --no-sandbox --locales-dir-path=/home/radek/Predator/VSLinuxDbg/ChromelyTest/locales --log-severity=info --resources-dir-path=/home/radek/Predator/VSLinuxDbg/ChromelyTest --lang=en-US --user-data-dir=/home/radek/.config/cef_user_data --default-encoding=utf-8 --allow-file-access-from-files --allow-universal-access-from-files --disable-web-security --ignore-certificate-errors
Could not execute because the specified command or file was not found.
Possible reasons for this include:
  * You misspelled a built-in dotnet command.
  * You intended to execute a .NET program, but dotnet---type=utility does not exist.
  * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.
[1125/113346.658543:ERROR:network_service_instance_impl.cc(978)] Network service crashed, restarting service.
On CefGlue child process launch arguments:
/proc/self/exe --type=utility --utility-sub-type=network.mojom.NetworkService --lang=en-US --service-sandbox-type=none --no-sandbox --locales-dir-path=/home/radek/Predator/VSLinuxDbg/ChromelyTest/locales --log-severity=info --resources-dir-path=/home/radek/Predator/VSLinuxDbg/ChromelyTest --lang=en-US --user-data-dir=/home/radek/.config/cef_user_data --default-encoding=utf-8 --allow-file-access-from-files --allow-universal-access-from-files --disable-web-security --ignore-certificate-errors
Could not execute because the specified command or file was not found.
Possible reasons for this include:
  * You misspelled a built-in dotnet command.
  * You intended to execute a .NET program, but dotnet---type=gpu-process does not exist.
  * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.
[1125/113346.739833:ERROR:gpu_process_host.cc(974)] GPU process exited unexpectedly: exit_code=256
[1125/113346.739900:WARNING:gpu_process_host.cc(1279)] The GPU process has crashed 5 time(s)
On CefGlue child process launch arguments:
/proc/self/exe --type=gpu-process --no-sandbox --locales-dir-path=/home/radek/Predator/VSLinuxDbg/ChromelyTest/locales --log-severity=info --resources-dir-path=/home/radek/Predator/VSLinuxDbg/ChromelyTest --lang=en-US --user-data-dir=/home/radek/.config/cef_user_data --default-encoding=utf-8 --allow-file-access-from-files --allow-universal-access-from-files --disable-web-security --ignore-certificate-errors
Could not execute because the specified command or file was not found.
Possible reasons for this include:
  * You misspelled a built-in dotnet command.
  * You intended to execute a .NET program, but dotnet---type=utility does not exist.
  * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.
[1125/113346.792768:ERROR:network_service_instance_impl.cc(978)] Network service crashed, restarting service.
On CefGlue child process launch arguments:
/proc/self/exe --type=utility --utility-sub-type=network.mojom.NetworkService --lang=en-US --service-sandbox-type=none --no-sandbox --locales-dir-path=/home/radek/Predator/VSLinuxDbg/ChromelyTest/locales --log-severity=info --resources-dir-path=/home/radek/Predator/VSLinuxDbg/ChromelyTest --lang=en-US --user-data-dir=/home/radek/.config/cef_user_data --default-encoding=utf-8 --allow-file-access-from-files --allow-universal-access-from-files --disable-web-security --ignore-certificate-errors
Could not execute because the specified command or file was not found.
Possible reasons for this include:
  * You misspelled a built-in dotnet command.
  * You intended to execute a .NET program, but dotnet---type=gpu-process does not exist.
  * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.
On CefGlue child process launch arguments:
/proc/self/exe --type=gpu-process --no-sandbox --locales-dir-path=/home/radek/Predator/VSLinuxDbg/ChromelyTest/locales --log-severity=info --resources-dir-path=/home/radek/Predator/VSLinuxDbg/ChromelyTest --lang=en-US --user-data-dir=/home/radek/.config/cef_user_data --default-encoding=utf-8 --allow-file-access-from-files --allow-universal-access-from-files --disable-web-security --ignore-certificate-errors
Could not execute because the specified command or file was not found.
Possible reasons for this include:
  * You misspelled a built-in dotnet command.
  * You intended to execute a .NET program, but dotnet---type=utility does not exist.
  * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.
[1125/113346.939843:ERROR:network_service_instance_impl.cc(978)] Network service crashed, restarting service.
On CefGlue child process launch arguments:
/proc/self/exe --type=utility --utility-sub-type=network.mojom.NetworkService --lang=en-US --service-sandbox-type=none --no-sandbox --locales-dir-path=/home/radek/Predator/VSLinuxDbg/ChromelyTest/locales --log-severity=info --resources-dir-path=/home/radek/Predator/VSLinuxDbg/ChromelyTest --lang=en-US --user-data-dir=/home/radek/.config/cef_user_data --default-encoding=utf-8 --allow-file-access-from-files --allow-universal-access-from-files --disable-web-security --ignore-certificate-errors
Could not execute because the specified command or file was not found.
Possible reasons for this include:
  * You misspelled a built-in dotnet command.
  * You intended to execute a .NET program, but dotnet---type=gpu-process does not exist.
  * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.
[1125/113347.035262:ERROR:gpu_process_host.cc(974)] GPU process exited unexpectedly: exit_code=256
[1125/113347.035299:WARNING:gpu_process_host.cc(1279)] The GPU process has crashed 6 time(s)
[1125/113347.035321:FATAL:gpu_data_manager_impl_private.cc(447)] GPU process isn't usable. Goodbye.
Could not execute because the specified command or file was not found.
Possible reasons for this include:
  * You misspelled a built-in dotnet command.
  * You intended to execute a .NET program, but dotnet---type=utility does not exist.
  * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.
Trace/breakpoint trap (core dumped)
`

**Comment by mattkol** [comment]
@Chebona 

It is not quite obvious what you are trying to do.
From the message you shared -
> Could not execute because the specified command or file was not found.
Possible reasons for this include:

Seems like dotnet is not installed yet on your workstation

Are you able to run the [Chromely.CrossPlat](https://github.com/chromelyapps/demo-projects/tree/master/regular-chromely/Chromely.CrossPlat) demo on Ubuntu? You can see more info in the [guide here](https://github.com/chromelyapps/demo-projects#running-the-demos).

**Comment by Chebona** [comment]
Hello mattkol,
thank you for your answer.

Yes, .NET 6.0.403 is installed. I use it for my other applications. All the program I write under Windows (in Visual Studio), where the program is also compiled and the output is copied to Ubuntu. In this way I write all my code with no problems.
And in this way I've also compiled and copied Chromely app (the Cross-plarfom example was also tested without success).

However, when I try to compile your Cross-plarfom example directly under Ubuntu, the program was successfully compiled and executed. 
So, the problem is with the compilation under Windows.
Is there any way how to compile it under Windows? I write/compile all the apps under Windows and use remote debugging if the program is also executed under Linux?

Thank you.

**Comment by mattkol** [comment]
@Chebona 

> So, the problem is with the compilation under Windows.

In Windows, I usually compile using Visual Studio. I am currently using Visual Studio 2022. Visual Studio Code, JetBrains Rider and other IDEs should work too.

I think it is best to compile in any IDE of your choice and we can see if the issues you get in that process can be addressed.

Thanks.
