### ISSUE TITLE
netcore2.0 on ubuntu 18.10

### ISSUE THREAD

**Issue by FrankPfattheicher** [chromelyapps/Chromely#65]
Hello,

i did not manage to run the sample as a self contained netcore 2.0 application under ubuntu 18.10.

Did someone have any idea why this error messages are comming?

frank@u18work:~/ICT Baden/Chromely/src/Demos/Chromely.CefGlue.Gtk.Linux.Demo/bin/Release/netcoreapp2.0/linux-x64/publish$ ./cefglue_gtk_linux_demo 
2019-01-17 13:56:55.616 [INFO] CefRuntime.ExecuteProcess() returns -1
[0117/135655.910138:ERROR:gpu_process_transport_factory.cc(1026)] Lost UI shared context.

DevTools listening on ws://127.0.0.1:20480/devtools/browser/40aafc96-5e81-40eb-a887-73341669e29e
[0117/135656.124559:ERROR:service_manager_context.cc(250)] Attempting to run unsupported native service: /home/frank/ICT Baden/Chromely/src/Demos/Chromely.CefGlue.Gtk.Linux.Demo/bin/Release/netcoreapp2.0/linux-x64/publish/content_renderer.service
[0117/135656.252285:ERROR:sandbox_linux.cc(378)] InitializeSandbox() called with multiple threads in process gpu-process.
frank@u18work:~/ICT Baden/Chromely/src/Demos/Chromely.CefGlue.Gtk.Linux.Demo/bin/Release/netcoreapp2.0/linux-x64/publish$

**Comment by FrankPfattheicher** [comment]
I also tried an own sample with the following options:

                .WithCustomSetting(CefSettingKeys.MultiThreadedMessageLoop, false)
                .WithCustomSetting(CefSettingKeys.SingleProcess, true)
                .WithCustomSetting(CefSettingKeys.NoSandbox, true)
            
                .WithCommandLineArg("disable-extensions", "1")
                .WithCommandLineArg("disable-gpu", "1")
                .WithCommandLineArg("disable-gpu-compositing", "1")
                .WithCommandLineArg("disable-smooth-scrolling", "1")
                .WithCommandLineArg("no-sandbox", "1");

Does not work either.

**Comment by mattkol** [comment]
For Linux, as it is now, you have to publish it. 

An alternative is to have and configure a subprocess  like what CefSharp has - [please see here](https://github.com/cefsharp/CefSharp/tree/30ee538ce0e0d1d33ed838665758ec2061165224/CefSharp.BrowserSubprocess). I just started looking into migrating that to Chromely.

**Comment by FrankPfattheicher** [comment]
Of cause i published it...
Did you test it with the lates v68 CEF?

The subprocess attempt results in an more complex process structure at runtime - i do not prefer this.

**Comment by mattkol** [comment]
No I did not. Not yet. @WSpadaro was helping with this.

Please see issues:  https://github.com/mattkol/Chromely/issues/48#issue-379879978 and https://github.com/mattkol/Chromely/issues/60#issue-391818630

My last comment on https://github.com/mattkol/Chromely/issues/60#issue-391818630 may be most helpful as a starting point.

**Comment by FrankPfattheicher** [comment]
adding **`.WithCommandLineArg("no-zygote", "1") `** did the job :-)

**Comment by mattkol** [comment]
@FrankPfattheicher great job!!!
So this works for v68/70?

**Comment by FrankPfattheicher** [comment]
@mattkol  It is using the version, the current CefGlue.Gtk is referencing.
Linux-x64, CEF version 3440 => cef_binary_3.3440.1806.g65046b7_linux64 => chromium v68.

**Comment by mattkol** [comment]
@FrankPfattheicher that is really really nice! I am sure it will work for v70 since the SingleProcess option was switched off from v68. Are you using a VM to test? Looks like gpu is kind of funny with VMs.
I will try testing over the weekend.

I kindda have MacOS working using Libui but I still had headache with Linux, when I have some bandwidth I may be able to figure out what is going on using the options you set. Certainly using Libui is not ready for prime-time.

Real progress!
Thanks.
