### ISSUE TITLE
Request access to contribute to the wiki

### ISSUE THREAD

**Issue by Fiahblade** [chromelyapps/Chromely#70]
Hi, love what you are doing! Chromely is truly amazing!
But it could use a solid documentation so everyone can easily get started. 

So hereby I'm requesting access to contribute on the wiki section.

Kind Regards

**Comment by Fiahblade** [comment]
Or maybe this isn't possible, personally I don't use GitHub that much.

**Comment by mattkol** [comment]
_Hi, love what you are doing! Chromely is truly amazing!_
Thank you.

Contributions are always welcome, I can send the request for you to join the [team](https://github.com/orgs/chromelyapps/people).  

You had: **EDIT: Nope, seems like GitHub Wikis aren't as powerful as I thought.** Does that mean, you changed your mind?

Please let me know.

**Comment by Fiahblade** [comment]
Oh no, I didn't change my mind. And yes joining the teams sounds great. I'd love to help out on a regular basis.

**Comment by mattkol** [comment]
Invitation sent,
Thanks.
