### ISSUE TITLE
ChromelyRequest.Parameters using the default LitJson Serializer omits "Values" from cefQuery calls.

### ISSUE THREAD

**Issue by Fydar** [chromelyapps/Chromely#77]
When making a cefQuery request and passing in a JavaScript object into the parameters field using the following JavaScript code:

```
var request = {
    "method": "GET",
    "url": "/controller/action",
    "parameters": { Asset: "Parameter Value" },
    "postData": null,
};
window.cefQuery({
                request: JSON.stringify(request)
```

The `ChromelyRequest.Parameters` property in the associated controller omits the `Values`. Below is a console output of all of the fields:

```
Count: 1
IsArray: False
IsBoolean: False
IsDouble: False
IsInt: False
IsLong: False
IsObject: True
IsString: False
Keys: System.Collections.Generic.Dictionary`2+KeyCollection[System.String,LitJson.JsonData]
```

However, `ChromelyRequest.PostData` does contain valid Json for the request.

`{"method":"GET","url":"/controller/action","parameters":{"Asset":"Parameter Value"},"postData":null}`

## Setup

Using `Chromely.CefGlue.Winapi` Version `66.0.0`

**Comment by Fiahblade** [comment]
@Fydar Unfortunately it looks like that JSON is invalid, you are missing some quotation marks around _Asset_

"parameters": { Asset: "Parameter Value" },
"parameters": { **"**Asset**"**: "Parameter Value" },

If it can't convert the JSON it returns null, hence why the `ChromelyRequest.Parameter` is null.

**Comment by Fydar** [comment]
@Fiahblade What I was passing into `parameters` was a JavaScript object, hence it doesn't require quotation marks around `Asset`. With your suggested change, the results are unchanged.

**Comment by Fiahblade** [comment]
@Fydar Ah I see, when parsing the JSON it came back  as 'invalid' and the code uses the default value null in that case, so I assumed that was issue, my bad.

Or is it possible you have registered your own handler?

**Comment by mattkol** [comment]
@Fiahblade I just  started looking into it.

Looks like LitJson is now in NETStandard. I want to merge that first then fix the issue. Initially I had to do the conversion to NETStandard. 

I am looking into adding a Raw json property to ChromelyRequest so that it will give developers more flexibility to use any Json mapper they want.

**Comment by mattkol** [comment]
Fixed.

ChromelyRequest now has a new property - RawJson.
This is only used for CefGlue cefQuery.
