### ISSUE TITLE
Loading wrong bitness libcef

### ISSUE THREAD

**Issue by ststeiger** [chromelyapps/Chromely#79]
The following setup:
Console-Application (.NET Core 2.1 or 2.2) 
Nuget: Chromely.CefGlue.Winapi
Build: AnyCpu
Machine: 64-Bit 

This loads the 32-Bit dlls. 
Then it fails with 

> incorrect format. (Exception from HRESULT: 0x8007000B)
> at Xilium.CefGlue.Interop.libcef.api_hash(Int32 entry)
> at Xilium.CefGlue.CefRuntime.CheckVersionByApiHash()
> at Xilium.CefGlue.CefRuntime.CheckVersion()
> at Xilium.CefGlue.CefRuntime.Load(String path)
> at Xilium.CefGlue.CefRuntime.Load()
> at RainbowMage.HtmlRenderer.Rendere

If I switch the application to 32-Bit Mode, then Visual Studio fails (Visual Studio bug, i presume). 

I assume it's either downloading the CefGlue from spotify, or it loads them from embedded resources. <br />
Judging from the time taken, I assume it's loading from embedded resources. <br />

It should look at System.IntPtr.Size*8 and load the correct-bitness libcef. 

I overwrote the cef-dlls with the correct-bitness version from spotify, and it started working immediately...

The following code
```
        static int Main(string[] args)
        {
            System.Console.WriteLine($"{System.IntPtr.Size * 8}-Bit"); // 64-Bit 

            var startUrl = "https://google.com";

            var config = ChromelyConfiguration
                           .Create()
                           .WithHostMode(WindowState.Normal, true)
                           .WithHostTitle("chromely")
                           .WithHostIconFile("chromely.ico")
                           .WithAppArgs(args)
                           .WithHostSize(1000, 600)
                           .WithStartUrl(startUrl);

            using (var window = new CefGlueBrowserWindow(config))
            {
                return window.Run(args);
            }
        }
```

**Comment by mattkol** [comment]
@stseiger with the current cef download process you have to specify the CPU for the build - x64 or x86. But you are right if none is specified, it should fall back to the OS bitness.

We have a new approach for the cef download and this will be considered.

Thanks for pointing this out.

**Comment by ststeiger** [comment]
@mattkol: The OS bitness might be different then the program bitness. Just FYI. What matters is the process bitness.

**Comment by mattkol** [comment]
@stseiger the new approach will take care of the process bitness check. For the current, it must be specified.

What I was saying is if process bitness check fails (should not happen) it will fall back to OS bitness. In reality CefGlue will allow only Cef binaries of the process bitness. I do not think it cares about the OS bitness, but something that needs to be verified.

**Comment by ststeiger** [comment]
I noticed, I don't even need Chromely. 
But it's cool, using CefGlue alone, I can now convert HTML+SVG to VectorPDF/RasterImage.
Works for any .NET Framwork, including .NET-Core. 
https://github.com/ststeiger/CefGlue_NetStandard
