### ISSUE TITLE
Chromely.CefGlue.Gtk.Linux.Demo

### ISSUE THREAD

**Issue by ganggbang** [chromelyapps/Chromely#80]
Hello,
Running Chromely.CefGlue.Gtk.Linux.Demo or @FrankPfattheicher sample (https://github.com/FrankPfattheicher/stonehenge.Chromely) in VM Debian 9 using  JetBrains Rider or command line .NET core 2.1. and I've faced with:

> icu_util.cc(133) invalid file descriptor to icu data received

Perhaps I am missing something...

**Comment by FrankPfattheicher** [comment]
I am out of office until monday - i will look at this then...

**Comment by FrankPfattheicher** [comment]
Try this:
http://chromely.org/cefglue_gtk_linux_demo.zip

packed using
`dotnet publish -r linux-x64 --self-contained`

additional option
`.WithCommandLineArg("no-zygote", "1")`

**Comment by ganggbang** [comment]
Thank you @FrankPfattheicher.

./cefglue_gtk_linux_demo working but how to build my binary file from sources?

I'm using this option in code
> .WithCommandLineArg("no-zygote", "1")

**Comment by FrankPfattheicher** [comment]
@ganggbang 
I just used
`dotnet publish -r linux-x64 --self-contained`
to build and pack the application.
After this you have to copy the CEF binaries to the destination folder.

**Comment by FrankPfattheicher** [comment]
@ganggbang now i get your error ;-)
This is trying to run using mono. I never tried this ...
I will look at this (a little bit)
For long time we do support .net Core only...

**Comment by mattkol** [comment]
This is now superseded by .NET Core 3 - https://github.com/chromelyapps/Chromely/wiki/Migration-to-.NET-Core-3-and-MacOS-Support
