### ISSUE TITLE
Message Router(cefglue.winapi) Return Allways Same Response...

### ISSUE THREAD

**Issue by progsung** [chromelyapps/Chromely#82]
Hi I think I found a error about MessageRouter(cefglue.winapi).
I tested  [demo-project](https://github.com/chromelyapps/demo-projects/tree/master/regular-chromely/Chromely.CefGlue.Winapi.netCoreDemo) at version 68

            //original
           var request = {
                "method": "GET",
                "url": "/democontroller/movies",
                "parameters": null,
                "postData": null,
            };
            window.cefQuery({
                request: JSON.stringify(request),
                onSuccess: function (response) {
                    messageRouterResult1(response);
                }, onFailure: function (err, msg) {
                    console.log(err, msg);
                }
            });
            // change url
           var request = {
                "method": "GET",
                "url": "/democontroller/nomovies",   //Change url!!!!
                "parameters": null,
                "postData": null,
            };
            window.cefQuery({
                request: JSON.stringify(request),
                onSuccess: function (response) {
                    messageRouterResult1(response);
                }, onFailure: function (err, msg) {
                    console.log(err, msg);
                }
            });

return same results ...

**Comment by progsung** [comment]
It seems to be responding to any url. Even using url that does not exist ...
```
  //Chromely.CefGlue.Winapi.netCoreDemo\Controllers\DemoController.cs
  namespace Chromely.CefGlue.Winapi.netCoreDemo.Controllers
  {
    //...
    [ControllerProperty(Name = "DemoController", Route = "democontroller")]
    public class DemoController : ChromelyController
    {
        public DemoController()
        {
            RegisterGetRequest("/democontroller/movies", GetMovies);
            RegisterPostRequest("/democontroller/movies", SaveMovies);
        }
        // ....
```

**Comment by mattkol** [comment]
@progsung well, that will be interesting. This has not changed in a long time.

It will be difficult to confirm by someone else without the actual html/javascript code you are using. Please paste or attach the html. 

Did you ensure that the result table is reset for the invalid url result?:

````csharp
 $('#messageRouterResult1 tbody').html('');
````


Also please ensure you put a breakpoint in GetMovies action/method to ensure that the invalid url actually gets there.

**Comment by progsung** [comment]
I printed the log to the console and confirmed that the controller method was actually called.

**Comment by mattkol** [comment]
@progsung I just reproduced it too. Thanks for finding that. I will look at it closely later in the evening.

**Comment by mattkol** [comment]
@progsung I found what that is. 
https://github.com/chromelyapps/Chromely/commit/bdb6945e2ec835b0448bf1ea63a8cb7cc5418cdb
You can please get the latest and use this change, while I check closely later.

**Comment by progsung** [comment]
Latest changed so many things(namespace, cef 70.0 and etc..)!
Fortunately, I was able to test it. When checked only in my program, it seems fixed.
Thanks a lot @mattkol for the quick fix!

**Comment by mattkol** [comment]
@progsung was a good catch!
Thanks.
I will close this now.
