### ISSUE TITLE
Cross-Origin Read Blocking (CORB) blocked cross-origin response

### ISSUE THREAD

**Issue by anmaitrannguyen** [chromelyapps/Chromely#85]
I'm having issues when call API with Axios in Vue App.
The call is success, but the response is empty.
After some research, I found that this is feature of  Chromium.
Is it possible to have an option to disable WebSecurity of Chromium?
BrowserWindow have a setting WebSecurity:
https://github.com/cefsharp/CefSharp/blob/3423670740532e5756b2d92fdedc74bb59aac6fd/CefSharp/IBrowserSettings.cs

**Comment by mattkol** [comment]
@anmaitrannguyen not sure what Chromium version you are using.

For Chromely current versions - (CefSharp v71, CefGlue v70) the security is disabled. 
https://github.com/chromelyapps/Chromely/blob/30bd58a484f70e445536367a3428ab61b493ddc1/src/Chromely.CefGlue/Browser/CefGlueBrowser.cs#L202
https://github.com/chromelyapps/Chromely/blob/a9062bb6302b7b65173674636325e4934bb030c1/src/Chromely.CefSharp.Winapi/Browser/ChromiumWebBrowser.cs#L348

If you are using older versions of Chromely. This is not needed. If you need it, you may have to do it manually.

No formal release yet, you may have to get the latest code or try the [demos](https://github.com/chromelyapps/demo-projects/tree/master/regular-chromely).

Please let us know if you need more info.

**Comment by mattkol** [comment]
@anmaitrannguyen  the Ajax Demo post is usually the test for this.
![ajax_demo_post](https://user-images.githubusercontent.com/18384207/56578194-9d49c980-6592-11e9-9465-f497ca602102.png)

**Comment by anmaitrannguyen** [comment]
Hi @mattkol ,
I have modify my BE to allow CORS, and the request has worked.

**Comment by MohammedHameedullahBaig** [comment]
Hi @mattkol we are using angular chromely, even for us status is 200 but response is blocked by CORB, we have 5.0.77, but we are not using cefSharp
