### ISSUE TITLE
The package tried to add a framework reference to System.Web which was not found in the GAC.

### ISSUE THREAD

**Issue by cyanidee** [chromelyapps/Chromely#87]
I get this error while trying to get Chromely.CefSharp.Winapi from NuGet from within Visual Studio 2017. Both my project and solution platform is set to x86. I have installed Winapi and Chromely.Core using Nuget, that's the only package I failed fetching.

**Comment by mattkol** [comment]
@cyanidee I am not able to look closely at the moment.
What happens if you add the dlls directly?

**Comment by cyanidee** [comment]
Right now I tried to pull binaries from repo:
- Created new project
- Added CefSharp.Common and CefSharp.WinForms using NuGet
- Referenced Chromely.Core and Chromely.CefSharp.Winapi dll's
- Built the project with both project and solution platform set to x86

Everything compiled nicely, but at the runtime i get that:
```
2019-04-25 17:38:27.333 [ERROR] Oops! Something went wrong.     Method 'get_IsDisposed' in type 'Chromely.CefSharp.Winapi.Browser.ChromiumWebBrowser' from assembly 'Chromely.CefSharp.Winapi, Version=67.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation in Chromely.CefSharp.Winapi.BrowserWindow.Window..ctor(HostBase application, ChromelyConfiguration hostConfig, CefSettings settings)
   w Chromely.CefSharp.Winapi.BrowserWindow.CefSharpBrowserWindow.CreateMainView(CefSettings settings)
   w Chromely.CefSharp.Winapi.BrowserWindow.HostBase.RunInternal(String[] args)
   w Chromely.CefSharp.Winapi.BrowserWindow.HostBase.Run(String[] args)```

**Comment by mattkol** [comment]
@cyanidee you are likely missing Winapi.dll.  You can add that using nuget. CefSharp.WinForms not required. 

Please see guide - https://github.com/chromelyapps/Chromely/wiki/Getting-Started-CefSharp-Winapi
