### ISSUE TITLE
Error - A callback was made on a garbage collected delegate of type 'WinApi!WinApi.User32.WindowProc::Invoke

### ISSUE THREAD

**Issue by RupertAvery** [chromelyapps/Chromely#90]
I am making a series of web requests using HttpClient.GetAsync(), as part of an automation process (login to a site, navigate to a page, retrieve data) 

```
using (var httpResponse = await _client.GetAsync(url))
```

HttpClient instance is reused between calls, 

The first call goes through without problems, but the second call throws the error 

```
A callback was made on a garbage collected delegate of type 'WinApi!WinApi.User32.WindowProc::Invoke'. 
```

This code works fine outside Chromely.

**Comment by mattkol** [comment]
@RupertAvery it will be nice to know where this is happening. Is it possible you share a pseudo code or so of where this is happening?

**Comment by RupertAvery** [comment]
To replicate I added some code to the demo:

The httpClient is only created once in the constructor. Reusing HttpClient is the accepted practice, and in the service I am using it in, it is also only created once and reused for each request.

```
        HttpClient httpClient;

        public DemoController()
        {
            httpClient = new HttpClient();
             ...
        }

        private ChromelyResponse GetMovies(ChromelyRequest request)
        {
            List<MovieInfo> movieInfos = new List<MovieInfo>();
            string assemblyName = typeof(MovieInfo).Assembly.GetName().Name;

            using (var httpResponse = httpClient.GetAsync("http://www.google.com").Result)
            {
            }
            using (var httpResponse = httpClient.GetAsync("http://www.google.com").Result)
            {
            }
            using (var httpResponse = httpClient.GetAsync("http://www.google.com").Result)
            {
            }

...
```

Upon exit of the method, the exception is thrown from `Program.cs` at `return window.Run(args); `

```
Managed Debugging Assistant 'CallbackOnCollectedDelegate' : 'A callback was made on a garbage collected delegate of type 'WinApi!WinApi.User32.WindowProc::Invoke'. This may cause application crashes, corruption and data loss. When passing delegates to unmanaged code, they must be kept alive by the managed application until it is guaranteed that they will never be called.'
```

It will also happen if you only have 1 http request in the method. The first time you execute the method, it will work. The second call will throw the exception.

**Comment by RupertAvery** [comment]
I was using the demo app code which used older versions of the libraries and Cef. After using the latest source and latest Cef  the problem seems to have gone away. Thanks!
