### ISSUE TITLE
.Net Core issues

### ISSUE THREAD

**Issue by grbd** [chromelyapps/Chromely#95]
Hi,
I've recently been experimenting trying to use the chromely demos

## Chromely.CefGlue.Winapi.Demo

so far I've managed to get the Chromely.CefGlue.Winapi.Demo to work which is the one that targets the traditional (non .net core) framework
however I had to swap the in repo dll dependencies for Nuget related ones that were more up-to-date before it worked.

## Chromely.CefGlue.Winapi.netCoreDemo

For the .net core demo Chromely.CefGlue.Winapi.netCoreDemo
I think there are a couple of problems

The first is Chromely seems to be looking for dll's within the build directory / same location as the compiled main dll that dotnet is run against. This is true for traditional .net apps where when you build something, a copy of referenced dll's are placed into the build directory

However with .net core apps during debugging instead the apps reference dll's located in a shared nuget store
typically C:\Users\userid\\.nuget\packages\
So i'm guessing it might be using some kind of custom dll loader and expecting the dll's to be in a certain path when in fact they're located somewhere else
I'm assuming a publish might put everything in one directory, but I couldn't get that to work without a
"The RuntimeIdentifier platform 'win-x32' and the PlatformTarget 'x86' must be compatible." error
manually copying Chromely.CefGlue.dll, Chromely.CefGlue.Winapi.dll, Chromely.Core.dll, WinApi.dll into the build dir seemed to resolve some of this

A second issue which I haven't figured out yet although may be related to the above
is as soon as window.Run(args); is hit the whole thing crashes / drops out
and there's no exception caught by Visual studio just an event in the application event log.
Perhaps this is related to the use of WinApi / a specific version of windows 10

I came acoross these which I think might be related
https://github.com/chromelyapps/Chromely/issues/66
https://github.com/chromelyapps/Chromely/issues/74

**Comment by mattkol** [comment]
@grbd that is interesting that you find some difficulty testing Chromely.CefGlue.Winapi.Demo. I hope it is not related to #93  and #94. The demo was updated earlier today to use Nuget, so please try that again. It should run as-is. It has not changed for months.

On .NET Core, it is difficult to give a one-size-fits-all answer as you are familiar with how dotnet works.

Current CEF/Chromium versions are MultiProcess so you cannot really debug Chromely.CefGlue.Winapi.netCoreDemo. To test it successfully you have to publish it. Please see wiki for more info - [Guide](https://github.com/chromelyapps/Chromely/wiki/Getting-Started-CefGlue-Winapi-(.NET-Core)). To debug successfully a .NET Core  CEF MultiProcess  without publishing you need a subprocess - CefGlue/Chromely do not have that implemented yet. 

Earlier CEF/CefGlue versions (v66 and lower) supported SingleProcess.

I usually point developers to Chromely cli for CefGlue v66 - [CLI CefGlue-Chromium v66](https://github.com/chromelyapps/Chromely#run-starter-template-using-dotnet-core-cli-for-more-info-please-see---dotnet-cli-demo-template-install) or [here..](https://github.com/chromelyapps/Chromely/wiki/dotnet-cli-Starter-Template). This is SingleProcess. Please start here, get familiar with it, it is a good starting point. Try publish this too and then you can see how this runs.

**Comment by grbd** [comment]
## Testing Demos

Okay,
it looks like everything under demo's is now using NuGet references now
so this fixes Chromely.CefGlue.Winapi.Demo quite nicely

I managed to get Chromely.CefGlue.Winapi.netCoreDemo running with publish
using **win-x86** / **self-contained** for the options
I think the version of libcef in use is 32bit from the looks of things

## Experimenting with running without publish

I understand what you're saying about MultiProcess / SingleProcess
I figured I'd see how far I could get with just launching it from visual studio without publishing just out of interest.
I figured I'd post this here for anyone else that's interested although I understand this isn't supported

  * First I changed the references for Chromely.CefGlue / Chromely.CefGlue.Winapi / Chromely.Core
    across from nuget to the latest master sources
  * Next I triggered a build to 32bit under visual studio
  * Next I copied / pasted the libcef files across from a known working published version of the code
    *.pak, *.bin, *.dat, locales/, chrome_elf.dll, libcef.dll, libEGL.dll, libGLESv2.dll since normally these are only included in the nuget packages
  * I also installed the 32bit version of the dotnet core sdk so I could launch the cefglue_winapi_netcoredemo.dll from the command line in 32bit mode

Launching from visual studio seems to result in a
```
'dotnet.exe' (CoreCLR: DefaultDomain): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.0.9\System.Private.CoreLib.dll'. 
The program '[24548] dotnet.exe' has exited with code -532462766 (0xe0434352).
```

Launching using the command line (without publish) using the 32bit version of dotnet
```
"C:\Program Files (x86)\dotnet\dotnet.exe" cefglue_winapi_netcoredemo.dll
```
results in a partally open window but it looks like something is trying to launch dotnet in a loop with unknown options
```
Run 'dotnet [command] --help' for more information on a command.
Unknown option: --type=gpu-process
Unknown option: --no-sandbox
Unknown option: --locales-dir-path=D:\Temp\10\Chromely-test\demo-projects\regular-chromely\Chromely.CefGlue.Winapi.netCoreDemo\bin\x86\Debug\netcoreapp2.0\locales
Unknown option: --log-file=logs\chromely.cef_new.log
Unknown option: --log-severity=info
Unknown option: --resources-dir-path=D:\Temp\10\Chromely-test\demo-projects\regular-chromely\Chromely.CefGlue.Winapi.netCoreDemo\bin\x86\Debug\netcoreapp2.0
Unknown option: --lang=en-US
Unknown option: --gpu-preferences=KAAAAAAAAACAAwBAAQAAAAAAAAAAAGAAAAAAAAAAAAAIAAAAAAAAACgAAAAEAAAAIAAAAAAAAAAoAAAAAAAAADAAAAAAAAAAOAAAAAAAAAAQAAAAAAAAAAAAAAAKAAAAEAAAAAAAAAAAAAAACwAAABAAAAAAAAAAAQAAAAoAAAAQAAAAAAAAAAEAAAALAAAA
Unknown option: --locales-dir-path=D:\Temp\10\Chromely-test\demo-projects\regular-chromely\Chromely.CefGlue.Winapi.netCoreDemo\bin\x86\Debug\netcoreapp2.0\locales
Unknown option: --log-file=logs\chromely.cef_new.log
Unknown option: --log-severity=info
Unknown option: --resources-dir-path=D:\Temp\10\Chromely-test\demo-projects\regular-chromely\Chromely.CefGlue.Winapi.netCoreDemo\bin\x86\Debug\netcoreapp2.0
Unknown option: --lang=en-US
Unknown option: --service-request-channel-token=11786224945804448682
Unknown option: --mojo-platform-channel-handle=2424
.NET Command Line Tools (2.2.203)
```

I suspect this has something to do with cefglue_winapi_netcoredemo being a dll instead of an exe

**Comment by mattkol** [comment]
@grbd 

````
I suspect this has something to do with cefglue_winapi_netcoredemo being a dll instead of an exe
````
That is the point I was making. You cannot debug/run in Visual Studio without a sub-process. If you find a way to do it without publishing, please share with us. There may be a way ... The way I know so far .. is .. publish to exe and run the exe.

You are not tied to x86. Please look at the project file to set the appropriate flags. Check what the cli project has and sync with yours. I believe the demo project sets all options. Please also make sure your project configurations matches the bitness that you want. Any mismatch can give you unexpected behavior.

You can remove what you do not need in the project file -- looks like it is picking the first option.

````
  <PropertyGroup>
....
    <RuntimeIdentifiers>win-x64;win-x32;ubuntu.16.10-x64</RuntimeIdentifiers>
    <Platforms>x64;x86</Platforms>
....
  </PropertyGroup>
````

I will change it now to default back to x64 - what the cli has.

**Comment by grbd** [comment]
thanks for the info

**Comment by mattkol** [comment]
@grbd yw.

I will see if I can spare a couple of hours this week to create and integrate a sub-process. This will help.

**Comment by grbd** [comment]
I suspect it might have been set to x86 due to a bit of strangeness with the publishing path

If I set the solution configuration to x86
Then set the publish target is set to win-x86 (not win-x32 which doesn't work)
The end result which works will end up in bin\x86\Debug\netcoreapp2.0\win-x86\

If I set the solution configuration to x64
Then set the publish target is set to win-x64
for some reason it creates two directories
bin\x64\Debug\netcoreapp2.0\publish\ <- this one is highlighted in the publish window, but ignore
bin\x64\Debug\netcoreapp2.0\win-x64\ <- this is the one it works / runs from

**Comment by mattkol** [comment]
@grbd ok.
Do we need to update the wiki?

**Comment by grbd** [comment]
I did make an attempt to see if I could alter / fudge the command line during runtime within CefGlueApp.cs / OnBeforeCommandLineProcessing that CefGlue was using.

The idea being if I could get it to work with being launched as a dll from donet then maybe something like this might have worked

  * https://marketplace.visualstudio.com/items?itemName=vsdbgplat.MicrosoftChildProcessDebuggingPowerTool

But I couldn't get it to work, so I think like you've said it'll need a sub-process

**Comment by mattkol** [comment]
@grbd thanks for the link. Will be useful for debugging a subprocess. 
Yes, you are right on runtime command line parsing in OnBeforeCommandLineProcessing. It is also what CefSharp uses.

I have actually started work on this months ago, but never had the bandwidth to finish it.

Thanks.

**Comment by mattkol** [comment]
@grbd suprocess is now implemented - https://github.com/chromelyapps/Chromely/commit/3053aa63b8f108e4e7dd57c588b1f7f076972d7a#diff-25d902c24283ab8cfbac54dfa101ad31

[Demo](https://github.com/chromelyapps/demo-projects/tree/master/regular-chromely/CefGlueSubprocess)

**Comment by grbd** [comment]
I just tried it out and it works fantastic
the only change I had to make was to add WinAPI via nuget to CefGlueSubprocess/Chromely.CefGlue.Winapi.Demo

then I added in the libcef files manually and it works spot on
