### ISSUE TITLE
ToolTips (HTML title attributes) does not work.

### ISSUE THREAD

**Issue by FrankPfattheicher** [chromelyapps/Chromely#98]
Running the app the title attribute which results in a tool tip hovering with the mouse does not show up anything.

Maybe the mousemove events are not bubbled to the browser instance.

**Comment by ViceIce** [comment]
Seeing this too. using `Chromely.CefGlue.Winapi@4.0.70`

**Comment by ViceIce** [comment]
Using an [app.manifest](https://gitlab.com/xiliumhq/chromiumembedded/cefglue/blob/master/CefGlue.Demo.WinForms/app.manifest) works

add to `PropertyGroup` in `csproj` file
```xml
  <ApplicationManifest>app.manifest</ApplicationManifest>
```

**Comment by mattkol** [comment]
@FrankPfattheicher @ViceIce is adding app.manifest the solution for this? Do we need to add this to the demos?

**Comment by FrankPfattheicher** [comment]
@mattkol yes, i will give this a try, if it works as expected we should include one by default.
But this will be next week....

**Comment by ViceIce** [comment]
for me it solved this error, so i would say yes.

I'm using cefglue with net472.

**Comment by ViceIce** [comment]
for netcoreapp2.2 i got the following error when published:
```
07:26:03  INFO Running Windows chromium 70.0.3538.102
07:26:03  ERROR
System.DllNotFoundException: Unable to load DLL 'libcef' or one of its dependencies: Das angegebene Modul wurde nicht gefunden. (Exception from HRESULT: 0x8007007E)
   at Xilium.CefGlue.Interop.libcef.api_hash(Int32 entry)
   at Xilium.CefGlue.CefRuntime.CheckVersionByApiHash()
   at Xilium.CefGlue.CefRuntime.Load(String path)
   at Chromely.CefGlue.BrowserWindow.CefBinariesLoader.Load(ChromelyConfiguration config)
07:26:03  ERROR
System.ComponentModel.Win32Exception (193): The specified executable is not a valid application for this OS platform.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Chromely.CefGlue.BrowserWindow.CefBinariesLoader.LaunchHtmlWarningPage(Tuple`3 message)
   at Chromely.CefGlue.BrowserWindow.CefBinariesLoader.WarnUserOnLoad()
```

**Comment by ViceIce** [comment]
ok using `SilentCefBinariesLoading` as workaround.

the manifest is not used by netcoreapp2.2 or i don't know how to add it.

**Comment by ViceIce** [comment]
looks like manifest is supported from netcoreapp3.0 onwards.

https://github.com/dotnet/core-setup/issues/5053

**Comment by FrankPfattheicher** [comment]
Found this CEF issue (status wontfix):
https://bitbucket.org/chromiumembedded/cef/issues/854/cef3-title-attribute-of-tags-is-not

and:
https://magpcss.org/ceforum/viewtopic.php?f=6&t=15749
which also explains  incorrectly positioned tooltips on linux.

but i could'nt find out why OnTooltip is never called :-(

**Comment by ViceIce** [comment]
Do we use OSR? otherwise it should work, excerpt on windows, where we need a manifest.

https://magpcss.org/ceforum/viewtopic.php?f=14&t=15212&p=35463&hilit=tooltips#p35467
https://bitbucket.org/chromiumembedded/cef/src/master/tests/cefclient/resources/win/cefclient.exe.manifest

They use a more minimal manifest. so `Microsoft.Windows.Common-Controls` are required for tooltips on windows.

**Comment by FrankPfattheicher** [comment]
@ViceIce - manifests currently do not work on netcore ....

**Comment by ViceIce** [comment]
I know, but will come soon with netcore 3.0, or you use a tool to manipulate the embedded manifest after publish

**Comment by FrankPfattheicher** [comment]
@ViceIce @mattkol For now, depolying a manifest as separate file <AppName>.exe.manifest works after publish. Maybe there is a better solution after Core 3.0 release.

Still a problem on linux is the wrong position of tooltips.

**Comment by ViceIce** [comment]
The modified date must be after the exe modified, otherwise windows will ignore the manifest

Core 3.0 supports the manifest out of the box. see https://github.com/dotnet/core-setup/issues/5053#issuecomment-458722369

**Comment by FrankPfattheicher** [comment]
@ViceIce thanks for the "modified" hint :-)
